# generated by datamodel-codegen:
#   filename:  tmpnz66xr7a.json
#   timestamp: 2026-05-19T21:56:49+00:00

from __future__ import annotations

from enum import Enum, IntEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, confloat, conint, constr


class Phase(IntEnum):
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3
    integer_4 = 4
    integer_5 = 5


class BuildingContext(BaseModel):
    """
    에이전트 입력 — 건물 컨텍스트. A01(진단)이 PNU에서 생성, A03/A04/A07 등이 입력으로 받음.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    pnu: str = Field(..., description='법정 PNU 19자리')
    address: str
    usage_type: str = Field(
        ..., description='건축물대장 용도. constants.py BUILDING_USAGE_MAP 참조'
    )
    gross_area: float = Field(..., description='연면적 (m²)')
    floors: int
    built_year: int
    structure: str
    eui: float = Field(..., description='Energy Use Intensity (kWh/m²·yr)')
    energy_tier: conint(ge=1, le=5) = Field(
        ..., description='data_tier (1=measured, 5=ep_lookup)'
    )
    energy_grade: str = Field(..., description='1+~7 또는 ZEB 등급')
    has_kapt: bool | None = False
    has_hourly: bool | None = False
    has_fire_risk: bool | None = False


class AgentResult(BaseModel):
    """
    에이전트 출력 표준 — 카르테 카드/포트폴리오/SSE에 동일 형식.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    agent_name: str = Field(..., description="예: 'a01_diagnosis'")
    version: str = Field(..., description='에이전트 버전 (semver)')
    confidence: confloat(ge=0.0, le=1.0) = Field(
        ..., description='결과 신뢰도. 5-Tier 데이터 품질 기반 계산'
    )
    summary: str = Field(..., description='한 문장 요약 (카드 헤더)')
    payload: dict[str, Any] | None = Field(
        {}, description='에이전트별 자유 형식 데이터'
    )
    method_used: str | None = Field(
        '', description="사용된 방법 라벨 (예: 'L0_template' / 'L2_llm')"
    )
    ml_model_version: str | None = Field(
        None,
        description="L1 ML 경로 시 모델 식별자 (예: 'patchtst_v5_168to24'). L0/룰 분기에서는 null.",
    )
    elapsed_sec: confloat(ge=0.0) | None = Field(0.0, description='실행 시간 (초)')
    warnings: list[str] | None = []
    error: str | None = None


class BuildingForecast(BaseModel):
    """
    PNU → 168h 시계열 + 24h 예측. AI 챔피언 a02_forecast 의존성 (Phase D 마이그레이션 A). ems_transformer Gateway `/v1/building/forecast?pnu=` 가 본 모델로 응답.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    pnu: constr(min_length=19, max_length=19)
    context_168h_kw: list[float] | None = Field(
        None,
        description='168h hourly 실측 (kW). 미보유 시 null — fixture/L0 fallback 분기 가능',
    )
    forecast_24h_kw: list[float] = Field(
        ...,
        description='Korean_BB TwGauss-M 24h hourly 예측 (kW)',
        max_length=24,
        min_length=24,
    )
    peak_kw_24h: confloat(ge=0.0) | None = 0.0
    avg_kw_24h: confloat(ge=0.0) | None = 0.0
    ml_model_version: str = Field(
        ...,
        description="예: 'patchtst_v5_168to24_real' / 'patchtst_v5_168to24_synthetic'",
    )
    timeseries_available: bool | None = Field(
        False, description='실측 168h 시계열 보유 여부. false 면 forecast 도 synthetic'
    )


class AlertSignals(BaseModel):
    """
    PNU → 능동 알림 트리거 신호 집계 (DR 이벤트/등록, 화재 위험, 점검 의무). AI 챔피언 a16_messenger 의존성. Gateway `/v1/building/alert-signals?pnu=` 응답.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    pnu: constr(min_length=19, max_length=19)
    active_dr_event: bool | None = False
    dr_enrolled: bool | None = False
    fire_high_risk: bool | None = False
    fire_score: conint(ge=0) | None = 0
    has_obligation: bool | None = False


class MaintenanceFacts(BaseModel):
    """
    PNU → 유지보수 사실 (fire_risk 일부 + inspection cycle + alterations 이력). AI 챔피언 a13_predictive_maintenance 의존성. Gateway `/v1/building/maintenance-facts?pnu=` 응답.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    pnu: constr(min_length=19, max_length=19)
    available: bool
    age_score: conint(ge=0) | None = 0
    structure_score: conint(ge=0) | None = 0
    history_score: conint(ge=0) | None = 0
    total_score: conint(ge=0) | None = 0
    inspection_cycle_years: int | None = None
    valid_until: str | None = Field(
        None, description='ISO date — 다음 점검 due year 계산 입력'
    )
    obligation_type: str | None = None
    alt_5yr: conint(ge=0) | None = Field(0, description='최근 5년 대수선 건수')
    alt_total: conint(ge=0) | None = 0


class Severity(Enum):
    high = 'high'
    medium = 'medium'


class Anomaly(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    hour: conint(ge=0, le=23) | None = None
    actual_kw: float | None = None
    predicted_kw: float | None = None
    z_score: float | None = None
    severity: Severity | None = None


class AnomalyDetection(BaseModel):
    """
    PNU → Korean_BB 잔차 기반 24h 이상 탐지. AI 챔피언 a12_anomaly 의존성. Gateway `/v1/building/anomaly?pnu=` 응답.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    pnu: constr(min_length=19, max_length=19)
    available: bool = Field(
        ...,
        description='잔차 분석 가능 여부 (실측 192h + 모델). false 면 a12 rules 분기',
    )
    anomaly_count: conint(ge=0) | None = 0
    anomalies: list[Anomaly] | None = Field([], validate_default=True)
    cvrmse_pct: confloat(ge=0.0) | None = 0.0
    anomaly_rate_pct: confloat(ge=0.0) | None = 0.0
    high_severity_count: conint(ge=0) | None = 0
    engine: str | None = Field(None, description="예: 'patchtst_v5_168to24_real'")


class DREnrollment(BaseModel):
    """
    PNU → DR venue 등록 상태 + 감축 잠재. AI 챔피언 a11_dr_orchestrator 의존성. ems_transformer Gateway `/v1/building/dr-enrollment?pnu=` 응답.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    pnu: constr(min_length=19, max_length=19)
    enrolled: bool = Field(
        ...,
        description='dr_venues active 등록 여부. false 면 a11 가 eligibility 룰 분기',
    )
    ven_id: str | None = None
    venue_kind: str | None = None
    venue_type: str | None = None
    group_id: str | int | None = None
    max_reduction_kw: confloat(ge=0.0) | None = 0.0
    baseline_kw: confloat(ge=0.0) | None = 0.0
    recent_telem_count_7d: conint(ge=0) | None = 0
    has_recent_telemetry: bool | None = False


class IndustryContext(BaseModel):
    """
    공장/제조에 한해 한국에너지공단 GHG 광역시도 평균. 비공장 null. 사냥꾼 3차 S3-9 required 필드 명시.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    region: str
    source: str
    year: int | None = None
    biz_count: conint(ge=0)
    avg_co2_ton_per_biz: float
    total_co2_ton: float | None = None
    note: str | None = None


class BenchmarkStats(BaseModel):
    """
    PNU+EUI → 같은 용도·연식 그룹 percentile + 공장 산업 컨텍스트. AI 챔피언 a07_benchmark 의존성. ems_transformer Gateway `/v1/building/benchmark?pnu=&eui=&usage_type=&built_year=` 응답.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    pnu: constr(min_length=19, max_length=19)
    available: bool = Field(
        ...,
        description='그룹 비교 가능 여부 (같은 그룹 ≥ 10개). false 면 a07 fallback (산업 컨텍스트만 있을 수 있음)',
    )
    percentile: float | None = None
    group_total: conint(ge=0) | None = 0
    group_avg_eui: float | None = None
    q25: float | None = None
    q75: float | None = None
    rank: str | None = Field(
        None, description='상위 우수 / 평균 이상 / 평균 이하 / 하위'
    )
    target_eui: float | None = None
    improvement_kwh: float | None = None
    group_label: str | None = Field(None, description="예: '업무시설 · 2011-2020'")
    industry_context: IndustryContext | None = Field(
        None,
        description='공장/제조에 한해 한국에너지공단 GHG 광역시도 평균. 비공장 null. 사냥꾼 3차 S3-9 required 필드 명시.',
    )


class FireRiskAssessment(BaseModel):
    """
    PNU → building_fire_risk MV (7-component scoring) + inspection_obligation_active. AI 챔피언 a05_safety 의존성. ems_transformer Gateway `/v1/building/fire-risk?pnu=` 응답.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    pnu: constr(min_length=19, max_length=19)
    available: bool = Field(
        ..., description='MV 데이터 가용 여부. false 면 a05 rules 분기'
    )
    structure_score: conint(ge=0) | None = 0
    age_score: conint(ge=0) | None = 0
    usage_score: conint(ge=0) | None = 0
    height_score: conint(ge=0) | None = 0
    disaster_zone_score: conint(ge=0) | None = 0
    history_score: conint(ge=0) | None = 0
    inspection_score: conint(ge=0) | None = 0
    total_score: conint(ge=0) | None = 0
    risk_grade: str | None = Field(None, description='HIGH / MEDIUM / LOW')
    has_obligation: bool | None = False
    obligation_source: str | None = None
    obligation_confidence: str | None = None
    obligation_type: str | None = None


class SetbackPattern(BaseModel):
    """
    PNU → 야간감축 setback 패턴 분류. AI 챔피언 a03_optimizer 의존성 (Phase D 마이그레이션). inverse_ems RF 분류기 결과. ems_transformer Gateway `/v1/building/setback-pattern?pnu=` 응답.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    pnu: constr(min_length=19, max_length=19)
    available: bool = Field(
        ...,
        description='분류 가능 여부 (실측 시계열 + 모델 가용). false 면 a03 가 rules 만 사용',
    )
    label: str | None = Field(
        None, description="예: 'SETBACK' / 'NO_SETBACK' / 'MIXED'"
    )
    probability: confloat(ge=0.0, le=1.0) | None = None
    is_setback: bool | None = False
    days_used: conint(ge=0) | None = 0
    engine: str | None = Field(None, description="예: 'rf_v1_168h_F1_0.911'")


class SggCalibrationFactor(BaseModel):
    """
    자치구·에너지원·세그먼트별 보정계수 (정답지 vs 추정 비). AI 챔피언 a04_carbon 의존성 (Phase E 마이그레이션 K). sgg_calibration_factors DB. ems_transformer Gateway `/v1/building/sgg-factor?sgg_cd=&energy_type=&segment=&year=` 응답.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    sgg_cd: constr(min_length=5, max_length=5) = Field(
        ..., description='법정 시군구 5자리 코드'
    )
    energy_type: str | None = Field(None, description='전기 / 가스 / 지역난방')
    segment: str | None = Field(None, description='residential / commercial')
    year: conint(ge=2000, le=2100) | None = 2022
    factor: confloat(ge=0.0) = Field(..., description='보정 계수 (1.0 = 미보정)')
    source: str | None = Field(None, description="예: 'seoul_oa22362_2022'")


class AgentCapability(Enum):
    """
    A01~A10 핵심 능력 + Phase 4 a11 dr_orchestration
    """

    diagnosis = 'diagnosis'
    forecast = 'forecast'
    optimization = 'optimization'
    carbon = 'carbon'
    safety = 'safety'
    renewable = 'renewable'
    benchmark = 'benchmark'
    market = 'market'
    policy = 'policy'
    coordination = 'coordination'
    dr_orchestration = 'dr_orchestration'


class MaturityLevel(Enum):
    """
    에이전트 성숙도 (RQ-AI 프레임). L0=정적 템플릿, L1=규칙 기반, L2=LLM, L3=최적화 알고리즘
    """

    L0_template = 'L0_template'
    L1_rule = 'L1_rule'
    L2_llm = 'L2_llm'
    L3_optimization = 'L3_optimization'


class DataSource(Enum):
    """
    출처 축. measured=실 계량, certified=공식 인증, simulated=시뮬 산출, predicted=ML 예측, external=외부 벤더, synthetic=합성/생성기, mock=의도적 모킹
    """

    measured = 'measured'
    certified = 'certified'
    simulated = 'simulated'
    predicted = 'predicted'
    external = 'external'
    synthetic = 'synthetic'
    mock = 'mock'


class Registry(BaseModel):
    id: constr(pattern=r'^a(0[1-9]|1[0-9]|2[0-9])$') = Field(
        ..., description='a01~a29까지 허용 (Phase 4 a11 dr_orchestrator 도입)'
    )
    name_en: str
    name_kr: str
    capability: AgentCapability
    phase: Phase
    maturity: MaturityLevel | None = None
    requires: list[str] | None = Field(
        None, description='선행 에이전트 ID (예: A03/A04/A07은 A01 필요)'
    )
    output_strategies: list[constr(pattern=r'^M(0[0-9]|1[0-5])$')] | None = Field(
        None,
        description='이 에이전트가 산출할 수 있는 EMS 전략 코드 (Phase H 추가). 비어있으면 전략을 산출하지 않음 (예: 진단·예측·벤치마크).',
    )
    output_data_source: DataSource | None = Field(
        None,
        description='이 에이전트 결과의 데이터 출처 분류 (Phase H 추가). measured/certified/simulated/predicted/external/synthetic/mock',
    )


class AgentcontractSsotAi(BaseModel):
    """
    A01~A10 에이전트 입출력 Protocol. building-energy-3d/src/agents/core/contract.py 와 동기. AI 챔피언 본선 카르테 시스템의 단일 진실.
    """

    registry: dict[str, Registry] | None = Field(
        None, description='에이전트 카탈로그 (Phase 1~3: A01~A10, Phase 4+: A11~)'
    )
