# generated by datamodel-codegen:
#   filename:  tmprc7jfbxu.json
#   timestamp: 2026-05-19T19:34:11+00:00

from __future__ import annotations

from enum import Enum, IntEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, confloat, conint, constr


class Phase(IntEnum):
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3
    integer_4 = 4
    integer_5 = 5


class BuildingContext(BaseModel):
    """
    에이전트 입력 — 건물 컨텍스트. A01(진단)이 PNU에서 생성, A03/A04/A07 등이 입력으로 받음.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    pnu: str = Field(..., description='법정 PNU 19자리')
    address: str
    usage_type: str = Field(
        ..., description='건축물대장 용도. constants.py BUILDING_USAGE_MAP 참조'
    )
    gross_area: float = Field(..., description='연면적 (m²)')
    floors: int
    built_year: int
    structure: str
    eui: float = Field(..., description='Energy Use Intensity (kWh/m²·yr)')
    energy_tier: conint(ge=1, le=5) = Field(
        ..., description='data_tier (1=measured, 5=ep_lookup)'
    )
    energy_grade: str = Field(..., description='1+~7 또는 ZEB 등급')
    has_kapt: bool | None = False
    has_hourly: bool | None = False
    has_fire_risk: bool | None = False


class AgentResult(BaseModel):
    """
    에이전트 출력 표준 — 카르테 카드/포트폴리오/SSE에 동일 형식.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    agent_name: str = Field(..., description="예: 'a01_diagnosis'")
    version: str = Field(..., description='에이전트 버전 (semver)')
    confidence: confloat(ge=0.0, le=1.0) = Field(
        ..., description='결과 신뢰도. 5-Tier 데이터 품질 기반 계산'
    )
    summary: str = Field(..., description='한 문장 요약 (카드 헤더)')
    payload: dict[str, Any] | None = Field(
        {}, description='에이전트별 자유 형식 데이터'
    )
    method_used: str | None = Field(
        '', description="사용된 방법 라벨 (예: 'L0_template' / 'L2_llm')"
    )
    ml_model_version: str | None = Field(
        None,
        description="L1 ML 경로 시 모델 식별자 (예: 'patchtst_v5_168to24'). L0/룰 분기에서는 null.",
    )
    elapsed_sec: confloat(ge=0.0) | None = Field(0.0, description='실행 시간 (초)')
    warnings: list[str] | None = []
    error: str | None = None


class BuildingForecast(BaseModel):
    """
    PNU → 168h 시계열 + 24h 예측. AI 챔피언 a02_forecast 의존성 (Phase D 마이그레이션 A). ems_transformer Gateway `/v1/building/forecast?pnu=` 가 본 모델로 응답.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    pnu: constr(min_length=19, max_length=19)
    context_168h_kw: list[float] | None = Field(
        None,
        description='168h hourly 실측 (kW). 미보유 시 null — fixture/L0 fallback 분기 가능',
    )
    forecast_24h_kw: list[float] = Field(
        ...,
        description='Korean_BB TwGauss-M 24h hourly 예측 (kW)',
        max_length=24,
        min_length=24,
    )
    peak_kw_24h: confloat(ge=0.0) | None = 0.0
    avg_kw_24h: confloat(ge=0.0) | None = 0.0
    ml_model_version: str = Field(
        ...,
        description="예: 'patchtst_v5_168to24_real' / 'patchtst_v5_168to24_synthetic'",
    )
    timeseries_available: bool | None = Field(
        False, description='실측 168h 시계열 보유 여부. false 면 forecast 도 synthetic'
    )


class AgentCapability(Enum):
    """
    A01~A10 핵심 능력 + Phase 4 a11 dr_orchestration
    """

    diagnosis = 'diagnosis'
    forecast = 'forecast'
    optimization = 'optimization'
    carbon = 'carbon'
    safety = 'safety'
    renewable = 'renewable'
    benchmark = 'benchmark'
    market = 'market'
    policy = 'policy'
    coordination = 'coordination'
    dr_orchestration = 'dr_orchestration'


class MaturityLevel(Enum):
    """
    에이전트 성숙도 (RQ-AI 프레임). L0=정적 템플릿, L1=규칙 기반, L2=LLM, L3=최적화 알고리즘
    """

    L0_template = 'L0_template'
    L1_rule = 'L1_rule'
    L2_llm = 'L2_llm'
    L3_optimization = 'L3_optimization'


class DataSource(Enum):
    """
    출처 축. measured=실 계량, certified=공식 인증, simulated=시뮬 산출, predicted=ML 예측, external=외부 벤더, synthetic=합성/생성기, mock=의도적 모킹
    """

    measured = 'measured'
    certified = 'certified'
    simulated = 'simulated'
    predicted = 'predicted'
    external = 'external'
    synthetic = 'synthetic'
    mock = 'mock'


class Registry(BaseModel):
    id: constr(pattern=r'^a(0[1-9]|1[0-9]|2[0-9])$') = Field(
        ..., description='a01~a29까지 허용 (Phase 4 a11 dr_orchestrator 도입)'
    )
    name_en: str
    name_kr: str
    capability: AgentCapability
    phase: Phase
    maturity: MaturityLevel | None = None
    requires: list[str] | None = Field(
        None, description='선행 에이전트 ID (예: A03/A04/A07은 A01 필요)'
    )
    output_strategies: list[constr(pattern=r'^M(0[0-9]|1[0-5])$')] | None = Field(
        None,
        description='이 에이전트가 산출할 수 있는 EMS 전략 코드 (Phase H 추가). 비어있으면 전략을 산출하지 않음 (예: 진단·예측·벤치마크).',
    )
    output_data_source: DataSource | None = Field(
        None,
        description='이 에이전트 결과의 데이터 출처 분류 (Phase H 추가). measured/certified/simulated/predicted/external/synthetic/mock',
    )


class AgentcontractSsotAi(BaseModel):
    """
    A01~A10 에이전트 입출력 Protocol. building-energy-3d/src/agents/core/contract.py 와 동기. AI 챔피언 본선 카르테 시스템의 단일 진실.
    """

    registry: dict[str, Registry] | None = Field(
        None, description='에이전트 카탈로그 (Phase 1~3: A01~A10, Phase 4+: A11~)'
    )
