# generated by datamodel-codegen:
#   filename:  airo_request.json
#   timestamp: 2026-09-22T10:18:42+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, constr


class Surface(Enum):
    mcp = 'mcp'
    studio = 'studio'
    lab = 'lab'
    airos = 'airos'
    agentleague = 'agentleague'


class IdSource(Enum):
    """
    세션이 있으면 서버가 airos_session 으로 덮어쓴다. declared 는 검증됨이 아니다
    """

    airos_session = 'airos_session'
    declared = 'declared'


class Asker(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    login_id: constr(pattern=r'^[a-z]+\.[a-z_]+\.[0-9]{3}$')
    alias: constr(max_length=60) | None = None
    persona: constr(pattern=r'^P-[A-Z]{2,5}$') | None = None
    id_source: IdSource | None = Field(
        None,
        description='세션이 있으면 서버가 airos_session 으로 덮어쓴다. declared 는 검증됨이 아니다',
    )


class Kind(Enum):
    asset = 'asset'
    portfolio = 'portfolio'
    building = 'building'
    region = 'region'
    archetype = 'archetype'


class Source(Enum):
    query = 'query'
    selection = 'selection'
    previous = 'previous'
    user_default = 'user_default'
    login_assignment = 'login_assignment'
    auto_first = 'auto_first'
    chain_step = 'chain_step'


class Archetype(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    building_type: str
    hvac: str | None = None
    city: str | None = None
    derived_from: str | None = Field(
        None,
        description='로그인 배정 건물에서 자동 연결했으면 그 AIR id(기록된 원형). 없으면 가상 건물',
    )


class Grain(Enum):
    hour = 'hour'
    day = 'day'
    month = 'month'
    year = 'year'
    NoneType_None = None


class Basis(Enum):
    question_literal = 'question_literal'
    recent_n_from_data_end = 'recent_n_from_data_end'
    subject_default = 'subject_default'
    client_selection = 'client_selection'
    NoneType_None = None


class Period(BaseModel):
    """
    서버의 단일 파서가 text 를 start·end_exclusive·grain·basis 로 정규화한다. LLM 은 정규화 값을 직접 주지 않는다(날짜를 지어내지 않게).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    text: constr(max_length=200) | None = Field(
        None, description='LLM 이 주는 유일한 기간 값 — 질문 원문의 부분 문자열'
    )
    start: AwareDatetime | None = None
    end_exclusive: AwareDatetime | None = None
    tz: Literal['Asia/Seoul'] = 'Asia/Seoul'
    grain: Grain | None = None
    basis: Basis | None = None


class Target(BaseModel):
    """
    필지번호(19자리)는 대상이 아니다 — 필지 화면의 조회 열쇠로만. ms-·원천 코드·BE-3D 정수 패킷 번호는 서버 안에서만.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Kind
    ids: list[str] = Field(..., max_length=50, min_length=1)
    label: constr(max_length=60) | None = None
    source: Source | None = None
    archetype: Archetype | None = None


class AiroAiroRequestV2(BaseModel):
    """
    다섯 응용(게이트웨이·MCP·AIROS·AgentLeague·Studio·Lab)의 질의형 입구가 받는 하나의 봉투. 누가(asker)·무엇을(target)·언제(period)를 싣는다. LLM 함수 호출 스키마에는 target(서버가 정한 것)·period.text·질문이 정할 값만 보이고, 자료·정본 참조·표지·서버 산출물 참조는 서버 결속기가 채운다. 근거: 공모전 docs/API_UNIFICATION_PROPOSAL_2026-09-22.md, docs/QUERY_ASKER_TOP_LEVEL_RULE_2026-09-22.md.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    contract: Literal['airo-request/v2'] = 'airo-request/v2'
    request_id: constr(min_length=1, max_length=120) | None = Field(
        None, description='호출자가 주는 요청 번호. 없으면 서버가 봉투 해시로 짓는다'
    )
    asker: Asker
    target: Target
    period: Period | None = None
    query: constr(min_length=1, max_length=4000) = Field(..., description='질문 원문')
    surface: Surface | None = None
