# generated by datamodel-codegen:
#   filename:  airos_replay_anomaly_policy.json
#   timestamp: 2026-09-28T14:26:42+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class Source(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['canonical_self']
    path: Literal[
        'projects/energy-contracts/energy_contracts/schemas/airos_replay_anomaly_policy.json#default'
    ]
    sha256: Literal['951ee3268b8df411e2518af5c00b82629c53102399aed58b2aae41ef33921ffa']
    sha256_rule: str | None = None
    applied_by: list[str] = Field(..., min_length=1)
    basis: str


class AirosReplayAnomalyPolicy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    policy_id: Literal['airos-query500-replay-anomaly']
    version: Literal['1.0']
    classification: Literal['declared_replay_analysis_policy']
    timezone: Literal['Asia/Seoul']
    replay_day: Literal['2022-07-21']
    previous_day: Literal['2022-07-20']
    baseline_start: Literal['2022-06-01']
    baseline_end_exclusive: Literal['2022-07-01']
    sensor_start: Literal['2022-07-01']
    sensor_end_exclusive: Literal['2022-08-01']
    residual_z_threshold: float
    comparison: Literal['strictly_greater']
    standard_deviation: Literal['population']
    sensor_rule: Literal['all_observed_thermostat_values_zero; missing_is_unknown']
    execution_authorized: Literal[False]
    source: Source
