# generated by datamodel-codegen:
#   filename:  airo_request.json
#   timestamp: 2026-09-28T08:40:13+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, constr


class Surface(Enum):
    mcp = 'mcp'
    studio = 'studio'
    lab = 'lab'
    airos = 'airos'
    agentleague = 'agentleague'


class Intent(Enum):
    """
    무엇을 원하나 — value=값만(기본) · scene=화면만 · both=값과 화면을 함께. 없으면 value 로 본다(기존 요청의 바이트가 달라지지 않는다). 2026-09-23 신설: 이 칸이 없을 때 봉투가 작업 방식을 value 로 고정해 장면 요구가 조용히 사라지던 것을 고친다.
    """

    value = 'value'
    scene = 'scene'
    both = 'both'


class IdSource(Enum):
    """
    세션이 있으면 서버가 airos_session 으로 덮어쓴다. declared 는 검증됨이 아니다
    """

    airos_session = 'airos_session'
    declared = 'declared'


class Asker(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    login_id: constr(pattern=r'^[a-z]+\.[a-z_]+\.[0-9]{3}$')
    alias: constr(max_length=60) | None = None
    persona: constr(pattern=r'^P-[A-Z]{2,5}$') | None = None
    id_source: IdSource | None = Field(
        None,
        description='세션이 있으면 서버가 airos_session 으로 덮어쓴다. declared 는 검증됨이 아니다',
    )


class Kind(Enum):
    asset = 'asset'
    portfolio = 'portfolio'
    building = 'building'
    region = 'region'
    archetype = 'archetype'


class Source(Enum):
    query = 'query'
    selection = 'selection'
    previous = 'previous'
    user_default = 'user_default'
    login_assignment = 'login_assignment'
    auto_first = 'auto_first'
    chain_step = 'chain_step'


class Archetype(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    building_type: str
    hvac: str | None = None
    city: str | None = None
    derived_from: str | None = Field(
        None,
        description='로그인 배정 건물에서 자동 연결했으면 그 AIR id(기록된 원형). 없으면 가상 건물',
    )


class Grain(Enum):
    hour = 'hour'
    day = 'day'
    month = 'month'
    year = 'year'
    NoneType_None = None


class Basis(Enum):
    question_literal = 'question_literal'
    recent_n_from_data_end = 'recent_n_from_data_end'
    subject_default = 'subject_default'
    client_selection = 'client_selection'
    NoneType_None = None


class Period(BaseModel):
    """
    서버의 단일 파서가 text 를 start·end_exclusive·grain·basis 로 정규화한다. LLM 은 정규화 값을 직접 주지 않는다(날짜를 지어내지 않게).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    text: constr(max_length=200) | None = Field(
        None, description='LLM 이 주는 유일한 기간 값 — 질문 원문의 부분 문자열'
    )
    start: AwareDatetime | None = None
    end_exclusive: AwareDatetime | None = None
    tz: Literal['Asia/Seoul'] = 'Asia/Seoul'
    grain: Grain | None = None
    basis: Basis | None = None


class Attributes(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sido: constr(pattern=r'^[0-9]{2}$') | None = None
    sigungu: constr(pattern=r'^[0-9]{5}$') | None = None
    climate_city: constr(pattern=r'^C(0[1-9]|1[0-8])$') | None = None
    archetype: constr(pattern=r'^B(0[1-9]|1[0-8])$') | None = None
    hvac: constr(pattern=r'^H_[A-G]$') | None = None
    usage: str | None = None
    gross_floor_area_m2: float | None = None
    building_mgmt_no: constr(pattern=r'^[0-9]{25}$') | None = None
    parcel_id: constr(pattern=r'^[0-9]{19}$') | None = None
    identity_status: str | None = None


class Source2(Enum):
    record = 'record'
    registry = 'registry'
    derived = 'derived'
    question = 'question'
    default = 'default'
    none = 'none'


class AbsenceKind(Enum):
    missing = 'missing'
    not_applicable = 'not_applicable'
    unknown = 'unknown'
    NoneType_None = None


class AttributeSources(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Source2
    absence_kind: AbsenceKind | None = None
    flag: str | None = Field(None, description='예: area_unverified(D1 면적 미확인)')
    basis: str | None = None


class TargetContext(BaseModel):
    """
    응답에 싣는 대상 문맥(2026-09-28 일반화 G1). 요청 Target 의 kind·ids·source 를 **그대로** 되돌리고(출처를 'request' 로 뭉치지 않는다), 서버가 끌어낸 속성과 그 속성의 출처를 싣는다. 못 끌어낸 속성은 null + attribute_sources 에 absence_kind. 기본값을 쓰면 출처 'default'.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Kind
    ids: list[str] = Field(..., max_length=50, min_length=1)
    source: Source
    label: constr(max_length=60) | None = None
    resolved: bool | None = Field(None, description='서버가 대상을 식별자까지 풀었는가')
    attributes: Attributes | None = None
    attribute_sources: dict[str, AttributeSources] | None = Field(
        None,
        description='속성 이름 → {source: record|registry|derived|default|question, absence_kind?, flag?}',
    )


class Target(BaseModel):
    """
    필지번호(19자리)는 대상이 아니다 — 필지 화면의 조회 열쇠로만. ms-·원천 코드·BE-3D 정수 패킷 번호는 서버 안에서만.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Kind
    ids: list[str] = Field(..., max_length=50, min_length=1)
    label: constr(max_length=60) | None = None
    source: Source | None = None
    archetype: Archetype | None = None


class AiroAiroRequestV2(BaseModel):
    """
    다섯 응용(게이트웨이·MCP·AIROS·AgentLeague·Studio·Lab)의 질의형 입구가 받는 하나의 봉투. 누가(asker)·무엇을(target)·언제(period)를 싣는다. LLM 함수 호출 스키마에는 target(서버가 정한 것)·period.text·질문이 정할 값만 보이고, 자료·정본 참조·표지·서버 산출물 참조는 서버 결속기가 채운다. 근거: 공모전 docs/API_UNIFICATION_PROPOSAL_2026-09-22.md, docs/QUERY_ASKER_TOP_LEVEL_RULE_2026-09-22.md.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    contract: Literal['airo-request/v2'] = 'airo-request/v2'
    request_id: constr(min_length=1, max_length=120) | None = Field(
        None, description='호출자가 주는 요청 번호. 없으면 서버가 봉투 해시로 짓는다'
    )
    asker: Asker
    target: Target
    period: Period | None = None
    query: constr(min_length=1, max_length=4000) = Field(..., description='질문 원문')
    surface: Surface | None = None
    intent: Intent | None = Field(
        'value',
        description='무엇을 원하나 — value=값만(기본) · scene=화면만 · both=값과 화면을 함께. 없으면 value 로 본다(기존 요청의 바이트가 달라지지 않는다). 2026-09-23 신설: 이 칸이 없을 때 봉투가 작업 방식을 value 로 고정해 장면 요구가 조용히 사라지던 것을 고친다.',
    )
