# generated by datamodel-codegen:
#   filename:  tmp_ocdu0wg.json
#   timestamp: 2026-10-01T11:40:41+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class Product(Enum):
    """
    통합 화면이 보낼 수 있는 상품 이름. studio = 지역·공공 값·표 분석(정책 담당 공무원) · airos = 로그인한 사람의 내 건물·점포·가정 운영 · be3d = 3D 장면·지도(Lab 포함) · agentleague = 이해관계자 토론 · mcp = 외부 도구(Claude Desktop 등) 사용. 역할 글·예문·규칙 낱말은 게이트웨이 상품 표 한 곳(serving/product_router.py)이 가진다 — 이 목록은 이름만 정한다.
    """

    studio = 'studio'
    airos = 'airos'
    be3d = 'be3d'
    agentleague = 'agentleague'
    mcp = 'mcp'


class WhyKo(RootModel[constr(min_length=2, max_length=120)]):
    root: constr(min_length=2, max_length=120) = Field(
        ...,
        description='그 상품을 고른 이유 한 줄(한국어). 줄바꿈 없음. 질문에 없는 수·지명·건물 이름을 싣지 않는다(게이트웨이가 검사하고, 어기면 규칙 문장으로 바꾼다).',
    )


class RouteContinuation(BaseModel):
    """
    이어 묻기 표시(선택). 있으면 이 질문이 앞 답을 잇는다 — 상품 이름을 가리키는 말(규칙 표의 상품 낱말)이 없으면 직전 상품을 지킨다.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    prior_request_id: constr(min_length=1, max_length=120) = Field(
        ...,
        description='이 질문이 이어 묻는 앞 답의 request_id(질의 봉투 continuation.prior_request_id 와 같은 값).',
    )
    prior_question_ko: constr(pattern=r'\S', min_length=1, max_length=4000) | None = (
        Field(
            None,
            description="앞 질문 글(선택) — '2도는?' 같은 짧은 이어 묻기를 LLM 이 앞 질문과 함께 읽게 한다.",
        )
    )


class Alternative(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    product: Product
    why_ko: WhyKo


class Source(Enum):
    """
    llm = 질문 이해 LLM 이 고르고 질문 글 근거 조각이 검사를 지났다 · rule = LLM 이 못 골라(공급자 장애·느림·근거 없음) 상품 표의 선언 낱말로 골랐다 · fallback = 그것도 없어 직전 상품(없으면 studio)으로 갔다. · interpretation(1.1) = 질문 해석 한 번(정형·대상 종류·표현 방식 — 근거 글 조각을 코드가 검사)의 결과와 질의자 권한으로 게이트웨이가 상품 표에서 정했다(LLM 이 상품 이름을 고르지 않았다). 1.1 한 번 해석 경로에서 rule 은 '선언 낱말이 실제로 걸려 한 상품만 가리켰다(갈림 없음)'도 뜻한다 — 그때 질문 해석(정형) LLM 이 돌았더라도 상품은 낱말이 정했으므로 model 칸이 없다.
    """

    llm = 'llm'
    rule = 'rule'
    fallback = 'fallback'
    interpretation = 'interpretation'


class Response(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_: Literal['airo-product-route/v1'] = Field(
        ...,
        alias='schema',
        description='응답 표지 — 화면은 이 글자가 정확히 같을 때만 상품 결정으로 받는다.',
    )
    product: Product = Field(
        ...,
        description='고른 상품 — 화면은 질문 상자 옆 칩으로 보이고 사용자가 바꿀 수 있다(바꾸면 같은 질문을 그 상품으로 다시 보낸다).',
    )
    why_ko: WhyKo
    alternatives: list[Alternative] = Field(
        ...,
        description='칩 옆에 보일 다른 후보(0~2). 상품은 서로 다르고 고른 상품과도 다르다(게이트웨이 코드 검사).',
        max_length=2,
    )
    source: Source = Field(
        ...,
        description="llm = 질문 이해 LLM 이 고르고 질문 글 근거 조각이 검사를 지났다 · rule = LLM 이 못 골라(공급자 장애·느림·근거 없음) 상품 표의 선언 낱말로 골랐다 · fallback = 그것도 없어 직전 상품(없으면 studio)으로 갔다. · interpretation(1.1) = 질문 해석 한 번(정형·대상 종류·표현 방식 — 근거 글 조각을 코드가 검사)의 결과와 질의자 권한으로 게이트웨이가 상품 표에서 정했다(LLM 이 상품 이름을 고르지 않았다). 1.1 한 번 해석 경로에서 rule 은 '선언 낱말이 실제로 걸려 한 상품만 가리켰다(갈림 없음)'도 뜻한다 — 그때 질문 해석(정형) LLM 이 돌았더라도 상품은 낱말이 정했으므로 model 칸이 없다.",
    )
    model: constr(min_length=1, max_length=120) | None = Field(
        None,
        description='source=llm 일 때 고른 모델 이름(공급자가 돌려준 것) · source=interpretation 이면 해석을 LLM 이 했을 때만 그 모델(선택). rule·fallback 이면 칸이 없다.',
    )


class IdSource(Enum):
    """
    세션이 있으면 서버가 airos_session 으로 덮어쓴다. declared 는 검증됨이 아니다
    """

    airos_session = 'airos_session'
    declared = 'declared'


class Asker(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    login_id: constr(pattern=r'^[a-z]+\.[a-z_]+\.[0-9]{3}$')
    alias: constr(max_length=60) | None = None
    persona: constr(pattern=r'^P-[A-Z]{2,5}$') | None = None
    id_source: IdSource | None = Field(
        None,
        description='세션이 있으면 서버가 airos_session 으로 덮어쓴다. declared 는 검증됨이 아니다',
    )


class Request(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    question_ko: constr(pattern=r'\S', min_length=1, max_length=4000) = Field(
        ...,
        description='사용자가 질문 상자에 쓴 글 그대로(airo_request.query 와 같은 길이 상한).',
    )
    surface: Literal['stage'] = Field(
        ...,
        description='부른 화면 — 통합 화면(Studio /stage) 하나뿐이다. 다른 표면은 자기 질의 봉투(airo_request)를 쓴다.',
    )
    asker: Asker | None = Field(
        None,
        description='지금 화면에 보이는 질의자(선택). 기록용이며, 1.1 한 번 해석 경로(게이트웨이 정형 질문 스위치 켬)에서는 질의자가 쓸 수 없는 상품을 고르지 않는 데에도 쓴다(선언 페르소나로 읽는다 — 자료 접근 권한은 그대로 고른 상품의 입구가 본다). 세션 검증을 하지 않으므로 늘 선언 질의자로 기록한다(id_source 를 airos_session 이라 적어 보내도 검증됨이 아니다).',
    )
    prior_product: Product | None = Field(
        None,
        description='직전 답을 낸 상품(선택). 고르기가 실패하면 여기로 간다(없으면 studio). 이어 묻기면 LLM 에게도 보인다.',
    )
    continuation: RouteContinuation | None = None


class AiroAiroProductRouteV1(RootModel[Request | Response]):
    root: Request | Response = Field(
        ...,
        description='통합 화면(Studio 새 경로 /stage — 질문 상자 하나)이 질문을 어느 상품(studio · airos · be3d · agentleague · mcp)으로 보낼지 게이트웨이에 묻는 계약(POST /v2/route-product). 요청 = $defs/Request · 응답 = $defs/Response. LLM 은 상품 하나와 그 이유 한 줄만 고른다 — 질의자·대상·값은 고르지 않는다(질의자는 고른 상품의 기본 질의자 규칙이 정한다). LLM 이 못 고르면 규칙(게이트웨이 상품 표의 선언 낱말), 그것도 없으면 직전 상품(없으면 studio). 1.1(2026-10-01 19:5x 사용자 결정 · 공모전 docs/CAPABILITY_FIRST_QUERY_DESIGN_2026-09-30.md §3.1 한 번 해석): 게이트웨이 정형 질문 스위치가 켜져 있으면 LLM 이 상품 이름을 고르지 않는다 — 규칙이 확실하면 LLM 없이(rule), 아니면 질문 해석 한 번(정형·표현 방식)에서 서버가 상품을 정한다(interpretation). 근거 = 공모전 docs/INTEGRATED_INTERFACE_AND_LLM_ROLE_RESEARCH_2026-10-01.md D1(사용자 결정 2026-10-01 09:5x · 통합 화면 + LLM 상품 선택) · docs/PRODUCT_ROLES_AND_QUESTION_SET_PLAN_2026-09-30.md §0(상품 역할).',
        title='AIRO 통합 화면 상품 고르기 (airo-product-route/v1)',
    )
