# generated by datamodel-codegen:
#   filename:  airos_replay_anomaly_policy.json
#   timestamp: 2026-09-27T01:23:42+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class Source(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: Literal[
        '공모전/2026-04-24_AI챔피언_전국민AI경진대회/validation/query500/store_ops_brief_support.py'
    ]
    sha256: Literal['682d4091a9ffef2133531080bac9a0bdaeba49ccb8613d0402ce80b87622a4e5']
    basis: Literal[
        'Existing 2026-09-13 delegated and explicitly declared replay criteria; no new threshold or date chosen.'
    ]


class AirosReplayAnomalyPolicy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    policy_id: Literal['airos-query500-replay-anomaly']
    version: Literal['1.0']
    classification: Literal['declared_replay_analysis_policy']
    timezone: Literal['Asia/Seoul']
    replay_day: Literal['2022-07-21']
    previous_day: Literal['2022-07-20']
    baseline_start: Literal['2022-06-01']
    baseline_end_exclusive: Literal['2022-07-01']
    sensor_start: Literal['2022-07-01']
    sensor_end_exclusive: Literal['2022-08-01']
    residual_z_threshold: float
    comparison: Literal['strictly_greater']
    standard_deviation: Literal['population']
    sensor_rule: Literal['all_observed_thermostat_values_zero; missing_is_unknown']
    execution_authorized: Literal[False]
    source: Source
