# generated by datamodel-codegen:
#   filename:  anomaly_response.json
#   timestamp: 2026-06-30T02:29:41+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, Field, confloat


class EntityType(Enum):
    """
    분석 대상 유형
    """

    building = 'building'
    ven = 'ven'


class Method(Enum):
    """
    이상탐지 알고리즘
    """

    z_score = 'z_score'
    isolation_forest = 'isolation_forest'
    forecast_residual = 'forecast_residual'
    lstm_ae = 'lstm_ae'


class Status(Enum):
    """
    이상 상태 분류
    """

    normal = 'normal'
    warning = 'warning'
    anomaly = 'anomaly'


class Details(BaseModel):
    """
    알고리즘별 상세 지표
    """

    z_score: float | None = Field(None, description='z-score 값 (|z| ≥ 3.0 → anomaly)')
    window_hours: int | None = Field(None, description='슬라이딩 윈도우 크기 (시간)')
    mean_kw: float | None = Field(None, description='윈도우 평균 전력 (kW)')
    std_kw: float | None = Field(None, description='윈도우 표준편차 (kW)')
    current_kw: float | None = Field(None, description='현재 측정 전력 (kW)')
    forecast_residual_kwh: float | None = Field(
        None, description='예측값과 실측값의 차이 (kWh, forecast_residual 방법 시)'
    )


class Window(BaseModel):
    """
    분석에 사용된 시계열 구간
    """

    start: AwareDatetime | None = None
    end: AwareDatetime | None = None
    points: int | None = Field(None, description='데이터 포인트 수')


class AnomalyResponse(BaseModel):
    """
    건물/VEN 이상탐지 API 응답. VW: GET /api/v1/smart-building/{pnu}/anomaly, GB MQTT: _check_anomaly()
    """

    entity_id: str = Field(
        ...,
        description='건물 PNU(19자리) 또는 VEN ID',
        examples=['1168010300100140000', 'VEN-STORE-B008'],
    )
    entity_type: EntityType = Field(..., description='분석 대상 유형')
    method: Method = Field(..., description='이상탐지 알고리즘', examples=['z_score'])
    status: Status = Field(..., description='이상 상태 분류')
    score: confloat(ge=0.0, le=1.0) = Field(
        ..., description='이상 점수 (0.0 = 정상, 1.0 = 최대 이상)'
    )
    threshold: float | None = Field(
        None,
        description='이상 판정 임계값 (score > threshold → anomaly)',
        examples=[0.7],
    )
    details: Details | None = Field(None, description='알고리즘별 상세 지표')
    triggered_at: AwareDatetime | None = Field(
        None, description='이상 감지 시각 (ISO 8601, UTC)'
    )
    window: Window | None = Field(None, description='분석에 사용된 시계열 구간')
