# generated by datamodel-codegen:
#   filename:  auth_policy.json
#   timestamp: 2026-06-30T02:29:43+00:00

from __future__ import annotations

from pydantic import BaseModel


class AuthPolicySsotPhaseJ10(BaseModel):
    """
    JWT·쿠키·refresh token 정책. auth_scopes.json 의 권한 매핑은 별개, 본 SSOT는 토큰 발급·유효기간·전송 채널 정책.
    """
