# generated by datamodel-codegen:
#   filename:  auth_scopes.json
#   timestamp: 2026-06-30T02:29:47+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, RootModel, constr


class AuthScopesRbacSsotPhaseI2(BaseModel):
    """
    워크스페이스 공통 RBAC. edge-agent admin/operator/technician + AgentLeague admin + EduArena student/teacher/admin + building-energy-3d guest 통합. permissions 매트릭스는 verb:resource 라벨.
    """

    scopes: dict[str, Any] | None = None
    permissions: dict[str, Any] | None = None
    project_default_scopes: dict[str, Any] | None = None


class Scope(Enum):
    super_admin = 'super_admin'
    admin = 'admin'
    operator = 'operator'
    technician = 'technician'
    teacher = 'teacher'
    student = 'student'
    guest = 'guest'


class Permission(RootModel[constr(pattern=r'^(read|write|delete|exec):[a-z_]+$')]):
    root: constr(pattern=r'^(read|write|delete|exec):[a-z_]+$') = Field(
        ..., description='verb:resource (예: write:portfolio, read:telemetry)'
    )
