# generated by datamodel-codegen:
#   filename:  building_usage_map.json
#   timestamp: 2026-09-28T13:48:25+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class EnergyPattern(BaseModel):
    """
    에너지 사용 분담 (collect_energy.py _FRACS 호환)
    """

    heating: float | None = None
    cooling: float | None = None
    hot_water: float | None = None
    lighting: float | None = None
    ventilation: float | None = None


class UsageEntry(BaseModel):
    code: str = Field(..., description='건축물대장 code (예: 02000)')
    name_kr: str
    name_en: str
    registry_usage: str | None = Field(
        ...,
        description='usage_archetype.rows 의 키(또는 usage_aliases 키) — 원형은 그 행에서 파생한다(손으로 적지 않는다). null = 원형 없음(기타 등 — 기본 원형으로 채우지 않는다).',
    )
    default_eui_kwh_m2: float | None = None
    energy_pattern: EnergyPattern | None = Field(
        None, description='에너지 사용 분담 (collect_energy.py _FRACS 호환)'
    )


class Rule(Enum):
    office_by_gross_floor_area = 'office_by_gross_floor_area'
    apartment_by_floors = 'apartment_by_floors'


class Classification(Enum):
    """
    assumed = 가장 가까운 원형의 선언 가정(확장 용도)
    """

    declared = 'declared'
    assumed = 'assumed'


class UsageArchetypeRow1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    archetype: constr(pattern=r'^B(0[1-9]|1[0-8])$') | None
    rule: Rule | None = None
    basis: str | None = None
    classification: Classification | None = Field(
        None, description='assumed = 가장 가까운 원형의 선언 가정(확장 용도)'
    )
    absence: str | None = Field(
        None, description='archetype 이 null 인 행의 결손 이름(예 no_doe_archetype)'
    )
    detail_of: str | None = Field(
        None,
        description='세부 용도 행이 속한 대장 주용도(예 편의점 → 제1종근린생활시설). 세부 용도를 알면 이 행이 주용도 행보다 앞선다',
    )


class UsageArchetypeRow2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    archetype: constr(pattern=r'^B(0[1-9]|1[0-8])$') | None = None
    rule: Rule
    basis: str | None = None
    classification: Classification | None = Field(
        None, description='assumed = 가장 가까운 원형의 선언 가정(확장 용도)'
    )
    absence: str | None = Field(
        None, description='archetype 이 null 인 행의 결손 이름(예 no_doe_archetype)'
    )
    detail_of: str | None = Field(
        None,
        description='세부 용도 행이 속한 대장 주용도(예 편의점 → 제1종근린생활시설). 세부 용도를 알면 이 행이 주용도 행보다 앞선다',
    )


class UsageArchetypeRow(RootModel[UsageArchetypeRow1 | UsageArchetypeRow2]):
    root: UsageArchetypeRow1 | UsageArchetypeRow2


class UsageArchetype(BaseModel):
    """
    주용도 → 원형 정본. 표에 없는 용도·용도 미상은 원형 없음(기본 원형으로 채우지 않는다) — 결손 종류는 absence 칸.
    """

    rows: dict[str, UsageArchetypeRow] | None = None
    office_by_gross_floor_area: dict[str, Any] | None = None
    apartment_by_floors: dict[str, Any] | None = None
    absence: dict[str, Any] | None = None
    decision: str | None = None
    usage_aliases: dict[str, str] | None = Field(
        None, description='세부 용도·옛 이름 → 주용도(rows 키).'
    )


class BuildingUsageMapSsotPhaseJ7(BaseModel):
    """
    건축물대장 용도 코드 ↔ archetype ↔ 에너지 사용패턴 매핑. 한국(740만 건물) + 인도네시아 BEMS(12.5M ASEAN 건물). v1.1 (2026-09-28): usage_archetype = 건축물대장 주용도 → 원형(Bxx) **정본 한 표**. 사본 8벌(EC 2·be-3d 2·AIROS 2·Studio 2)이 업무시설을 대형/중형 사무소로 갈라 답했다. usages[*] 는 registry_usage 로 이 표를 가리키고 원형은 생성기가 파생한다(v1.2).
    """

    usage_archetype: UsageArchetype | None = Field(
        None,
        description='주용도 → 원형 정본. 표에 없는 용도·용도 미상은 원형 없음(기본 원형으로 채우지 않는다) — 결손 종류는 absence 칸.',
    )
