# generated by datamodel-codegen:
#   filename:  building_usage_map.json
#   timestamp: 2026-06-30T02:30:09+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class BuildingUsageMapSsotPhaseJ7(BaseModel):
    """
    건축물대장 용도 코드 ↔ archetype ↔ 에너지 사용패턴 매핑. 한국(729만 건물) + 인도네시아 BEMS(12.5M ASEAN 건물).
    """


class EnergyPattern(BaseModel):
    """
    에너지 사용 분담 (collect_energy.py _FRACS 호환)
    """

    heating: float | None = None
    cooling: float | None = None
    hot_water: float | None = None
    lighting: float | None = None
    ventilation: float | None = None


class UsageEntry(BaseModel):
    code: str = Field(..., description='건축물대장 code (예: 02000)')
    name_kr: str
    name_en: str
    archetype: str = Field(..., description='EnergyPlus archetype 매핑')
    default_eui_kwh_m2: float | None = None
    energy_pattern: EnergyPattern | None = Field(
        None, description='에너지 사용 분담 (collect_energy.py _FRACS 호환)'
    )
