# generated by datamodel-codegen:
#   filename:  building_passport.json
#   timestamp: 2026-09-11T10:06:11+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, confloat, constr


class DataTier(Enum):
    """
    basic=기본정보, eui_only=EUI/연합계, historical_series=월·일·시간 이력, building_and_measured=건물·설비정보와 실측, realtime_control=최신 telemetry·point map·제어권한.
    """

    basic = 'basic'
    eui_only = 'eui_only'
    historical_series = 'historical_series'
    building_and_measured = 'building_and_measured'
    realtime_control = 'realtime_control'


class AssetClass(Enum):
    building = 'building'
    home = 'home'
    site = 'site'
    portfolio_member = 'portfolio_member'


class Identity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pnu: constr(pattern=r'^[0-9]{19}$') | None = None
    asset_class: AssetClass
    use_type: str | None = None
    timezone: str | None = 'Asia/Seoul'


class BuildingMetadata(Enum):
    none = 'none'
    register = 'register'
    drawing = 'drawing'
    field_verified = 'field_verified'


class Geometry(Enum):
    none = 'none'
    footprint = 'footprint'
    floor_zones = 'floor_zones'
    zone_mesh = 'zone_mesh'


class Equipment(Enum):
    none = 'none'
    type_only = 'type_only'
    inventory = 'inventory'
    topology = 'topology'
    point_mapped = 'point_mapped'


class EnergyHistory(Enum):
    none = 'none'
    annual_total = 'annual_total'
    monthly = 'monthly'
    daily = 'daily'
    hourly = 'hourly'
    subhourly = 'subhourly'


class ControlAuthority(Enum):
    none = 'none'
    advisory = 'advisory'
    shadow = 'shadow'
    approval_required = 'approval_required'
    bounded_auto = 'bounded_auto'


class Availability(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    building_metadata: BuildingMetadata
    geometry: Geometry | None = None
    equipment: Equipment | None = None
    energy_history: EnergyHistory
    history_start: AwareDatetime | None = None
    history_end: AwareDatetime | None = None
    coverage_ratio: confloat(ge=0.0, le=1.0) | None = None
    realtime_telemetry: bool
    telemetry_as_of: AwareDatetime | None = None
    control_authority: ControlAuthority


class SourceType(Enum):
    measured = 'measured'
    document = 'document'
    register = 'register'
    derived = 'derived'
    estimated = 'estimated'
    archetype = 'archetype'


class KnownField(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field: str
    source_type: SourceType
    source_ref: str | None = None
    confidence: confloat(ge=0.0, le=1.0)
    observed_at: AwareDatetime | None = None


class Provenance(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    manifest_ref: constr(min_length=1)
    content_hash: constr(pattern=r'^(sha256:)?[a-fA-F0-9]{64}$')
    data_timestamp: AwareDatetime | None = None
    restrictions: list[str] | None = None


class BuildingPassport(BaseModel):
    """
    건물 의사결정 시점에 무엇을 알고 무엇을 모르는지 고정하는 데이터 여권. 건물 모델 자체가 아니라 모델 라우팅·증거표시의 입력 계약이다.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    passport_id: constr(min_length=1)
    building_id: constr(min_length=1)
    captured_at: AwareDatetime
    data_tier: DataTier = Field(
        ...,
        description='basic=기본정보, eui_only=EUI/연합계, historical_series=월·일·시간 이력, building_and_measured=건물·설비정보와 실측, realtime_control=최신 telemetry·point map·제어권한.',
    )
    identity: Identity
    availability: Availability
    known_fields: list[KnownField] | None = None
    provenance: Provenance
