# generated by datamodel-codegen:
#   filename:  building_passport.json
#   timestamp: 2026-09-12T04:16:23+00:00

from __future__ import annotations

from enum import Enum

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    confloat,
    conint,
    constr,
)


class DataTier(Enum):
    """
    basic=기본정보, eui_only=EUI/연합계, historical_series=월·일·시간 이력, building_and_measured=건물·설비정보와 실측, realtime_control=최신 telemetry·point map·제어권한.
    """

    basic = 'basic'
    eui_only = 'eui_only'
    historical_series = 'historical_series'
    building_and_measured = 'building_and_measured'
    realtime_control = 'realtime_control'


class PhysicalIdentity(Enum):
    """
    여권의 주어 수준. building = building_mgmt_no 있음(BuildingIdentity.official_building), parcel = 필지만(parcel_proxy), none = 둘 다 없음.
    """

    building = 'building'
    parcel = 'parcel'
    none = 'none'


class IdentityMatchStatus(Enum):
    """
    물리 식별의 매치 등급 — building_model_packet BuildingIdentity.selected_identifier_match_status 와 같은 어휘. exact = 소유자 원장이 verified 로 승격, probable = 공공대장 후보(candidate/candidate_physical), unmatched = 번호 없음·ambiguous·not_found. probable 을 exact 로 오표현하지 않기 위한 필드.
    """

    exact = 'exact'
    probable = 'probable'
    unmatched = 'unmatched'


class AssetClass(Enum):
    building = 'building'
    home = 'home'
    site = 'site'
    portfolio_member = 'portfolio_member'


class ResidentialSubtype(Enum):
    detached_prosumer = 'detached_prosumer'
    apartment = 'apartment'


class Identity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    building_mgmt_no: constr(pattern=r'^[0-9]{25}$') | None = Field(
        None,
        description='25자리 건물관리번호(건축물대장 bld_mgt_sn). 물리 건물 하나. 앞 19자리 = parcel_id. 공공데이터(주소검색 bdMgtSn 또는 필지 위 건물 목록)에서만 온다.',
    )
    parcel_id: constr(pattern=r'^[0-9]{19}$') | None = Field(
        None,
        description='19자리 필지 PNU. 필지 단위 에너지의 공유 근거 키. pnu 는 호환 별칭으로 같은 값.',
    )
    pnu: constr(pattern=r'^[0-9]{19}$') | None = None
    physical_identity: PhysicalIdentity | None = Field(
        None,
        description='여권의 주어 수준. building = building_mgmt_no 있음(BuildingIdentity.official_building), parcel = 필지만(parcel_proxy), none = 둘 다 없음.',
    )
    identity_match_status: IdentityMatchStatus | None = Field(
        None,
        description='물리 식별의 매치 등급 — building_model_packet BuildingIdentity.selected_identifier_match_status 와 같은 어휘. exact = 소유자 원장이 verified 로 승격, probable = 공공대장 후보(candidate/candidate_physical), unmatched = 번호 없음·ambiguous·not_found. probable 을 exact 로 오표현하지 않기 위한 필드.',
    )
    asset_class: AssetClass
    use_type: str | None = None
    residential_subtype: ResidentialSubtype | None = None
    built_year: conint(ge=1800, le=2200) | None = None
    vintage_class: constr(max_length=50) | None = None
    district: constr(max_length=100) | None = None
    timezone: str | None = 'Asia/Seoul'


class BuildingMetadata(Enum):
    none = 'none'
    register = 'register'
    drawing = 'drawing'
    field_verified = 'field_verified'


class Geometry(Enum):
    none = 'none'
    footprint = 'footprint'
    floor_zones = 'floor_zones'
    zone_mesh = 'zone_mesh'


class Equipment(Enum):
    none = 'none'
    type_only = 'type_only'
    inventory = 'inventory'
    topology = 'topology'
    point_mapped = 'point_mapped'


class EnergyHistory(Enum):
    none = 'none'
    annual_total = 'annual_total'
    monthly = 'monthly'
    daily = 'daily'
    hourly = 'hourly'
    subhourly = 'subhourly'


class ControlAuthority(Enum):
    none = 'none'
    advisory = 'advisory'
    shadow = 'shadow'
    approval_required = 'approval_required'
    bounded_auto = 'bounded_auto'


class Availability(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    building_metadata: BuildingMetadata
    geometry: Geometry | None = None
    equipment: Equipment | None = None
    energy_history: EnergyHistory
    history_start: AwareDatetime | None = None
    history_end: AwareDatetime | None = None
    coverage_ratio: confloat(ge=0.0, le=1.0) | None = None
    realtime_telemetry: bool
    telemetry_as_of: AwareDatetime | None = None
    control_authority: ControlAuthority


class SourceType(Enum):
    measured = 'measured'
    document = 'document'
    register = 'register'
    derived = 'derived'
    estimated = 'estimated'
    archetype = 'archetype'


class KnownField(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field: str
    source_type: SourceType
    source_ref: str | None = None
    confidence: confloat(ge=0.0, le=1.0)
    observed_at: AwareDatetime | None = None


class Provenance(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    manifest_ref: constr(min_length=1)
    content_hash: constr(pattern=r'^(sha256:)?[a-fA-F0-9]{64}$')
    data_timestamp: AwareDatetime | None = None
    restrictions: list[str] | None = None


class BuildingPassport(BaseModel):
    """
    건물 의사결정 시점에 무엇을 알고 무엇을 모르는지 고정하는 데이터 여권. 건물 모델 자체가 아니라 모델 라우팅·증거표시의 입력 계약이다.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    passport_id: constr(min_length=1)
    building_id: constr(min_length=1)
    captured_at: AwareDatetime
    data_tier: DataTier = Field(
        ...,
        description='basic=기본정보, eui_only=EUI/연합계, historical_series=월·일·시간 이력, building_and_measured=건물·설비정보와 실측, realtime_control=최신 telemetry·point map·제어권한.',
    )
    identity: Identity
    availability: Availability
    known_fields: list[KnownField] | None = None
    provenance: Provenance
