# generated by datamodel-codegen:
#   filename:  building_archetypes.json
#   timestamp: 2026-09-30T21:53:11+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, conint, constr


class DoeBuildings(BaseModel):
    name_en: str | None = None
    area_m2: float | None = Field(
        None,
        description='원형 연면적 ㎡ — v4 정본(8.simulation docs/_ssot/template_floor_area_v4.json, _shared/floor_area_ssot.area_for)과 같은 값(2026-09-28 O2 정정: B02 4,982→12,000 · B04 4,835→4,598.25 · B16 1,457→3,134.61 · B17 3,135→7,836.48 등). EUI 분모가 이 값이다',
    )
    hvac_types: list[str] | None = None
    representative_hvac: constr(pattern=r'^H[A-G]$') | None = Field(
        None,
        description='원형의 대표 냉난방(설비 조합을 모를 때 하나를 고르는 규칙 — hvac_types 중 하나). 2026-09-28 최종 라운드: be-3d policy_savings._HVAC_REPRESENTATIVE 손 표를 이관. 한국 실정 = 중층 아파트 개별 가스보일러 온돌(HE) · 고층 아파트 지역난방(HG) · 단독주택 HE — hvac_types 의 첫 값이 대표가 아니다(B16 첫 값 HD · B17 첫 값 HE). 모르는 원형은 기본값 없음(이름 있는 결손)',
    )
    electricity_price_class: str | None = Field(
        None,
        description='원형의 전기 요금 종별(target_vocabulary.electricity_price_classes 의 열쇠 — 규칙 = default.electricity_price_class_rule). 자산 종류가 없는 원형 대상의 참조 단가를 고르는 칸(계약 요금이 아니다)',
    )
    kbep_id: conint(ge=0) | None = Field(
        None, description='KBEP building_type 정수(B01=0…B18=17)'
    )
    name_kr: str | None = None
    snake: str | None = Field(
        None, description='snake_case 표기(게이트웨이 kbep_client 키)'
    )
    aliases: list[str] | None = Field(
        None,
        description='그 밖에 들어오는 표기(짧은 코드 LO/MO 등·옛 철자). 코드·영문·snake·한글·정수는 생성기가 붙인다',
    )
    source: str | None = None


class RetrofitScenario(BaseModel):
    name_kr: str | None = None
    name_en: str | None = None
    eui_reduction_pct: float | None = None
    cost_per_m2_krw: int | None = None


class EnergyMix(BaseModel):
    electricity: float | None = None
    gas: float | None = None
    district_heat: float | None = None


class BuildingArchetypes(BaseModel):
    """
    건물 유형·용도 매핑·BUILDWISE EUI SSOT. NAMING_UNIFICATION.md §2 + constants.py 기반. v2.1 (2026-09-28 일반화 G0·G1): B18 단독주택(한국 자산 KR_DetachedHouse, DOE 원형 아님) 추가 — 게이트웨이·KBEP·Studio 는 이미 17번으로 쓰고 있었다. 원형마다 축 어휘 칸(kbep_id·name_kr·snake·aliases)을 더해 KBEP 인코더 사본들이 이 표에서 파생되게 했다. usage_to_buildwise 는 building_usage_map.usage_archetype (용도→원형 정본 한 표)과 archetype_to_buildwise 에서 파생된 투영이다(validate_ssot 가 대조).
    """

    doe_buildings: dict[str, DoeBuildings] | None = Field(
        None,
        description='원형 B01~B18. B01~B17 = DOE Commercial Reference Building, B18 = 한국 단독주택 자산(KR_DetachedHouse 1존 85 m², 8.simulation docs/B18_DETACHED_HOUSE_ONBOARDING_2026-09-13.md). kbep_id = KBEP 정수 축(B01=0 … B18=17).',
    )
    usage_to_buildwise: dict[str, str] | None = Field(
        None, description='한국 건축 용도 → BuildWise 건물 유형 매핑'
    )
    default_buildwise_type: str | None = None
    buildwise_eui_seoul: dict[str, dict[str, float]] | None = Field(
        None,
        description='BuildWise EUI 룩업 (kWh/m2/yr, 서울 기준). 키=건물유형, 값=전략별 EUI',
    )
    retrofit_scenarios: list[RetrofitScenario] | None = Field(
        None, description='리트로핏 시나리오별 절감률·단가'
    )
    usage_retrofit_factor: dict[str, float] | None = Field(
        None, description='용도별 리트로핏 절감률 보정 계수 (업무시설=1.0 기준)'
    )
    energy_mix: dict[str, EnergyMix] | None = Field(
        None,
        description='용도별 에너지 믹스 (전기/가스/지역난방 비율). ENERGY_SSOT.md §5.',
    )
    archetype_to_buildwise: dict[str, str] | None = Field(
        None,
        description='원형(Bxx) → BuildWise EUI 표의 유형. 표에 그 유형이 없으면 대리 유형(주거·숙박 → medium_office). usage_to_buildwise 는 usage_archetype 과 이 표의 합성이다.',
    )
