# generated by datamodel-codegen:
#   filename:  building_archetypes.json
#   timestamp: 2026-06-30T02:29:54+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class DoeBuildings(BaseModel):
    name_en: str | None = None
    area_m2: float | None = None
    hvac_types: list[str] | None = None


class RetrofitScenario(BaseModel):
    name_kr: str | None = None
    name_en: str | None = None
    eui_reduction_pct: float | None = None
    cost_per_m2_krw: int | None = None


class EnergyMix(BaseModel):
    electricity: float | None = None
    gas: float | None = None
    district_heat: float | None = None


class BuildingArchetypes(BaseModel):
    """
    건물 유형·용도 매핑·BUILDWISE EUI SSOT. NAMING_UNIFICATION.md §2 + constants.py 기반.
    """

    doe_buildings: dict[str, DoeBuildings] | None = Field(
        None, description='DOE Reference Building B01~B17'
    )
    usage_to_buildwise: dict[str, str] | None = Field(
        None, description='한국 건축 용도 → BuildWise 건물 유형 매핑'
    )
    default_buildwise_type: str | None = None
    buildwise_eui_seoul: dict[str, dict[str, float]] | None = Field(
        None,
        description='BuildWise EUI 룩업 (kWh/m2/yr, 서울 기준). 키=건물유형, 값=전략별 EUI',
    )
    retrofit_scenarios: list[RetrofitScenario] | None = Field(
        None, description='리트로핏 시나리오별 절감률·단가'
    )
    usage_retrofit_factor: dict[str, float] | None = Field(
        None, description='용도별 리트로핏 절감률 보정 계수 (업무시설=1.0 기준)'
    )
    energy_mix: dict[str, EnergyMix] | None = Field(
        None,
        description='용도별 에너지 믹스 (전기/가스/지역난방 비율). ENERGY_SSOT.md §5.',
    )
