# generated by datamodel-codegen:
#   filename:  building_envelope.json
#   timestamp: 2026-06-30T02:30:05+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, Field, confloat, conint


class SourceOfTruth(Enum):
    """
    정확성 출처. field=현장 실측 / 에너지진단 / 준공도면, register=건축물대장, archetype=용도·연대별 원형 추정치. 우선순위: field > register > archetype.
    """

    field = 'field'
    register = 'register'
    archetype = 'archetype'


class Structure(Enum):
    """
    구조 분류. RC=철근콘크리트, SRC=철골철근콘크리트.
    """

    RC = 'RC'
    SRC = 'SRC'
    wood = 'wood'
    steel = 'steel'
    masonry = 'masonry'
    other = 'other'


class Geometry(BaseModel):
    """
    건물 기하. floor_area_m2 는 시뮬레이션 baseline_kw 계산의 핵심 입력.
    """

    floor_area_m2: confloat(ge=1.0) | None = Field(
        None, description='연면적 m². 대장 vs 실측 차이 최대 30% 가능.'
    )
    conditioned_area_m2: confloat(ge=1.0) | None = Field(
        None, description='냉난방 공조면적 m². 보통 연면적 × 0.7~0.9.'
    )
    floor_count: conint(ge=1) | None = Field(None, description='지상 층수. 지하 제외.')
    basement_count: conint(ge=0) | None = Field(None, description='지하 층수.')
    built_year: conint(ge=1900, le=2100) | None = Field(
        None, description='준공 연도. archetype 선택의 핵심 키.'
    )
    orientation_deg: confloat(ge=0.0, lt=360.0) | None = Field(
        None, description='정면 방위각 (북=0, 동=90, 남=180, 서=270).'
    )
    structure: Structure | None = Field(
        None, description='구조 분류. RC=철근콘크리트, SRC=철골철근콘크리트.'
    )


class Envelope(BaseModel):
    """
    외피 열성능. 단위: U-value = W/m²·K, WWR/SHGC/VLT = 0~1 비율.
    """

    wall_uvalue: confloat(ge=0.1, le=5.0) | None = Field(
        None,
        description='외벽 열관류율 W/m²·K. 건축물대장 미기재 → archetype 추정. 실측은 열화상·열류계.',
    )
    roof_uvalue: confloat(ge=0.1, le=5.0) | None = Field(
        None, description='지붕 열관류율 W/m²·K.'
    )
    floor_uvalue: confloat(ge=0.1, le=5.0) | None = Field(
        None, description='하부 바닥(외기·지반 접촉) 열관류율 W/m²·K.'
    )
    window_uvalue: confloat(ge=0.5, le=7.0) | None = Field(
        None,
        description='창호 열관류율 W/m²·K. Low-E 복층=1.8~2.4, 일반 복층=2.8~3.3, 단층=5.8+.',
    )
    wwr: confloat(ge=0.0, le=1.0) | None = Field(
        None, description='Window-to-Wall Ratio. 오피스 평균 0.4, 편의점 0.25~0.35.'
    )
    shgc: confloat(ge=0.0, le=1.0) | None = Field(
        None, description='Solar Heat Gain Coefficient. Low-E=0.3~0.5, 일반=0.7~0.85.'
    )
    vlt: confloat(ge=0.0, le=1.0) | None = Field(
        None, description='Visible Light Transmittance. 주광 활용 해석용.'
    )
    infiltration_ach50: confloat(ge=0.0) | None = Field(
        None, description='기밀도 ACH @ 50 Pa. 신축 강화=1.5, 일반=4~8, 노후=10+.'
    )


class HvacType(Enum):
    """
    주 공조 방식. VRF=냉매 가변유량, EHP=전기 히트펌프, GHP=가스 히트펌프.
    """

    VRF = 'VRF'
    EHP = 'EHP'
    GHP = 'GHP'
    chiller_boiler = 'chiller_boiler'
    district_heating = 'district_heating'
    individual_ac = 'individual_ac'
    packaged_rooftop = 'packaged_rooftop'
    none = 'none'


class Systems(BaseModel):
    """
    설비 메타. COP/효율은 EnergyPlus 시뮬 baseline 설정에 사용.
    """

    hvac_type: HvacType | None = Field(
        None,
        description='주 공조 방식. VRF=냉매 가변유량, EHP=전기 히트펌프, GHP=가스 히트펌프.',
    )
    hvac_cop_cooling: confloat(ge=1.0, le=10.0) | None = Field(
        None, description='냉방 COP. VRF 신형=4.0+, 일반=3.0~3.5.'
    )
    hvac_cop_heating: confloat(ge=1.0, le=10.0) | None = Field(
        None, description='난방 COP. 히트펌프 3.0~4.0.'
    )
    boiler_efficiency: confloat(ge=0.0, le=1.0) | None = Field(
        None, description='보일러 열효율. 콘덴싱=0.92+, 일반=0.85.'
    )
    lighting_lpd_w_m2: confloat(ge=0.0, le=50.0) | None = Field(
        None, description='조명 밀도 W/m². LED 교체 후=5~8, 형광등=12~15.'
    )
    plug_load_w_m2: confloat(ge=0.0) | None = Field(
        None, description='기기부하 밀도 W/m². 오피스=10~15, 편의점 냉장설비 포함=30+.'
    )
    has_ess: bool | None = False
    ess_capacity_kwh: confloat(ge=0.0) | None = Field(
        None, description='ESS 정격 용량 kWh. has_ess=true 일 때 필수.'
    )
    ess_power_kw: confloat(ge=0.0) | None = Field(None, description='ESS 정격 출력 kW.')
    has_pv: bool | None = False
    pv_capacity_kw: confloat(ge=0.0) | None = Field(
        None, description='태양광 정격 kW-DC. has_pv=true 일 때 필수.'
    )


class Overrides(BaseModel):
    """
    VEN 개별 오버라이드 메모. 기본 archetype 대비 변경된 필드만 기록. YAML Tier 3 (RFC §4.2) 대응.
    """

    base_archetype: str | None = None
    changed_fields: list[str] | None = Field(
        None,
        description="오버라이드된 필드 경로. 예: ['envelope.wall_uvalue', 'systems.hvac_cop_cooling'].",
    )


class BuildingEnvelope(BaseModel):
    """
    건물 외피·기하·설비 메타. 건축물대장 부정확 문제 해결용 — 현장 실측(field) 우선, 대장(register) 차선, 원형(archetype) 최후. Edge 등록 시 fleet/register 페이로드에 embed 가능하며 VW 측에서 포트폴리오 UI 로 편집.
    """

    source_of_truth: SourceOfTruth = Field(
        ...,
        description='정확성 출처. field=현장 실측 / 에너지진단 / 준공도면, register=건축물대장, archetype=용도·연대별 원형 추정치. 우선순위: field > register > archetype.',
    )
    measured_at: AwareDatetime | None = Field(
        None,
        description='source_of_truth=field 일 때 실측 일시. register 는 대장 발급일, archetype 은 생략.',
    )
    measured_by: str | None = Field(
        None,
        description="실측 주체. 예: '2024 에너지진단 — 한국에너지공단', '준공도면 — 성동구청'.",
    )
    geometry: Geometry | None = Field(
        None,
        description='건물 기하. floor_area_m2 는 시뮬레이션 baseline_kw 계산의 핵심 입력.',
    )
    envelope: Envelope | None = Field(
        None,
        description='외피 열성능. 단위: U-value = W/m²·K, WWR/SHGC/VLT = 0~1 비율.',
    )
    systems: Systems | None = Field(
        None, description='설비 메타. COP/효율은 EnergyPlus 시뮬 baseline 설정에 사용.'
    )
    weather_zone: str | None = Field(
        None,
        description="기후대. ASHRAE 90.1 (예: '4A') 또는 한국 지역코드 (예: 'seoul', 'busan', 'jeju'). EnergyPlus EPW 파일 선택의 근거.",
    )
    archetype_reference: str | None = Field(
        None,
        description="source_of_truth=archetype 일 때 참조 원형 ID. 예: 'DOE_MediumOffice_2010', 'KR_ConvStore_2015', 'KR_Apt_1990'.",
    )
    overrides: Overrides | None = Field(
        None,
        description='VEN 개별 오버라이드 메모. 기본 archetype 대비 변경된 필드만 기록. YAML Tier 3 (RFC §4.2) 대응.',
    )
    notes: str | None = Field(
        None,
        description="자유 메모. 비정형 정보 (예: '2023 창호 교체', '지하주차장 BMS 연계 없음').",
    )
