# generated by datamodel-codegen:
#   filename:  building_model_packet.json
#   timestamp: 2026-09-11T10:06:11+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    conint,
    constr,
)


class Capability(Enum):
    baseline = 'baseline'
    scenario = 'scenario'
    profile = 'profile'


class Sha256(RootModel[constr(pattern=r'^sha256:[a-f0-9]{64}$')]):
    root: constr(pattern=r'^sha256:[a-f0-9]{64}$')


class ValidationGrade(Enum):
    """
    A=건물 실측 보정, B=동일 cohort 독립검증, C=E+ in-domain 검증, D=탐색용 fallback, U=지원 불가. 직접 E+ 실행만으로 A가 되지 않는다.
    """

    A = 'A'
    B = 'B'
    C = 'C'
    D = 'D'
    U = 'U'


class IdentifierKind(Enum):
    official_building = 'official_building'
    parcel_proxy = 'parcel_proxy'
    virtual_asset = 'virtual_asset'


class IdentityStatus(Enum):
    canonical = 'canonical'
    provisional = 'provisional'
    conflicted = 'conflicted'
    retired = 'retired'


class IdentifierAliasRef(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class SelectedIdentifierMatchStatus(Enum):
    """
    선택된 건물번호/PNU 연결 중 가장 약한 매치 상태. probable을 canonical로 오표현하지 않기 위한 보조 필드.
    """

    exact = 'exact'
    probable = 'probable'
    unmatched = 'unmatched'


class BindingStatusCounts(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    exact: conint(ge=0)
    probable: conint(ge=0)
    conflict: conint(ge=0)


class BuildingIdentity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    identifier_kind: IdentifierKind
    identity_status: IdentityStatus
    bld_mgt_sn: constr(pattern=r'^[0-9]{25}$') | None = None
    pnu: constr(pattern=r'^[0-9]{19}$') | None = None
    identifier_alias_refs: list[IdentifierAliasRef] | None = None
    selected_identifier_match_status: SelectedIdentifierMatchStatus | None = Field(
        None,
        description='선택된 건물번호/PNU 연결 중 가장 약한 매치 상태. probable을 canonical로 오표현하지 않기 위한 보조 필드.',
    )
    binding_status_counts: BindingStatusCounts | None = None


class Resolution(Enum):
    annual = 'annual'
    monthly = 'monthly'
    daily = 'daily'
    hourly = 'hourly'
    subhourly = 'subhourly'


class Status(Enum):
    active = 'active'
    fallback = 'fallback'
    quarantined = 'quarantined'
    unsupported = 'unsupported'


class ModelClass(Enum):
    """
    E0=건물 실측 보정 E+, E1=계층·cohort 보정 E+, E2=E+ 출력 학습 surrogate, E3=E+ 기준선+실측 잔차, E4=E+ archetype lookup·scale, U=지원 불가.
    """

    E0 = 'E0'
    E1 = 'E1'
    E2 = 'E2'
    E3 = 'E3'
    E4 = 'E4'
    U = 'U'


class ReasonCode(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class SimulationManifestRef(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class EPlusLineage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    engine: Literal['EnergyPlus']
    engine_version: constr(min_length=1)
    archetype_id: constr(min_length=1)
    template_id: constr(min_length=1)
    source_idf_hash: Sha256
    config_hash: Sha256
    lineage_hash: Sha256
    simulation_manifest_refs: list[SimulationManifestRef] = Field(..., min_length=1)


class TrainingManifestRef(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class ModelArtifacts(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schedule_profile_ref: constr(min_length=1)
    schedule_profile_hash: Sha256
    surrogate_model_ref: constr(min_length=1) | None = None
    surrogate_model_hash: Sha256 | None = None
    residual_model_ref: constr(min_length=1) | None = None
    residual_model_hash: Sha256 | None = None
    scale_pack_ref: constr(min_length=1) | None = None
    scale_pack_hash: Sha256 | None = None
    calibration_snapshot_ref: constr(min_length=1) | None = None
    calibration_snapshot_hash: Sha256 | None = None
    training_manifest_refs: list[TrainingManifestRef] | None = Field(None, min_length=1)
    uncertainty_profile_ref: constr(min_length=1) | None = None
    uncertainty_profile_hash: Sha256 | None = None


class Purpose(Enum):
    baseline = 'baseline'
    forecast = 'forecast'
    scenario = 'scenario'


class InputMode(Enum):
    epw = 'epw'
    surrogate_features = 'surrogate_features'


class SpatialResolution(Enum):
    station = 'station'
    field_5km_grid = '5km_grid'
    field_1km_grid = '1km_grid'
    site_adjusted = 'site_adjusted'


class ScenarioFamily(Enum):
    current = 'current'
    forecast = 'forecast'
    tmy = 'tmy'
    amy = 'amy'
    ssp126 = 'ssp126'
    ssp245 = 'ssp245'
    ssp370 = 'ssp370'
    ssp585 = 'ssp585'
    custom = 'custom'


class WeatherVariable(Enum):
    dry_bulb_temperature = 'dry_bulb_temperature'
    dew_point_temperature = 'dew_point_temperature'
    relative_humidity = 'relative_humidity'
    station_pressure = 'station_pressure'
    global_horizontal_radiation = 'global_horizontal_radiation'
    direct_normal_radiation = 'direct_normal_radiation'
    diffuse_horizontal_radiation = 'diffuse_horizontal_radiation'
    wind_direction = 'wind_direction'
    wind_speed = 'wind_speed'
    total_sky_cover = 'total_sky_cover'
    opaque_sky_cover = 'opaque_sky_cover'
    precipitation_depth = 'precipitation_depth'


class DatasetType(Enum):
    observed = 'observed'
    forecast = 'forecast'
    tmy = 'tmy'
    amy = 'amy'
    ssp = 'ssp'


class QualityFlag(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class WeatherSnapshot(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    weather_snapshot_id: constr(pattern=r'^wx_[a-zA-Z0-9_-]+$')
    weather_cell_id: constr(min_length=1)
    dataset_type: DatasetType
    source_ref: constr(min_length=1)
    content_hash: Sha256
    captured_at: AwareDatetime
    issued_at: AwareDatetime | None = None
    valid_from: AwareDatetime
    valid_to: AwareDatetime
    timezone: constr(min_length=1)
    spatial_resolution: SpatialResolution
    variables: list[WeatherVariable] = Field(..., min_length=1)
    meets_requirement: Literal[True]
    epw_ready: bool
    epw_hash: Sha256 | None = None
    quality_flags: list[QualityFlag] | None = None


class Status1(Enum):
    in_domain = 'in_domain'
    warning = 'warning'
    out_of_domain = 'out_of_domain'
    not_evaluated = 'not_evaluated'


class OodDimensionStatus(Enum):
    in_domain = 'in_domain'
    warning = 'warning'
    out_of_domain = 'out_of_domain'
    not_evaluated = 'not_evaluated'


class EvidenceRef(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class AssignmentProvenance(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    resolver_version: constr(min_length=1)
    resolver_hash: Sha256
    input_snapshot_hash: Sha256
    assigned_at: AwareDatetime
    evidence_refs: list[EvidenceRef] = Field(..., min_length=1)


class SourceSnapshotRef(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class Provenance(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    producer: constr(min_length=1)
    source_snapshot_refs: list[SourceSnapshotRef] = Field(..., min_length=1)
    input_snapshot_hash: Sha256
    content_hash: Sha256
    evidence_refs: list[EvidenceRef] = Field(..., min_length=1)


class Outcome(Enum):
    served = 'served'
    refused = 'refused'
    need_target = 'need_target'
    need_data = 'need_data'
    unsupported = 'unsupported'


class CapabilitiesUsedEnum(Enum):
    baseline = 'baseline'
    scenario = 'scenario'
    profile = 'profile'


class AssignmentRef(RootModel[constr(pattern=r'^bma_[a-zA-Z0-9_-]+$')]):
    root: constr(pattern=r'^bma_[a-zA-Z0-9_-]+$')


class WeatherSnapshotRef(RootModel[constr(pattern=r'^wx_[a-zA-Z0-9_-]+$')]):
    root: constr(pattern=r'^wx_[a-zA-Z0-9_-]+$')


class Replay(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    run_key: constr(min_length=1)
    replay_hash: Sha256
    code_hash: Sha256
    config_hash: Sha256
    deterministic_inputs_hash: Sha256


class ModelServingReceipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    receipt_id: constr(pattern=r'^msr_[a-zA-Z0-9_-]+$')
    served_at: AwareDatetime
    outcome: Outcome
    request_hash: Sha256
    packet_hash: Sha256
    output_hash: Sha256 | None = None
    capabilities_used: list[CapabilitiesUsedEnum] = Field(..., min_length=1)
    assignment_refs: list[AssignmentRef] = Field(..., min_length=1)
    weather_snapshot_refs: list[WeatherSnapshotRef]
    replay: Replay


class WeatherRequirement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    purpose: Purpose
    input_mode: InputMode
    temporal_resolution: Literal['hourly']
    spatial_resolution: SpatialResolution
    scenario_family: ScenarioFamily
    required_variables: list[WeatherVariable] = Field(..., min_length=1)


class Dimensions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    feature: OodDimensionStatus
    geographic: OodDimensionStatus
    temporal: OodDimensionStatus
    missingness: OodDimensionStatus
    model_disagreement: OodDimensionStatus
    interval_width: OodDimensionStatus


class OodAssessment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Status1
    hard_ood: bool
    dimensions: Dimensions
    reason_codes: list[ReasonCode]
    assessed_at: AwareDatetime
    assessment_hash: Sha256


class WeatherBinding(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    requirement: WeatherRequirement
    snapshot: WeatherSnapshot | None = None


class CapabilityAssignment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assignment_id: constr(pattern=r'^bma_[a-zA-Z0-9_-]+$')
    capability: Capability
    resolution: Resolution
    status: Status
    model_class: ModelClass = Field(
        ...,
        description='E0=건물 실측 보정 E+, E1=계층·cohort 보정 E+, E2=E+ 출력 학습 surrogate, E3=E+ 기준선+실측 잔차, E4=E+ archetype lookup·scale, U=지원 불가.',
    )
    grade: ValidationGrade
    model_version_ref: constr(min_length=1) | None = None
    eplus_lineage: EPlusLineage | None = None
    model_artifacts: ModelArtifacts | None = None
    weather: WeatherBinding
    ood: OodAssessment
    valid_from: AwareDatetime
    valid_to: AwareDatetime | None = None
    reason_codes: list[ReasonCode] | None = None
    provenance: AssignmentProvenance


class Baseline(CapabilityAssignment):
    capability: Literal['baseline'] = 'baseline'


class Scenario(CapabilityAssignment):
    capability: Literal['scenario'] = 'scenario'


class Profile(CapabilityAssignment):
    capability: Literal['profile'] = 'profile'


class Assignments(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    baseline: Baseline
    scenario: Scenario
    profile: Profile


class BuildingModelPacket(BaseModel):
    """
    Building Twin에 배정된 EnergyPlus 계보 모델과 서빙 증적을 전달하는 계약. 에너지 수치나 예측값을 생성·운반하지 않으며, 실제 계산은 등록된 전문 실행기가 담당한다.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0']
    packet_id: constr(pattern=r'^bmp_[a-zA-Z0-9_-]+$')
    building_id: constr(min_length=1)
    identity: BuildingIdentity
    assignment_epoch: conint(ge=1) = Field(
        ...,
        description='입력·모델·날씨 배정이 바뀔 때 증가하는 불변 배정 세대. 과거 배정을 덮어쓰지 않는다.',
    )
    captured_at: AwareDatetime
    overall_grade: ValidationGrade
    assignments: Assignments
    serving_receipt: ModelServingReceipt | None = Field(
        None,
        description='아직 서빙하지 않은 packet은 null. 서빙 후에는 선택 모델과 replay 입력 해시만 기록하며 계산 결과 수치는 담지 않는다.',
    )
    provenance: Provenance
