# generated by datamodel-codegen:
#   filename:  bundle_manifest.json
#   timestamp: 2026-06-30T02:30:13+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, Field, constr


class SupportedBackend(Enum):
    virtual = 'virtual'
    replay = 'replay'
    energyplus = 'energyplus'
    real_bas = 'real_bas'


class TechListItem(BaseModel):
    id: constr(pattern=r'^[a-z][a-z0-9_-]{1,63}$') = Field(
        ...,
        description='기술 식별자 (경로·URL 안전). 예: `pre-cooling`, `ess-discharge`, `lighting-dim`.',
    )
    title_ko: str | None = Field(None, description='UI 표시용 한국어 이름.')
    version: constr(pattern=r'^[0-9]+\.[0-9]+(\.[0-9]+)?$')
    sha256: constr(pattern=r'^[a-f0-9]{64}$') = Field(
        ...,
        description='이 기술 폴더(`tech/{id}/`) 전체 파일 정규화 해시. Edge 가 tar 해제 후 재계산·검증.',
    )
    assets: list[str] | None = Field(
        None,
        description='번들 내 상대경로 (예: `tech/pre-cooling/index.html`). 디버그·감사용.',
    )
    supported_backends: list[SupportedBackend] | None = Field(
        None,
        description='이 기술이 실제로 작동하는 백엔드 목록. Edge `/api/capabilities` 에서 이 건물 backend 와 교집합 계산.',
    )
    applicable_building_types: list[str] | None = Field(
        None, description='적용 가능한 건물 유형. 비어있으면 모든 유형 (범용 기술).'
    )


class Algo(Enum):
    ed25519 = 'ed25519'
    cosign_ed25519 = 'cosign-ed25519'


class Signature(BaseModel):
    """
    번들 전체 무결성 서명. GB 가 ed25519 개인키로 발급, Edge 는 공개키 embed 로 검증.
    """

    algo: Algo
    value: str = Field(
        ..., description='서명 대상: canonical(manifest) + tar 해시. base64 인코딩.'
    )
    key_id: str | None = Field(None, description='공개키 fingerprint (로테이션 대비).')


class BundleManifest(BaseModel):
    """
    GB Bundle Builder 가 22기술 정적 자산을 서명된 `.tar.gz` 로 패키징할 때 루트에 포함하는 manifest. Edge 가 `bundle_store/{version}/` 에 풀어 `active` 심볼릭 링크로 A/B atomic swap. Edge 는 `min_edge_schema` 로 역호환을 검증. R8-5 (2026-04-20). **Delivery**: GB 노출 경로 `GET /api/v1/gridbridge/catalog/bundles/latest`. Edge 는 `GB_BUNDLE_MANIFEST_PATH` 환경변수로 오버라이드 가능. 다운로드: `GET /api/v1/gridbridge/catalog/bundles/{version}/download` (Bearer 토큰 필수). MQTT 알림: `fleet/bundle/notify/{ven_id}` (QoS 1, retain=false).
    """

    version: constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$') = Field(
        ...,
        description='번들 시맨틱 버전 (semver). Bundle Builder 가 발급. 예: `1.3.0`.',
    )
    min_edge_schema: constr(pattern=r'^[0-9]+\.[0-9]+$') = Field(
        ...,
        description='이 번들이 요구하는 최소 Edge 계약 버전 (energy-contracts 릴리즈). Edge 가 본인 버전보다 크면 번들 로드 거부 → 이전 슬롯 유지.',
    )
    built_at: AwareDatetime = Field(..., description='Bundle Builder 빌드 완료 시각.')
    source_commit: constr(pattern=r'^[0-9a-f]{7,40}$') | None = Field(
        None, description='`smartbuilding/web/` 소스 리포 커밋 해시 (추적용).'
    )
    tech_list: list[TechListItem] = Field(
        ..., description='번들에 포함된 22기술 (또는 부분집합) 메타.', min_length=1
    )
    signature: Signature | None = Field(
        None,
        description='번들 전체 무결성 서명. GB 가 ed25519 개인키로 발급, Edge 는 공개키 embed 로 검증.',
    )
