# generated by datamodel-codegen:
#   filename:  calendar_conventions.json
#   timestamp: 2026-09-28T08:49:37+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, conint


class CalendarConventions(BaseModel):
    """
    달력 규약 정본(2026-09-28 일반화 G1). 계절 체계·하루 창·기간 결과 칸·상대 표현 기준점을 **이름 붙여** 한 곳에 둔다. 월→계절 정의가 10곳·야간 정의가 4가지로 흩어져 같은 '여름'·'야간'이 도구마다 다른 달·시간을 뜻했다. 한 체계를 여러 곳이 쓰면 결과에 체계 이름(season_system·day_window)을 싣는다. 값을 바꾸지 않고 이름을 붙였다 — 서로 다른 뜻은 다른 이름으로 남는다(예: night_product 0~5시 ↔ night_dr 22~06시).
    """


class PeriodRole(Enum):
    """
    기간 말의 역할. '전년 대비' = comparison_base, '2030년 목표' = target_year — 자료 창(window)으로 쓰지 않는다.
    """

    window = 'window'
    comparison_base = 'comparison_base'
    target_year = 'target_year'


class DayWindow(BaseModel):
    hours: list[conint(ge=0, le=23)]
    label_ko: str | None = None
    source: str | None = None
