# generated by datamodel-codegen:
#   filename:  capability_tier.json
#   timestamp: 2026-09-11T10:06:13+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel


class BuildingCapabilityTierSsot(RootModel[Any]):
    root: Any = Field(
        ...,
        description="건물 그룹 EMS 에서 멤버 건물의 **능력**을 표기하는 3 직교 축 — 관측(C0~C4) · 제어(A0~A4) · 기준선 출처. 그룹사 30동 중 BEMS 가 있는 건 몇 동뿐이고 나머지는 월 청구서밖에 없다. 능력이 낮은 건물을 그룹에서 빼면 '건물 그룹 EMS' 가 아니라 'BEMS 있는 건물만 EMS' 가 되므로, **빼지 않고 등급으로 포함하되 능력 밖의 명령은 보내지 않는다**. 세 축은 독립이다 — C4/A0(계측 완비인데 제어 불가한 임차 건물)도 C1/A1(청구서만 있는데 사람이 끄는 건물)도 실재하므로, 하나의 스칼라 등급으로 뭉개면 둘 중 하나를 반드시 틀리게 표시한다.",
        title='Building Capability Tier SSOT',
    )


class ObservationTier(Enum):
    """
    관측 능력 — 이 건물에서 **무엇이 들어오나**. C0 미계측 · C1 청구서(월) · C2 총량(15분) · C3 용도별 · C4 존·설비
    """

    C0 = 'C0'
    C1 = 'C1'
    C2 = 'C2'
    C3 = 'C3'
    C4 = 'C4'


class ControlTier(Enum):
    """
    제어 능력 — 이 건물에 **무엇을 쓸 수 있나**. A0 읽기전용 · A1 수동·권고 · A2 운영모드 · A3 점 설정 · A4 발령
    """

    A0 = 'A0'
    A1 = 'A1'
    A2 = 'A2'
    A3 = 'A3'
    A4 = 'A4'


class BaselineSource(Enum):
    """
    기준선 출처. observed=관측 표본 · simulated=E+ 원형 시뮬(신축) · none=없음. ⚠ observed 와 simulated 는 단위는 같지만 **의미가 다르다** — 그룹 집계에서 합산하면 절감량이 근거 없는 수가 된다. 출처별로 나눠 보고한다.
    """

    observed = 'observed'
    simulated = 'simulated'
    none = 'none'


class EvidenceStatus(Enum):
    """
    이 등급을 **관측으로 판정할 수 있는가**. observable=계약에 채널이 있어 판정 가능 · no_contract_channel=계약에 채널 자체가 없어 관측 불가(신고값만 가능) · declared_only=본질적으로 사람이 정하는 값
    """

    observable = 'observable'
    no_contract_channel = 'no_contract_channel'
    declared_only = 'declared_only'


class TierAssessment(BaseModel):
    """
    멤버 건물 하나의 능력 판정 결과. **declared 와 observed 를 둘 다 보관**한다 — 사람이 적은 등급은 낡고, 관측은 안 낡는다. 불일치는 숨기지 않고 지목한다.
    """

    model_config = ConfigDict(
        extra='allow',
    )
    declared_observation: ObservationTier | None = None
    declared_control: ControlTier | None = None
    observed_observation: ObservationTier | None = None
    observed_control: ControlTier | None = None
    target_observation: ObservationTier | None = None
    target_control: ControlTier | None = None
    baseline_source: BaselineSource | None = None
    stale: bool | None = Field(
        None,
        description="관측이 최근에 끊겼다. ⚠ **강등이 아니다** — '지금 안 온다'와 '원래 없다'를 같은 색으로 칠하면 설비 투자 판단이 틀어진다. stale 인 동안 observed_* 는 마지막 판정을 유지한다.",
    )
    mismatch: list[str] | None = Field(
        None,
        description="declared 와 observed 가 다른 축의 이름. 예: ['observation'] — 신고는 C3 인데 관측은 C2",
    )
