# generated by datamodel-codegen:
#   filename:  certified_tests.json
#   timestamp: 2026-09-30T10:17:43+00:00

from __future__ import annotations

from pydantic import BaseModel


class CertifiedTests(BaseModel):
    """
    공인 시험 성적의 정본 전달 표(2026-09-30, 0.3.70). 공인 성적서에 적힌 값만 싣는다 — 가상·추정으로 만들지 않는다(가짜 공인 금지). 값의 원천 = 캠페인 docs/CAMPAIGN_REFERENCE.md 의 정본 표. 그 표에 없는 값은 null 과 사유(note)로 둔다. 자체 검증값(성적서에 없는 값)에는 공인 라벨을 붙이지 않는다.
    """
