# generated by datamodel-codegen:
#   filename:  common.json
#   timestamp: 2026-06-30T02:30:17+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import Field, RootModel, constr


class CommonDefinitions(RootModel[Any]):
    root: Any = Field(
        ...,
        description='공용 enum · 패턴 정의 SSOT. 다른 스키마가 복제하더라도 이 파일과 동기화 유지.',
        title='CommonDefinitions',
    )


class Strategy(Enum):
    """
    통일 EMS 전략 코드 (21종, M00~M20). M00=Baseline, M01=ScheduleOpt, M02=Economizer, M03=Staging, M04=PMV±0.5, M05=PMV±0.7, M06=NightCycle, M07=DCV, M08=HeatRecovery, M09=Precooling, M10=DemandResponse, M11~M15=Combined. M16~M20=DR 제어 액션(M16=DR_NightSetback, M17=LightingControl, M18=ESSPeakShaving, M19=DR_Integrated, M20=DR_EmergencyCurtail). 상세: ems_strategies.json.
    """

    M00 = 'M00'
    M01 = 'M01'
    M02 = 'M02'
    M03 = 'M03'
    M04 = 'M04'
    M05 = 'M05'
    M06 = 'M06'
    M07 = 'M07'
    M08 = 'M08'
    M09 = 'M09'
    M10 = 'M10'
    M11 = 'M11'
    M12 = 'M12'
    M13 = 'M13'
    M14 = 'M14'
    M15 = 'M15'
    M16 = 'M16'
    M17 = 'M17'
    M18 = 'M18'
    M19 = 'M19'
    M20 = 'M20'


class StrategyPattern(RootModel[constr(pattern=r'^M(0[0-9]|1[0-9]|20)$')]):
    root: constr(pattern=r'^M(0[0-9]|1[0-9]|20)$') = Field(
        ...,
        description='통일 코드 패턴 (M00~M20). v2.0에서 ^M[0-8]$ → ^M(0[0-9]|1[0-9]|20)$ 확장.',
    )


class Kind(Enum):
    """
    수용가 운영 모드. telemetry=관측형(read-only), dispatch=제어형(양방향).
    """

    telemetry = 'telemetry'
    dispatch = 'dispatch'


class Backend(Enum):
    """
    구현 기술. replay=과거 데이터 재생, energyplus=E+ 코시뮬, real_bas=실 설비, virtual=가상 드라이버.
    """

    replay = 'replay'
    energyplus = 'energyplus'
    real_bas = 'real_bas'
    virtual = 'virtual'


class BuildingType(Enum):
    """
    건물 유형 (DOE Reference Building 분류 기반). v2.0: code-first 네이밍 통일.
    """

    large_office = 'large_office'
    medium_office = 'medium_office'
    small_office = 'small_office'
    hospital = 'hospital'
    primary_school = 'primary_school'
    standalone_retail = 'standalone_retail'
    convenience_store = 'convenience_store'
    apartment = 'apartment'
    other = 'other'


class EdgeType(Enum):
    """
    노드 데이터소스 (backend 정합). device=현장 디바이스(real_bas) · replay=DB 리플레이 · eplus=E+ 시뮬 · synthetic=규칙/합성(virtual). 가상/현장은 별개 축 = 관제점 바인딩(점 단위, OPEN_CONNECTIVITY §2.6).
    """

    device = 'device'
    replay = 'replay'
    eplus = 'eplus'
    synthetic = 'synthetic'


class SignalLevel(Enum):
    """
    DR 신호 강도. signal_level → strategy 매핑: NORMAL→M17(LightingControl) · MODERATE→M04(PMV±0.5) · HIGH→M19(DR_Integrated) · EMERGENCY→M20(DR_EmergencyCurtail). 상세: ems_strategies.json signal_mapping.
    """

    NORMAL = 'NORMAL'
    MODERATE = 'MODERATE'
    HIGH = 'HIGH'
    EMERGENCY = 'EMERGENCY'


class VenId(
    RootModel[
        constr(pattern=r'^VEN-(STORE|EP|REAL|TEST|E2E|SHOP)-[A-Z0-9][A-Z0-9\-]*$')
    ]
):
    root: constr(pattern=r'^VEN-(STORE|EP|REAL|TEST|E2E|SHOP)-[A-Z0-9][A-Z0-9\-]*$') = (
        Field(
            ...,
            description='VEN 식별자. 접두 5종 + 영숫자·하이픈. 예: VEN-STORE-B001, VEN-EP-OFFICE-01, VEN-REAL-BLDG-A-01.',
        )
    )


class ESGGroupId(RootModel[str]):
    root: str = Field(
        ...,
        description='ESG 사전 정의 그룹. CLAUDE.md §ESG 사전 정의 그룹 참조.',
        examples=['ESG-STORE-100', 'ESG-STORE-120', 'ESG-EP-OFFICE', 'ESG-EP-APT'],
    )


class VirtualPNU(RootModel[constr(pattern=r'^[0-9]{10,19}$')]):
    root: constr(pattern=r'^[0-9]{10,19}$') = Field(
        ...,
        description='가상 PNU: 99001xxxxx=ESG-STORE-100 그룹, 99002xxxxx=ESG-STORE-120 그룹. 실 PNU는 일반 형식.',
    )


class Interlock(RootModel[str]):
    root: str = Field(
        ...,
        description="안전 인터록 발동 메시지. 예: 'HVAC 상한 제한: 28°C', 'ESS SOC 10% 하한 도달'.",
    )
