# generated by datamodel-codegen:
#   filename:  common.json
#   timestamp: 2026-09-28T08:40:09+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import Field, RootModel, constr


class CommonDefinitions(RootModel[Any]):
    root: Any = Field(
        ...,
        description='공용 enum · 패턴 정의 SSOT. 다른 스키마가 복제하더라도 이 파일과 동기화 유지.',
        title='CommonDefinitions',
    )


class Strategy(Enum):
    """
    통일 EMS 전략 코드 (23종, M00~M22). ⛔ 손으로 적지 않는다 — ems_strategies.json#default.strategies 의 키 목록을 gen_constants.py --all 이 여기와 ems_strategies $defs.StrategyCode 에 투영한다(validate_ssot check_strategy_list_projection). 2026-09-28 전에는 이 목록이 21종(M00~M20)에 멈춰 정본(23종)과 갈려 있었다. 뜻·이름: ems_strategies.json.
    """

    M00 = 'M00'
    M01 = 'M01'
    M02 = 'M02'
    M03 = 'M03'
    M04 = 'M04'
    M05 = 'M05'
    M06 = 'M06'
    M07 = 'M07'
    M08 = 'M08'
    M09 = 'M09'
    M10 = 'M10'
    M11 = 'M11'
    M12 = 'M12'
    M13 = 'M13'
    M14 = 'M14'
    M15 = 'M15'
    M16 = 'M16'
    M17 = 'M17'
    M18 = 'M18'
    M19 = 'M19'
    M20 = 'M20'
    M21 = 'M21'
    M22 = 'M22'


class StrategyPattern(RootModel[constr(pattern=r'^M(0[0-9]|1[0-9]|[2-9][0-9])$')]):
    root: constr(pattern=r'^M(0[0-9]|1[0-9]|[2-9][0-9])$') = Field(
        ...,
        description='통일 코드 패턴 (M00~M99, 유효성=enum). 2026-07-10 경계 하드코딩 제거: ^M(0[0-9]|1[0-9]|[2-9][0-9])$ → M99. 실제 유효 코드 = ems_strategies.json#StrategyCode.enum.',
    )


class Kind(Enum):
    """
    수용가 운영 모드. telemetry=관측형(read-only), dispatch=제어형(양방향).
    """

    telemetry = 'telemetry'
    dispatch = 'dispatch'


class Backend(Enum):
    """
    구현 기술. replay=과거 데이터 재생, energyplus=E+ 코시뮬, real_bas=실 설비, virtual=가상 드라이버.
    """

    replay = 'replay'
    energyplus = 'energyplus'
    real_bas = 'real_bas'
    virtual = 'virtual'


class BuildingType(Enum):
    """
    건물 유형 (DOE Reference Building 분류 기반). v2.0: code-first 네이밍 통일.
    """

    large_office = 'large_office'
    medium_office = 'medium_office'
    small_office = 'small_office'
    hospital = 'hospital'
    primary_school = 'primary_school'
    standalone_retail = 'standalone_retail'
    convenience_store = 'convenience_store'
    apartment = 'apartment'
    other = 'other'


class EdgeType(Enum):
    """
    노드 데이터소스 (backend 정합). device=현장 디바이스(real_bas) · replay=DB 리플레이 · eplus=E+ 시뮬 · synthetic=규칙/합성(virtual). 가상/현장은 별개 축 = 관제점 바인딩(점 단위, OPEN_CONNECTIVITY §2.6).
    """

    device = 'device'
    replay = 'replay'
    eplus = 'eplus'
    synthetic = 'synthetic'


class SignalLevel(Enum):
    """
    DR 신호 강도. signal_level → strategy 매핑: NORMAL→M17(LightingControl) · MODERATE→M04(PMV±0.5) · HIGH→M19(DR_Integrated) · EMERGENCY→M20(DR_EmergencyCurtail). 상세: ems_strategies.json signal_mapping.
    """

    NORMAL = 'NORMAL'
    MODERATE = 'MODERATE'
    HIGH = 'HIGH'
    EMERGENCY = 'EMERGENCY'


class VenId(
    RootModel[
        constr(pattern=r'^VEN-(STORE|EP|REAL|TEST|E2E|SHOP)-[A-Z0-9][A-Z0-9\-]*$')
    ]
):
    root: constr(pattern=r'^VEN-(STORE|EP|REAL|TEST|E2E|SHOP)-[A-Z0-9][A-Z0-9\-]*$') = (
        Field(
            ...,
            description='VEN 식별자. 접두 5종 + 영숫자·하이픈. 예: VEN-STORE-B001, VEN-EP-OFFICE-01, VEN-REAL-BLDG-A-01.',
        )
    )


class ESGGroupId(RootModel[str]):
    root: str = Field(
        ...,
        description='ESG 사전 정의 그룹. CLAUDE.md §ESG 사전 정의 그룹 참조.',
        examples=['ESG-STORE-100', 'ESG-STORE-120', 'ESG-EP-OFFICE', 'ESG-EP-APT'],
    )


class VirtualPNU(RootModel[constr(pattern=r'^[0-9]{10,19}$')]):
    root: constr(pattern=r'^[0-9]{10,19}$') = Field(
        ...,
        description='가상 PNU: 99001xxxxx=ESG-STORE-100 그룹, 99002xxxxx=ESG-STORE-120 그룹. 실 PNU는 일반 형식.',
    )


class Interlock(RootModel[str]):
    root: str = Field(
        ...,
        description="안전 인터록 발동 메시지. 예: 'HVAC 상한 제한: 28°C', 'ESS SOC 10% 하한 도달'.",
    )


class BuildingMgmtNo(RootModel[constr(pattern=r'^[0-9]{25}$')]):
    root: constr(pattern=r'^[0-9]{25}$') = Field(
        ...,
        description='건물관리번호 25자리(도로명주소 건물 관리번호·footprint). 공공 건물 대상의 식별자.',
    )


class ParcelId(RootModel[constr(pattern=r'^[0-9]{19}$')]):
    root: constr(pattern=r'^[0-9]{19}$') = Field(
        ...,
        description='필지번호(PNU) 19자리 = 시군구 5 + 법정동 5 + 대지구분 1 + 본번 4 + 부번 4. 필지 화면의 조회 열쇠 — 건물 대상을 필지로 바꿔 넣지 않는다.',
    )


class SidoCode(RootModel[constr(pattern=r'^[0-9]{2}$')]):
    root: constr(pattern=r'^[0-9]{2}$') = Field(
        ...,
        description='시도 2자리. 폐지 코드(42·45)의 승계 = region_codes.json#default.admin_succession.sido_successor.',
    )


class SigunguCode(RootModel[constr(pattern=r'^[0-9]{5}$')]):
    root: constr(pattern=r'^[0-9]{5}$') = Field(
        ...,
        description='시군구 5자리. 폐지·개편 승계 = region_codes.json#default.admin_succession.',
    )


class LegalDongCode(RootModel[constr(pattern=r'^[0-9]{10}$')]):
    root: constr(pattern=r'^[0-9]{10}$') = Field(..., description='법정동 10자리.')


class RegionId(RootModel[constr(pattern=r'^region:([0-9]{2}|[0-9]{5}|[0-9]{10}|kr)$')]):
    root: constr(pattern=r'^region:([0-9]{2}|[0-9]{5}|[0-9]{10}|kr)$') = Field(
        ..., description='대상 칸의 지역 id — 시도·시군구·법정동·전국.'
    )


class AirAssetKind(Enum):
    """
    AIR 자산 종류. 종류별 대상 칸·건물번호·시계열 = target_vocabulary.json#default.air_asset_kinds.
    """

    BLD = 'BLD'
    FAC = 'FAC'
    HOM = 'HOM'
    RET = 'RET'
    PRT = 'PRT'


class AirAssetId(RootModel[constr(pattern=r'^AIR-(BLD|FAC|HOM|RET)-[0-9]{3,4}$')]):
    root: constr(pattern=r'^AIR-(BLD|FAC|HOM|RET)-[0-9]{3,4}$') = Field(
        ...,
        description='AIR 단일 자산 번호(포트폴리오 제외). 3자리·4자리 모두 받는다 — 3자리 전용 패턴 금지(점포·4자리 번호가 거절됐다).',
    )


class AirPortfolioId(RootModel[constr(pattern=r'^AIR-PRT-[0-9]{3,4}$')]):
    root: constr(pattern=r'^AIR-PRT-[0-9]{3,4}$') = Field(
        ..., description='AIR 포트폴리오 번호.'
    )


class ArchetypeCode(RootModel[constr(pattern=r'^B(0[1-9]|1[0-8])$')]):
    root: constr(pattern=r'^B(0[1-9]|1[0-8])$') = Field(
        ...,
        description='원형 코드 B01~B18 = building_archetypes.json#default.doe_buildings 키.',
    )


class HvacCode(RootModel[constr(pattern=r'^H_[A-G]$')]):
    root: constr(pattern=r'^H_[A-G]$') = Field(
        ...,
        description='공조 방식 정본 코드 H_A~H_G = region_codes.json#default.hvac_types 키.',
    )


class CityCode(RootModel[constr(pattern=r'^C(0[1-9]|1[0-8])$')]):
    root: constr(pattern=r'^C(0[1-9]|1[0-8])$') = Field(
        ...,
        description='시뮬 기후 도시 C01~C18 = region_codes.json#default.simulation_cities 키.',
    )


class MeasurementSetId(RootModel[constr(pattern=r'^ms-[0-9a-f]{24}$')]):
    root: constr(pattern=r'^ms-[0-9a-f]{24}$') = Field(
        ...,
        description='측정 묶음 id(AIROS 레코드, 원천 매장코드의 대체). 밖으로 나가는 산출물에 넣지 않는다.',
    )
