# generated by datamodel-codegen:
#   filename:  computer_profile.json
#   timestamp: 2026-09-11T10:06:15+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class ComputerProfileSsotPhaseJ6(BaseModel):
    """
    워크스페이스 컴퓨터 A/B identity SSOT. ~/.claude/CLAUDE.md Computer Identity 섹션을 머신리더블로. SessionStart hook 자동 로드 대상.
    """


class Machine(Enum):
    A = 'A'
    B = 'B'
    CI = 'CI'
    Linux_Dev = 'Linux-Dev'
