# generated by datamodel-codegen:
#   filename:  control_response.json
#   timestamp: 2026-06-30T02:30:37+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint, constr


class Status(Enum):
    """
    applied=요청대로, clamped=인터록으로 일부 제한, rejected=거부, queued=로컬 큐 적재, failed=드라이버 오류
    """

    applied = 'applied'
    clamped = 'clamped'
    rejected = 'rejected'
    queued = 'queued'
    failed = 'failed'


class Actual(BaseModel):
    """
    실제 적용된 값(인터록 클램프 후).
    """

    model_config = ConfigDict(
        extra='allow',
    )
    hvac_setpoint_c: float | None = None
    lighting_pct: float | None = None
    ess_discharge_kw: float | None = None


class ControlResponse(BaseModel):
    """
    제어 명령 적용 결과. Edge → GB/VW 피드백. ack의 상세 payload로 사용하거나 별도 토픽으로 발행 가능.
    """

    ven_id: str
    correlation_id: str = Field(
        ..., description='원 명령의 correlation_id. 왕복 매칭 키.'
    )
    status: Status = Field(
        ...,
        description='applied=요청대로, clamped=인터록으로 일부 제한, rejected=거부, queued=로컬 큐 적재, failed=드라이버 오류',
    )
    applied_at: AwareDatetime
    strategy: constr(pattern=r'^M(0[0-9]|1[0-9]|20)$') | None = Field(
        None,
        description='적용된 EMS 전략. control_command 에서는 required 이지만 여기선 optional — status=failed/rejected 시 전략이 적용되지 않았으므로 생략 가능. common.json §Strategy 와 동기화 유지.',
    )
    strategy_name: str | None = None
    requested: dict[str, Any] | None = Field(
        None, description='사용자가 요청한 원값. control_command.json 의 부분집합.'
    )
    actual: Actual | None = Field(None, description='실제 적용된 값(인터록 클램프 후).')
    interlocks: list[str] | None = Field(
        None, description="발동한 인터록 메시지 목록(예: 'HVAC 상한 제한: 28°C')"
    )
    baseline_kw: float | None = Field(None, description='감축 계산 기준 전력')
    current_kw: float | None = Field(None, description='적용 직후 관측/시뮬 전력')
    reduction_kw: float | None = Field(None, description='baseline - current')
    simulation_step: conint(ge=0) | None = Field(
        None, description='backend=energyplus 일 때 누적 스텝 번호 (선택)'
    )
    error: str | None = Field(None, description='status=failed/rejected 일 때 사유')
