# generated by datamodel-codegen:
#   filename:  control_decision.json
#   timestamp: 2026-07-09T21:50:34+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, Field, constr


class Kind(Enum):
    threshold = 'threshold'
    cadence = 'cadence'
    external = 'external'


class Trigger(BaseModel):
    kind: Kind
    detail: str | None = Field(None, description='예: power_kw 210 > peak_band 180')


class RiskTier(Enum):
    LOW = 'LOW'
    HIGH = 'HIGH'


class Decision(Enum):
    pass_ = 'pass'
    warn = 'warn'
    block = 'block'


class CriticVerdict(BaseModel):
    decision: Decision | None = None
    reasons: list[str] | None = None


class Disposition(Enum):
    """
    shadow_only = Phase 1 자문 전용.
    """

    auto_dispatched = 'auto_dispatched'
    hitl_pending = 'hitl_pending'
    hitl_approved = 'hitl_approved'
    hitl_rejected = 'hitl_rejected'
    hitl_expired = 'hitl_expired'
    blocked = 'blocked'
    shadow_only = 'shadow_only'


class Outcome(BaseModel):
    """
    FEEDBACK 관측 (ack + 후속 telemetry).
    """

    ack_status: str | None = None
    observed_power_kw_after: float | None = None
    comfort_held: bool | None = None


class ControlDecision(BaseModel):
    """
    killer 오케스트레이터 단일 인지 결정 기록 — 감사·재현·학습용. proposed_command 는 control_command.json 준수(runtime 별도 검증, cross-file $ref 회피). killer/docs/DATA_CONTRACTS.md §2.
    """

    decision_id: str = Field(..., description='예: dec_20260706_ab12cd34')
    ven_id: str
    trace_id: constr(pattern=r'^trc_[0-9]{8}_[a-z0-9]{6,32}$') = Field(
        ..., description='게이트웨이 분석 호출과 동일 trace (GAP5).'
    )
    ts: AwareDatetime
    trigger: Trigger
    proposed_command: dict[str, Any] | None = Field(
        None,
        description='LLM 제안 control_command (control_command.json 준수 — killer 가 발행 전 별도 검증). block/거부 시 생략.',
    )
    risk_tier: RiskTier | None = None
    critic_verdict: CriticVerdict | None = None
    disposition: Disposition = Field(
        ..., description='shadow_only = Phase 1 자문 전용.'
    )
    reasoning: str | None = Field(None, description='LLM 근거 요약.')
    analysis_refs: list[str] | None = Field(
        None,
        description='호출한 ems_transformer tool + 핵심 수치 (forecast peak, recommend payback 등).',
    )
    outcome: Outcome | None = Field(
        None, description='FEEDBACK 관측 (ack + 후속 telemetry).'
    )
