# generated by datamodel-codegen:
#   filename:  data_classification.json
#   timestamp: 2026-09-28T13:26:36+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class DataSource(Enum):
    """
    출처 축. measured=실 계량, certified=공식 인증, simulated=시뮬 산출, predicted=ML 예측, external=외부 벤더, synthetic=합성/생성기, mock=의도적 모킹 calibrated=실측에 맞춰 보정(실측 아님), imputed=우리가 채운 값(method 필수), virtual=경진대회 가상 채움(자료가 없어 생성기·규칙으로 만든 값 — 생성 규칙·근거·생성기 이름 필수, 사람 대면 표시 '가상', 실측이 생기면 실측이 먼저). ⚠ 이 축은 **값이 있을 때만** 쓴다. 값이 없는 이유는 AbsenceKind 로 적는다.
    """

    measured = 'measured'
    certified = 'certified'
    simulated = 'simulated'
    predicted = 'predicted'
    external = 'external'
    synthetic = 'synthetic'
    mock = 'mock'
    calibrated = 'calibrated'
    imputed = 'imputed'
    virtual = 'virtual'


class EvidenceDisplayClass(Enum):
    """
    여러 Evidence를 하나의 답변·화면에 표시할 때 쓰는 합성 라벨. 원천 출처가 아니며 DataSource를 대체하지 않는다. 실제 원천은 data_sources[]에 DataSource로 별도 보존한다. virtual=경진대회 가상 채움('가상' 배지), unknown=분류를 모른다('분류 미표시' — 실측으로 올리지 않는다).
    """

    measured = 'measured'
    forecast = 'forecast'
    estimated = 'estimated'
    reference = 'reference'
    synthetic = 'synthetic'
    mixed = 'mixed'
    virtual = 'virtual'
    unknown = 'unknown'


class ClassificationWord(Enum):
    """
    결과·결속 출처의 **분류 낱말**(값 하나 또는 결과 전체가 무엇으로 만들어졌나). 낱말마다 출처(DataSource)·표시 등급(EvidenceDisplayClass)·한글 라벨이 default.classification.words 에 있다. 옛 낱말은 default.classification.aliases 로 이 낱말에 잇는다. 여러 출처를 합칠 때는 default.classification.composite 규칙(코드 = rules_pure.ec_classification_combine).
    """

    measured = 'measured'
    measured_with_imputed = 'measured_with_imputed'
    calibrated = 'calibrated'
    certified = 'certified'
    simulated = 'simulated'
    predicted = 'predicted'
    estimated = 'estimated'
    imputed = 'imputed'
    external = 'external'
    reference = 'reference'
    declared = 'declared'
    assumed = 'assumed'
    virtual = 'virtual'
    synthetic = 'synthetic'
    mock = 'mock'
    mixed = 'mixed'
    unknown = 'unknown'


class DataTier(RootModel[conint(ge=1, le=5)]):
    root: conint(ge=1, le=5) = Field(
        ...,
        description='품질 등급 1~5 (1=최고). building-energy-3d data_tier와 동일. synthetic/mock은 N/A로 표기 (별도 필드)',
    )


class DataCategory(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    source: DataSource
    tier: DataTier | None = None
    description: str | None = None
    example: str | None = None
    is_runtime: bool | None = Field(
        None, description='true=운영 데이터, false=테스트 전용'
    )


class DataAvailability(Enum):
    """
    테스트 데이터 가용성. immediate=conftest fixture, synthetic_generator=동적 생성, external_static=사전 다운로드 정적, pipeline_ingested=파이프라인 단계적 입수
    """

    immediate = 'immediate'
    synthetic_generator = 'synthetic_generator'
    external_static = 'external_static'
    pipeline_ingested = 'pipeline_ingested'


class PipelineStage(Enum):
    """
    파이프라인 입수 단계. raw→curated→published 진행
    """

    raw = 'raw'
    downloaded = 'downloaded'
    normalized = 'normalized'
    validated = 'validated'
    curated = 'curated'
    published = 'published'


class AbsenceKind(Enum):
    """
    부재 축 — **값이 왜 없나**. DataSource(출처 축)와 섞지 않는다. not_applicable=설계·물리·정책상 대상이 아니다(자원을 쓰지 않는다) · missing=대상인데 아직 안 받았다(여기만 자원을 쓴다) · unknown=대상인지조차 판정 못 했다(못 잼 — 통과로 세지 않는다). ⛔ 분모는 covered+missing 이다. not_applicable 을 분모에 넣으면 진척이 실제보다 나빠 보이고 없는 결손에 예산이 나간다(전역 룰 absence-has-kinds).
    """

    not_applicable = 'not_applicable'
    missing = 'missing'
    unknown = 'unknown'


class DataClassificationSsotPhaseF(BaseModel):
    """
    데이터 분류 2축 (출처 × 품질). building-energy-3d data_tier 호환 + 합성·외부·mock 카테고리 추가. 프로젝트는 extensions로 자체 카테고리 추가 가능.
    """

    sources: dict[DataSource, DataCategory] | None = None
    tier_mapping: dict[str, Any] | None = Field(
        None, description='building-energy-3d data_tier 호환 매핑'
    )
    extensions: dict[str, Any] | None = Field(
        None, description='프로젝트별 자체 카테고리 추가'
    )
