# generated by datamodel-codegen:
#   filename:  data_classification.json
#   timestamp: 2026-06-30T02:30:41+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class DataSource(Enum):
    """
    출처 축. measured=실 계량, certified=공식 인증, simulated=시뮬 산출, predicted=ML 예측, external=외부 벤더, synthetic=합성/생성기, mock=의도적 모킹
    """

    measured = 'measured'
    certified = 'certified'
    simulated = 'simulated'
    predicted = 'predicted'
    external = 'external'
    synthetic = 'synthetic'
    mock = 'mock'


class DataTier(RootModel[conint(ge=1, le=5)]):
    root: conint(ge=1, le=5) = Field(
        ...,
        description='품질 등급 1~5 (1=최고). building-energy-3d data_tier와 동일. synthetic/mock은 N/A로 표기 (별도 필드)',
    )


class DataCategory(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    source: DataSource
    tier: DataTier | None = None
    description: str | None = None
    example: str | None = None
    is_runtime: bool | None = Field(
        None, description='true=운영 데이터, false=테스트 전용'
    )


class DataAvailability(Enum):
    """
    테스트 데이터 가용성. immediate=conftest fixture, synthetic_generator=동적 생성, external_static=사전 다운로드 정적, pipeline_ingested=파이프라인 단계적 입수
    """

    immediate = 'immediate'
    synthetic_generator = 'synthetic_generator'
    external_static = 'external_static'
    pipeline_ingested = 'pipeline_ingested'


class PipelineStage(Enum):
    """
    파이프라인 입수 단계. raw→curated→published 진행
    """

    raw = 'raw'
    downloaded = 'downloaded'
    normalized = 'normalized'
    validated = 'validated'
    curated = 'curated'
    published = 'published'


class DataClassificationSsotPhaseF(BaseModel):
    """
    데이터 분류 2축 (출처 × 품질). building-energy-3d data_tier 호환 + 합성·외부·mock 카테고리 추가. 프로젝트는 extensions로 자체 카테고리 추가 가능.
    """

    sources: dict[DataSource, DataCategory] | None = None
    tier_mapping: dict[str, Any] | None = Field(
        None, description='building-energy-3d data_tier 호환 매핑'
    )
    extensions: dict[str, Any] | None = Field(
        None, description='프로젝트별 자체 카테고리 추가'
    )
