# generated by datamodel-codegen:
#   filename:  db_migrations.json
#   timestamp: 2026-06-30T02:30:48+00:00

from __future__ import annotations

from pydantic import BaseModel


class DbMigrationsSsotPhaseK16(BaseModel):
    """
    각 프로젝트 Alembic 마이그레이션 head/현재 버전 추적. 다중 인스턴스 환경에서 DB 스키마 drift 방지.
    """
