# generated by datamodel-codegen:
#   filename:  declared_assumptions.json
#   timestamp: 2026-09-29T10:05:12+00:00

from __future__ import annotations

from pydantic import BaseModel


class DeclaredAssumptions(BaseModel):
    """
    선언 가정 상수 정본(2026-09-28 경진대회 최종 라운드 N32). 질문이 값을 말하지 않을 때 쓰는 **선언 가정**(합의된 운영 기준·실측이 아님)을 한 곳에 둔다 — 게이트웨이 여러 모듈이 손 리터럴로 들던 값(폭염 33℃·한파 −12℃·노후 30년·조치 적용 문턱·가상 ESS 왕복효율·기본 용도 분해). 값마다 classification(declared=공공 기준 인용 · assumed=우리 선언)과 출처를 싣는다. 답에는 규칙 문장(rule_ko)을 함께 싣고, 질문이 값을 말하면 질문이 먼저다.
    """
