# generated by datamodel-codegen:
#   filename:  dr_dispatch_event.json
#   timestamp: 2026-06-30T02:31:05+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    confloat,
    conint,
    constr,
)


class Trace(BaseModel):
    """
    디버깅용 — 의사결정 트레이스
    """

    model_config = ConfigDict(
        extra='allow',
    )
    smp_at_dispatch: float | None = None
    weather_at_dispatch: dict[str, Any] | None = None
    policy_version: str | None = None


class DispatchSource(Enum):
    """
    발령 출처. reliability=외부 발령창(수동/KPX 대체), economic=경제성 정책 엔진 자동.
    """

    reliability = 'reliability'
    economic = 'economic'


class DispatchStatus(Enum):
    """
    라이프사이클. pending→acknowledged→active→completed (정상) 또는 failed/cancelled (예외).
    """

    pending = 'pending'
    acknowledged = 'acknowledged'
    active = 'active'
    completed = 'completed'
    failed = 'failed'
    cancelled = 'cancelled'


class DispatchWindow(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    start: AwareDatetime
    end: AwareDatetime


class MemberAllocation(BaseModel):
    """
    분배 결과 — 각 멤버에 할당된 감축량.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    ven_id: str
    allocated_kw: confloat(ge=0.0)
    strategy: constr(pattern=r'^M(0[0-9]|1[0-9]|20)$') | None = Field(
        None,
        description='적용된 EMS 전략 코드 (M00~M20). ems_strategies.json#StrategyPattern 참조. DB CHECK도 동일 패턴.',
    )
    reasoning: str | None = Field(
        None, description='분배 알고리즘이 남긴 결정 근거 (디버깅·UI 표시용)'
    )


class ViolationType(Enum):
    pmv_exceeded = 'pmv_exceeded'
    setpoint_deviation_exceeded = 'setpoint_deviation_exceeded'


class ComfortViolation(BaseModel):
    ven_id: str | None = None
    violation_type: ViolationType | None = None
    value: float | None = None


class ExecutionReport(BaseModel):
    """
    이행 결과 보고서 (status=completed/failed 시 필수).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    target_kw: confloat(ge=0.0) | None = None
    achieved_kw: confloat(ge=0.0) | None = None
    unallocated_kw: confloat(ge=0.0) | None = Field(
        None,
        description='분배 단계에서 할당 못 한 양 (mandatory + partial_execution 결합 시 발생)',
    )
    shortfall_kw: float | None = Field(
        None, description='이행 후 부족분 (target − achieved)'
    )
    avoided_cost_krw: float | None = Field(
        None,
        description='회피비용 = Σ(회피kWh × (SMP − bid_price)). 음수 가능 (역손실).',
    )
    comfort_violations: list[ComfortViolation] | None = None


class DrDispatchEvent(BaseModel):
    """
    외부 발령창 또는 경제성 정책 엔진이 발생시키는 DR 디스패치 이벤트. dr_event.json (기존, 단순 신호 모델)과 구분 — 본 스키마는 ESG Aggregator 레이어가 받아 분배·실행하는 정책 명령. Phase 4 도입.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    event_id: constr(pattern=r'^dispatch-[0-9]{4}-[0-9]{4,}$') = Field(
        ..., description='예: dispatch-2026-0001'
    )
    source: DispatchSource
    group_id: str = Field(..., description='esg_groups.group_id 참조')
    target_kw: confloat(ge=0.0) = Field(..., description='목표 감축량 (kW)')
    window: DispatchWindow
    mandatory: bool = Field(
        ...,
        description='true=의무 이행 (신뢰성 DR 통상), false=선택적 (경제성 DR 통상)',
    )
    advance_notice_minutes: conint(ge=0) | None = Field(
        None,
        description='발령 시각부터 window.start까지 예고 시간. esg_policy.reliability.min_advance_minutes 와 비교 검증.',
    )
    dispatched_by: (
        constr(
            pattern=r'^(operator-[a-zA-Z0-9_-]{3,64}|auto-esg-policy-[a-zA-Z0-9_-]+)$'
        )
        | None
    ) = Field(
        None,
        description='서버측 JWT claim에서 derive. operator-{jwt.sub} 또는 auto-{policy_id}. 클라이언트 입력값은 서버가 무시·덮어쓴다. UI 표시는 dispatched_by_display 사용 (PII 보호).',
    )
    jti: constr(min_length=16, max_length=128) | None = Field(
        None,
        description='JWT ID — replay 방어. gridbridge Redis nonce store (TTL=window.end+24h)에 보존. UNIQUE.',
    )
    dispatched_at: AwareDatetime
    status: DispatchStatus
    distribution_algorithm: str | None = Field(
        None,
        description='사용된 분배 알고리즘 (esg_policy.distribution.algorithm 또는 override)',
    )
    allocations: list[MemberAllocation] | None = Field(
        None, description='분배 결과. status≥acknowledged 시 채워짐.'
    )
    execution_report: ExecutionReport | None = Field(
        None, description='이행 후 보고서. status=completed/failed 시 필수.'
    )
    trace: Trace | None = Field(None, description='디버깅용 — 의사결정 트레이스')
