# generated by datamodel-codegen:
#   filename:  dr_dispatch_event.json
#   timestamp: 2026-09-11T10:06:20+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    confloat,
    conint,
    constr,
)


class Trace(BaseModel):
    """
    디버깅용 — 의사결정 트레이스
    """

    model_config = ConfigDict(
        extra='allow',
    )
    smp_at_dispatch: float | None = None
    weather_at_dispatch: dict[str, Any] | None = None
    policy_version: str | None = None


class DispatchSource(Enum):
    """
    발령 출처 (R18 Item 1·3 확장). DispatchSource = ems_strategies.json#/$defs/ObjectiveType {reliability,economic,carbon,optimal} ∪ {microgrid_safety}. reliability=외부 발령창(수동/KPX 대체) · economic=경제성 정책 엔진 자동 · carbon=탄소최소 정책 · optimal=통합 균형 · microgrid_safety=마이크로그리드 안전 급전(MGCC, 물리 배전 도메인 — GB 정산축 아님). objective 4종은 ObjectiveType 과 lock-step(validate_ssot.check_objective_dispatch_sync 강제). 인라인 enum 유지 이유=gen_constants 가 DISPATCH_SOURCES 를 .enum 으로 파싱.
    """

    reliability = 'reliability'
    economic = 'economic'
    carbon = 'carbon'
    optimal = 'optimal'
    microgrid_safety = 'microgrid_safety'


class SetpointCommand(BaseModel):
    """
    설정온도 직접 지정 (how). MGCC/APE 가 절감량(what) 대신 설정온도를 직접 준다. Edge 가 인터록·critics_gate 통과 후 clamp. GB 는 kW 의무 산출 불가 → 정산 대상 아님(measured passthrough).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    setpoint_c: float = Field(..., description='목표 설정온도(°C).')
    ramp: confloat(ge=0.0) | None = Field(
        None, description='설정온도 도달까지 램프 시간(분). 0=즉시.'
    )
    zone: str | None = Field(None, description='대상 존(선택). 미지정=건물 전체.')


class Profile(Enum):
    """
    APE 운영 프로파일 (ObjectiveType lock-step). MGCC 가 그룹 멤버 엣지의 상시 운영 정책을 지정. microgrid_safety 는 dispatch source 축이지 profile 아님(제외).
    """

    reliability = 'reliability'
    economic = 'economic'
    carbon = 'carbon'
    optimal = 'optimal'


class OperatingModeCommand(BaseModel):
    """
    운영 모드 설정 (§5.5, MG 적극성). MGCC 가 엣지 APE 운영 프로파일을 상시 설정 — 일회성 액션(target/setpoint/peak)과 달리 해제까지 지속되는 정책 설정. 정산 무관(정책, mandatory=false 필수). producer=MGCC / consumer=edge-agent(APE persona 갱신) / GB 무관. profile 4종은 ems_strategies.json#/$defs/ObjectiveType lock-step.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    profile: Profile = Field(
        ...,
        description='APE 운영 프로파일 (ObjectiveType lock-step). MGCC 가 그룹 멤버 엣지의 상시 운영 정책을 지정. microgrid_safety 는 dispatch source 축이지 profile 아님(제외).',
    )
    enforce: bool | None = Field(
        False,
        description='APE 실 강제 여부. true=AUTONOMOUS 권한으로 즉시 적용(EDGE_PERSONA_ENFORCE 상당) / false=informational(텔레메트리 부착만).',
    )


class DispatchCommand1(BaseModel):
    """
    발령 명령 (R18 Item 3 + operating_mode §5.5). 정확히 하나: target_kw(감축량) | setpoint_command(설정온도) | peak_limit_kw(계약전력 상한) | operating_mode(운영 프로파일 상시 설정). GB 정산 경계 — target_kw·peak_limit_kw = GB settlement 대상(kW 의무배분·패널티 산출) / setpoint_command·operating_mode = Edge 직접제어·정책설정(GB measured passthrough·정산무관, 상위 mandatory=false 필수). operating_mode 는 MGCC producer 전용(GB 무관).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    target_kw: confloat(ge=0.0) = Field(
        ..., description='목표 감축량(kW). GB settlement 대상.'
    )


class DispatchCommand2(BaseModel):
    """
    발령 명령 (R18 Item 3 + operating_mode §5.5). 정확히 하나: target_kw(감축량) | setpoint_command(설정온도) | peak_limit_kw(계약전력 상한) | operating_mode(운영 프로파일 상시 설정). GB 정산 경계 — target_kw·peak_limit_kw = GB settlement 대상(kW 의무배분·패널티 산출) / setpoint_command·operating_mode = Edge 직접제어·정책설정(GB measured passthrough·정산무관, 상위 mandatory=false 필수). operating_mode 는 MGCC producer 전용(GB 무관).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    setpoint_command: SetpointCommand


class DispatchCommand3(BaseModel):
    """
    발령 명령 (R18 Item 3 + operating_mode §5.5). 정확히 하나: target_kw(감축량) | setpoint_command(설정온도) | peak_limit_kw(계약전력 상한) | operating_mode(운영 프로파일 상시 설정). GB 정산 경계 — target_kw·peak_limit_kw = GB settlement 대상(kW 의무배분·패널티 산출) / setpoint_command·operating_mode = Edge 직접제어·정책설정(GB measured passthrough·정산무관, 상위 mandatory=false 필수). operating_mode 는 MGCC producer 전용(GB 무관).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    peak_limit_kw: confloat(ge=0.0) = Field(
        ...,
        description='계약전력 상한(kW) — 초과 억제분. kW 환산 가능 → GB settlement 대상.',
    )


class DispatchCommand4(BaseModel):
    """
    발령 명령 (R18 Item 3 + operating_mode §5.5). 정확히 하나: target_kw(감축량) | setpoint_command(설정온도) | peak_limit_kw(계약전력 상한) | operating_mode(운영 프로파일 상시 설정). GB 정산 경계 — target_kw·peak_limit_kw = GB settlement 대상(kW 의무배분·패널티 산출) / setpoint_command·operating_mode = Edge 직접제어·정책설정(GB measured passthrough·정산무관, 상위 mandatory=false 필수). operating_mode 는 MGCC producer 전용(GB 무관).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    operating_mode: OperatingModeCommand


class DispatchCommand(
    RootModel[DispatchCommand1 | DispatchCommand2 | DispatchCommand3 | DispatchCommand4]
):
    root: DispatchCommand1 | DispatchCommand2 | DispatchCommand3 | DispatchCommand4 = (
        Field(
            ...,
            description='발령 명령 (R18 Item 3 + operating_mode §5.5). 정확히 하나: target_kw(감축량) | setpoint_command(설정온도) | peak_limit_kw(계약전력 상한) | operating_mode(운영 프로파일 상시 설정). GB 정산 경계 — target_kw·peak_limit_kw = GB settlement 대상(kW 의무배분·패널티 산출) / setpoint_command·operating_mode = Edge 직접제어·정책설정(GB measured passthrough·정산무관, 상위 mandatory=false 필수). operating_mode 는 MGCC producer 전용(GB 무관).',
        )
    )


class DispatchStatus(Enum):
    """
    라이프사이클. pending→acknowledged→active→completed (정상) 또는 failed/cancelled (예외).
    """

    pending = 'pending'
    acknowledged = 'acknowledged'
    active = 'active'
    completed = 'completed'
    failed = 'failed'
    cancelled = 'cancelled'


class DispatchWindow(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    start: AwareDatetime
    end: AwareDatetime


class MemberAllocation(BaseModel):
    """
    분배 결과 — 각 멤버에 할당된 감축량.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    ven_id: str
    allocated_kw: confloat(ge=0.0) = Field(
        ...,
        description='할당 감축량(kW). setpoint_command 경로에선 0 허용(kW 의무 없음) + setpoint_c 병기.',
    )
    setpoint_c: float | None = Field(
        None,
        description='설정온도 경로(command.setpoint_command) 시 이 멤버에 적용된 목표 설정온도(°C). optional — kW 경로에선 생략. GB 정산 무연동(measured passthrough).',
    )
    strategy: constr(pattern=r'^M(0[0-9]|1[0-9]|[2-9][0-9])$') | None = Field(
        None,
        description='적용된 EMS 전략 코드 (M00~M20). ems_strategies.json#StrategyPattern 참조. DB CHECK도 동일 패턴.',
    )
    reasoning: str | None = Field(
        None, description='분배 알고리즘이 남긴 결정 근거 (디버깅·UI 표시용)'
    )


class ViolationType(Enum):
    pmv_exceeded = 'pmv_exceeded'
    setpoint_deviation_exceeded = 'setpoint_deviation_exceeded'


class ComfortViolation(BaseModel):
    ven_id: str | None = None
    violation_type: ViolationType | None = None
    value: float | None = None


class ExecutionReport(BaseModel):
    """
    이행 결과 보고서 (status=completed/failed 시 필수).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    target_kw: confloat(ge=0.0) | None = None
    achieved_kw: confloat(ge=0.0) | None = None
    unallocated_kw: confloat(ge=0.0) | None = Field(
        None,
        description='분배 단계에서 할당 못 한 양 (mandatory + partial_execution 결합 시 발생)',
    )
    shortfall_kw: float | None = Field(
        None, description='이행 후 부족분 (target − achieved)'
    )
    avoided_cost_krw: float | None = Field(
        None,
        description='회피비용 = Σ(회피kWh × (SMP − bid_price)). 음수 가능 (역손실).',
    )
    comfort_violations: list[ComfortViolation] | None = None


class DrDispatchEvent(BaseModel):
    """
    외부 발령창 또는 경제성 정책 엔진이 발생시키는 DR 디스패치 이벤트. dr_event.json (기존, 단순 신호 모델)과 구분 — 본 스키마는 ESG Aggregator 레이어가 받아 분배·실행하는 정책 명령. Phase 4 도입.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    event_id: constr(pattern=r'^dispatch-[0-9]{4}-[0-9]{4,}$') = Field(
        ..., description='예: dispatch-2026-0001'
    )
    source: DispatchSource
    group_id: str = Field(..., description='esg_groups.group_id 참조')
    target_kw: confloat(ge=0.0) | None = Field(
        None,
        description='목표 감축량 (kW). 하위호환 필수 필드 유지 — command 미사용 시 이 값이 GB settlement 입력. command.setpoint_command 경로에선 target_kw=0 + mandatory=false.',
    )
    command: DispatchCommand | None = Field(
        None,
        description='발령 명령 다형 (R18 Item 3, 선택). oneOf(target_kw|setpoint_command|peak_limit_kw). 생략 시 top-level target_kw 사용(하위호환). setpoint_command 경로는 mandatory=false 필수(GB measured passthrough).',
    )
    window: DispatchWindow
    mandatory: bool = Field(
        ...,
        description='true=의무 이행 (신뢰성 DR 통상), false=선택적 (경제성 DR 통상)',
    )
    advance_notice_minutes: conint(ge=0) | None = Field(
        None,
        description='발령 시각부터 window.start까지 예고 시간. esg_policy.reliability.min_advance_minutes 와 비교 검증.',
    )
    dispatched_by: (
        constr(
            pattern=r'^(operator-[a-zA-Z0-9_-]{3,64}|auto-esg-policy-[a-zA-Z0-9_-]+)$'
        )
        | None
    ) = Field(
        None,
        description='서버측 JWT claim에서 derive. operator-{jwt.sub} 또는 auto-{policy_id}. 클라이언트 입력값은 서버가 무시·덮어쓴다. UI 표시는 dispatched_by_display 사용 (PII 보호).',
    )
    jti: constr(min_length=16, max_length=128) | None = Field(
        None,
        description='JWT ID — replay 방어. gridbridge Redis nonce store (TTL=window.end+24h)에 보존. UNIQUE.',
    )
    dispatched_at: AwareDatetime
    status: DispatchStatus
    distribution_algorithm: str | None = Field(
        None,
        description='사용된 분배 알고리즘 (esg_policy.distribution.algorithm 또는 override)',
    )
    allocations: list[MemberAllocation] | None = Field(
        None, description='분배 결과. status≥acknowledged 시 채워짐.'
    )
    execution_report: ExecutionReport | None = Field(
        None, description='이행 후 보고서. status=completed/failed 시 필수.'
    )
    trace: Trace | None = Field(None, description='디버깅용 — 의사결정 트레이스')
