# generated by datamodel-codegen:
#   filename:  tmp50k6huri.json
#   timestamp: 2026-06-30T02:31:18+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, Field, RootModel, conint, constr


class EventType(Enum):
    LOAD_REDUCTION = 'LOAD_REDUCTION'
    PRECOOL = 'PRECOOL'
    ESS_DISCHARGE = 'ESS_DISCHARGE'


class TriggerSource(Enum):
    smp_peak = 'smp_peak'
    weather_heat = 'weather_heat'
    manual = 'manual'
    kpx = 'kpx'


class TargetArea(BaseModel):
    sido_cd: str | None = None
    sgg_cd: str | None = None


class SignalLevel(Enum):
    NORMAL = 'NORMAL'
    MODERATE = 'MODERATE'
    HIGH = 'HIGH'
    EMERGENCY = 'EMERGENCY'


class Status(Enum):
    PENDING = 'PENDING'
    ACTIVE = 'ACTIVE'
    COMPLETED = 'COMPLETED'
    CANCELLED = 'CANCELLED'


class Recurrence(Enum):
    none = 'none'
    daily = 'daily'
    weekdays = 'weekdays'
    weekly = 'weekly'
    monthly = 'monthly'


class Source(Enum):
    vworld = 'vworld'
    gridbridge = 'gridbridge'
    auto = 'auto'


class DailySchedule(RootModel[Any]):
    root: Any


class ReductionSchedule(BaseModel):
    """
    감축 스케줄 — N일간 시간대별 절감 계획. VWorld→GridBridge/EdgeAgent 전달.
    """

    schedule_id: str | None = Field(None, description='스케줄 고유 ID')
    name: str | None = Field(None, description='스케줄 이름')
    ven_id: str | None = Field(None, description='대상 VEN (경로2: 개별)')
    group_id: str | None = Field(None, description='대상 ESG 그룹 (경로1: 그룹)')
    days: list[DailySchedule] = Field(..., min_length=1)
    recurrence: Recurrence | None = None
    created_by: str | None = 'system'
    source: Source | None = None


class DreventLegacySimpleSignalModel(BaseModel):
    """
    DR 이벤트 단순 신호 모델 — Phase 3 이전 사용. **신규 코드는 dr_dispatch_event.json 사용 권장** (Phase 4 ESG Aggregator 레이어 모델, allocations + execution_report + 4-eye RBAC 포함). 본 스키마는 기존 GridBridge dispatch 경로 호환용으로 유지. 향후 dr_dispatch_event.json v2.0에 통합 예정.
    """

    event_id: constr(pattern=r'^EVT-\d{8}-\w+$')
    event_type: EventType
    trigger_source: TriggerSource | None = None
    target_area: TargetArea | None = None
    signal_level: SignalLevel | None = None
    reduction_target_kw: conint(ge=0) | None = None
    start_time: AwareDatetime = Field(..., description='이벤트 예정 시작 시각.')
    end_time: AwareDatetime = Field(
        ...,
        description='이벤트 예정 종료 시각. status=CANCELLED 시에도 원래 예정 종료 시각을 그대로 보존(참고용). 실제 종료는 updated_at 로 추적.',
    )
    status: Status | None = None
    schedule: ReductionSchedule | None = Field(
        None, description='상세 감축 스케줄 (Optional)'
    )
