# generated by datamodel-codegen:
#   filename:  edge_strategy_capability.json
#   timestamp: 2026-09-11T10:06:23+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, constr


class EdgeStrategyCapability(BaseModel):
    """
    엣지가 **실제로 구동할 수 있는** EMS 전략. 정본(ems_strategies.json M00~M22 23종)의 부분집합이다. ⚠ 이 파일은 '무엇을 부를 수 있는가'가 아니라 '무엇을 할 수 있는가'를 선언한다. 2026-08-16 인수검사에서 화면은 23종을 내주고 엣지는 9종만 받는 격차 14종이 실측됐고, 거부 메시지는 'M00~M20 이어야 함'이라 실제 이유를 거짓으로 말하고 있었다. **2026-08-17: 14종을 실제로 구현했다.** 전략이 3개 점(HVAC·조명·ESS)만 쓸 수 있어 '냉동기'·'외기댐퍼'·'전열교환기'를 말할 어휘가 없던 것이 근본 원인이었다. 제어점을 10개로 넓혀 전 전략이 자기 축을 갖는다. 그래서 이 목록은 이제 **고정 집합이 아니라 기준 구성(reference)** 이다 — 실제 지원 여부는 드라이버의 점 지도에서 파생된다.
    """

    version: str
    dispatchable: list[constr(pattern=r'^M(0\d|1\d|2[0-2])$')] = Field(
        ...,
        description='엣지가 지금 구동 가능한 전략. 화면은 이 집합만 실행 가능한 것으로 내줘야 한다.',
    )
    not_dispatchable: dict[str, str] = Field(
        ...,
        description="정본에는 있으나 이 구성에서 못 하는 전략 → 사유. **비워 두지 말 것** — 비면 '왜 못 하는지'가 사라진다. 2026-08-17 기준 구성(virtual)에서는 전부 구동하므로 비어 있다.",
    )
