# generated by datamodel-codegen:
#   filename:  edge_registration.json
#   timestamp: 2026-06-30T02:31:22+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, Field, confloat, conint, constr


class EdgeType(Enum):
    """
    common.json §EdgeType SSOT (backend 정합). backend real_bas=device, replay=replay, energyplus=eplus, virtual=synthetic. 가상/현장은 별개 축 = 관제점 바인딩.
    """

    device = 'device'
    replay = 'replay'
    eplus = 'eplus'
    synthetic = 'synthetic'


class Kind(Enum):
    """
    운영 모드 — common.json §Kind SSOT. 관례: replay=telemetry, device·eplus·synthetic=dispatch.
    """

    telemetry = 'telemetry'
    dispatch = 'dispatch'


class Backend(Enum):
    """
    구현 기술 — common.json §Backend SSOT.
    """

    replay = 'replay'
    energyplus = 'energyplus'
    real_bas = 'real_bas'
    virtual = 'virtual'


class BuildingType(Enum):
    """
    common.json §BuildingType SSOT.
    """

    office_large = 'office_large'
    office_medium = 'office_medium'
    office_small = 'office_small'
    hospital = 'hospital'
    school = 'school'
    retail = 'retail'
    convenience_store = 'convenience_store'
    apartment = 'apartment'
    other = 'other'


class Location(BaseModel):
    lat: float | None = None
    lng: float | None = None


class Capabilities(BaseModel):
    supported_strategies: list[constr(pattern=r'^M(0[0-9]|1[0-9]|20)$')]
    controllable_points: list[str] | None = Field(
        None, description="예: ['hvac_setpoint','lighting_pct','ess_discharge']"
    )
    has_ess: bool | None = False
    has_pv: bool | None = False
    step_seconds: conint(ge=60) | None = Field(
        None, description='시뮬/계측 최소 타임스텝'
    )


class DriverType(Enum):
    virtual = 'virtual'
    replay = 'replay'
    energyplus = 'energyplus'
    bacnet = 'bacnet'
    modbus = 'modbus'
    matter = 'matter'


class Software(BaseModel):
    firmware_version: str | None = None
    edge_agent_version: str | None = None
    driver_types: list[DriverType] | None = None


class Hardware(BaseModel):
    platform: str | None = Field(
        None, description='예: rpi5, x86-industrial, container'
    )
    cpu_cores: int | None = None
    memory_mb: int | None = None


class EdgeRegistration(BaseModel):
    """
    EdgeAgent 기동 시 MQTT `fleet/register/{ven_id}` 또는 `gridbridge/registration/{ven_id}` 토픽으로 발행하는 자동 등록 메타. Edge → GB. VW broker-architecture §5 호환.
    """

    ven_id: constr(
        pattern=r'^VEN-(STORE|EP|REAL|TEST|E2E|SHOP)-[A-Z0-9][A-Z0-9\-]*$'
    ) = Field(
        ...,
        description='ven_id 네이밍 규칙: VEN-STORE-xxx(관측형 편의점) · VEN-EP-xxx(E+ 가상) · VEN-REAL-xxx(실 설비) · VEN-TEST-xxx · VEN-E2E-xxx. 접두 뒤엔 영숫자·하이픈 조합 자유.',
    )
    edge_type: EdgeType = Field(
        ...,
        description='common.json §EdgeType SSOT (backend 정합). backend real_bas=device, replay=replay, energyplus=eplus, virtual=synthetic. 가상/현장은 별개 축 = 관제점 바인딩.',
    )
    kind: Kind = Field(
        ...,
        description='운영 모드 — common.json §Kind SSOT. 관례: replay=telemetry, device·eplus·synthetic=dispatch.',
    )
    backend: Backend = Field(..., description='구현 기술 — common.json §Backend SSOT.')
    building_type: BuildingType | None = Field(
        None, description='common.json §BuildingType SSOT.'
    )
    group_id: str | None = Field(
        None,
        description='ESG 그룹. 예: ESG-STORE-100, ESG-STORE-120, ESG-EP-OFFICE, ESG-EP-APT',
    )
    pnu: str | None = None
    building_name: str | None = None
    location: Location | None = None
    ep_model: str | None = Field(
        None,
        description='backend=energyplus 일 때 IDF 템플릿 식별자(예: medium_office_2010_RC)',
    )
    baseline_kw: confloat(ge=0.0) | None = None
    max_reduction_kw: confloat(ge=0.0) | None = None
    capabilities: Capabilities
    software: Software | None = None
    hardware: Hardware | None = None
    mqtt_client_id: str | None = None
    registered_at: AwareDatetime
    envelope: dict[str, Any] | None = Field(
        None,
        description='건물 외피·기하·설비 메타 (선택). 전체 스키마는 building_envelope.json v1.0 SSOT 참조. Edge 가 현장 실측값 보유 시 등록 페이로드에 embed — VW 측 포트폴리오 UI 에서 편집 가능.',
    )
