# generated by datamodel-codegen:
#   filename:  edge_registration.json
#   timestamp: 2026-09-11T10:06:21+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    confloat,
    conint,
    constr,
)


class EdgeType(Enum):
    """
    common.json §EdgeType SSOT (backend 정합). backend real_bas=device, replay=replay, energyplus=eplus, virtual=synthetic. 가상/현장은 별개 축 = 관제점 바인딩.
    """

    device = 'device'
    replay = 'replay'
    eplus = 'eplus'
    synthetic = 'synthetic'


class Kind(Enum):
    """
    운영 모드 — common.json §Kind SSOT. 관례: replay=telemetry, device·eplus·synthetic=dispatch.
    """

    telemetry = 'telemetry'
    dispatch = 'dispatch'


class Backend(Enum):
    """
    구현 기술 — common.json §Backend SSOT.
    """

    replay = 'replay'
    energyplus = 'energyplus'
    real_bas = 'real_bas'
    virtual = 'virtual'


class BuildingType(Enum):
    """
    common.json §BuildingType SSOT.
    """

    office_large = 'office_large'
    office_medium = 'office_medium'
    office_small = 'office_small'
    hospital = 'hospital'
    school = 'school'
    retail = 'retail'
    convenience_store = 'convenience_store'
    apartment = 'apartment'
    other = 'other'


class Type(Enum):
    esg = 'esg'
    microgrid = 'microgrid'
    independent = 'independent'
    dr_resource = 'dr_resource'
    legal_entity = 'legal_entity'
    building = 'building'


class Affiliation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type
    id: str = Field(
        ...,
        description='소속 식별자. type=esg → esg_groups.group_id · type=microgrid → microgridDomainId · type=independent → 자유 · type=dr_resource → 수요관리사업자가 부여한 자원 id · type=legal_entity → 법인/사업장 식별자 · type=building → PNU(건축물대장). ⚠ 배타성: microgrid·legal_entity·building 은 각 1개(물리·법적으로 하나뿐), esg·dr_resource 는 복수 가능(같은 건물이 여러 포트폴리오·자원에 들 수 있다). ⚠ 저작 주체: microgrid=MGCC · esg/dr_resource=GB(수요관리사업자) · legal_entity=그룹사 마스터 · building=건축물대장. 소비자가 남의 축을 지어내면 시장 등록 구성과 어긋난다',
    )


class Location(BaseModel):
    lat: float | None = None
    lng: float | None = None


class Capabilities(BaseModel):
    supported_strategies: list[constr(pattern=r'^M(0[0-9]|1[0-9]|[2-9][0-9])$')]
    controllable_points: list[str] | None = Field(
        None, description="예: ['hvac_setpoint','lighting_pct','ess_discharge']"
    )
    has_ess: bool | None = False
    has_pv: bool | None = False
    step_seconds: conint(ge=60) | None = Field(
        None, description='시뮬/계측 최소 타임스텝'
    )


class DriverType(Enum):
    virtual = 'virtual'
    replay = 'replay'
    energyplus = 'energyplus'
    bacnet = 'bacnet'
    modbus = 'modbus'
    matter = 'matter'


class Software(BaseModel):
    firmware_version: str | None = None
    edge_agent_version: str | None = None
    driver_types: list[DriverType] | None = None


class Hardware(BaseModel):
    platform: str | None = Field(
        None, description='예: rpi5, x86-industrial, container'
    )
    cpu_cores: int | None = None
    memory_mb: int | None = None


class Kind1(Enum):
    """
    equipment_taxonomy#/$defs/EquipmentKind
    """

    hvac = 'hvac'
    ahu = 'ahu'
    vav = 'vav'
    chiller = 'chiller'
    boiler = 'boiler'
    fan = 'fan'
    pump = 'pump'
    lighting = 'lighting'
    ess = 'ess'
    pv = 'pv'
    plug = 'plug'
    meter = 'meter'
    radiant = 'radiant'
    vrf = 'vrf'
    district_heat = 'district_heat'
    dhw = 'dhw'
    refrigeration = 'refrigeration'
    cooling_tower = 'cooling_tower'
    erv = 'erv'
    other = 'other'


class EquipmentItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    device_id: str = Field(..., description='VEN 내 unique')
    kind: Kind1 = Field(..., description='equipment_taxonomy#/$defs/EquipmentKind')
    subtype: str | None = Field(
        None, description='equipment_taxonomy.subtypes 권장 목록(열린 값)'
    )
    label: str | None = None
    floor: int | None = None
    zone: str | None = None
    point_id: str | None = Field(None, description='CPA 정규 주소(있으면)')


class EdgeRegistration(BaseModel):
    """
    EdgeAgent 기동 시 MQTT `fleet/register/{ven_id}` 또는 `gridbridge/registration/{ven_id}` 토픽으로 발행하는 자동 등록 메타. Edge → GB. VW broker-architecture §5 호환.
    """

    ven_id: constr(
        pattern=r'^VEN-(STORE|EP|REAL|TEST|E2E|SHOP)-[A-Z0-9][A-Z0-9\-]*$'
    ) = Field(
        ...,
        description='ven_id 네이밍 규칙: VEN-STORE-xxx(관측형 편의점) · VEN-EP-xxx(E+ 가상) · VEN-REAL-xxx(실 설비) · VEN-TEST-xxx · VEN-E2E-xxx. 접두 뒤엔 영숫자·하이픈 조합 자유.',
    )
    edge_type: EdgeType = Field(
        ...,
        description='common.json §EdgeType SSOT (backend 정합). backend real_bas=device, replay=replay, energyplus=eplus, virtual=synthetic. 가상/현장은 별개 축 = 관제점 바인딩.',
    )
    kind: Kind = Field(
        ...,
        description='운영 모드 — common.json §Kind SSOT. 관례: replay=telemetry, device·eplus·synthetic=dispatch.',
    )
    backend: Backend = Field(..., description='구현 기술 — common.json §Backend SSOT.')
    building_type: BuildingType | None = Field(
        None, description='common.json §BuildingType SSOT.'
    )
    group_id: str | None = Field(
        None,
        description='[DEPRECATED — affiliations[] 로 대체, R18 Item 2] 단일 ESG 그룹. 하위호환 유지: 신규 발행은 affiliations[{type:esg, id:...}] 사용. group_id 만 온 구형 페이로드는 GB 가 affiliations[{type:esg, id:group_id}] 로 자동 마이그레이션(무회귀). 예: ESG-STORE-100, ESG-EP-OFFICE',
    )
    affiliations: list[Affiliation] | None = Field(
        None,
        description='소속 다형 (R18 Item 2). 한 VEN 이 여러 소속 동시 보유 가능(ESG + microgrid). type 축 분리: esg=논리적 감축 포트폴리오(GB 정산 단위, esg_group_venues 정션 반영) / microgrid=물리적 배전 도메인(Edge 실행 컨텍스트 — GB 정산 무연동, passthrough) / independent=무소속. GB 는 type=esg 만 esg_group_venues 에 upsert. **v1.3 확장(2026-08-02)**: dr_resource=수요자원 거래시장 등록 단위(수요관리사업자가 참여고객을 모아 구성 — 전력시장운영규칙) / legal_entity=법인·사업장(온실가스 목표관리제·에너지다소비사업자 보고 단위) / building=동 식별(건축물대장·PNU, ZEB·BEMS 설치확인 단위). **왜 필요한가**: 그룹 단위가 제도 축마다 다르다 — 건물 성능 제도는 동 1개, 온실가스는 법인, DR 은 다수 수용가 묶음이다. 하나의 그룹 숫자를 세 곳에 쓸 수 없어 축별 롤업 경로가 필요하다.',
    )
    pnu: str | None = None
    building_name: str | None = None
    location: Location | None = None
    ep_model: str | None = Field(
        None,
        description='backend=energyplus 일 때 IDF 템플릿 식별자(예: medium_office_2010_RC)',
    )
    baseline_kw: confloat(ge=0.0) | None = None
    max_reduction_kw: confloat(ge=0.0) | None = None
    capabilities: Capabilities
    software: Software | None = None
    hardware: Hardware | None = None
    mqtt_client_id: str | None = None
    registered_at: AwareDatetime
    envelope: dict[str, Any] | None = Field(
        None,
        description='건물 외피·기하·설비 메타 (선택). 전체 스키마는 building_envelope.json v1.0 SSOT 참조. Edge 가 현장 실측값 보유 시 등록 페이로드에 embed — VW 측 포트폴리오 UI 에서 편집 가능.',
    )
    equipment_summary: (
        dict[
            constr(
                pattern=r'^(hvac|ahu|vav|chiller|boiler|fan|pump|lighting|ess|pv|plug|meter|radiant|vrf|district_heat|dhw|refrigeration|cooling_tower|erv|other)$'
            ),
            conint(ge=0),
        ]
        | None
    ) = Field(
        None,
        description="설비 종류 → 대수. 엣지 로컬 설비 대장(DeviceCatalog)의 **요약**이다. **왜 요약인가**: 전체 목록은 건물당 수백 개까지 가고 드라이버 주소 같은 현장 바인딩 상세를 포함한다 — 그룹 관제가 알아야 할 것은 '이 건물에 무엇이 몇 대 있나' 까지다. 전수는 `equipment[]`(선택)로.",
    )
    equipment: list[EquipmentItem] | None = Field(
        None,
        description='설비 대장 **요약 엔트리**(선택). 그룹 드릴다운용이며 ⚠ **`driver_address` 는 싣지 않는다** — BACnet 인스턴스·Modbus 레지스터는 현장 바인딩 상세이고, 원격이 들고 있으면 현장이 배선을 바꿔도 원격 사본이 낡은 채 남는다(§DECISION-POINT-ADDRESSING: BACnet=바인딩 / CPA=식별).',
    )
