# generated by datamodel-codegen:
#   filename:  edge_status.json
#   timestamp: 2026-06-30T02:31:28+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, Field, conint, constr


class State(Enum):
    """
    online=정상, degraded=일부 드라이버 단절, offline=곧 종료/응답불가, booting=기동중
    """

    online = 'online'
    degraded = 'degraded'
    offline = 'offline'
    booting = 'booting'


class Queue(BaseModel):
    """
    로컬 outbox 큐 상태(브로커 단절 내성).
    """

    size: conint(ge=0) | None = None
    oldest_age_sec: int | None = None
    max_age_sec: int | None = None


class Driver(BaseModel):
    name: str = Field(
        ..., description='예: virtual, energyplus, bacnet, modbus, replay'
    )
    connected: bool
    last_read_at: AwareDatetime | None = None
    last_error: str | None = None
    points_ok: int | None = Field(None, description='정상 포인트 수')
    points_err: int | None = Field(None, description='오류 포인트 수')


class Ems(BaseModel):
    """
    현재 EMS 실행 상태.
    """

    active_strategy: constr(pattern=r'^M(0[0-9]|1[0-9]|20)$') | None = None
    schedule_slot_idx: int | None = None
    schedule_id: str | None = None
    interlocks_fired_1h: conint(ge=0) | None = None


class Links(BaseModel):
    """
    외부 연결 상태.
    """

    mqtt_gb: bool | None = None
    mqtt_vw: bool | None = None
    ven_vtn: bool | None = Field(None, description='OpenADR VEN 레거시 경로')


class EdgeStatus(BaseModel):
    """
    EdgeAgent heartbeat + 설비·드라이버 상태. Edge → GB (보통 30~60초 주기).
    """

    ven_id: str
    timestamp: AwareDatetime
    state: State = Field(
        ...,
        description='online=정상, degraded=일부 드라이버 단절, offline=곧 종료/응답불가, booting=기동중',
    )
    uptime_sec: conint(ge=0)
    edge_agent_version: str | None = None
    queue: Queue | None = Field(
        None, description='로컬 outbox 큐 상태(브로커 단절 내성).'
    )
    drivers: list[Driver] | None = None
    ems: Ems | None = Field(None, description='현재 EMS 실행 상태.')
    links: Links | None = Field(None, description='외부 연결 상태.')
    config_hash: constr(pattern=r'^[a-f0-9]{16}$') | None = Field(
        None,
        description='현재 적용 중인 Edge 설정(YAML 전체)의 SHA256 앞 16자리 16진수. VW/GB 가 중앙 저장된 설정과 비교하여 drift 감지. 미일치 시 VW 측에서 재배포 플로우 트리거. 계산 범위: envelope + connection + data_points + interlocks + supported_strategies (민감정보·타임스탬프 제외).',
    )
    config_updated_at: AwareDatetime | None = Field(
        None,
        description='Edge 측 설정 파일 마지막 반영 시각. VW 중앙 설정의 updated_at 과 비교하여 신선도 확인.',
    )
    api_token_hash: constr(pattern=r'^[a-f0-9]{16}$|^$') | None = Field(
        None,
        description='Edge 로컬 HTTP API (R7 W1) 토큰의 SHA256 앞 16자리. VW/GB 가 현장 토큰 재생성·드리프트 탐지용. 토큰 미설정(=localhost only) 이면 빈 문자열 또는 생략. v1.2 (R7-3, 2026-04-19).',
    )
