# generated by datamodel-codegen:
#   filename:  emission_factors.json
#   timestamp: 2026-06-30T02:31:42+00:00

from __future__ import annotations

from datetime import date

from pydantic import BaseModel, Field


class KR(BaseModel):
    electricity: float = Field(..., description='전력 간접배출 (소비단, 2023 확정)')
    gas: float = Field(..., description='LNG 도시가스 연소 (IPCC 2006)')
    district_heat: float = Field(..., description='지역난방 수도권 (2024)')


class ID(BaseModel):
    """
    인도네시아 (PLN grid)
    """

    electricity: float | None = None
    gas: float | None = None


class Co2Kgco2eqPerKwh(BaseModel):
    """
    에너지원별 CO2 배출계수 (kgCO2eq/kWh)
    """

    KR_1: KR = Field(..., alias='KR')
    ID_1: ID | None = Field(None, alias='ID', description='인도네시아 (PLN grid)')


class Metadata(BaseModel):
    source: str | None = None
    reference_year: int | None = None
    publish_date: date | None = None
    next_update: str | None = None
    governance: str | None = None


class EmissionFactors(BaseModel):
    """
    CO2 배출계수 SSOT. ENERGY_SSOT.md §1 기반. 모든 모듈은 이 값을 단일 원본으로 사용.
    """

    co2_kgco2eq_per_kwh: Co2Kgco2eqPerKwh | None = Field(
        None, description='에너지원별 CO2 배출계수 (kgCO2eq/kWh)'
    )
    metadata: Metadata | None = None
