# generated by datamodel-codegen:
#   filename:  ems_strategies.json
#   timestamp: 2026-09-14T21:15:28+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, confloat


class Type(Enum):
    """
    단일 전략 vs 복합 전략
    """

    single = 'single'
    combined = 'combined'


class LegacyMapping(BaseModel):
    """
    구 코드 → 통일 코드 매핑 (읽기 전용, 신규 작성 금지)
    """

    ems_simulation: dict[str, Any] | None = None
    gcs_e_codes: dict[str, Any] | None = Field(
        None,
        description='GENERATED — 손편집 금지. legacy_ems_code_mapping.json#deprecated_e_codes[*].maps_to 의 투영이다(scripts/legacy_e_codes.py, gen_constants.py --all 이 동기화). 뜻(다중 M)은 그 표의 components 를 읽는다.',
    )
    ems_transformer_sc: dict[str, Any] | None = None


class StrategyCode(Enum):
    """
    통일 EMS 전략 코드 (23종, M00~M22). M00~M20=시뮬 EMS(NAMING §1.1), M16~M20=DR 제어 액션(ADR-EMS-NAMESPACE-UNIFY), M21~M22=시뮬 확장 전략(ThermalStorage/PV 자가소비, 2026-07-10 승격).
    """

    M00 = 'M00'
    M01 = 'M01'
    M02 = 'M02'
    M03 = 'M03'
    M04 = 'M04'
    M05 = 'M05'
    M06 = 'M06'
    M07 = 'M07'
    M08 = 'M08'
    M09 = 'M09'
    M10 = 'M10'
    M11 = 'M11'
    M12 = 'M12'
    M13 = 'M13'
    M14 = 'M14'
    M15 = 'M15'
    M16 = 'M16'
    M17 = 'M17'
    M18 = 'M18'
    M19 = 'M19'
    M20 = 'M20'
    M21 = 'M21'
    M22 = 'M22'


class ObjectiveType(Enum):
    """
    운영 목적(objective) 축 — APE 운영 프로파일 · signal_mapping_dr dr_type · dr_dispatch_event.DispatchSource(∪ microgrid_safety) 의 단일 SSOT (R18 Item 1). reliability=신뢰성 우선 / economic=비용최적 / carbon=탄소최소 / optimal=통합 균형. dr_dispatch_event.json 은 이 enum 을 재사용(DispatchSource = ObjectiveType ∪ {microgrid_safety}); validate_ssot.check_objective_dispatch_sync 가 동기 강제.
    """

    reliability = 'reliability'
    economic = 'economic'
    carbon = 'carbon'
    optimal = 'optimal'


class SignalDrMapping(BaseModel):
    """
    한 SignalLevel 에서 objective(ObjectiveType) 별 전략 코드. 4 objective 전부 필수.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    reliability: StrategyCode
    economic: StrategyCode
    carbon: StrategyCode
    optimal: StrategyCode


class PersonaStrategy(BaseModel):
    """
    한 운영 프로파일(objective)의 기본 전략 — 상시(normal)·피크(peak) M-code + ESS 예비율. APE 가 objective 해석 시 사용.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    normal: StrategyCode
    peak: StrategyCode
    ess_reserve_pct: confloat(ge=0.0, le=100.0) = Field(
        ...,
        description='피크 대비 유지할 ESS 최소 예비율(%). reliability↑ → 예비 보수적, economic/carbon → 적극 방전.',
    )


class OpMode(Enum):
    """
    건물 운영 모드(BEMS 스케줄 구간 축) — bems-console lib/presets.ts OpMode 의 단일 SSOT. occupied=근무중(업무시간 점유) / night=야간(비점유·셋백) / weekend=주말(휴일·최소) / peak=피크(수요반응·부하감축) / emergency=비상(안전 우선). 콘솔이 시간구간(from~to)에 이 모드를 저작 → provision → edge ScheduleRunner 가 opmode_strategy_map 으로 M-code 해석해 실행.
    """

    occupied = 'occupied'
    night = 'night'
    weekend = 'weekend'
    peak = 'peak'
    emergency = 'emergency'


class Strategies(BaseModel):
    name_en: str
    name_kr: str
    description: str | None = None
    type: Type = Field(..., description='단일 전략 vs 복합 전략')
    components: list[StrategyCode] = Field(
        ..., description='복합 전략의 구성 요소 (single은 빈 배열)'
    )


class SignalMapping(BaseModel):
    """
    DR SignalLevel → 기본 전략 매핑 (flat, fallback). dr_type 컨텍스트 없을 때 사용.
    """

    NORMAL: StrategyCode | None = None
    MODERATE: StrategyCode | None = None
    HIGH: StrategyCode | None = None
    EMERGENCY: StrategyCode | None = None


class SignalMappingDr(BaseModel):
    """
    DR SignalLevel → 전략 매핑, objective(dr_type)별 분기 (Phase 4 도입, R18 Item 1 에서 2 objective→4 objective 확장). esg_policy.dr_type / APE 운영 프로파일 ∈ ObjectiveType {reliability,economic,carbon,optimal} 시 사용. 4 SignalLevel × 4 objective = 16 키 모두 필수. Fallback 체인: signal_mapping_dr.{level}.{objective} 정의 누락(신규 carbon/optimal 포함) 시 → signal_mapping_dr.{level}.reliability (보수적 가정) → signal_mapping.{level} (flat) → M00. dr_agent / APE loader 가 startup 시 16 키 모두 존재 검증(edge·be-3d 소관; GB 는 DispatchSource 생성측이라 본 매핑 비소비).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    NORMAL: SignalDrMapping
    MODERATE: SignalDrMapping
    HIGH: SignalDrMapping
    EMERGENCY: SignalDrMapping


class PersonaStrategyMap(BaseModel):
    """
    APE 운영 프로파일(objective) → 기본 전략(상시/피크 M-code + ESS 예비율) 매핑 (R18 Item 1). ObjectiveType 4종 전부 필수. APE 가 dr_dispatch_event 없이 자율 운영할 때의 기본 프로파일. peak M-code 는 SignalLevel HIGH/EMERGENCY 시 참고값(실제 발령은 signal_mapping_dr 우선).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    reliability: PersonaStrategy
    economic: PersonaStrategy
    carbon: PersonaStrategy
    optimal: PersonaStrategy


class OpmodeStrategyMap(BaseModel):
    """
    건물 운영 모드(OpMode) → 기본 EMS 전략(M-code) 매핑. bems-console 이 스케줄 구간에 저작한 OpMode 를 edge ScheduleRunner 가 실행 가능한 M-code 로 해석하는 SSOT. OpMode 5종 전부 필수. peak/emergency 는 signal_mapping_dr(DR 발령) 우선 — 본 매핑은 DR 신호 부재 시 스케줄 자율 운영 기본값. 건물 고유 override 는 provision schedule.entries[].strategy 로 개별 지정 가능(본 매핑은 미지정 시 폴백).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    occupied: StrategyCode
    night: StrategyCode
    weekend: StrategyCode
    peak: StrategyCode
    emergency: StrategyCode


class EmsStrategies(BaseModel):
    """
    EMS 전략 코드 SSOT (M00~M20). M00~M20=시뮬 EMS(NAMING §1.1), M16~M20=DR 제어 액션. ADR-EMS-NAMESPACE-UNIFY. 모든 모듈은 이 정의를 참조.
    """

    strategies: dict[StrategyCode, Strategies] | None = None
    signal_mapping: SignalMapping | None = Field(
        None,
        description='DR SignalLevel → 기본 전략 매핑 (flat, fallback). dr_type 컨텍스트 없을 때 사용.',
    )
    signal_mapping_dr: SignalMappingDr | None = Field(
        None,
        description='DR SignalLevel → 전략 매핑, objective(dr_type)별 분기 (Phase 4 도입, R18 Item 1 에서 2 objective→4 objective 확장). esg_policy.dr_type / APE 운영 프로파일 ∈ ObjectiveType {reliability,economic,carbon,optimal} 시 사용. 4 SignalLevel × 4 objective = 16 키 모두 필수. Fallback 체인: signal_mapping_dr.{level}.{objective} 정의 누락(신규 carbon/optimal 포함) 시 → signal_mapping_dr.{level}.reliability (보수적 가정) → signal_mapping.{level} (flat) → M00. dr_agent / APE loader 가 startup 시 16 키 모두 존재 검증(edge·be-3d 소관; GB 는 DispatchSource 생성측이라 본 매핑 비소비).',
    )
    persona_strategy_map: PersonaStrategyMap | None = Field(
        None,
        description='APE 운영 프로파일(objective) → 기본 전략(상시/피크 M-code + ESS 예비율) 매핑 (R18 Item 1). ObjectiveType 4종 전부 필수. APE 가 dr_dispatch_event 없이 자율 운영할 때의 기본 프로파일. peak M-code 는 SignalLevel HIGH/EMERGENCY 시 참고값(실제 발령은 signal_mapping_dr 우선).',
    )
    opmode_strategy_map: OpmodeStrategyMap | None = Field(
        None,
        description='건물 운영 모드(OpMode) → 기본 EMS 전략(M-code) 매핑. bems-console 이 스케줄 구간에 저작한 OpMode 를 edge ScheduleRunner 가 실행 가능한 M-code 로 해석하는 SSOT. OpMode 5종 전부 필수. peak/emergency 는 signal_mapping_dr(DR 발령) 우선 — 본 매핑은 DR 신호 부재 시 스케줄 자율 운영 기본값. 건물 고유 override 는 provision schedule.entries[].strategy 로 개별 지정 가능(본 매핑은 미지정 시 폴백).',
    )
    legacy_mapping: LegacyMapping | None = Field(
        None, description='구 코드 → 통일 코드 매핑 (읽기 전용, 신규 작성 금지)'
    )
