# generated by datamodel-codegen:
#   filename:  ems_strategies.json
#   timestamp: 2026-06-30T02:31:45+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class Type(Enum):
    """
    단일 전략 vs 복합 전략
    """

    single = 'single'
    combined = 'combined'


class LegacyMapping(BaseModel):
    """
    구 코드 → 통일 코드 매핑 (읽기 전용, 신규 작성 금지)
    """

    ems_simulation: dict[str, Any] | None = None
    gcs_e_codes: dict[str, Any] | None = None
    ems_transformer_sc: dict[str, Any] | None = None


class StrategyCode(Enum):
    """
    통일 EMS 전략 코드 (21종, M00~M20). M00~M20=시뮬 EMS(NAMING §1.1), M16~M20=DR 제어 액션(ADR-EMS-NAMESPACE-UNIFY).
    """

    M00 = 'M00'
    M01 = 'M01'
    M02 = 'M02'
    M03 = 'M03'
    M04 = 'M04'
    M05 = 'M05'
    M06 = 'M06'
    M07 = 'M07'
    M08 = 'M08'
    M09 = 'M09'
    M10 = 'M10'
    M11 = 'M11'
    M12 = 'M12'
    M13 = 'M13'
    M14 = 'M14'
    M15 = 'M15'
    M16 = 'M16'
    M17 = 'M17'
    M18 = 'M18'
    M19 = 'M19'
    M20 = 'M20'


class Strategies(BaseModel):
    name_en: str
    name_kr: str
    description: str | None = None
    type: Type = Field(..., description='단일 전략 vs 복합 전략')
    components: list[StrategyCode] = Field(
        ..., description='복합 전략의 구성 요소 (single은 빈 배열)'
    )


class SignalMapping(BaseModel):
    """
    DR SignalLevel → 기본 전략 매핑 (flat, fallback). dr_type 컨텍스트 없을 때 사용.
    """

    NORMAL: StrategyCode | None = None
    MODERATE: StrategyCode | None = None
    HIGH: StrategyCode | None = None
    EMERGENCY: StrategyCode | None = None


class NORMAL(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    reliability: StrategyCode
    economic: StrategyCode


class MODERATE(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    reliability: StrategyCode
    economic: StrategyCode


class HIGH(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    reliability: StrategyCode
    economic: StrategyCode


class EMERGENCY(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    reliability: StrategyCode
    economic: StrategyCode


class SignalMappingDr(BaseModel):
    """
    DR SignalLevel → 전략 매핑, dr_type별 분기 (Phase 4 도입). esg_policy.dr_type ∈ {reliability,economic,both} 시 사용. 4 SignalLevel × 2 dr_type = 8 키 모두 필수. Fallback 체인: signal_mapping_dr.{level}.{type} 정의 누락 시 → signal_mapping_dr.{level}.reliability (보수적 가정) → signal_mapping.{level} (flat) → M00. dr_agent loader가 startup 시 8 키 모두 존재 검증.
    """

    NORMAL_1: NORMAL = Field(..., alias='NORMAL')
    MODERATE_1: MODERATE = Field(..., alias='MODERATE')
    HIGH_1: HIGH = Field(..., alias='HIGH')
    EMERGENCY_1: EMERGENCY = Field(..., alias='EMERGENCY')


class EmsStrategies(BaseModel):
    """
    EMS 전략 코드 SSOT (M00~M20). M00~M20=시뮬 EMS(NAMING §1.1), M16~M20=DR 제어 액션. ADR-EMS-NAMESPACE-UNIFY. 모든 모듈은 이 정의를 참조.
    """

    strategies: dict[StrategyCode, Strategies] | None = None
    signal_mapping: SignalMapping | None = Field(
        None,
        description='DR SignalLevel → 기본 전략 매핑 (flat, fallback). dr_type 컨텍스트 없을 때 사용.',
    )
    signal_mapping_dr: SignalMappingDr | None = Field(
        None,
        description='DR SignalLevel → 전략 매핑, dr_type별 분기 (Phase 4 도입). esg_policy.dr_type ∈ {reliability,economic,both} 시 사용. 4 SignalLevel × 2 dr_type = 8 키 모두 필수. Fallback 체인: signal_mapping_dr.{level}.{type} 정의 누락 시 → signal_mapping_dr.{level}.reliability (보수적 가정) → signal_mapping.{level} (flat) → M00. dr_agent loader가 startup 시 8 키 모두 존재 검증.',
    )
    legacy_mapping: LegacyMapping | None = Field(
        None, description='구 코드 → 통일 코드 매핑 (읽기 전용, 신규 작성 금지)'
    )
