# generated by datamodel-codegen:
#   filename:  energyplus_run_manifest.json
#   timestamp: 2026-09-11T10:06:26+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    confloat,
    constr,
)


class Code(Enum):
    H_A = 'H_A'
    H_B = 'H_B'
    H_C = 'H_C'
    H_D = 'H_D'
    H_E = 'H_E'
    H_F = 'H_F'
    H_G = 'H_G'


class HvacHypothesis(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Code
    label: constr(min_length=1)
    is_observed: Literal[False]


class Period(Enum):
    annual = 'annual'
    design_week = 'design_week'
    custom = 'custom'


class Runs(BaseModel):
    pass


class Sha256(RootModel[constr(pattern=r'^sha256:[a-f0-9]{64}$')]):
    root: constr(pattern=r'^sha256:[a-f0-9]{64}$')


class CoolingSetpointC(Enum):
    number_24 = 24
    number_25 = 25
    number_26 = 26


class Role(Enum):
    baseline = 'baseline'
    counterfactual = 'counterfactual'


class AnnualEnergyKwh(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    electricity: confloat(ge=0.0)
    natural_gas: confloat(ge=0.0)
    district_heating: confloat(ge=0.0)
    district_cooling: confloat(ge=0.0)
    facility_total: confloat(ge=0.0)


class Comfort(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    method: constr(min_length=1)
    warm_limit: confloat(ge=0.0)
    cold_limit: confloat(le=0.0)
    pmv_warmest: float
    pmv_coldest: float


class Run(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    run_id: constr(min_length=1)
    cooling_setpoint_c: CoolingSetpointC
    role: Role
    status: Literal['verified']
    energyplus_version: constr(min_length=1)
    input_idf_sha256: Sha256
    result_sha256: Sha256
    severe_count: Literal[0]
    annual_energy_kwh: AnnualEnergyKwh
    comfort: Comfort


class BuildingArchetype(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: constr(pattern=r'^B(0[1-9]|1[0-7])$')
    name: constr(min_length=1)
    source_idf_sha256: Sha256


class Weather(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    city: constr(min_length=1)
    epw_sha256: Sha256


class EnergyPlusRunManifest(BaseModel):
    """
    표준 HVAC 가설 하나의 불변 EnergyPlus 설정온도 실행 묶음. 실측·현장 적용·M&V 증거가 아니다.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0']
    manifest_id: constr(pattern=r'^eplus-grid-[a-z0-9_-]+$')
    created_at: AwareDatetime
    producer: constr(min_length=1)
    evidence_state: Literal['energyplus_cross_check']
    building_archetype: BuildingArchetype
    hvac_hypothesis: HvacHypothesis
    weather: Weather
    period: Period
    runs: list[Run] | Runs = Field(..., max_length=3, min_length=3)
