# generated by datamodel-codegen:
#   filename:  energy_units.json
#   timestamp: 2026-06-30T02:31:51+00:00

from __future__ import annotations

from pydantic import BaseModel


class EnergyUnitsConversionSsotPhaseJ12(BaseModel):
    """
    kWh ↔ MJ ↔ kg-CO2 ↔ 1차 에너지 변환계수. ~/.claude/ENERGY_SSOT.md + CARBON_EMISSION_FACTORS.yaml 의 머신리더블 추출. 계산 코드는 본 SSOT를 사용.
    """
