# generated by datamodel-codegen:
#   filename:  energy_constants.json
#   timestamp: 2026-09-28T01:13:22+00:00

from __future__ import annotations

from datetime import date
from enum import Enum

from pydantic import BaseModel, Field, confloat


class PeFactors(BaseModel):
    """
    1차에너지 환산계수 (무차원). 국토부고시 제2024-1026호 (2025.1.1 시행)
    """

    electricity: float | None = None
    gas: float | None = None
    district_heat: float | None = None
    district_cool: float | None = None


class Grades(BaseModel):
    max_pe_kwh: float | None = None
    min_self_sufficiency_pct: float | None = None


class Zeb(BaseModel):
    """
    ZEB 등급 기준 (녹색건축법, 2025.1.1 통합인증). min_self_sufficiency_pct=에너지자립률(%)=공식 ZEB 등급 결정 기준(Plus120/1:100/2:80/3:60/4:40/5:20, 20%p 밴드, zeb.energy.or.kr 2026-06-21 재확인). max_pe_kwh=본 시스템 EUI-proxy(baseline150×ratio, 비공식 근사). 공식 1차에너지소요량은 주거/비주거 별도표(음수 포함). 의무화 임계 1,000m²(공공 2025.1.1 / 민간 일반 2025.12.31).
    """

    baseline_kwh_m2_yr: float | None = Field(
        None, description='에너지절약설계기준 1차에너지 상한'
    )
    grades: dict[str, Grades] | None = Field(
        None, description='ZEB 등급별 상한 (kWh/m2/yr) 및 자립률'
    )


class EnergyGrades(BaseModel):
    """
    에너지효율등급 (1+++~5)
    """

    labels: list[str] | None = Field(None, description='등급 라벨 (순서: 최고→최저)')
    colors: dict[str, str] | None = Field(None, description='등급별 CSS hex 색상')


class Co2Grades(BaseModel):
    """
    CO2 배출 등급 임계값
    """

    thresholds_kgco2_m2_yr: list[int] | None = Field(
        None, description='4단계 분류 경계값'
    )


class KrBbox(BaseModel):
    lat_min: float | None = None
    lat_max: float | None = None
    lng_min: float | None = None
    lng_max: float | None = None


class Climate(BaseModel):
    """
    기후 관련 기준값
    """

    hdd_base_temp_c: float | None = None
    cdd_base_temp_c: float | None = None
    kr_bbox: KrBbox | None = None


class Simulation(BaseModel):
    """
    시뮬레이션 공통 파라미터. ENERGY_SSOT.md §6.
    """

    cooling_setpoint_c: float | None = None
    heating_setpoint_c: float | None = None
    chiller_cop: float | None = None
    boiler_efficiency: float | None = None
    energyplus_version: str | None = None
    pv_efficiency_pct: float | None = None
    pv_performance_ratio: float | None = None
    rooftop_utilization: float | None = None


class Scope(Enum):
    """
    national=국가 전체 순배출 / building=건물부문.
    """

    national = 'national'
    building = 'building'


class Targets(BaseModel):
    scope: Scope = Field(
        ..., description='national=국가 전체 순배출 / building=건물부문.'
    )
    base_year: int
    target_year: int
    label_ko: str = Field(..., description='사람 대면 표기(출처 칸에 그대로 쓴다).')
    reduction_rate: confloat(ge=0.0, le=1.0) | None = Field(
        None,
        description='기준연도 대비 감축률(0~1, 양수=감축). 범위 목표면 비우고 min/max 를 쓴다.',
    )
    reduction_rate_min: confloat(ge=0.0, le=1.0) | None = None
    reduction_rate_max: confloat(ge=0.0, le=1.0) | None = None
    base_emissions_mtco2eq: float | None = Field(
        None, description='기준연도 배출량(백만 tCO2eq). 발표에 있을 때만.'
    )
    target_emissions_mtco2eq: float | None = Field(
        None, description='목표연도 배출량(백만 tCO2eq). 발표에 있을 때만.'
    )
    status: str | None = Field(None, description='확정 단계(예: 국무회의 확정).')
    data_source: str = Field(
        ..., description='data_classification.json#DataSource — 공식 발표 = external.'
    )
    source_title: str
    source_url: str
    source_date: date = Field(..., description='발표·확정일.')
    retrieved: date | None = Field(None, description='EC 등재 시 원문 확인일.')
    note: str | None = None


class NdcTargets(BaseModel):
    """
    국가 온실가스 감축목표(NDC) — 국가 전체와 부문별을 **다른 키**로 둔다(2026-09-28 추가). 국가 전체 −40% 는 국가 전체 맥락에서만, 건물 한 동·건물군·시군구 건물 배출의 목표는 건물부문 값을 쓴다. 두 값을 섞지 않는다. 값은 외부 공식 발표(data_source=external)이며 출처·발표일을 항목마다 싣는다.
    """

    default_target: str = Field(
        ...,
        description='건물 배출 맥락의 기본 목표 키(targets 의 키). 국가 전체 질문은 national_2030 을 명시해 고른다.',
    )
    targets: dict[str, Targets]


class EnergyConstants(BaseModel):
    """
    에너지 기준값·등급·환산계수 SSOT. ENERGY_SSOT.md §2~§3 기반.
    """

    pe_factors: PeFactors | None = Field(
        None,
        description='1차에너지 환산계수 (무차원). 국토부고시 제2024-1026호 (2025.1.1 시행)',
    )
    zeb: Zeb | None = Field(
        None,
        description='ZEB 등급 기준 (녹색건축법, 2025.1.1 통합인증). min_self_sufficiency_pct=에너지자립률(%)=공식 ZEB 등급 결정 기준(Plus120/1:100/2:80/3:60/4:40/5:20, 20%p 밴드, zeb.energy.or.kr 2026-06-21 재확인). max_pe_kwh=본 시스템 EUI-proxy(baseline150×ratio, 비공식 근사). 공식 1차에너지소요량은 주거/비주거 별도표(음수 포함). 의무화 임계 1,000m²(공공 2025.1.1 / 민간 일반 2025.12.31).',
    )
    energy_grades: EnergyGrades | None = Field(
        None, description='에너지효율등급 (1+++~5)'
    )
    co2_grades: Co2Grades | None = Field(None, description='CO2 배출 등급 임계값')
    climate: Climate | None = Field(None, description='기후 관련 기준값')
    simulation: Simulation | None = Field(
        None, description='시뮬레이션 공통 파라미터. ENERGY_SSOT.md §6.'
    )
    ndc_targets: NdcTargets | None = Field(
        None,
        description='국가 온실가스 감축목표(NDC) — 국가 전체와 부문별을 **다른 키**로 둔다(2026-09-28 추가). 국가 전체 −40% 는 국가 전체 맥락에서만, 건물 한 동·건물군·시군구 건물 배출의 목표는 건물부문 값을 쓴다. 두 값을 섞지 않는다. 값은 외부 공식 발표(data_source=external)이며 출처·발표일을 항목마다 싣는다.',
    )
