# generated by datamodel-codegen:
#   filename:  energyplus_run_manifest.json
#   timestamp: 2026-09-16T09:18:36+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    PositiveFloat,
    RootModel,
    confloat,
    conint,
    constr,
)


class Code(Enum):
    H_A = 'H_A'
    H_B = 'H_B'
    H_C = 'H_C'
    H_D = 'H_D'
    H_E = 'H_E'
    H_F = 'H_F'
    H_G = 'H_G'


class HvacHypothesis(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Code
    label: constr(min_length=1)
    is_observed: Literal[False]


class Period(Enum):
    annual = 'annual'
    design_week = 'design_week'
    custom = 'custom'


class Runs(BaseModel):
    pass


class Sha256(RootModel[constr(pattern=r'^sha256:[a-f0-9]{64}$')]):
    root: constr(pattern=r'^sha256:[a-f0-9]{64}$')


class ComfortExtremum(BaseModel):
    """
    극값이 실제로 발생한 지점. 어느 존이 극값을 몰았는지 알아야 그 이탈이 비공조 존 때문인지(not_applicable) 실제 결과인지(missing) 갈린다. clo·met 은 생산자가 쓴 값을 그대로 싣는다 — 소비처가 생산자 코드의 계절 규칙을 옮겨 적으면 그 규칙이 바뀔 때 조용히 어긋난다.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    zone: constr(min_length=1)
    hour_index: conint(ge=0)
    ta_c: float
    tr_c: float
    rh_pct: confloat(ge=0.0, le=100.0)
    clo: PositiveFloat | None = Field(
        None, description='이 극값 시점에 실제로 쓴 착의량. 계절로 갈린다.'
    )
    met: PositiveFloat | None = Field(
        None,
        description='이 극값 시점에 실제로 쓴 대사량. 주거 원형과 비주거가 다르다.',
    )
    air_velocity_m_s: confloat(ge=0.0) | None = None


class CoolingSetpointC(Enum):
    number_24 = 24
    number_25 = 25
    number_26 = 26


class Role(Enum):
    baseline = 'baseline'
    counterfactual = 'counterfactual'


class AnnualEnergyKwh(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    electricity: confloat(ge=0.0)
    natural_gas: confloat(ge=0.0)
    district_heating: confloat(ge=0.0)
    district_cooling: confloat(ge=0.0)
    facility_total: confloat(ge=0.0)


class Comfort(BaseModel):
    """
    PMV 는 계산 규칙에 따라 달라지므로 값만으로는 재현되지 않는다. 아래 선택 항목은 그 계산이 어느 존 집합에 무슨 코드로 적용됐는지를 값과 함께 싣는다. 옛 번들에는 없으므로 required 에 넣지 않는다.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    method: constr(min_length=1)
    warm_limit: confloat(ge=0.0)
    cold_limit: confloat(le=0.0)
    pmv_warmest: float
    pmv_coldest: float
    zone_selection: constr(min_length=1) | None = Field(
        None, description='존을 고른 규칙. 예: idf_zonehvac_equipmentconnections'
    )
    conditioned_zone_count: conint(ge=0) | None = None
    reported_zone_count: conint(ge=0) | None = None
    occupied_zone_hours: confloat(ge=0.0) | None = None
    postprocess_code_sha256: Sha256 | None = Field(
        None,
        description='후처리 코드의 해시. 입력 해시가 같아도 계산 규칙이 바뀌면 PMV 가 달라지므로 이것이 없으면 그 변경이 드러나지 않는다.',
    )
    warmest_at: ComfortExtremum | None = None
    coldest_at: ComfortExtremum | None = None
    zones_used: list[constr(min_length=1)] | None = None
    zones_excluded: list[constr(min_length=1)] | None = None
    start_dow_used: conint(ge=0, le=6) | None = Field(
        None,
        description='재실 마스크가 실제로 쓴 주 시작 요일. 0=월 .. 6=일. 요일은 재실 창에만 쓰이고 에너지에는 쓰이지 않으므로 comfort 의 인자다. 2026-09-16: 후처리가 0(월)을 가정했으나 RunPeriod 는 화요일이어서 마스크가 하루 밀렸고, 63 run 중 50 run 의 PMV 가 움직였다(에너지·period_hours 는 0). 값을 좌우하는 인자가 계보에 없으면 그 차이를 사후에 설명할 수 없다.',
    )
    start_dow_source: constr(min_length=1) | None = Field(
        None,
        description='그 요일을 읽은 곳. 예: eplusout.eio:Environment,WeatherFileRunPeriod. ⚠ 이것은 선언이다 — 생산자가 실제로 그 자리에서 읽었는지를 이 필드가 증명하지는 않는다. 출처가 하나뿐인 동안은 무해하나, 둘 이상이 되면 측정으로 바꿔야 한다.',
    )


class Run(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    run_id: constr(min_length=1)
    cooling_setpoint_c: CoolingSetpointC
    role: Role
    status: Literal['verified']
    energyplus_version: constr(min_length=1)
    input_idf_sha256: Sha256
    result_sha256: Sha256
    severe_count: Literal[0]
    eio_sha256: Sha256 | None = Field(
        None,
        description='이 run 의 eplusout.eio 해시. start_dow_used 가 여기서 나오므로, 요일이 결과를 좌우하는 입력이 된 이상 그 출처 파일도 input_idf_sha256·result_sha256 과 같은 층에서 계보에 묶여야 한다. 옛 번들에는 없으므로 required 가 아니다.',
    )
    period_hours: conint(ge=1) | None = Field(
        None,
        description='결과 창의 실제 길이(시간). period 는 선언이고 이것은 측정이다 — 설계일이 앞에 붙은 CSV 를 전 행 합산하면 총계가 부풀지만 성분 합=총계가 유지돼 정합성 검사도 단조성도 통과한다(2026-09-16 B02 3셀, 0.60~0.82% 오염). 남는 유일한 구분점이 창 길이다. 옛 번들에는 없으므로 required 가 아니다.',
    )
    annual_energy_kwh: AnnualEnergyKwh
    comfort: Comfort = Field(
        ...,
        description='PMV 는 계산 규칙에 따라 달라지므로 값만으로는 재현되지 않는다. 아래 선택 항목은 그 계산이 어느 존 집합에 무슨 코드로 적용됐는지를 값과 함께 싣는다. 옛 번들에는 없으므로 required 에 넣지 않는다.',
    )


class BuildingArchetype(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: constr(pattern=r'^B(0[1-9]|1[0-7])$')
    name: constr(min_length=1)
    source_idf_sha256: Sha256


class Weather(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    city: constr(min_length=1)
    epw_sha256: Sha256


class EnergyPlusRunManifest(BaseModel):
    """
    표준 HVAC 가설 하나의 불변 EnergyPlus 설정온도 실행 묶음. 실측·현장 적용·M&V 증거가 아니다.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0']
    manifest_id: constr(pattern=r'^eplus-grid-[a-z0-9_-]+$')
    created_at: AwareDatetime
    producer: constr(min_length=1)
    evidence_state: Literal['energyplus_cross_check']
    building_archetype: BuildingArchetype
    hvac_hypothesis: HvacHypothesis
    weather: Weather
    period: Period
    runs: list[Run] | Runs = Field(..., max_length=3, min_length=3)
