# generated by datamodel-codegen:
#   filename:  tmp9j9w6ki7.json
#   timestamp: 2026-06-30T02:32:09+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    Field,
    RootModel,
    confloat,
    conint,
    constr,
)


class SelectedTech(RootModel[constr(pattern=r'^[a-z][a-z0-9_-]{1,63}$')]):
    root: constr(pattern=r'^[a-z][a-z0-9_-]{1,63}$') = Field(
        ...,
        description='bundle_manifest.tech_list[].id 와 동일 패턴 (R8-5-a VW/GB Minor).',
    )


class DryRunResult(BaseModel):
    """
    Dry-run (4단계) 결과. seal 전 반드시 passed=true 여야 함.
    """

    passed: bool
    tested_techs: list[str] | None = Field(
        None, description='실제로 프리뷰·시뮬을 돌린 기술 ID 목록.'
    )
    warnings: list[str] | None = None
    elapsed_sec: confloat(ge=0.0) | None = Field(
        None, description='Dry-run 총 소요 시간.'
    )


class BuildingType(Enum):
    """
    common.json §BuildingType SSOT.
    """

    office_large = 'office_large'
    office_medium = 'office_medium'
    office_small = 'office_small'
    hospital = 'hospital'
    school = 'school'
    retail = 'retail'
    convenience_store = 'convenience_store'
    apartment = 'apartment'
    other = 'other'


class Kind(Enum):
    telemetry = 'telemetry'
    dispatch = 'dispatch'


class Backend(Enum):
    replay = 'replay'
    energyplus = 'energyplus'
    real_bas = 'real_bas'
    virtual = 'virtual'


class Protocol(Enum):
    """
    설비 통신 방법 (backend 와 다름 — RFC R6-6 용어 통일).
    """

    replay = 'replay'
    energyplus = 'energyplus'
    modbus = 'modbus'
    bacnet = 'bacnet'
    matter = 'matter'
    virtual = 'virtual'


class Replay(BaseModel):
    """
    backend=replay 시 필수. R6-3 옵션 a 로 GB 가 CSV 경로·URL 전달 가능.
    """

    csv: str | None = Field(None, description='로컬 CSV 경로 또는 GB 서빙 URL')
    csv_url: AnyUrl | None = Field(
        None, description='GB 가 HTTP 로 서빙하는 CSV. Edge 가 다운로드 후 로컬 캐시.'
    )
    col_ts: str | None = None
    col_power_w: str | None = None
    year_shift_to: int | None = None
    speed: float | None = None


class Energyplus(BaseModel):
    idf: str | None = None
    epw: str | None = None
    step_seconds: conint(ge=60) | None = None
    rt_factor: float | None = None


class Modbus(BaseModel):
    host: str | None = None
    port: int | None = None
    slave_id: int | None = None


class Bacnet(BaseModel):
    ip: str | None = None
    device_id: int | None = None
    object_list: list[Any] | None = None


class Connection(BaseModel):
    """
    연결 설정. protocol·data_points·interval + backend별 상세 (replay/energyplus/modbus/bacnet).
    """

    protocol: Protocol = Field(
        ..., description='설비 통신 방법 (backend 와 다름 — RFC R6-6 용어 통일).'
    )
    data_points: list[str] | None = None
    interval_sec: conint(ge=1) | None = None
    replay: Replay | None = Field(
        None,
        description='backend=replay 시 필수. R6-3 옵션 a 로 GB 가 CSV 경로·URL 전달 가능.',
    )
    energyplus: Energyplus | None = None
    modbus: Modbus | None = None
    bacnet: Bacnet | None = None


class Interlocks(BaseModel):
    """
    안전 인터록 오버라이드. 지정 안 하면 Edge 기본값 사용.
    """

    max_indoor_temp_c: float | None = None
    min_indoor_temp_c: float | None = None
    min_ess_soc_pct: float | None = None
    min_lighting_pct: float | None = None


class Config(BaseModel):
    """
    Edge 설정 본문. edge-agent/templates/ 의 YAML 구조와 동일.
    """

    schema_version: str | None = Field(
        None, description="energy-contracts 버전. 예: '1.2'."
    )
    ven_id: str
    building_name: str | None = None
    pnu: str | None = None
    building_type: BuildingType | None = Field(
        None, description='common.json §BuildingType SSOT.'
    )
    group_id: str | None = None
    kind: Kind
    backend: Backend
    baseline_kw: confloat(ge=0.0) | None = None
    max_reduction_kw: confloat(ge=0.0) | None = None
    envelope: dict[str, Any] | None = Field(
        None, description='building_envelope.json v1.0 구조. 전체 스키마 참조.'
    )
    connection: Connection | None = Field(
        None,
        description='연결 설정. protocol·data_points·interval + backend별 상세 (replay/energyplus/modbus/bacnet).',
    )
    interlocks: Interlocks | None = Field(
        None, description='안전 인터록 오버라이드. 지정 안 하면 Edge 기본값 사용.'
    )


class EngineeringSession(BaseModel):
    """
    Edge 현장 기사가 건물 엔지니어링 (설치·시운전·수정) 을 한 번 수행한 세션 기록. Edge 가 설치 마법사 완료 (seal) 시점에 로컬 `engineering/sessions/{session_id}.yaml` 에 저장하고, `fleet/engineering/{ven_id}` (retain=True) 로 최신 세션을 GB 에 복제. 재방문 시 기사가 previous_session_id 체인으로 타임라인을 조회. R8-5 (2026-04-20).
    """

    session_id: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    ) = Field(..., description='세션 고유 ID (UUIDv4). Edge 로컬 파일명과 일치.')
    ven_id: constr(
        pattern=r'^VEN-(STORE|EP|REAL|TEST|E2E|SHOP)-[A-Z0-9][A-Z0-9\-]*$'
    ) = Field(..., description='대상 VEN. common.json §VenId SSOT.')
    technician_id: constr(max_length=64) | None = Field(
        None, description='기사 식별자 (본사 발급). 익명 해시 허용.'
    )
    started_at: AwareDatetime = Field(
        ..., description='세션 시작 시각 (기사 도착·접속). ISO 8601 + timezone.'
    )
    sealed_at: AwareDatetime = Field(
        ...,
        description='seal 시점 — 설치 마법사 5단계 완료. commissioning_hash 생성 시각.',
    )
    bundle_version: constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$') = Field(
        ...,
        description='이 세션에서 사용한 22기술 번들 버전. bundle_manifest.json 의 version 과 일치. 예: `1.3.0`.',
    )
    selected_techs: list[SelectedTech] | None = Field(
        None,
        description='이 건물에 적용 가능하다고 기사가 체크한 22기술 ID 목록 (bundle_manifest.tech_list[].id 참조). 설치 이후 Monitoring Skills 탭 하이라이트 대상.',
    )
    provisioning_config: Config | None = Field(
        None,
        description='이 세션에서 확정된 Edge 설정. provision.json#/properties/config 와 동일 형식. Edge 로컬 `provisioned/{ven_id}.yaml` 과 일치해야 함.',
    )
    dry_run_result: DryRunResult | None = Field(
        None, description='Dry-run (4단계) 결과. seal 전 반드시 passed=true 여야 함.'
    )
    commissioning_hash: constr(pattern=r'^sha256:[a-f0-9]{64}$') = Field(
        ...,
        description="seal 무결성 봉인 해시. 알고리즘 SSOT 는 `protocols/commissioning-hash.md` (ARCH-R8-1, 2026-04-20). 요약: 입력 = {selected_techs(정렬), provisioning_config, bundle_version, technician_id or ''} → JSON canonical (sort_keys=True, separators=(',',':'), ensure_ascii=False, UTF-8 인코딩) → SHA-256 → `sha256:` 접두. VW/GB/Edge 구현은 반드시 동일 바이트를 입력해야 재현 가능.",
    )
    previous_session_id: (
        constr(
            pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
        )
        | None
    ) = Field(
        None,
        description='직전 세션 UUID (재방문·수정 시). 초기 설치면 null. engineering_diff.json 로 변경 내역 기록.',
    )
    notes: constr(max_length=2048) | None = Field(
        None, description='기사 자유 기입 메모 (현장 특이사항·설비 교체 이력 등).'
    )
