# generated by datamodel-codegen:
#   filename:  equipment_taxonomy.json
#   timestamp: 2026-09-11T10:06:28+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, constr


class EquipmentKind(Enum):
    """
    설비 종류. hvac=통합 공조(존 온도) · ahu=공기조화기 · vav=가변풍량 · chiller=냉동기 · boiler=보일러(난방) · fan=팬(환기) · pump=펌프 · lighting=조명(구 console 'light') · ess=에너지저장 · pv=태양광 · plug=플러그부하 · meter=계량기(read-only) · other=기타.

    **v1.2 확장(2026-08-03)** — E+ IDF 42본 전수 파싱 근거로 7종 신설. 추가 기준은 이름이 아니라 **표준 점 집합이 달라지거나 제어 의미가 달라질 때**만이다: radiant=온돌·복사난방(공급수온 제어 + 지연응답 → 설정온도 즉시 반영 가정이 깨진다) · vrf=VRF/EHP 실외기(실외기 1:실내기 N 계층의 계량·제어 단위. 실내기는 hvac+subtype) · district_heat=지역난방 인수(생산이 아니라 **구매** — 회계축이 다르다) · dhw=급탕(별도 용도 + 레지오넬라 온도 하한) · refrigeration=냉장·냉동(**식품안전 제약으로 DR 제외 대상** — hvac 로 뭉치면 잘못 감축한다) · cooling_tower=냉각탑(접근온도·팬 단수) · erv=전열교환기(EMS M08 의 지목 대상). 출현 근거: radiant 8 · vrf 9 · district_heat 6 · dhw 21(최다) · refrigeration 17 · cooling_tower 3 · erv 6 본.
    """

    hvac = 'hvac'
    ahu = 'ahu'
    vav = 'vav'
    chiller = 'chiller'
    boiler = 'boiler'
    fan = 'fan'
    pump = 'pump'
    lighting = 'lighting'
    ess = 'ess'
    pv = 'pv'
    plug = 'plug'
    meter = 'meter'
    radiant = 'radiant'
    vrf = 'vrf'
    district_heat = 'district_heat'
    dhw = 'dhw'
    refrigeration = 'refrigeration'
    cooling_tower = 'cooling_tower'
    erv = 'erv'
    other = 'other'


class DeviceAction(Enum):
    """
    물리 동작 verb. driver.apply_device_action() 에 1:1 매핑(edge onsite authoritative). on/off/stop/discharge/emergency_* = value 없음 · set_temp/dim/set_speed = 수치 value(value_specs 참조).
    """

    on = 'on'
    off = 'off'
    set_temp = 'set_temp'
    dim = 'dim'
    discharge = 'discharge'
    stop = 'stop'
    set_speed = 'set_speed'
    emergency_off = 'emergency_off'
    emergency_on = 'emergency_on'


class ValueType(Enum):
    """
    허용 value 타입. bool 은 항상 거부(True/False 가 1/0 통과 함정 차단). value_required=false 면 omit.
    """

    number = 'number'


class ValueSpec(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value_required: bool = Field(
        ..., description='value 필수 여부. false 면 on/off 처럼 인자 없음.'
    )
    value_type: ValueType | None = Field(
        None,
        description='허용 value 타입. bool 은 항상 거부(True/False 가 1/0 통과 함정 차단). value_required=false 면 omit.',
    )
    min: float | None = Field(
        None, description='허용 최소값(포함). value_required=true 일 때만.'
    )
    max: float | None = Field(None, description='허용 최대값(포함).')
    unit: str | None = Field(None, description='표시 단위(°C, %). UI 라벨용.')


class PointRole(Enum):
    """
    점의 역할. Project Haystack 의 sensor/sp/cmd 3분 그대로다 — sensor=읽는 값 · sp=목표값(setpoint) · cmd=내리는 명령.
    **왜 표준을 따르나**: 이 3분이 '읽기만 하는 점'과 '쓰면 설비가 움직이는 점'을 가른다. 자체 어휘를 만들면 권한·감사 정책이 소비단마다 갈린다.
    """

    sensor = 'sensor'
    sp = 'sp'
    cmd = 'cmd'


class EquipmentPoint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mnemonic: constr(pattern=r'^[A-Z][A-Z0-9_]*$') = Field(
        ...,
        description='CPA 의 {point} 세그먼트와 **같은 어휘**(bems-console MNEMONICS 정본). 여기서 새 니모닉을 발명하지 않는다 — 주소 어휘가 둘로 갈린다.',
    )
    role: PointRole
    required: bool | None = Field(
        False,
        description="표준이 이 설비에 **기대하는** 점인가. 없다고 계약 위반은 아니다 — 현장마다 계측 범위가 다르다. 없으면 '미계측'으로 표시할 근거가 된다.",
    )
    unit: str | None = None
    brick: constr(pattern=r'^brick:[A-Za-z0-9_]+$') | None = Field(
        None, description='Brick Schema 클래스(있는 경우). 외부 온톨로지 연결점.'
    )
    haystack: str | None = Field(
        None, description='Project Haystack 태그 조합(있는 경우).'
    )
    field_comment: str | None = Field(None, alias='$comment')


class EnergySource(Enum):
    """
    에너지원. 한국 BEMS 제도가 요구하는 **에너지원 × 용도 교차 계량**의 한 축이다(구 「건축물의 에너지절약설계기준」 별표 12 #3 — 생산·저장·사용 에너지를 전기/연료/열로). ⚠ 이 축은 Brick·Haystack·IFC **어디에도 없다** — 국제 표준의 결함이 아니라 관할권 요구다.
    """

    electricity = 'electricity'
    fuel = 'fuel'
    heat = 'heat'
    renewable = 'renewable'


class EndUse(Enum):
    """
    용도. 한국 제도의 **5대 용도**(냉방·난방·급탕·조명·환기) + other. ⚠ 「동력」은 5대 용도에 **없다**(초판 오류 정정). 펌프·냉장·플러그는 other 다. 신재생은 용도가 아니라 **에너지원/생산 축**이다.
    """

    cooling = 'cooling'
    heating = 'heating'
    dhw = 'dhw'
    lighting = 'lighting'
    ventilation = 'ventilation'
    other = 'other'


class SimulationBacked(Enum):
    """
    이 설비의 성과를 **시뮬로 대조할 수 있나**. full=설비 단위 시뮬 근거 있음 · meter_only=용도별 계량으로만(설비 단위 절감을 말하지 않는다) · **unreported=모델은 도는데 출력이 회수되지 않음** · none=시뮬 근거 없음.
    ⚠ `unreported` 를 `none` 과 나눈 이유: 둘 다 '지금 못 쓴다' 지만 **해야 할 일이 완전히 다르다**. none(ESS)은 모델을 새로 만들어야 하고, unreported(PV)는 출력 미터 2줄을 추가해 재실행하면 된다. 같은 칸에 넣으면 저렴한 복구가 비싼 신규 개발 뒤에 줄을 선다.
    ⚠ 캠페인마다 값이 다르므로 **캠페인별로** 적는다 — 하나의 스칼라로 뭉개면 한국 건물 화면에 미국 근거가 붙는다.
    """

    full = 'full'
    meter_only = 'meter_only'
    unreported = 'unreported'
    none = 'none'


class EnergyEndUse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    energy_source: EnergySource | None = None
    end_use: EndUse | None = None


class EquipmentTaxonomy(BaseModel):
    """
    설비 종류(EquipmentKind) · 물리 동작(DeviceAction) · 종류→가능동작 capability 매트릭스 · 동작별 value 스펙 SSOT. 수용가(VEN) 마스터 데이터 모델의 설비 축을 정본화한다. 그 전엔 edge-agent(device_catalog.VALID_KINDS/value_spec._SPEC)·bems-console(EquipmentKind/OutputKind)·scope.py(Literal) 3벌이 서로 다른 vocabulary 로 조용히 드리프트했다(edge {hvac,lighting,...} vs console {ahu,vav,light,...}). 본 스키마가 단일 정본 → gen_constants.py 가 EQUIPMENT_KINDS/DEVICE_ACTIONS/EQUIPMENT_CAPABILITIES/DEVICE_ACTION_VALUE_SPEC 로 파생.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    capability_matrix: dict[
        constr(
            pattern=r'^(hvac|ahu|vav|chiller|boiler|fan|pump|lighting|ess|pv|plug|meter|radiant|vrf|district_heat|dhw|refrigeration|cooling_tower|erv|other)$'
        ),
        list[DeviceAction],
    ] = Field(
        ...,
        description='EquipmentKind → 지원 DeviceAction 목록. 이 표에 없는 (kind, action) 조합은 저작/실행 단계에서 거부(예: lighting 에 set_temp 금지). meter=[](read-only).',
    )
    value_specs: dict[
        constr(
            pattern=r'^(on|off|set_temp|dim|discharge|stop|set_speed|emergency_off|emergency_on)$'
        ),
        ValueSpec,
    ] = Field(
        ...,
        description='DeviceAction → ValueSpec. edge value_spec._SPEC 범위 정본(무 behavior 변경).',
    )
    point_sets: dict[str, list[EquipmentPoint]] | None = Field(
        None,
        description="설비 종류 → 표준 관제점 집합. **왜 필요한가**: EquipmentKind 는 '무엇인가'만 말하고, 그 설비에 **어떤 점이 있어야 하는가**는 아무 데도 없었다. 그래서 소비단마다 점 목록을 손으로 적었다.\n용도: ① 커버리지 판정('AHU 인데 급기온도가 없다') ② 자동 점 생성 뼈대 ③ 외부 온톨로지(Brick/Haystack) 연결.\n⚠ 이 목록은 **기대치이지 강제가 아니다**. 현장마다 계측 범위가 다르므로 빠진 점은 '위반'이 아니라 '미계측'이다 — 없는 것을 있다고 하지 않기 위한 근거다.",
    )
    subtypes: dict[str, list[str]] | None = Field(
        None,
        description="설비 종류 → **권장 하위형** 목록. 종류를 늘리지 않고 실체를 남기는 축이다.\n⚠ `subtype` 은 **표시·분류용이고 제어 계약이 아니다**. 그래서 값집합을 열어 두되 권장 목록을 여기 실어 소비단이 같은 말을 쓰게 한다 — 안 그러면 현장마다 '벽걸이'·'PTAC'·'패키지' 가 따로 논다.",
    )
    simulation_backed: dict[str, dict[str, SimulationBacked]] | None = Field(
        None,
        description="설비 종류 → 캠페인별 시뮬 근거 표기. 화면·리포트에서 '시뮬 대비 절감' 을 말할 수 있는 범위를 **계약이 정한다**.",
    )
    energy_end_use: dict[str, EnergyEndUse] | None = Field(
        None,
        description='설비 종류 → (에너지원, 용도). 한국 BEMS 제도의 교차 계량 축이며 국제 표준엔 없다. ⚠ boiler 가 급탕을 겸하면 **분리 계량이 필수**다 — 난방과 급탕은 제도상 다른 용도다.',
    )
