# generated by datamodel-codegen:
#   filename:  error_response.json
#   timestamp: 2026-06-30T02:32:11+00:00

from __future__ import annotations

from typing import Any

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, conint, constr


class ErrorResponseSsotPhaseI3(BaseModel):
    """
    RFC 7807 application/problem+json 호환 통일 에러 응답. 6 프로젝트 FastAPI exception handler 가 공통 ProblemResponse 모델로 응답.
    """

    type_prefix: str | None = None
    codes: dict[str, Any] | None = None


class Problem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: AnyUrl
    title: str
    status: conint(ge=400, le=599)
    detail: str | None = None
    instance: str | None = None
    code: constr(pattern=r'^[A-Z][A-Z0-9_]+$') = Field(
        ..., description='안정적 식별자 (UPPER_SNAKE)'
    )
    trace_id: str | None = None
    errors: list[dict[str, Any]] | None = Field(
        None, description='validation 다중 필드 에러용'
    )
