# generated by datamodel-codegen:
#   filename:  error_response.json
#   timestamp: 2026-09-30T12:59:56+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel, conint, constr


class ErrorResponseSsotPhaseI3(BaseModel):
    """
    RFC 7807 application/problem+json 호환 통일 에러 응답. 6 프로젝트 FastAPI exception handler 가 공통 ProblemResponse 모델로 응답.
    """

    type_prefix: str | None = None
    codes: dict[str, Any] | None = None


class Kind(Enum):
    """
    거절 갈래 — question=질문이 정해야 할 것이 빠졌거나 모호(되묻기) · data=자료가 없거나 덮지 못함 · permission=권한·배정 밖 · internal=우리 결함. 거절 사전의 갈래(질문·자료·권한·내부)와 같다. 자료/질문/결함을 가르지 않으면 고칠 곳을 못 찾는다.
    """

    question = 'question'
    data = 'data'
    permission = 'permission'
    internal = 'internal'


class Retry(Enum):
    """
    ask=사용자에게 되묻는다 · fill=서버가 채울 수 있다(가상·추정 채움 + 출처 표시, 또는 자료 적재 뒤) · none=같은 요청을 다시 보내도 같은 답 · later=일시 장애(시간 초과·과부하·외부 서비스 일시 중단) — 잠시 뒤 같은 요청을 다시 보내면 답이 달라질 수 있다
    """

    ask = 'ask'
    fill = 'fill'
    none = 'none'
    later = 'later'


class Refusal(BaseModel):
    """
    거절 봉투(1.1 M3 — INTERFACES §4.2④). 도구·결속기·게이트웨이가 거절을 싣는 모양 6가지(code · 예외 문장 · error 문자열 · 중첩 error/detail/refusal · refusal_code · status+reason)를 이 하나로 모은다. 코드는 뜻 단위로 짓고 어느 칸인지는 field 로 싣는다(칸마다 '<칸>_REQUIRED' 새 이름을 만들지 않는다). 옛 코드(거절 사전 1,370개)는 legacy_code 로 이어 응답 바이트 해석을 깨지 않는다. airo-result/v1 의 refusal 칸과 Problem 의 확장 칸이 이 정의를 가리킨다.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    code: constr(pattern=r'^[A-Z][A-Z0-9_]+$') = Field(
        ...,
        description='뜻 단위 거절 코드(UPPER_SNAKE) — 예 INPUT_REQUIRED · TARGET_KIND_UNSUPPORTED · PERIOD_NOT_COVERED · PLACE_AMBIGUOUS',
    )
    kind: Kind = Field(
        ...,
        description='거절 갈래 — question=질문이 정해야 할 것이 빠졌거나 모호(되묻기) · data=자료가 없거나 덮지 못함 · permission=권한·배정 밖 · internal=우리 결함. 거절 사전의 갈래(질문·자료·권한·내부)와 같다. 자료/질문/결함을 가르지 않으면 고칠 곳을 못 찾는다.',
    )
    field: constr(max_length=200) | None = Field(
        None,
        description='무엇이 문제인 칸(예 target · period · params.top_share · place). 뜻은 code, 칸은 field',
    )
    expected: Any | None = Field(
        None, description='그 칸이 받아야 했던 것(값·모양·종류 목록). 형식 자유'
    )
    got: Any | None = Field(
        None,
        description='실제로 받은 것(비식별 값만 — 좌표·주소·원천 코드 금지). 형식 자유',
    )
    message_ko: constr(min_length=1, max_length=1000) = Field(
        ..., description='사람이 읽는 거절 사유(한국어). 원인을 가리지 않는다'
    )
    next_ko: constr(max_length=1000) | None = Field(
        None, description="사용자가 다음에 할 일(예 '지역을 하나 골라 주세요')"
    )
    retry: Retry = Field(
        ...,
        description='ask=사용자에게 되묻는다 · fill=서버가 채울 수 있다(가상·추정 채움 + 출처 표시, 또는 자료 적재 뒤) · none=같은 요청을 다시 보내도 같은 답 · later=일시 장애(시간 초과·과부하·외부 서비스 일시 중단) — 잠시 뒤 같은 요청을 다시 보내면 답이 달라질 수 있다',
    )
    legacy_code: constr(pattern=r'^[A-Z][A-Z0-9_]+$') | None = Field(
        None,
        description='옛 거절 코드(게이트웨이 refusal_dictionary). 별칭표로 뜻 단위 code 에 잇는다 — 판정 원장이 읽는 옛 이름을 끊지 않는다',
    )


class Expected(RootModel[Any]):
    root: Any = Field(
        ..., description='그 칸이 받아야 했던 것(값·모양·종류 목록). 형식 자유'
    )


class FieldModel(RootModel[constr(max_length=200) | None]):
    root: constr(max_length=200) | None = Field(
        ...,
        description='무엇이 문제인 칸(예 target · period · params.top_share · place). 뜻은 code, 칸은 field',
    )


class Got(RootModel[Any]):
    root: Any = Field(
        ...,
        description='실제로 받은 것(비식별 값만 — 좌표·주소·원천 코드 금지). 형식 자유',
    )


class LegacyCode(RootModel[constr(pattern=r'^[A-Z][A-Z0-9_]+$') | None]):
    root: constr(pattern=r'^[A-Z][A-Z0-9_]+$') | None = Field(
        ...,
        description='옛 거절 코드(게이트웨이 refusal_dictionary). 별칭표로 뜻 단위 code 에 잇는다 — 판정 원장이 읽는 옛 이름을 끊지 않는다',
    )


class MessageKo(RootModel[constr(min_length=1, max_length=1000)]):
    root: constr(min_length=1, max_length=1000) = Field(
        ..., description='사람이 읽는 거절 사유(한국어). 원인을 가리지 않는다'
    )


class NextKo(RootModel[constr(max_length=1000) | None]):
    root: constr(max_length=1000) | None = Field(
        ..., description="사용자가 다음에 할 일(예 '지역을 하나 골라 주세요')"
    )


class Problem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: AnyUrl
    title: str
    status: conint(ge=400, le=599)
    detail: str | None = None
    instance: str | None = None
    code: constr(pattern=r'^[A-Z][A-Z0-9_]+$') = Field(
        ..., description='안정적 식별자 (UPPER_SNAKE)'
    )
    trace_id: str | None = None
    errors: list[dict[str, Any]] | None = Field(
        None, description='validation 다중 필드 에러용'
    )
    kind: Kind | None = None
    field: FieldModel | None = None
    expected: Expected | None = None
    got: Got | None = None
    message_ko: MessageKo | None = None
    next_ko: NextKo | None = None
    retry: Retry | None = None
    legacy_code: LegacyCode | None = None
