# generated by datamodel-codegen:
#   filename:  esg_policy.json
#   timestamp: 2026-06-30T02:32:15+00:00

from __future__ import annotations

from enum import Enum

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    confloat,
    conint,
    constr,
)


class DRType(Enum):
    """
    DR 참여 유형. none=불참, reliability=신뢰성 DR만, economic=경제성 DR만, both=둘다.
    """

    none = 'none'
    reliability = 'reliability'
    economic = 'economic'
    both = 'both'


class ManagementMode(Enum):
    """
    그룹 내 멤버 관리 모드. unified=ESG가 목표 받아 멤버 분배, individual=멤버 각자 ReductionSlot 수신.
    """

    unified = 'unified'
    individual = 'individual'


class BidStrategy(Enum):
    """
    경제성 DR 입찰 정책. conservative=SMP-20% (낙찰 우선), balanced=SMP-10%, aggressive=SMP-5% (수익 우선).
    """

    conservative = 'conservative'
    balanced = 'balanced'
    aggressive = 'aggressive'


class DistributionAlgorithm(Enum):
    """
    부하 분배 알고리즘 카탈로그. distribution/{name}.py로 구현. Strategy pattern.
    """

    weighted_capability = 'weighted_capability'
    proportional_load = 'proportional_load'
    equal_split = 'equal_split'
    cost_optimal = 'cost_optimal'
    comfort_priority = 'comfort_priority'


class TimeSlotCurve(
    RootModel[dict[constr(pattern=r'^[0-2][0-9]-[0-2][0-9]$'), confloat(ge=0.0)]]
):
    root: dict[constr(pattern=r'^[0-2][0-9]-[0-2][0-9]$'), confloat(ge=0.0)] = Field(
        ..., description="시간대별 임계값 곡선. 키는 HH-HH 패턴 (예: '14-17')."
    )


class ComfortConstraint(BaseModel):
    """
    쾌적성 제약. 빌딩은 PMV, 가정은 setpoint deviation 적용.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    pmv_max: confloat(ge=0.0, le=3.0) | None = Field(
        None, description='PMV 절댓값 상한 (KS A ISO 7730)'
    )
    setpoint_deviation_max_c: confloat(ge=0.0) | None = Field(
        None, description='BAU 대비 setpoint 편차 상한 (°C)'
    )


class SmpThresholds(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    weekday: TimeSlotCurve
    weekend: TimeSlotCurve


class Learning(BaseModel):
    """
    입찰 학습 (P7 stub).
    """

    enabled: bool | None = None
    history_window_days: conint(ge=1) | None = None
    model: str | None = Field(
        None, description='학습 모델 식별자. stub_v1=히스토리만, linucb_v1=LinUCB 등.'
    )


class EconomicPolicy(BaseModel):
    """
    경제성 DR 정책 (풍부).
    """

    smp_thresholds: SmpThresholds
    bid_strategy: BidStrategy
    min_reduction_ratio: confloat(ge=0.0, le=1.0) | None = Field(
        None, description='그룹 평균 부하 대비 최소 감축 비율'
    )
    max_reduction_ratio: confloat(ge=0.0, le=1.0) | None = Field(
        None, description='그룹 평균 부하 대비 최대 감축 비율'
    )
    comfort_constraint: ComfortConstraint | None = None
    learning: Learning | None = Field(None, description='입찰 학습 (P7 stub).')


class ReliabilityPolicy(BaseModel):
    """
    신뢰성 DR 정책 (외부 발령 대응).
    """

    auto_accept: bool = Field(..., description='발령 자동 수락 여부')
    min_advance_minutes: conint(ge=0) | None = Field(
        None, description='최소 예고 시간 (분). 이보다 짧으면 거부.'
    )
    max_obligation_kw: confloat(ge=0.0) | None = Field(
        None, description='그룹 최대 수용 가능 감축량 (kW)'
    )
    partial_execution: bool | None = Field(
        True,
        description='능력 부족 시 최대 가능량 발행 + 부족분 보고 (true) vs 실패 보고만 (false). false 선택 시 failure_escalation_url 필수 (계통 운영자 통보).',
    )
    failure_escalation_url: AnyUrl | None = Field(
        None,
        description='partial_execution=false + mandatory 실패 시 외부 계통 운영자에 통보할 webhook URL. 신뢰성 의무 회피 방지.',
    )


class DistributionPolicy(BaseModel):
    """
    부하 분배 정책. 주 알고리즘 + fallback.
    """

    algorithm: DistributionAlgorithm
    fallback_algorithm: DistributionAlgorithm | None = Field(
        None,
        description='주 알고리즘 5% 초과 shortfall 시 호출. 같은 알고리즘 가능 (재시도).',
    )
    max_retry: conint(ge=0, le=10) | None = 3


class MemberWeight(BaseModel):
    """
    멤버별 분배 가중치. 합 = 1.0 (정규화 안 되어 있으면 자동 정규화).
    """

    weight: confloat(ge=0.0, le=1.0)
    auto_derived: bool | None = Field(
        False,
        description='true=현재 부하 비례 자동 산정 (실시간 갱신), false=수동 정의.',
    )


class EsgAggregatorPolicy(BaseModel):
    """
    ESG 그룹(Aggregator)의 DR 운영 정책 SSOT. 신뢰성/경제성 DR 분기, 분배 알고리즘 선택, 풍부 정책 (요일별 임계값 곡선·멤버 가중치·학습). Phase 4 DR 자율 에이전트 도입.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    policy_id: constr(pattern=r'^esg-policy-[a-zA-Z0-9_-]+$')
    group_id: str = Field(..., description='esg_groups.group_id 참조')
    dr_type: DRType
    management_mode: ManagementMode
    economic: EconomicPolicy | None = Field(
        None, description='dr_type ∈ {economic, both} 시 필수'
    )
    reliability: ReliabilityPolicy | None = Field(
        None, description='dr_type ∈ {reliability, both} 시 필수'
    )
    distribution: DistributionPolicy | None = None
    member_weights: dict[str, MemberWeight] | None = Field(
        None, description='키=ven_id (esg_group_venues 참조)'
    )
    version: constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$')
    updated_at: AwareDatetime | None = None
