# generated by datamodel-codegen:
#   filename:  field_evidence_event.json
#   timestamp: 2026-09-11T10:06:31+00:00

from __future__ import annotations

from enum import Enum

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    confloat,
    conint,
    constr,
)


class EventType(Enum):
    recommendation = 'recommendation'
    approval = 'approval'
    command = 'command'
    acknowledgement = 'acknowledgement'
    observation = 'observation'
    mv_result = 'mv_result'


class ActorType(Enum):
    decision_service = 'decision_service'
    operator = 'operator'
    bems = 'bems'
    edge = 'edge'
    metering = 'metering'
    mv_service = 'mv_service'


class Status(Enum):
    proposed = 'proposed'
    approved = 'approved'
    rejected = 'rejected'
    expired = 'expired'
    sent = 'sent'
    queued = 'queued'
    applied = 'applied'
    clamped = 'clamped'
    failed = 'failed'
    observed = 'observed'
    verified = 'verified'
    inconclusive = 'inconclusive'


class EvidenceRef(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class Payload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Status
    setpoint_c: confloat(ge=10.0, le=40.0) | None = None
    correlation_id: constr(min_length=1) | None = None
    baseline_method: constr(min_length=1) | None = None
    savings_kwh: float | None = None
    uncertainty_kwh: confloat(ge=0.0) | None = None
    detail: str | None = None
    evidence_refs: list[EvidenceRef]


class FieldEvidenceEvent(BaseModel):
    """
    Append-only evidence event for a building decision from recommendation through field M&V.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    event_id: constr(pattern=r'^fev_[a-zA-Z0-9_-]+$')
    action_id: constr(pattern=r'^act_[a-zA-Z0-9_-]+$')
    building_id: constr(min_length=1)
    event_type: EventType
    occurred_at: AwareDatetime
    recorded_at: AwareDatetime
    actor_type: ActorType
    payload: Payload
    previous_event_hash: (
        constr(pattern=r'^(sha256|hmac-sha256):[a-f0-9]{64}$') | None
    ) = Field(..., description='직전 이벤트 해시. 첫 이벤트는 null.')
    event_hash: constr(pattern=r'^(sha256|hmac-sha256):[a-f0-9]{64}$')
    seq: conint(ge=0) = Field(
        ...,
        description='자원별 원장 내 0-base 순번. 해시 사슬은 앞으로만 검증하므로 순번과 꼬리 앵커가 있어야 절단을 탐지할 수 있다.',
    )
