# generated by datamodel-codegen:
#   filename:  flexibility_envelope.json
#   timestamp: 2026-09-11T10:06:32+00:00

from __future__ import annotations

from enum import Enum

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    confloat,
    conint,
    constr,
)


class Source(Enum):
    """
    산출 근거. source 자체가 현장 적용 또는 M&V 완료를 뜻하지 않는다.
    """

    archetype = 'archetype'
    simulation = 'simulation'
    surrogate = 'surrogate'
    measured_validation = 'measured_validation'
    field_operation = 'field_operation'


class Availability(Enum):
    available = 'available'
    conditional = 'conditional'
    unavailable = 'unavailable'


class Interval(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    start: AwareDatetime
    baseline_kw: confloat(ge=0.0)
    downward_flex_kw: confloat(ge=0.0) = Field(
        ..., description='baseline에서 낮출 수 있는 전력 크기. 양수.'
    )
    upward_flex_kw: confloat(ge=0.0) = Field(
        ..., description='baseline에서 높일 수 있는 전력 크기. 양수.'
    )
    max_duration_minutes: conint(ge=0)
    recovery_minutes: conint(ge=0)
    rebound_energy_kwh: confloat(ge=0.0)
    availability: Availability
    constraint_refs: list[str] | None = None


class Category(Enum):
    safety = 'safety'
    comfort = 'comfort'
    production = 'production'
    contract = 'contract'
    equipment = 'equipment'
    occupant = 'occupant'
    data_quality = 'data_quality'


class Severity(Enum):
    hard = 'hard'
    soft = 'soft'


class Constraint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    constraint_id: str
    category: Category
    severity: Severity
    description: str


class EvidenceType(Enum):
    surrogate = 'surrogate'
    energyplus_cross_check = 'energyplus_cross_check'
    replay = 'replay'
    measured_validation = 'measured_validation'
    field_applied = 'field_applied'
    mv_verified = 'mv_verified'
    synthetic = 'synthetic'


class Status(Enum):
    available = 'available'
    pending = 'pending'
    failed = 'failed'
    not_applicable = 'not_applicable'


class EvidenceRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    evidence_type: EvidenceType
    ref: constr(min_length=1)
    status: Status
    content_hash: constr(pattern=r'^(sha256:)?[a-fA-F0-9]{64}$') | None = None


class FlexibilityEnvelope(BaseModel):
    """
    건물·가정이 Portfolio/MG에 제공하는 시간별 단기 전력 유연성 계약. 연간 상시 효율 절감과 합산하지 않는다.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    envelope_id: constr(min_length=1)
    resource_id: constr(min_length=1)
    building_passport_id: str | None = None
    created_at: AwareDatetime
    valid_from: AwareDatetime
    valid_to: AwareDatetime
    resolution_minutes: conint(ge=1, le=1440)
    source: Source = Field(
        ...,
        description='산출 근거. source 자체가 현장 적용 또는 M&V 완료를 뜻하지 않는다.',
    )
    confidence: confloat(ge=0.0, le=1.0)
    intervals: list[Interval] = Field(..., min_length=1)
    constraints: list[Constraint] | None = None
    evidence_refs: list[EvidenceRef] = Field(..., min_length=1)
    persistent_efficiency_ref: str | None = Field(
        None,
        description='연간 상시 효율 결과의 별도 참조. intervals의 단기 유연성과 수치 합산 금지.',
    )
