# generated by datamodel-codegen:
#   filename:  forecast_response.json
#   timestamp: 2026-06-30T02:32:35+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field, confloat, conint, constr


class Model(Enum):
    """
    사용된 예측 모델 식별자
    """

    patchtst_v5 = 'patchtst_v5'
    korean_bb_fallback = 'korean_bb_fallback'
    archetype_fallback = 'archetype_fallback'


class InputSource(Enum):
    """
    입력 시계열 출처
    """

    telemetry = 'telemetry'
    store_energy = 'store_energy'
    synthetic = 'synthetic'


class ForecastItem(BaseModel):
    hour: conint(ge=0, le=23) = Field(..., description='예측 시각 (0~23)')
    energy_kwh: confloat(ge=0.0) = Field(..., description='예측 에너지 소비량 (kWh)')
    lower_bound: float | None = Field(None, description='90% 신뢰구간 하한 (kWh)')
    upper_bound: float | None = Field(None, description='90% 신뢰구간 상한 (kWh)')


class Metrics(BaseModel):
    """
    예측 품질 지표 (캘리브레이션 데이터 있을 때만)
    """

    cvrmse_pct: confloat(ge=0.0) | None = Field(
        None, description='ASHRAE G14 CVRMSE (%)'
    )
    nmbe_pct: float | None = Field(None, description='ASHRAE G14 NMBE (%)')
    mape_pct: confloat(ge=0.0) | None = Field(None, description='MAPE (%)')


class ForecastResponse(BaseModel):
    """
    PatchTST 168h→24h 에너지 예측 API 응답 (GET /api/v1/smart-building/{pnu}/forecast)
    """

    pnu: constr(pattern=r'^\d{19}$') = Field(..., description='건물 PNU (19자리)')
    model: Model = Field(
        ..., description='사용된 예측 모델 식별자', examples=['patchtst_v5']
    )
    input_hours: Literal[168] = Field(
        ..., description='예측에 사용된 과거 시계열 길이 (시간)'
    )
    input_source: InputSource | None = Field(
        None, description='입력 시계열 출처', examples=['telemetry']
    )
    forecast: list[ForecastItem] = Field(
        ..., description='24시간 예측값 배열', max_length=24, min_length=24
    )
    metrics: Metrics | None = Field(
        None, description='예측 품질 지표 (캘리브레이션 데이터 있을 때만)'
    )
    generated_at: AwareDatetime | None = Field(
        None, description='예측 생성 시각 (ISO 8601, UTC)'
    )
