# generated by datamodel-codegen:
#   filename:  gateway_routing.json
#   timestamp: 2026-06-30T02:32:37+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, constr


class SecretEnv(Enum):
    GATEWAY_BACKEND_SECRET = 'GATEWAY_BACKEND_SECRET'
    LLM_GATEWAY_SECRET = 'LLM_GATEWAY_SECRET'
    ANTHROPIC_API_KEY = 'ANTHROPIC_API_KEY'


class Mode(Enum):
    demo = 'demo'
    test = 'test'
    prod = 'prod'
    dev = 'dev'


class ModeCredentials(BaseModel):
    """
    DEMO/TEST/PROD 3-mode 적용 — mode-credentials.md 정합. PROD 에서는 /v1/config 가 mode 노출 금지.
    """

    run_mode_env: Literal['EMS_TRANSFORMER_RUN_MODE'] = 'EMS_TRANSFORMER_RUN_MODE'
    default_mode: Literal['demo'] = 'demo'
    modes: list[Mode] | None = None


class Gateway(BaseModel):
    id: Literal['ems_transformer']
    host_port: Literal[8030]
    base_url_env: Literal['EMS_GATEWAY_URL']
    external_hostname: Literal['ems-api.building-energy.xyz'] = (
        'ems-api.building-energy.xyz'
    )
    secret_envs: list[SecretEnv]
    mode_credentials: ModeCredentials = Field(
        ...,
        description='DEMO/TEST/PROD 3-mode 적용 — mode-credentials.md 정합. PROD 에서는 /v1/config 가 mode 노출 금지.',
    )


class Constants(BaseModel):
    max_tool_rounds: Literal[3] = 3
    default_timeout_s: float = None


class Method(Enum):
    GET = 'GET'
    POST = 'POST'


class Path(BaseModel):
    method: Method
    path: str
    purpose: str


class Kind(Enum):
    in_process = 'in_process'
    http_microservice = 'http_microservice'
    proxy = 'proxy'
    external_api = 'external_api'


class Backend(BaseModel):
    kind: Kind
    host_port: int | None = None
    url_env: str | None = None
    upstream_path: str | None = None
    model_id_ref: str | None = Field(
        None, description='_models/registry.yaml#<key> 참조'
    )


class Status(Enum):
    """
    operational = 운영 중 / training_pending = 모델 학습 대기 / spec_only = 설계만 (Phase 4 이후 구현) / deprecated
    """

    operational = 'operational'
    training_pending = 'training_pending'
    spec_only = 'spec_only'
    deprecated = 'deprecated'


class RequiresPersonaRoleEnum(Enum):
    household = 'household'
    building_owner = 'building_owner'
    facility_manager = 'facility_manager'
    govt = 'govt'
    admin = 'admin'


class Tier(Enum):
    """
    F14 같은 2-tier 라우팅에서 sub-classification
    """

    fast = 'fast'
    slow = 'slow'


class FunctionEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(pattern=r'^F\d+[a-z]?$') = Field(
        ..., description='F1~F14 또는 sub-id (예: F5b, F10a, F11a)'
    )
    name: str
    method: Method | None = None
    path: constr(pattern=r'^/v1/[a-z][a-z0-9/_\-\{\}]*$') | None = None
    paths: list[Path] | None = Field(
        None,
        description='다중 endpoint (예: F14 의 sync/async/polling/batch 4 endpoint)',
    )
    backend: Backend
    status: Status = Field(
        ...,
        description='operational = 운영 중 / training_pending = 모델 학습 대기 / spec_only = 설계만 (Phase 4 이후 구현) / deprecated',
    )
    external_facing: bool = Field(
        ...,
        description='true = 외부 UI/agent 호출 / false = 내부 격리 (F12 internal agent proxy 같은)',
    )
    tool_registry_name: str | None = Field(
        None, description='Qwen tool-calling 에서 호출되는 tool name (해당하는 경우)'
    )
    latency_budget_p99_s: float | None = Field(
        None, description='p99 latency 게이트 (s). 미정 시 omit.'
    )
    requires_persona_role: list[RequiresPersonaRoleEnum] | None = Field(
        None,
        description='X-Persona-Role 헤더 강제 (해당 endpoint 가 특정 persona 만 허용)',
    )
    requires_dual_signoff: bool | None = Field(
        None, description='AI 챔피언 plan §8.5.3 govt persona dual sign-off'
    )
    tier: Tier | None = Field(
        None, description='F14 같은 2-tier 라우팅에서 sub-classification'
    )
    ssot_refs: list[str] | None = None


class Namespace(Enum):
    """
    current = Q1~Q17 / legacy = src/api/main.py Q1~Q7 / future_debate = Q18~Qn
    """

    current = 'current'
    legacy = 'legacy'
    future_debate = 'future_debate'


class RequiresField(Enum):
    building = 'building'
    city = 'city'
    hvac = 'hvac'
    ems = 'ems'
    ems_compare_to = 'ems_compare_to'
    base_ems = 'base_ems'
    cooling_setpoint = 'cooling_setpoint'
    heating_setpoint = 'heating_setpoint'
    area_m2 = 'area_m2'


class ResponsibleModel(Enum):
    """
    본 qa_type 의 책임 모델 (8.simulation/CLAUDE.md 의 시계열 책임 분담 SSOT). LLM 응답이 책임 모델인 경우 F2 가 정상 라우팅. korean_bb_twgauss 책임 qa_type 은 F2 → 422 reject + F4 가이드 (Korean_BB :8040 /v1/forecast/24h).
    """

    qwen_v25 = 'qwen_v25'
    exaone_v25 = 'exaone_v25'
    korean_bb_twgauss = 'korean_bb_twgauss'


class QaTypeEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(pattern=r'^Q\d+$') = Field(
        ..., description='Q1~Q17 (현행) / Q18~Qn (debate 이후 확장)'
    )
    qa_type: str
    category: str
    namespace: Namespace | None = Field(
        'current',
        description='current = Q1~Q17 / legacy = src/api/main.py Q1~Q7 / future_debate = Q18~Qn',
    )
    requires_fields: list[RequiresField]
    responsible_model: ResponsibleModel = Field(
        ...,
        description='본 qa_type 의 책임 모델 (8.simulation/CLAUDE.md 의 시계열 책임 분담 SSOT). LLM 응답이 책임 모델인 경우 F2 가 정상 라우팅. korean_bb_twgauss 책임 qa_type 은 F2 → 422 reject + F4 가이드 (Korean_BB :8040 /v1/forecast/24h).',
    )


class BackendId(Enum):
    reverse = 'reverse'
    korean_bb = 'korean_bb'
    building_ai = 'building_ai'
    ecmhs = 'ecmhs'
    energyplus = 'energyplus'
    kbep = 'kbep'


class ToolEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Qwen tool name (TOOLS[].function.name)')
    backend_id: BackendId
    function_id_ref: constr(pattern=r'^F\d+[a-z]?$') = Field(
        ..., description='본 tool 이 호출 chain 상 어느 F# 기능에 속하는지'
    )
    upstream_url_env: str | None = None


class GatewayRoutingSSOT(BaseModel):
    """
    ems_transformer 통합 게이트웨이 (:8030) 의 단일 라우팅 SSOT. F1~F14 기능 catalog + Q1~Q17 QA 유형 + tool_registry (Qwen tool-calling) 통합. 워크스페이스 정본 UNIFIED_GATEWAY_DESIGN.md v1.2 의 머신리더블 버전. 변경 시 양쪽 동시 갱신 필수.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    gateway: Gateway
    functions: list[FunctionEntry] = Field(
        ...,
        description='F1~F14 기능 catalog. 신설 시 UNIFIED_GATEWAY_DESIGN.md v1.x §3 표 + 본 array 동시 갱신.',
    )
    qa_types: list[QaTypeEntry] = Field(
        ...,
        description='Q1~Q17 QA 유형 (F2 = /v1/qa/{qa_type}). debate 이후 Q18~Qn 확장 layer 는 별 namespace.',
    )
    tools: list[ToolEntry] = Field(
        ...,
        description='Qwen tool-calling TOOLS list. serving/tool_registry.py 와 정합. 각 tool 은 단일 backend endpoint 호출.',
    )
    constants: Constants
