# generated by datamodel-codegen:
#   filename:  household_consent.json
#   timestamp: 2026-08-26T06:44:52+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, Field, confloat, conint, constr


class ConsentPresetId(Enum):
    """
    동의 프리셋 식별자. **정본 3 종**이며 기본 선택은 없다(가구가 고르지 않으면 동의가 아니다). 값·라벨은 아래 `default.presets` 가 정본.
    """

    light = 'light'
    standard = 'standard'
    deep = 'deep'


class ParticipationState(Enum):
    """
    참여 상태. ⚠ 넷을 뭉치면 거짓이 된다 — 두절(OFFLINE)을 철회(OPTED_OUT)로 세면 동의한 가구를 잃고, 철회를 두절로 세면 **거부한 집에 계속 명령을 보낸다**. NOT_ENROLLED = 한 번도 동의한 적 없음(두절과 다르다).
    """

    NOT_ENROLLED = 'NOT_ENROLLED'
    OPTED_IN = 'OPTED_IN'
    OPTED_OUT = 'OPTED_OUT'
    OFFLINE = 'OFFLINE'


class ConsentEnvelope(BaseModel):
    """
    가구가 동의한 **범위**. 세 축을 모두 갖는다 — *"에어컨 1℃ 까지"* 와 *"3℃ 까지"* 는 다른 동의이고, 범위 없는 동의는 동의가 아니다.
    """

    max_setpoint_delta_c: confloat(ge=0.0, le=5.0) = Field(
        ...,
        description="설정온도를 기준선 대비 몇 ℃ 까지 **올려도** 되는가(냉방 기준). ⚠ 기준선은 '현재값' 이 아니라 `현재 − 지금 걸린 제어` 다 — 현재값으로 재면 24→26→28 로 동의의 두 배를 쓴다. ⚠ **내리는 축은 이 계약에 없다**(예냉 등은 별도 동의 사안).",
    )
    max_duration_min: conint(ge=0, le=480) = Field(
        ...,
        description='한 번에 몇 분까지. 명령이 지속시간을 안 밝히면 이 값을 상한으로 적용한다 — 모른다고 무제한으로 두면 동의한 시간을 넘겨 걸린다.',
    )
    max_events_per_day: conint(ge=0, le=24) = Field(
        ...,
        description='**하루** 몇 회까지. 동의는 횟수도 갖는다. ⚠ 날짜 경계에서 리셋되지 않으면 이 값은 하루 한도가 아니라 **평생 한도**가 된다(상시 가동 엣지에서 N 회 이후 전건 거부).',
    )


class ConsentPreset(BaseModel):
    """
    화면에 내놓는 선택지 하나. **숫자를 그대로 표시**해야 한다 — 라벨만 보여주면 무엇에 동의했는지 가구가 알 수 없고, 그건 동의가 아니라 위임이다.
    """

    preset_id: ConsentPresetId
    label_ko: str = Field(..., description='화면 표시 라벨(한국어).')
    envelope: ConsentEnvelope


class ConsentRequest(BaseModel):
    """
    참여 동의 등록·변경 요청 (PUT). 가구가 고른 프리셋을 보낸다.
    """

    preset_id: ConsentPresetId
    contract_version: str | None = Field(
        None,
        description='요청자가 읽은 이 계약의 버전. 미기재 허용(수신자 버전으로 간주).',
    )
    displayed: ConsentEnvelope | None = Field(
        None,
        description="**가구에게 실제로 보여준 숫자.** 선택. 보내면 수신자가 정본 프리셋과 대조해 **다르면 거부**한다 — 화면이 '2℃' 라 말하고 엣지가 3℃ 를 거는 드리프트를 계약 단계에서 잡는다.",
    )


class ProtectionState(BaseModel):
    """
    취약 거주자 보호 — **동의보다 위에 있는 상태**. 가구가 동의했더라도 이 상태가 서 있으면 감축을 걸지 않는다. ⚠ 동의와 보호는 다른 축이다: 동의는 '해도 되나', 보호는 '해서는 안 되나' 다. 재동의로 풀리지 않는다(풀려면 명시적으로 해제해야 한다) — 그래서 '권위' 다.
    """

    protected: bool = Field(
        ...,
        description="참이면 이 가구는 **DR 감축 대상에서 제외**된다. 설정온도를 올리는 명령은 동의 범위 안이라도 거부한다. ⚠ 제어 해제(기준선 복귀)는 계속 허용한다 — 보호는 '제어를 놓지 못하게' 하는 것이 아니다.",
    )
    declared_at: AwareDatetime | None = None
    note: constr(max_length=120) | None = Field(
        None,
        description='운영 메모(선택). ⚠ **건강·질병 정보를 적지 않는다.** 이 값은 로컬에만 남고 중앙 등록(fleet/register)에 실리지 않지만, 적는 순간 로그·백업으로 퍼진다. 필드 이름이 `vulnerable_*` 가 아닌 이유도 같다 — 사람을 분류하지 않고 **보호 조치**를 기록한다.',
    )


class PreflightBlocker(Enum):
    """
    제안을 **만들면 안 되는** 사유. ⚠ 소비자가 이 판정을 각자 재현하면 규칙이 두 곳에 살고 언젠가 갈라진다 — 엣지가 한 번 판정해 이름으로 돌려준다.
    """

    driver_not_attached = 'driver_not_attached'
    not_a_home_venue = 'not_a_home_venue'
    no_consent = 'no_consent'
    requires_reconsent = 'requires_reconsent'
    opted_out = 'opted_out'
    daily_quota_exhausted = 'daily_quota_exhausted'
    protected_resident = 'protected_resident'
    contract_version_mismatch = 'contract_version_mismatch'


class HouseholdConsent(BaseModel):
    """
    가정 1세대의 **직접부하제어 참여 동의**. 화면(AIRO Home)이 받은 선택과 엣지(edge-agent)가 강제하는 범위가 같은 정의를 읽게 하는 계약. ⚠ 제어 명령 계약(control_command.json)과 **별개 축**이다 — 명령에 동의 범위(델타·횟수)를 실으면 명령마다 동의가 재협상되는 꼴이 되고, 동의는 명령보다 수명이 길다.
    """

    presets: list[ConsentPreset] | None = Field(
        None,
        description='정본 프리셋 3 종. 화면·엣지가 **같은 표**를 읽는다.',
        max_length=3,
        min_length=3,
    )


class ConsentState(BaseModel):
    """
    현재 동의 상태 (GET 응답). 화면이 '남은 횟수' 를 스스로 계산하지 않아도 되게 파생값을 함께 준다.
    """

    household_id: str
    participation: ParticipationState
    preset_id: ConsentPresetId | None = Field(
        None, description='동의에 쓰인 프리셋. 미동의(NOT_ENROLLED) 시 null.'
    )
    contract_version: str = Field(..., description='이 상태를 강제하는 계약 버전.')
    consent: ConsentEnvelope | None = Field(
        None, description='적용 중인 범위. 미동의 시 null.'
    )
    applied_delta_c: float | None = Field(
        None, description='지금 걸려 있는 제어(℃). 기준선 계산에 쓰인다.'
    )
    events_today: conint(ge=0) = Field(..., description='오늘 쓴 횟수.')
    remaining_events_today: conint(ge=0) = Field(
        ...,
        description='**오늘 남은 횟수** = max(0, max_events_per_day − events_today). ⚠ 소비자가 직접 빼서 쓰면 날짜 롤오버 시점이 어긋난다(엣지는 넘어갔는데 화면은 어제 값으로 뺀다) — 그래서 파생을 **한 곳에서** 한다. 미동의 시 0.',
    )
    day: date = Field(
        ...,
        description='`events_today` 가 속한 날짜(엣지 로컬 TZ). 조회 시점에 롤오버가 반영된 값이어야 한다.',
    )
    capacity: dict[str, Any] | None = Field(
        None,
        description='상위 재계획 입력(동원 가능 자원). 철회=영구 감소 · 두절=일시 감소로 갈라 센다.',
    )
    requires_reconsent: bool | None = Field(
        False,
        description='정본 프리셋과 맞지 않는 **구 동의**를 들고 있었다는 표시. 이 상태에서는 참여로 세지 않는다(명령 전건 거부) — 화면은 가구에게 **다시 물어야** 한다. ⚠ 숫자가 정본에 없다는 것은 가구가 지금 표에 없는 범위에 동의했다는 뜻이고, 그 동의를 임의의 프리셋으로 승격하면 동의하지 않은 범위를 적용하게 된다.',
    )
    protection: ProtectionState | None = Field(
        None, description='취약 거주자 보호 상태. 동의보다 **위**다.'
    )


class PreflightState(BaseModel):
    """
    가정 참여 **준비 상태** — *"지금 이 가구에 제안을 만들어도 되는가"* 한 번에 답한다. 화면이 동의·잔여 횟수·보호 상태를 각각 조회해 스스로 조합하면, 그 조합 규칙이 화면과 엣지 양쪽에 살게 된다.
    """

    ven_id: str
    ready: bool = Field(
        ..., description='제안을 만들어 승인받아도 되는가. `blockers` 가 비어야 참이다.'
    )
    blockers: list[PreflightBlocker] = Field(
        ...,
        description='비어 있지 않으면 **제안을 만들지 않는다.** 만들어 놓고 거부당하면 가구는 눌렀는데 아무 일도 안 일어나는 경험을 한다.',
    )
    contract_version: str
    max_setpoint_c: float | None = Field(
        None,
        description='지금 제안 가능한 **설정온도 상한**(℃) = min(기준선 + 동의 델타, 엣지 인터록 상한). ⚠ 화면은 이 값을 넘겨 제안하지 않는다 — 넘겨 놓고 엣지가 자르면 승인 화면의 숫자와 실제가 달라진다.',
    )
    max_duration_min: int | None = Field(
        None, description='제안 가능한 최대 지속시간(분).'
    )
    remaining_events_today: conint(ge=0) | None = None
    baseline_setpoint_c: float | None = Field(
        None, description='제어가 걸리지 않았을 때의 설정온도. 제안 계산의 기준.'
    )
    consent: ConsentState | None = None
    evidence: dict[str, Any] | None = Field(
        None,
        description='증거 레인 — `data_source`(synthetic/simulated/measured) · `field_application` 가능 여부. 가상 응답을 현장 적용으로 승격하지 못하게 화면이 읽는다.',
    )
