# generated by datamodel-codegen:
#   filename:  hvac_ems_matrix.json
#   timestamp: 2026-06-30T02:32:41+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class HvacTypes(BaseModel):
    """
    ASHRAE 901 STD2019 5 종 (A~E) + 한국화 4 종 (HD~HG)
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    A: Literal['Central chilled water + boiler (chiller multi-stage)'] = (
        'Central chilled water + boiler (chiller multi-stage)'
    )
    B: Literal['Packaged DX (split / rooftop, 1~2 stage)'] = (
        'Packaged DX (split / rooftop, 1~2 stage)'
    )
    C: Literal['Single zone DX (residential / small commercial)'] = (
        'Single zone DX (residential / small commercial)'
    )
    D: Literal['VRF (inverter-driven multi-zone)'] = 'VRF (inverter-driven multi-zone)'
    E: Literal['Hydronic radiant + DOAS'] = 'Hydronic radiant + DOAS'
    HD: Literal['Korean — VRF + 온돌 (residential 한국화)'] = (
        'Korean — VRF + 온돌 (residential 한국화)'
    )
    HE: Literal['Korean — 온돌 + gas boiler + PTAC (mid-rise residential)'] = (
        'Korean — 온돌 + gas boiler + PTAC (mid-rise residential)'
    )
    HF: Literal['Korean — Hybrid (central + 온돌)'] = 'Korean — Hybrid (central + 온돌)'
    HG: Literal['Korean — gas-fired boiler + radiator (older retrofit)'] = (
        'Korean — gas-fired boiler + radiator (older retrofit)'
    )


class Compatibility(Enum):
    """
    compatible = 정상 / marginal = 절감 <5% warn / infeasible = 422 차단 / expected_skip = EMS §21 알려진 skip
    """

    compatible = 'compatible'
    marginal = 'marginal'
    infeasible = 'infeasible'
    expected_skip = 'expected_skip'


class StrategyRow1(BaseModel):
    compatibility: Compatibility
    expected_saving_pct_range: list[float] | None = Field(
        None,
        description='[min, max] %. infeasible 시 omit.',
        max_length=2,
        min_length=2,
    )
    note: str | None = None


class StrategyRow(
    RootModel[dict[constr(pattern=r'^M(0[0-9]|1[0-9]|20)$'), StrategyRow1]]
):
    root: dict[constr(pattern=r'^M(0[0-9]|1[0-9]|20)$'), StrategyRow1]


class Matrix(BaseModel):
    """
    key = HVAC type (A~E, HD~HG), value = { strategy_id: compatibility }. compatibility ∈ {compatible, marginal, infeasible, expected_skip}.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    A: StrategyRow | None = None
    B: StrategyRow | None = None
    C: StrategyRow | None = None
    D: StrategyRow | None = None
    E: StrategyRow | None = None
    HD: StrategyRow | None = None
    HE: StrategyRow | None = None
    HF: StrategyRow | None = None
    HG: StrategyRow | None = None


class HvacEmsCompatibilityMatrix(BaseModel):
    """
    HVAC type × EMS strategy 호환성 매트릭스 SSOT. F14 Policy Evaluation 의 G-PE1 validation 단계에서 infeasible 조합 차단에 사용. KOREAN_HVAC.md §13 + EMS_STRATEGY.md §21 EXPECTED_SKIP + SPEC_HVAC_SYSTEMS.md §3 통합.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    hvac_types: HvacTypes | None = Field(
        None, description='ASHRAE 901 STD2019 5 종 (A~E) + 한국화 4 종 (HD~HG)'
    )
    ems_strategies: dict[str, Any] | None = Field(
        None,
        description='M00~M20 EMS 전략 (ems_strategies.json#StrategyCode SSOT 참조)',
    )
    matrix: Matrix = Field(
        ...,
        description='key = HVAC type (A~E, HD~HG), value = { strategy_id: compatibility }. compatibility ∈ {compatible, marginal, infeasible, expected_skip}.',
    )
