# generated by datamodel-codegen:
#   filename:  hvac_ems_matrix.json
#   timestamp: 2026-09-14T21:15:28+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class HvacTypes(BaseModel):
    """
    행 키 → 정본 HVAC 코드(region_codes.json#hvac_types). 표시 이름은 그 표의 name_kr 만 쓴다. 짝 = 서빙 인코더 kbep_client._HVAC_TYPE_TO_ID (A=HA=H_A … G=HG=H_G). 대조 = validate_ssot.check_hvac_display_names.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    A: Literal['H_A'] = 'H_A'
    B: Literal['H_B'] = 'H_B'
    C: Literal['H_C'] = 'H_C'
    D: Literal['H_D'] = 'H_D'
    E: Literal['H_E'] = 'H_E'
    HD: Literal['H_D'] = 'H_D'
    HE: Literal['H_E'] = 'H_E'
    HF: Literal['H_F'] = 'H_F'
    HG: Literal['H_G'] = 'H_G'


class Compatibility(Enum):
    """
    compatible = 정상 / marginal = 절감 <5% warn / infeasible = 422 차단 / expected_skip = EMS §21 알려진 skip
    """

    compatible = 'compatible'
    marginal = 'marginal'
    infeasible = 'infeasible'
    expected_skip = 'expected_skip'


class StrategyRow1(BaseModel):
    compatibility: Compatibility
    expected_saving_pct_range: list[float] | None = Field(
        None,
        description='[min, max] %. infeasible 시 omit.',
        max_length=2,
        min_length=2,
    )
    note: str | None = None


class StrategyRow(
    RootModel[dict[constr(pattern=r'^M(0[0-9]|1[0-9]|[2-9][0-9])$'), StrategyRow1]]
):
    root: dict[constr(pattern=r'^M(0[0-9]|1[0-9]|[2-9][0-9])$'), StrategyRow1]


class Matrix(BaseModel):
    """
    key = HVAC type (A~E, HD~HG), value = { strategy_id: compatibility }. compatibility ∈ {compatible, marginal, infeasible, expected_skip}.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    A: StrategyRow | None = None
    B: StrategyRow | None = None
    C: StrategyRow | None = None
    D: StrategyRow | None = None
    E: StrategyRow | None = None
    HD: StrategyRow | None = None
    HE: StrategyRow | None = None
    HF: StrategyRow | None = None
    HG: StrategyRow | None = None


class HvacEmsCompatibilityMatrix(BaseModel):
    """
    HVAC type × EMS strategy 호환성 매트릭스 SSOT. F14 Policy Evaluation 의 G-PE1 validation 단계에서 infeasible 조합 차단에 사용. KOREAN_HVAC.md §13 + EMS_STRATEGY.md §21 EXPECTED_SKIP + SPEC_HVAC_SYSTEMS.md §3 통합.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    hvac_types: HvacTypes | None = Field(
        None,
        description='행 키 → 정본 HVAC 코드(region_codes.json#hvac_types). 표시 이름은 그 표의 name_kr 만 쓴다. 짝 = 서빙 인코더 kbep_client._HVAC_TYPE_TO_ID (A=HA=H_A … G=HG=H_G). 대조 = validate_ssot.check_hvac_display_names.',
    )
    ems_strategies: dict[str, Any] | None = Field(
        None,
        description='M00~M20 EMS 전략 (ems_strategies.json#StrategyCode SSOT 참조)',
    )
    matrix: Matrix = Field(
        ...,
        description='key = HVAC type (A~E, HD~HG), value = { strategy_id: compatibility }. compatibility ∈ {compatible, marginal, infeasible, expected_skip}.',
    )
