# generated by datamodel-codegen:
#   filename:  i18n_keys.json
#   timestamp: 2026-06-30T02:32:47+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class I18NKeysSsotPhaseJ8(BaseModel):
    """
    다국어 번역 키 SSOT. ko/en/id (한국·영어·인도네시아). EduArena + BEMS 6 테넌트 + 인도네시아 랜딩 공유. 키 충돌 방지.
    """


class Lang(Enum):
    ko = 'ko'
    en = 'en'
    id = 'id'
    ms = 'ms'
    th = 'th'
    vi = 'vi'
    tl = 'tl'
