# generated by datamodel-codegen:
#   filename:  tmpoudzsqj9.json
#   timestamp: 2026-09-29T12:25:21+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel, constr


class AiroTargetrefPeriodrefQuantity(RootModel[Any]):
    root: Any = Field(
        ...,
        description='질의 경로의 모든 단계(표면 어댑터·질문 틀·결속기·도구·결과 봉투·검산기)가 대상·기간·수량을 한 모양으로 주고받게 하는 공통 타입(2026-09-29 M3 — 공모전 docs/ARCHITECTURE_MIGRATION_M1_M6_2026-09-29.md §2 · scratch/expert_0929/INTERFACES.md §4.2①). 새 모양을 만들지 않고 이미 있는 정본을 가리킨다: 대상·기간 = airo_request.json 의 Target·Period, 분류 = data_classification.json 의 ClassificationWord. 도구 인자 이름 23가지(target_id·city·building_id …)·기간 인자 14가지는 이 타입에서 파생하는 선언 대응표로 옮긴다(어댑터층 이전 — 재작성하지 않는다).',
        title='AIRO 인터페이스 공통 타입 (TargetRef · PeriodRef · Quantity)',
    )


class QuantityUnit(Enum):
    """
    수량 단위 어휘. score = 점수·등급 문턱(예 화재 위험 70점 — 1.1 RV-B1, 게이트웨이 clarify SELECTION_QUALIFIERS risk). 에너지·전력·탄소·1차에너지·면적·온도의 표기는 energy_units.json#default.base_units 와 같다(시험이 포함 관계를 지킨다). ratio=0~1 비율 · pct=백분율(25 = 25%) — 질문의 '상위 25%' 는 pct 로 싣고 환산은 한 곳(질문 수 환산)에서 한다.
    """

    ratio = 'ratio'
    pct = 'pct'
    count = 'count'
    KRW = 'KRW'
    kWh = 'kWh'
    kW = 'kW'
    kWh_pe = 'kWh_pe'
    kWh_m2 = 'kWh/m2'
    kg_CO2 = 'kg_CO2'
    t_CO2 = 't_CO2'
    m2 = 'm2'
    celsius = 'celsius'
    yr = 'yr'
    month = 'month'
    day = 'day'
    hour = 'hour'
    score = 'score'


class Quantity(BaseModel):
    """
    수와 단위 한 쌍 — 질문 수 환산의 결과 모양. 수 인자에 단위를 선언해 버려지는 인자·비율/백분율 혼동을 막는다.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    value: float
    unit: QuantityUnit
    text: constr(max_length=200) | None = Field(
        None,
        description='질문 원문의 부분 문자열(질문이 말한 수일 때) — 수를 지어내지 않았다는 근거',
    )


class Kind(Enum):
    asset = 'asset'
    portfolio = 'portfolio'
    building = 'building'
    region = 'region'
    archetype = 'archetype'


class Source(Enum):
    query = 'query'
    selection = 'selection'
    previous = 'previous'
    user_default = 'user_default'
    login_assignment = 'login_assignment'
    auto_first = 'auto_first'
    chain_step = 'chain_step'


class Kind1(Enum):
    asset = 'asset'
    portfolio = 'portfolio'
    building = 'building'
    region = 'region'
    archetype = 'archetype'
    NoneType_None = None


class Source1(Enum):
    query = 'query'
    selection = 'selection'
    previous = 'previous'
    user_default = 'user_default'
    login_assignment = 'login_assignment'
    auto_first = 'auto_first'
    chain_step = 'chain_step'
    NoneType_None = None


class ChainStep(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class Choice(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class Attributes(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sido: constr(pattern=r'^[0-9]{2}$') | None = None
    sigungu: constr(pattern=r'^[0-9]{5}$') | None = None
    climate_city: constr(pattern=r'^C(0[1-9]|1[0-8])$') | None = None
    archetype: constr(pattern=r'^B(0[1-9]|1[0-8])$') | None = None
    hvac: constr(pattern=r'^H_[A-G]$') | None = None
    usage: str | None = None
    gross_floor_area_m2: float | None = None
    building_mgmt_no: constr(pattern=r'^[0-9]{25}$') | None = None
    parcel_id: constr(pattern=r'^[0-9]{19}$') | None = None
    identity_status: str | None = None


class Source2(Enum):
    record = 'record'
    registry = 'registry'
    derived = 'derived'
    question = 'question'
    default = 'default'
    none = 'none'


class AbsenceKind1(Enum):
    missing = 'missing'
    not_applicable = 'not_applicable'
    unknown = 'unknown'
    NoneType_None = None


class AttributeSources(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Source2
    absence_kind: AbsenceKind1 | None = None
    flag: str | None = Field(None, description='예: area_unverified(D1 면적 미확인)')
    basis: str | None = None


class Grain(Enum):
    hour = 'hour'
    day = 'day'
    month = 'month'
    year = 'year'
    NoneType_None = None


class Basis(Enum):
    """
    기간 근거. declared_replay_period = 선언된 재생 분석 기간(자료 끝이 아니라 등록된 재생 창) · calendar_relative_to_today = 오늘 기준 달력 상대 기간(예 '지난달') — 2026-09-28 W8(Studio S42) 이관 · coverage_of_needs = 질문이 기간을 말하지 않았을 때 도구가 필요로 하는 채널이 모두 덮는 창(operation_manifest default_period 한 규칙 — 2.3 M3/M4) · forecast_relative_to_today = 오늘 기준 **앞으로의** 상대 기간(예 '다음 주 예측' — 게이트웨이 general_ops/periods 예측 구간, 2.4)
    """

    question_literal = 'question_literal'
    recent_n_from_data_end = 'recent_n_from_data_end'
    subject_default = 'subject_default'
    client_selection = 'client_selection'
    declared_replay_period = 'declared_replay_period'
    calendar_relative_to_today = 'calendar_relative_to_today'
    coverage_of_needs = 'coverage_of_needs'
    forecast_relative_to_today = 'forecast_relative_to_today'
    NoneType_None = None


class ClassificationWord(Enum):
    """
    결과·결속 출처의 **분류 낱말**(값 하나 또는 결과 전체가 무엇으로 만들어졌나). 낱말마다 출처(DataSource)·표시 등급(EvidenceDisplayClass)·한글 라벨이 default.classification.words 에 있다. 옛 낱말은 default.classification.aliases 로 이 낱말에 잇는다. 여러 출처를 합칠 때는 default.classification.composite 규칙(코드 = rules_pure.ec_classification_combine).
    """

    measured = 'measured'
    measured_with_imputed = 'measured_with_imputed'
    calibrated = 'calibrated'
    certified = 'certified'
    simulated = 'simulated'
    predicted = 'predicted'
    estimated = 'estimated'
    imputed = 'imputed'
    external = 'external'
    reference = 'reference'
    declared = 'declared'
    assumed = 'assumed'
    virtual = 'virtual'
    synthetic = 'synthetic'
    mock = 'mock'
    mixed = 'mixed'
    unknown = 'unknown'


class AbsenceKind(Enum):
    """
    부재 축 — **값이 왜 없나**. DataSource(출처 축)와 섞지 않는다. not_applicable=설계·물리·정책상 대상이 아니다(자원을 쓰지 않는다) · missing=대상인데 아직 안 받았다(여기만 자원을 쓴다) · unknown=대상인지조차 판정 못 했다(못 잼 — 통과로 세지 않는다). ⛔ 분모는 covered+missing 이다. not_applicable 을 분모에 넣으면 진척이 실제보다 나빠 보이고 없는 결손에 예산이 나간다(전역 룰 absence-has-kinds).
    """

    not_applicable = 'not_applicable'
    missing = 'missing'
    unknown = 'unknown'


class Kind2(Enum):
    """
    거절 갈래 — question=질문이 정해야 할 것이 빠졌거나 모호(되묻기) · data=자료가 없거나 덮지 못함 · permission=권한·배정 밖 · internal=우리 결함. 거절 사전의 갈래(질문·자료·권한·내부)와 같다. 자료/질문/결함을 가르지 않으면 고칠 곳을 못 찾는다.
    """

    question = 'question'
    data = 'data'
    permission = 'permission'
    internal = 'internal'


class Retry(Enum):
    """
    ask=사용자에게 되묻는다 · fill=서버가 채울 수 있다(가상·추정 채움 + 출처 표시, 또는 자료 적재 뒤) · none=같은 요청을 다시 보내도 같은 답
    """

    ask = 'ask'
    fill = 'fill'
    none = 'none'


class Refusal(BaseModel):
    """
    거절 봉투(1.1 M3 — INTERFACES §4.2④). 도구·결속기·게이트웨이가 거절을 싣는 모양 6가지(code · 예외 문장 · error 문자열 · 중첩 error/detail/refusal · refusal_code · status+reason)를 이 하나로 모은다. 코드는 뜻 단위로 짓고 어느 칸인지는 field 로 싣는다(칸마다 '<칸>_REQUIRED' 새 이름을 만들지 않는다). 옛 코드(거절 사전 1,370개)는 legacy_code 로 이어 응답 바이트 해석을 깨지 않는다. airo-result/v1 의 refusal 칸과 Problem 의 확장 칸이 이 정의를 가리킨다.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    code: constr(pattern=r'^[A-Z][A-Z0-9_]+$') = Field(
        ...,
        description='뜻 단위 거절 코드(UPPER_SNAKE) — 예 INPUT_REQUIRED · TARGET_KIND_UNSUPPORTED · PERIOD_NOT_COVERED · PLACE_AMBIGUOUS',
    )
    kind: Kind2 = Field(
        ...,
        description='거절 갈래 — question=질문이 정해야 할 것이 빠졌거나 모호(되묻기) · data=자료가 없거나 덮지 못함 · permission=권한·배정 밖 · internal=우리 결함. 거절 사전의 갈래(질문·자료·권한·내부)와 같다. 자료/질문/결함을 가르지 않으면 고칠 곳을 못 찾는다.',
    )
    field: constr(max_length=200) | None = Field(
        None,
        description='무엇이 문제인 칸(예 target · period · params.top_share · place). 뜻은 code, 칸은 field',
    )
    expected: Any | None = Field(
        None, description='그 칸이 받아야 했던 것(값·모양·종류 목록). 형식 자유'
    )
    got: Any | None = Field(
        None,
        description='실제로 받은 것(비식별 값만 — 좌표·주소·원천 코드 금지). 형식 자유',
    )
    message_ko: constr(min_length=1, max_length=1000) = Field(
        ..., description='사람이 읽는 거절 사유(한국어). 원인을 가리지 않는다'
    )
    next_ko: constr(max_length=1000) | None = Field(
        None, description="사용자가 다음에 할 일(예 '지역을 하나 골라 주세요')"
    )
    retry: Retry = Field(
        ...,
        description='ask=사용자에게 되묻는다 · fill=서버가 채울 수 있다(가상·추정 채움 + 출처 표시, 또는 자료 적재 뒤) · none=같은 요청을 다시 보내도 같은 답',
    )
    legacy_code: constr(pattern=r'^[A-Z][A-Z0-9_]+$') | None = Field(
        None,
        description='옛 거절 코드(게이트웨이 refusal_dictionary). 별칭표로 뜻 단위 code 에 잇는다 — 판정 원장이 읽는 옛 이름을 끊지 않는다',
    )


class Archetype(RootModel[Any]):
    root: Any


class AssetKind(RootModel[Any]):
    root: Any


class SourceModel(Enum):
    query = 'query'
    selection = 'selection'
    previous = 'previous'
    user_default = 'user_default'
    login_assignment = 'login_assignment'
    auto_first = 'auto_first'
    chain_step = 'chain_step'


class TargetExpansion(RootModel[Any]):
    root: Any


class TargetMembers(RootModel[Any]):
    root: Any


class ClassificationWordRef(RootModel[ClassificationWord]):
    root: ClassificationWord = Field(
        ...,
        description='분류 낱말 = data_classification.json 의 정본 17 낱말. 도구 스키마의 지역 enum 10 변형을 이것 하나로 바꾼다(손실 있는 내림 맞춤 금지).',
    )


class AbsenceKindRef(RootModel[AbsenceKind]):
    root: AbsenceKind = Field(
        ..., description='부재 축(not_applicable · missing · unknown) — 값이 왜 없나.'
    )


class Target(BaseModel):
    """
    필지번호(19자리)는 대상이 아니다 — 필지 화면의 조회 열쇠로만. ms-·원천 코드·BE-3D 정수 패킷 번호는 서버 안에서만. 이 정의가 공통 타입 TargetRef 의 정본이다(interface_types.json#/$defs/TargetRef 가 이것을 가리킨다 — 사본 금지). 2.3: asset_kind·members·expansion 은 서버가 채우는 칸이다(표면이 보내면 서버 값이 덮는다).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Kind
    ids: list[str] = Field(..., max_length=50, min_length=1)
    label: constr(max_length=60) | None = None
    source: Source | None = None
    archetype: Archetype | None = None
    asset_kind: AssetKind | None = None
    members: TargetMembers | None = None
    expansion: TargetExpansion | None = None


class TargetContext(BaseModel):
    """
    응답에 싣는 대상 문맥(2026-09-28 일반화 G1). 요청 Target 의 kind·ids·source 를 **그대로** 되돌리고(출처를 'request' 로 뭉치지 않는다), 서버가 끌어낸 속성과 그 속성의 출처를 싣는다. 못 끌어낸 속성은 null + attribute_sources 에 absence_kind. 기본값을 쓰면 출처 'default'. 2.4: 대상이 없으면(resolved=false) kind·source 는 null, ids 는 빈 목록이다(대상을 지어내지 않는다 — '없음' 을 별도 출처 낱말로 적지 않는다). v1 요청이 대상을 실어 보냈으면 출처는 selection(호출자가 고른 대상)이다.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    contract: Literal['airo-target-context/v1'] = Field(
        'airo-target-context/v1',
        description='2.4: 응답 칸 표지 — 표지 칸 이름은 contract 하나',
    )
    kind: Kind1
    ids: list[str] = Field(..., max_length=50)
    source: Source1
    chain_steps: list[ChainStep] | None = Field(
        None,
        description='2.4: 연쇄 실행이면 단계 도구 이름(순서대로). 연쇄가 아니면 칸이 없다',
        max_length=50,
    )
    final_target_source: SourceModel | None = Field(
        None,
        description='2.4: 연쇄의 마지막 단계 대상이 어디서 왔나(앞 단계 결과 = chain_step). 요청 대상 출처(source)와 가른다',
    )
    choices: list[Choice] | None = Field(
        None,
        description='2.4: 대상을 정하지 못했을 때 고를 수 있는 후보 id(로그인 배정의 최상위 단위들)',
        max_length=50,
    )
    label: constr(max_length=60) | None = None
    resolved: bool | None = Field(None, description='서버가 대상을 식별자까지 풀었는가')
    asset_kind: AssetKind | None = Field(
        None,
        description='2.3: 요청 대상의 AIR 자산 종류를 그대로 보존한다(kind 를 asset→building 으로 바꾸지 않는다)',
    )
    members: TargetMembers | None = None
    expansion: TargetExpansion | None = None
    attributes: Attributes | None = None
    attribute_sources: dict[str, AttributeSources] | None = Field(
        None,
        description='속성 이름 → {source: record|registry|derived|default|question, absence_kind?, flag?}',
    )


class Period(BaseModel):
    """
    서버의 단일 파서가 text 를 start·end_exclusive·grain·basis 로 정규화한다. LLM 은 정규화 값을 직접 주지 않는다(날짜를 지어내지 않게).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    text: constr(max_length=200) | None = Field(
        None, description='LLM 이 주는 유일한 기간 값 — 질문 원문의 부분 문자열'
    )
    start: AwareDatetime | None = None
    end_exclusive: AwareDatetime | None = None
    tz: Literal['Asia/Seoul'] = 'Asia/Seoul'
    grain: Grain | None = None
    basis: Basis | None = Field(
        None,
        description="기간 근거. declared_replay_period = 선언된 재생 분석 기간(자료 끝이 아니라 등록된 재생 창) · calendar_relative_to_today = 오늘 기준 달력 상대 기간(예 '지난달') — 2026-09-28 W8(Studio S42) 이관 · coverage_of_needs = 질문이 기간을 말하지 않았을 때 도구가 필요로 하는 채널이 모두 덮는 창(operation_manifest default_period 한 규칙 — 2.3 M3/M4) · forecast_relative_to_today = 오늘 기준 **앞으로의** 상대 기간(예 '다음 주 예측' — 게이트웨이 general_ops/periods 예측 구간, 2.4)",
    )
    source: SourceModel | None = Field(
        None,
        description="2.4: 기간을 누가 정했나 — 대상 출처와 같은 낱말(query = 질문 원문 · selection = 요청이 준 경계 …). 질문의 기간을 'question' 같은 별도 낱말로 적지 않는다",
    )
    basis_ko: constr(max_length=400) | None = Field(
        None,
        description='2.4: 사람이 읽는 근거 한 줄 — basis 칸에서 만든다(글자 앞머리로 근거 종류를 되읽지 않는다)',
    )
    why: constr(max_length=400) | None = Field(
        None,
        description='2.4: 창을 정하지 못했을 때의 사유(말하지 않았음 · 자료 끝이 있어야 풀림 · 못 읽음). 창이 있으면 싣지 않는다',
    )
    generator: constr(max_length=160) | None = Field(
        None, description='2.4: 기간을 푼 코드(예 serving/general_ops/periods.py)'
    )
    contract: Literal['airo-period/v1'] = Field(
        'airo-period/v1',
        description='2.4: 응답 칸 표지(validation.period) — 표지 칸 이름은 contract 하나',
    )


class TargetRef(RootModel[Target]):
    root: Target = Field(
        ...,
        description='대상 참조 = airo-request/v2 의 Target 그대로(kind·ids·label·source·archetype) + 2.3 에서 더한 asset_kind(AIR 자산 종류 — v1 에서 잃던 것)·members(전개된 구성원)·expansion(전개 규칙 rule_id·rule_ko). 정의는 airo_request.json 한 곳이다(사본 금지).',
    )


class TargetContextRef(RootModel[TargetContext]):
    root: TargetContext = Field(
        ...,
        description='응답에 싣는 대상 문맥 = airo-request/v2 의 TargetContext 그대로(요청 kind·ids·source 보존 + asset_kind·members·expansion + 끌어낸 속성과 출처).',
    )


class PeriodRef(RootModel[Period]):
    root: Period = Field(
        ...,
        description="기간 참조 = airo-request/v2 의 Period 그대로(text·start·end_exclusive·tz·grain·basis). 끝은 배타(end_exclusive)다 — 포함 끝 'end' 를 쓰는 도구는 어댑터가 바꾼다. 결과의 period_used 는 basis 를 반드시 싣는다(기본 기간을 어떤 규칙으로 골랐는지 = coverage_of_needs 등).",
    )


class RequestResolution(BaseModel):
    """
    1.2(0.3.63 초안): 실행 전 해석 입구 POST /v1/request-resolution 의 응답(2026-09-29 3b-2 S1 · 공모전 docs/QUERY100_NEXT_BATCH_DESIGN_2026-09-29.md 3b-2 (c)). 요청 = airo-request v2 봉투 그대로(질의 입구와 같은 질의자·신원·대상 결정 함수). 도구·플래너·LLM 을 부르지 않는다 — be-3d Lab 장면 경로가 게이트웨이의 대상 결정을 먼저 받아 기본 대상(강남구)을 붙일지 정한다(E14).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    contract: Literal['request-resolution/v1'] = Field(
        ...,
        description='응답 표지 — 클라이언트는 이 글자가 정확히 같을 때만 결정으로 받는다(오류 본문 포함 — 200·422·401·403 모두 같은 글자).',
    )
    question_frame: dict[str, Any] | None = Field(
        ...,
        description='질의 응답 validation.question_frame 과 같은 칸(게이트웨이 question-frame/v1 — contract·subject_kind·places·period·strategies … + place_resolution). 입구가 틀을 뽑지 못했으면 null.',
    )
    target_context: TargetContextRef = Field(
        ...,
        description='실행 전 대상 = 질의 응답 validation.target_context 와 같은 함수로 만든다. 전국 = kind region · ids [region:kr] · 원형 = kind archetype. 되묻기·거절이면 resolved=false(kind·source null · ids 빈 목록).',
    )
    refusal: Refusal | None = Field(
        None,
        description='결정이 되묻기(PLACE_AMBIGUOUS — 200) 또는 거절(봉투 422 · 신원 401/403/503)이면 EC Refusal 1.1. 결정이 났으면 칸이 없다.',
    )
    period: dict[str, Any] | None = Field(
        None,
        description='덧칸(선택): 봉투 기간(period_window) 또는 입구가 한 번 푼 질문 기간(question_period). 클라이언트는 모르는 칸을 무시한다.',
    )
    place_decision: dict[str, Any] | None = Field(
        None,
        description='덧칸(선택): 지명 해석 결과(code·places·ambiguous·candidates·why — 게이트웨이 place_resolution 어댑터 모양).',
    )
    stage: Literal['pre_execution'] = Field(
        'pre_execution',
        description='덧칸(선택): 이 대상은 실행 전 대상이다 — 연쇄(chain_step)로 최종 대상이 바뀌는 질문은 질의 응답의 대상과 다를 수 있다.',
    )
    errors: list[str] | None = Field(
        None,
        description='덧칸(선택): 봉투 오류의 검사 메시지(airo-request/v2 422 의 errors 와 같은 것).',
        max_length=5,
    )
