# generated by datamodel-codegen:
#   filename:  judgement_thresholds.json
#   timestamp: 2026-09-28T08:49:37+00:00

from __future__ import annotations

from pydantic import BaseModel


class JudgementThresholds(BaseModel):
    """
    판정 문턱 정본(2026-09-28 일반화 G1). '이상'·'의미 있는 절감'·쾌적·설정온도 준수·자료 타당 범위의 문턱을 개념별로 이름 붙여 한 곳에 둔다. 같은 낱말에 문턱이 여럿이던 자리(이상 z3·z2·IQR1.5, 절감 3%·0.5%·5%)는 값을 지우지 않고 맥락 이름으로 가른다 — 답에는 어느 맥락의 문턱인지 싣는다. classification 이 assumed 인 값은 합의된 운영 기준이 아니다.
    """
