# generated by datamodel-codegen:
#   filename:  korean_building_standards.json
#   timestamp: 2026-09-17T04:14:22+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class KoreanBuildingStandardsLawSourced(BaseModel):
    """
    한국 건축 기준값 정본 — 외피 열관류율 상한·법정 기후지역·필요환기량·인증 평가 조건·설계용 실내 온습도·용도프로필. v1.0 (2026-09-17): 모든 값은 law.go.kr 현행 원문(시행일·별표·조회일·파일 sha256)에 묶인다. 원문 파일 = docs/legal_sources/<조회일>/. 전사는 scripts/verify_korean_law_sources.py 가 원문 텍스트로 대조한다. ⚠ 조회일·해시는 현행성 증명이 아니라 확인 이력이다 — currency.recheck_after_days 가 지나면 소비 코드는 '현행 법령' 실행을 거부한다. 법령값과 모델링 가정(소비 repo 의 modeling_policies)은 섞지 않는다. PE 계수 정본은 energy_constants.pe_factors — 여기는 원문 대조 기록만.
    """

    currency: dict[str, Any] | None = None
    sources: dict[str, Any] | None = None
    envelope_u_limits: dict[str, Any] | None = None
    climate_zones: dict[str, Any] | None = None
    ventilation: dict[str, Any] | None = None
    assessment_conditions: dict[str, Any] | None = None
    design_indoor_conditions: dict[str, Any] | None = None
    usage_profiles: dict[str, Any] | None = None
    primary_energy_factor_check: dict[str, Any] | None = None
    envelope_surface_rules: dict[str, Any] | None = None
    surface_resistances: dict[str, Any] | None = None
    air_layer_resistances: dict[str, Any] | None = None
    calculation_rules: dict[str, Any] | None = None
