# generated by datamodel-codegen:
#   filename:  legacy_ems_code_mapping.json
#   timestamp: 2026-10-10T12:52:05+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class Ssot(BaseModel):
    schema_ref: Literal['energy-contracts/ems_strategies.json#$defs/StrategyCode'] = (
        Field(..., description='정본 enum SSOT 위치')
    )
    strategy_code_regex: Literal['^M(0[0-9]|1[0-9]|[2-9][0-9])$'] = Field(
        ...,
        description='M00~M20 정확 매칭 (valid set = SSOT; M16~M20 = DR control-plane). lint hook 가 본 정규식 강제. M21+ 신설 시 본 패턴 + ems_strategies.json + 본 schema 동시 갱신 (ADR-EMS-NAMESPACE-P6).',
    )
    valid_count: Literal[23]


class DeprecatedECodes(BaseModel):
    """
    구 E0~E13 코드 → M-code. **E→M 의 유일한 정본**(ems_strategies.json 의 gcs_e_codes 는 이 표의 생성 투영). 번호 체계 = 2026-05-03 fix_gcs_ems_codes.py 리매핑 이후의 통합 metadata 번호(ems_transformer/scripts/unify_phase_data.py STRATEGY_TO_EMS · reverse/configs/data_spec.yaml e_to_m · RVK build_rvk_metadata.py 가 쓰는 번호). GCS 생성기(generate_ems_idfs.py) 의 원래 번호 뜻은 gcs_generator_codes 에 따로 적는다 — 둘을 한 표에 섞으면 E5·E6·E8 이 틀린다. components = 이 코드가 켜는 M 전략 전부(뜻의 정본). maps_to = 대표 M-code 하나: components 와 같은 전략이 있으면 그것(exact=true), 없으면 components 를 모두 포함하는 가장 작은 M00~M15 전략(exact=false, 과대 표기이니 뜻은 components 로 읽는다). 규칙 검사 = validate_ssot.check_legacy_code_consistency. 신규 코드 작성 금지.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    E0: Any | None = None
    E1: Any | None = None
    E2: Any | None = None
    E3: Any | None = None
    E4: Any | None = None
    E5: Any | None = None
    E6: Any | None = None
    E7: Any | None = None
    E8: Any | None = None
    E9: Any | None = None
    E10: Any | None = None
    E11: Any | None = None
    E12: Any | None = None
    E13: Any | None = None


class DeprecatedSCodes(BaseModel):
    """
    구 src/api/main.py (ems_transformer legacy multi-task transformer) S1~S7 코드. 새 코드 작성 금지. 본 schema 의 매핑은 legacy 호환 reference 만.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    S1: Any | None = Field(None, description='Staging')
    S2: Any | None = Field(None, description='Pre-cooling/Pre-heating')
    S3: Any | None = Field(None, description='Economizer')
    S4: Any | None = Field(None, description='ScheduleOpt')
    S5: Any | None = Field(None, description='Baseline (Night Setback 내장)')
    S6_strict: Any | None = Field(None, description='PMV ±0.5')
    S6_relaxed: Any | None = Field(None, description='PMV ±0.7')
    S7: Any | None = Field(None, description='DemandResponse')


class DeprecatedQLegacy(BaseModel):
    """
    구 src/api/main.py 의 Q1~Q7 query type 코드 (정책 코드와는 다른 layer). 현행 Q1~Q17 (gateway_routing.json#qa_types) 와 namespace 분리. debate 이후 Q18~Qn 확장은 future_debate namespace.
    """

    Q_REGEX_LEGACY: Literal['^Q[1-7]$'] = Field(
        '^Q[1-7]$', description='src/api/main.py 한정'
    )
    Q_REGEX_CURRENT: Literal['^Q(1[0-7]|[1-9])$'] = Field(
        '^Q(1[0-7]|[1-9])$', description='gateway_routing.json#qa_types Q1~Q17'
    )
    Q_NAMESPACE_FUTURE_DEBATE: Literal['Q\\d{2,}_debate_v\\d+'] = Field(
        'Q\\d{2,}_debate_v\\d+', description='debate 이후 확장 (예: Q18_debate_v1)'
    )


class ForbiddenPattern(BaseModel):
    pattern: str
    scope: str
    exception: list[str]


class DriftGuard(BaseModel):
    """
    drift 재발 차단 메타. Phase 2 의 lint hook + auto-add 스크립트가 본 메타 참조.
    """

    forbidden_patterns: list[ForbiddenPattern] = Field(
        [
            {
                'pattern': '(?<![A-Za-z_])E\\d{1,2}(?![A-Za-z0-9_])',
                'scope': 'all *.py / *.jsonl / *.yaml / *.md / *.sql',
                'exception': [
                    'docs/EMS_CODE_MAPPING.md (transitional ledger)',
                    'docs/NAMING_UNIFICATION.md (deprecated 표)',
                    'docs/specs/SPEC_POLICY_VECTOR.md (hallucination 예시 의도)',
                    'docs/DRIFT_INVENTORY.md (본 drift 보고서)',
                    'scripts/lint_ems_code_drift.py (lint 도구 자체)',
                    'scripts/add_ems_code.py',
                    'scripts/verify_ems_code_consistency.py',
                    'scripts/verify_no_e_codes.py',
                    'scripts/migrate_metadata_e_to_m.py',
                    'scripts/promote_model.py',
                    'tests/fixtures/debate_hallucinations.jsonl (의도된 fuzz hallucination corpus)',
                    'tests/test_e_to_m_drift_lint.py',
                    'tests/test_debate_fuzz.py',
                    'schemas/legacy_ems_code_mapping.json (본 SSOT)',
                    'data/unified/metadata_unified.jsonl.bak_',
                    'archive/',
                    'scripts/eval_v2/07_inference_v2_train_prompt.py (Phase A inference 도구 — v2.4 legacy E-code label dict 참조 평가용, 학습 본체 아님)',
                    'eval_v2.0/sets_30k/ (평가셋 30K stratified — query 안 우연 E-code 노이즈, 학습 데이터 아님)',
                ],
            },
            {
                'pattern': '(?<![A-Za-z_])S[1-7](?![A-Za-z0-9_])',
                'scope': 'all *.py / *.jsonl / *.yaml / *.md',
                'exception': [
                    'docs/specs/SPEC_EMS_STRATEGIES.md (legacy 표 잔존, 정정 PR 대기)',
                    'docs/specs/SPEC_POLICY_VECTOR.md (hallucination 예시 의도)',
                    'docs/DRIFT_INVENTORY.md',
                    'docs/NAMING_UNIFICATION.md (deprecated 표)',
                    'CLAUDE.md (MODEL_SWAP 디커플링 seam S1~S4 = refactor-seam 네임스페이스, EMS S-code 아님)',
                    'scripts/lint_ems_code_drift.py',
                    'scripts/add_ems_code.py',
                    'scripts/verify_ems_code_consistency.py',
                    'scripts/verify_no_e_codes.py',
                    'scripts/promote_model.py',
                    'tests/fixtures/debate_hallucinations.jsonl',
                    'tests/test_e_to_m_drift_lint.py',
                    'tests/test_debate_fuzz.py',
                    'schemas/legacy_ems_code_mapping.json',
                    'archive/',
                ],
            },
            {
                'pattern': '(?<![A-Za-z_])M(2[1-9]|[3-9]\\d)(?![A-Za-z0-9_])',
                'scope': 'all',
                'exception': [
                    'docs/specs/SPEC_POLICY_VECTOR.md (hallucination 예시 의도)',
                    'docs/adr/ADR-EMS-NAMESPACE-P6-F14-DR-CODES.md (M21+ 경계 결정 문서)',
                    'docs/DRIFT_INVENTORY.md',
                    'scripts/lint_ems_code_drift.py',
                    'scripts/add_ems_code.py (auto-add 스크립트 자체)',
                    'scripts/verify_ems_code_consistency.py',
                    'scripts/verify_no_e_codes.py',
                    'tests/fixtures/debate_hallucinations.jsonl',
                    'tests/test_e_to_m_drift_lint.py',
                    'tests/test_debate_fuzz.py',
                    'tests/contract/test_f14_contract.py',
                    'schemas/ems_strategies.json (auto-add 가 갱신할 SSOT)',
                    'schemas/legacy_ems_code_mapping.json',
                ],
            },
        ],
        description='신규 commit 차단 정규식. lint hook 가 staged 파일에 대해 본 패턴 매치 시 commit reject.',
        validate_default=True,
    )
    lint_hook: Literal['scripts/lint_ems_code_drift.py'] = Field(
        ...,
        description='Phase 2.2 산출. pre-commit hook + CI lint. forbidden_patterns 위반 시 reject.',
    )
    auto_add_script: Literal['scripts/add_ems_code.py'] = Field(
        ...,
        description='Phase 2.3 산출. M16 등 신규 EMS 추가 시 6 위치 자동 갱신 (ems_strategies.json + legacy_ems_code_mapping.json + gateway_routing.json + SPEC_EMS_STRATEGIES.md + EMS_CODE_MAPPING.md + generate_qa_unified.py).',
    )
    ssot_locations: list[str] = Field(
        [
            'projects/energy-contracts/energy_contracts/schemas/ems_strategies.json',
            'projects/energy-contracts/energy_contracts/schemas/legacy_ems_code_mapping.json',
            'projects/energy-contracts/energy_contracts/schemas/gateway_routing.json',
            '8.simulation/docs/NAMING_UNIFICATION.md',
            '8.simulation/ems_transformer/docs/specs/SPEC_EMS_STRATEGIES.md',
            '8.simulation/ems_transformer/docs/EMS_CODE_MAPPING.md',
        ],
        description='M00~M20 코드가 정의·참조되는 6 위치. 변경 시 모두 동기 갱신 의무.',
    )
    e_code_emitters: list[Any] | None = Field(
        [
            {
                'path': '8.simulation/reverse/configs/data_spec.yaml',
                'labels': 'ems.e_labels',
                'mapping': 'ems.e_to_m',
                'emitter': 'reverse Module B (/v1/ems/recommend → canvas 순위 카드)',
            }
        ],
        description='E-code 를 **내보내는** 파이프라인의 선언 위치(워크스페이스 상대). validate_ssot.check_e_code_emitter_coverage 가 labels 의 모든 코드가 deprecated_e_codes 에 있고 mapping 이 components 와 같은지 대조한다(형제 저장소가 없으면 건너뛴다).',
    )


class LegacyEmsCodeMapping(BaseModel):
    """
    EMS 전략 코드 SSOT = M00~M20 (ems_strategies.json#StrategyCode). 구 E0~E13, S1~S7 코드는 deprecated. 본 schema 는 deprecated 코드의 M-code 매핑 + drift 차단 메타 (정규식 / lint hook / auto-add 스크립트 참조) 를 단일 진실원으로 보유한다.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    ssot: Ssot
    deprecated_e_codes: DeprecatedECodes = Field(
        ...,
        description='구 E0~E13 코드 → M-code. **E→M 의 유일한 정본**(ems_strategies.json 의 gcs_e_codes 는 이 표의 생성 투영). 번호 체계 = 2026-05-03 fix_gcs_ems_codes.py 리매핑 이후의 통합 metadata 번호(ems_transformer/scripts/unify_phase_data.py STRATEGY_TO_EMS · reverse/configs/data_spec.yaml e_to_m · RVK build_rvk_metadata.py 가 쓰는 번호). GCS 생성기(generate_ems_idfs.py) 의 원래 번호 뜻은 gcs_generator_codes 에 따로 적는다 — 둘을 한 표에 섞으면 E5·E6·E8 이 틀린다. components = 이 코드가 켜는 M 전략 전부(뜻의 정본). maps_to = 대표 M-code 하나: components 와 같은 전략이 있으면 그것(exact=true), 없으면 components 를 모두 포함하는 가장 작은 M00~M15 전략(exact=false, 과대 표기이니 뜻은 components 로 읽는다). 규칙 검사 = validate_ssot.check_legacy_code_consistency. 신규 코드 작성 금지.',
    )
    gcs_generator_codes: dict[str, Any] | None = Field(
        {
            'meaning': {
                'E5': 'DemandLimiting (generate_ems_idfs.py:876)',
                'E6': 'PMV 0.5 (apply_pmv 위임, :1190)',
                'E7': 'PMV 0.7 (apply_pmv 위임, :1194)',
                'E8': 'Economizer + Staging (:1201)',
                'E9': 'Economizer + Staging + PMV 0.5 (:1213)',
                'E10': 'Economizer + Staging + PMV 0.7 (:1220)',
                'E11': 'Economizer + DemandLimiting (:1227)',
            },
            'remap_2026_05_03': {'E6': 'E7', 'E7': 'E12', 'E8': 'E10', 'E9': 'E11'},
            'unresolved': '생성기 E10(PMV 0.7 포함) 은 리매핑 대상이 아니었다. gcp 출처 E10 행이 리매핑분보다 65,640행 많다 — 그 행이 생성기 E10 이면 통합 번호로는 E13 이어야 한다. 원천 GCS 산출물로 확인 전까지 판정 보류.',
        },
        description='GCS 생성기(ems_transformer/scripts/generate_ems_idfs.py) 가 붙인 **원래 번호**의 뜻 — 기록 전용, E→M 조회에 쓰지 않는다. 번호는 deprecated_e_codes 와 겹치지만 뜻이 다르다. 2026-05-03 fix_gcs_ems_codes.py 가 metadata 를 remap 대로 옮겼다.',
    )
    deprecated_s_codes: DeprecatedSCodes = Field(
        ...,
        description='구 src/api/main.py (ems_transformer legacy multi-task transformer) S1~S7 코드. 새 코드 작성 금지. 본 schema 의 매핑은 legacy 호환 reference 만.',
    )
    deprecated_q_legacy: DeprecatedQLegacy = Field(
        ...,
        description='구 src/api/main.py 의 Q1~Q7 query type 코드 (정책 코드와는 다른 layer). 현행 Q1~Q17 (gateway_routing.json#qa_types) 와 namespace 분리. debate 이후 Q18~Qn 확장은 future_debate namespace.',
    )
    drift_guard: DriftGuard = Field(
        ...,
        description='drift 재발 차단 메타. Phase 2 의 lint hook + auto-add 스크립트가 본 메타 참조.',
    )
    ems_simulation_codes: dict[str, Any] | None = Field(
        {
            'producer': '8.simulation/ems_simulation/scripts/generate_comprehensive_csv.py + generate_idf.py',
            'csv': '8.simulation/building_ai/input/ems_simulation/10city_comprehensive_v3.csv',
            'baseline': 'baseline = autosize 기준(EMS 전략 아님 — 코드 없음)',
            'by_building': {
                'LO': {
                    'm0': {
                        'components': ['M06'],
                        'maps_to': 'M06',
                        'exact': True,
                        'basis': 'generate_idf.py:633~636 m0 = NightCycle 만 추가(BASELINE = M0 - NightCycle)',
                    },
                    'm1': {
                        'components': ['M01'],
                        'maps_to': 'M01',
                        'exact': True,
                        'basis': 'generate_idf.py 전략 라우팅(:633~)',
                    },
                    'm2': {
                        'components': ['M02'],
                        'maps_to': 'M02',
                        'exact': True,
                        'basis': 'generate_idf.py 전략 라우팅(:633~)',
                    },
                    'm3': {
                        'components': ['M03'],
                        'maps_to': 'M03',
                        'exact': True,
                        'basis': 'generate_idf.py 전략 라우팅(:633~)',
                    },
                    'm4': {
                        'components': ['M04'],
                        'maps_to': 'M04',
                        'exact': True,
                        'basis': 'generate_idf.py 전략 라우팅(:633~)',
                    },
                    'm5': {
                        'components': ['M05'],
                        'maps_to': 'M05',
                        'exact': True,
                        'basis': 'generate_idf.py 전략 라우팅(:633~)',
                    },
                    'm6': {
                        'components': ['M02', 'M03'],
                        'maps_to': 'M11',
                        'exact': False,
                        'basis': 'generate_idf.py:757·772·806 m6~m8 = M2+M3(+M4/M5), M1 제외 · :1030 _use_standard_schedule 이 m2~m10 을 먼저 잡아 :1136 M1 AvailMgr 분기는 m6~m8 에 닿지 않음(2026-05-19 IDF 서울 LO m6·m8 M1_OptimalStart_AvailMgr 0건)',
                    },
                    'm7': {
                        'components': ['M02', 'M03', 'M04'],
                        'maps_to': 'M12',
                        'exact': False,
                        'basis': 'generate_idf.py:757·772·806 m6~m8 = M2+M3(+M4/M5), M1 제외 · :1030 _use_standard_schedule 이 m2~m10 을 먼저 잡아 :1136 M1 AvailMgr 분기는 m6~m8 에 닿지 않음(2026-05-19 IDF 서울 LO m6·m8 M1_OptimalStart_AvailMgr 0건)',
                    },
                    'm8': {
                        'components': ['M02', 'M03', 'M05'],
                        'maps_to': 'M13',
                        'exact': False,
                        'basis': 'generate_idf.py:757·772·806 m6~m8 = M2+M3(+M4/M5), M1 제외 · :1030 _use_standard_schedule 이 m2~m10 을 먼저 잡아 :1136 M1 AvailMgr 분기는 m6~m8 에 닿지 않음(2026-05-19 IDF 서울 LO m6·m8 M1_OptimalStart_AvailMgr 0건)',
                    },
                },
                'MO': {
                    'm0': {
                        'components': ['M06'],
                        'maps_to': 'M06',
                        'exact': True,
                        'basis': 'generate_idf.py:633~636 m0 = NightCycle 만 추가(BASELINE = M0 - NightCycle)',
                    },
                    'm4': {
                        'components': ['M04'],
                        'maps_to': 'M04',
                        'exact': True,
                        'basis': 'generate_idf.py 전략 라우팅(:633~)',
                    },
                    'm5': {
                        'components': ['M05'],
                        'maps_to': 'M05',
                        'exact': True,
                        'basis': 'generate_idf.py 전략 라우팅(:633~)',
                    },
                },
                'SO': {
                    'm2': {
                        'components': ['M02'],
                        'maps_to': 'M02',
                        'exact': True,
                        'basis': 'generate_idf.py 전략 라우팅(:633~)',
                    },
                    'm4': {
                        'components': ['M04'],
                        'maps_to': 'M04',
                        'exact': True,
                        'basis': 'generate_idf.py 전략 라우팅(:633~)',
                    },
                    'm5': {
                        'components': ['M05'],
                        'maps_to': 'M05',
                        'exact': True,
                        'basis': 'generate_idf.py 전략 라우팅(:633~)',
                    },
                    'm6': {
                        'components': ['M02'],
                        'maps_to': 'M02',
                        'exact': True,
                        'basis': 'generate_idf.py:563~584 PSZ(small_office·standalone_retail) 재정의 M6=M2·M7=M2+M4·M8=M2+M5 · CSV 서울 m6 = m2(SO 7.47·SR -0.35)',
                    },
                    'm7': {
                        'components': ['M02', 'M04'],
                        'maps_to': 'M12',
                        'exact': False,
                        'basis': 'generate_idf.py:563~584 PSZ(small_office·standalone_retail) 재정의 M6=M2·M7=M2+M4·M8=M2+M5 · CSV 서울 m6 = m2(SO 7.47·SR -0.35)',
                    },
                    'm8': {
                        'components': ['M02', 'M05'],
                        'maps_to': 'M13',
                        'exact': False,
                        'basis': 'generate_idf.py:563~584 PSZ(small_office·standalone_retail) 재정의 M6=M2·M7=M2+M4·M8=M2+M5 · CSV 서울 m6 = m2(SO 7.47·SR -0.35)',
                    },
                },
                'SR': {
                    'm2': {
                        'components': ['M02'],
                        'maps_to': 'M02',
                        'exact': True,
                        'basis': 'generate_idf.py 전략 라우팅(:633~)',
                    },
                    'm4': {
                        'components': ['M04'],
                        'maps_to': 'M04',
                        'exact': True,
                        'basis': 'generate_idf.py 전략 라우팅(:633~)',
                    },
                    'm5': {
                        'components': ['M05'],
                        'maps_to': 'M05',
                        'exact': True,
                        'basis': 'generate_idf.py 전략 라우팅(:633~)',
                    },
                    'm6': {
                        'components': ['M02'],
                        'maps_to': 'M02',
                        'exact': True,
                        'basis': 'generate_idf.py:563~584 PSZ(small_office·standalone_retail) 재정의 M6=M2·M7=M2+M4·M8=M2+M5 · CSV 서울 m6 = m2(SO 7.47·SR -0.35)',
                    },
                    'm7': {
                        'components': ['M02', 'M04'],
                        'maps_to': 'M12',
                        'exact': False,
                        'basis': 'generate_idf.py:563~584 PSZ(small_office·standalone_retail) 재정의 M6=M2·M7=M2+M4·M8=M2+M5 · CSV 서울 m6 = m2(SO 7.47·SR -0.35)',
                    },
                    'm8': {
                        'components': ['M02', 'M05'],
                        'maps_to': 'M13',
                        'exact': False,
                        'basis': 'generate_idf.py:563~584 PSZ(small_office·standalone_retail) 재정의 M6=M2·M7=M2+M4·M8=M2+M5 · CSV 서울 m6 = m2(SO 7.47·SR -0.35)',
                    },
                },
                'PS': {
                    'm0': {
                        'components': ['M06'],
                        'maps_to': 'M06',
                        'exact': True,
                        'basis': 'generate_idf.py:633~636 m0 = NightCycle 만 추가(BASELINE = M0 - NightCycle)',
                    },
                    'm2': {
                        'components': ['M02'],
                        'maps_to': 'M02',
                        'exact': True,
                        'basis': 'generate_idf.py 전략 라우팅(:633~)',
                    },
                    'm3': {
                        'components': [],
                        'maps_to': None,
                        'exact': False,
                        'basis': 'PS m3 = 대수 제어 미적용(위 조건) — 표준 가용 스케줄만 바뀜 · CSV 서울 saving 0.19%',
                    },
                    'm4': {
                        'components': ['M04'],
                        'maps_to': 'M04',
                        'exact': True,
                        'basis': 'generate_idf.py 전략 라우팅(:633~)',
                    },
                    'm5': {
                        'components': ['M05'],
                        'maps_to': 'M05',
                        'exact': True,
                        'basis': 'generate_idf.py 전략 라우팅(:633~)',
                    },
                    'm6': {
                        'components': ['M02'],
                        'maps_to': 'M02',
                        'exact': True,
                        'basis': 'PS 는 :915 Chiller Staging 보존 조건(_check_equipment_for_strategy 대수 제어 검사, :1793 CoolSys1 Chiller 요구)을 못 넘어 대수 제어가 빠짐 · 2026-05-19 IDF PlantPump_EMS_Program 호출 0 · CSV 서울 m6 = m2 = 2.65',
                    },
                    'm7': {
                        'components': ['M02', 'M04'],
                        'maps_to': 'M12',
                        'exact': False,
                        'basis': 'PS 는 :915 Chiller Staging 보존 조건(_check_equipment_for_strategy 대수 제어 검사, :1793 CoolSys1 Chiller 요구)을 못 넘어 대수 제어가 빠짐 · 2026-05-19 IDF PlantPump_EMS_Program 호출 0 · CSV 서울 m6 = m2 = 2.65',
                    },
                    'm8': {
                        'components': ['M02', 'M05'],
                        'maps_to': 'M13',
                        'exact': False,
                        'basis': 'PS 는 :915 Chiller Staging 보존 조건(_check_equipment_for_strategy 대수 제어 검사, :1793 CoolSys1 Chiller 요구)을 못 넘어 대수 제어가 빠짐 · 2026-05-19 IDF PlantPump_EMS_Program 호출 0 · CSV 서울 m6 = m2 = 2.65',
                    },
                },
            },
        },
        description='ems_simulation 10city_comprehensive_v3.csv(building_ai 전략 표) 의 raw 전략 코드 m0~m8 → 실제 적용 M 전략. 키 = 건물(CSV 약어) → raw code. components = 그 건물 IDF 에 실제로 켜진 전략(뜻의 정본) · maps_to/exact = deprecated_e_codes 와 같은 규칙(legacy_e_codes.expected_maps_to)으로 산출 · 적용 안 된 경우 components=[]·maps_to=null. ⛔ 0 채움(m8→M08) 금지 — m6~m8 은 복합 전략이다. ⚠ ems_strategies.json#default.legacy_mapping.ems_simulation(M0→M00, M1→M06…)은 이 생산자와 다르다(2026-10-10 R095) — 이 칸이 정본. ⚠ CSV 판(2026-04-10)과 근거 IDF 판(2026-05-19)의 동일성은 미확인.',
    )
