# generated by datamodel-codegen:
#   filename:  legacy_ems_code_mapping.json
#   timestamp: 2026-06-30T02:33:03+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class Ssot(BaseModel):
    schema_ref: Literal['energy-contracts/ems_strategies.json#$defs/StrategyCode'] = (
        Field(..., description='정본 enum SSOT 위치')
    )
    strategy_code_regex: Literal['^M(0[0-9]|1[0-9]|20)$'] = Field(
        ...,
        description='M00~M20 정확 매칭 (valid set = SSOT; M16~M20 = DR control-plane). lint hook 가 본 정규식 강제. M21+ 신설 시 본 패턴 + ems_strategies.json + 본 schema 동시 갱신 (ADR-EMS-NAMESPACE-P6).',
    )
    valid_count: Literal[21]


class DeprecatedECodes(BaseModel):
    """
    구 generate_ems_idfs.py (GCS) E0~E13 코드. 2026-05-03 함수명↔구현 drift 정정. 신규 코드 작성 금지. 잔존 데이터 발견 시 정정 PR.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    E0: Any | None = None
    E1: Any | None = None
    E2: Any | None = None
    E3: Any | None = None
    E4: Any | None = None
    E5: Any | None = None
    E6: Any | None = None
    E7: Any | None = None
    E8: Any | None = None
    E9: Any | None = None
    E10: Any | None = None
    E11: Any | None = None
    E12: Any | None = None
    E13: Any | None = None


class DeprecatedSCodes(BaseModel):
    """
    구 src/api/main.py (ems_transformer legacy multi-task transformer) S1~S7 코드. 새 코드 작성 금지. 본 schema 의 매핑은 legacy 호환 reference 만.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    S1: Any | None = Field(None, description='Staging')
    S2: Any | None = Field(None, description='Pre-cooling/Pre-heating')
    S3: Any | None = Field(None, description='Economizer')
    S4: Any | None = Field(None, description='ScheduleOpt')
    S5: Any | None = Field(None, description='Baseline (Night Setback 내장)')
    S6_strict: Any | None = Field(None, description='PMV ±0.5')
    S6_relaxed: Any | None = Field(None, description='PMV ±0.7')
    S7: Any | None = Field(None, description='DemandResponse')


class DeprecatedQLegacy(BaseModel):
    """
    구 src/api/main.py 의 Q1~Q7 query type 코드 (정책 코드와는 다른 layer). 현행 Q1~Q17 (gateway_routing.json#qa_types) 와 namespace 분리. debate 이후 Q18~Qn 확장은 future_debate namespace.
    """

    Q_REGEX_LEGACY: Literal['^Q[1-7]$'] = Field(
        '^Q[1-7]$', description='src/api/main.py 한정'
    )
    Q_REGEX_CURRENT: Literal['^Q(1[0-7]|[1-9])$'] = Field(
        '^Q(1[0-7]|[1-9])$', description='gateway_routing.json#qa_types Q1~Q17'
    )
    Q_NAMESPACE_FUTURE_DEBATE: Literal['Q\\d{2,}_debate_v\\d+'] = Field(
        'Q\\d{2,}_debate_v\\d+', description='debate 이후 확장 (예: Q18_debate_v1)'
    )


class ForbiddenPattern(BaseModel):
    pattern: str
    scope: str
    exception: list[str]


class DriftGuard(BaseModel):
    """
    drift 재발 차단 메타. Phase 2 의 lint hook + auto-add 스크립트가 본 메타 참조.
    """

    forbidden_patterns: list[ForbiddenPattern] = Field(
        [
            {
                'pattern': '(?<![A-Za-z_])E\\d{1,2}(?![A-Za-z0-9_])',
                'scope': 'all *.py / *.jsonl / *.yaml / *.md / *.sql',
                'exception': [
                    'docs/EMS_CODE_MAPPING.md (transitional ledger)',
                    'docs/NAMING_UNIFICATION.md (deprecated 표)',
                    'docs/specs/SPEC_POLICY_VECTOR.md (hallucination 예시 의도)',
                    'docs/DRIFT_INVENTORY.md (본 drift 보고서)',
                    'scripts/lint_ems_code_drift.py (lint 도구 자체)',
                    'scripts/add_ems_code.py',
                    'scripts/verify_ems_code_consistency.py',
                    'scripts/verify_no_e_codes.py',
                    'scripts/migrate_metadata_e_to_m.py',
                    'scripts/promote_model.py',
                    'tests/fixtures/debate_hallucinations.jsonl (의도된 fuzz hallucination corpus)',
                    'tests/test_e_to_m_drift_lint.py',
                    'tests/test_debate_fuzz.py',
                    'schemas/legacy_ems_code_mapping.json (본 SSOT)',
                    'data/unified/metadata_unified.jsonl.bak_',
                    'archive/',
                    'scripts/eval_v2/07_inference_v2_train_prompt.py (Phase A inference 도구 — v2.4 legacy E-code label dict 참조 평가용, 학습 본체 아님)',
                    'eval_v2.0/sets_30k/ (평가셋 30K stratified — query 안 우연 E-code 노이즈, 학습 데이터 아님)',
                ],
            },
            {
                'pattern': '(?<![A-Za-z_])S[1-7](?![A-Za-z0-9_])',
                'scope': 'all *.py / *.jsonl / *.yaml / *.md',
                'exception': [
                    'docs/specs/SPEC_EMS_STRATEGIES.md (legacy 표 잔존, 정정 PR 대기)',
                    'docs/specs/SPEC_POLICY_VECTOR.md (hallucination 예시 의도)',
                    'docs/DRIFT_INVENTORY.md',
                    'docs/NAMING_UNIFICATION.md (deprecated 표)',
                    'CLAUDE.md (MODEL_SWAP 디커플링 seam S1~S4 = refactor-seam 네임스페이스, EMS S-code 아님)',
                    'scripts/lint_ems_code_drift.py',
                    'scripts/add_ems_code.py',
                    'scripts/verify_ems_code_consistency.py',
                    'scripts/verify_no_e_codes.py',
                    'scripts/promote_model.py',
                    'tests/fixtures/debate_hallucinations.jsonl',
                    'tests/test_e_to_m_drift_lint.py',
                    'tests/test_debate_fuzz.py',
                    'schemas/legacy_ems_code_mapping.json',
                    'archive/',
                ],
            },
            {
                'pattern': '(?<![A-Za-z_])M(2[1-9]|[3-9]\\d)(?![A-Za-z0-9_])',
                'scope': 'all',
                'exception': [
                    'docs/specs/SPEC_POLICY_VECTOR.md (hallucination 예시 의도)',
                    'docs/adr/ADR-EMS-NAMESPACE-P6-F14-DR-CODES.md (M21+ 경계 결정 문서)',
                    'docs/DRIFT_INVENTORY.md',
                    'scripts/lint_ems_code_drift.py',
                    'scripts/add_ems_code.py (auto-add 스크립트 자체)',
                    'scripts/verify_ems_code_consistency.py',
                    'scripts/verify_no_e_codes.py',
                    'tests/fixtures/debate_hallucinations.jsonl',
                    'tests/test_e_to_m_drift_lint.py',
                    'tests/test_debate_fuzz.py',
                    'tests/contract/test_f14_contract.py',
                    'schemas/ems_strategies.json (auto-add 가 갱신할 SSOT)',
                    'schemas/legacy_ems_code_mapping.json',
                ],
            },
        ],
        description='신규 commit 차단 정규식. lint hook 가 staged 파일에 대해 본 패턴 매치 시 commit reject.',
        validate_default=True,
    )
    lint_hook: Literal['scripts/lint_ems_code_drift.py'] = Field(
        ...,
        description='Phase 2.2 산출. pre-commit hook + CI lint. forbidden_patterns 위반 시 reject.',
    )
    auto_add_script: Literal['scripts/add_ems_code.py'] = Field(
        ...,
        description='Phase 2.3 산출. M16 등 신규 EMS 추가 시 6 위치 자동 갱신 (ems_strategies.json + legacy_ems_code_mapping.json + gateway_routing.json + SPEC_EMS_STRATEGIES.md + EMS_CODE_MAPPING.md + generate_qa_unified.py).',
    )
    ssot_locations: list[str] = Field(
        [
            'projects/energy-contracts/energy_contracts/schemas/ems_strategies.json',
            'projects/energy-contracts/energy_contracts/schemas/legacy_ems_code_mapping.json',
            'projects/energy-contracts/energy_contracts/schemas/gateway_routing.json',
            '8.simulation/docs/NAMING_UNIFICATION.md',
            '8.simulation/ems_transformer/docs/specs/SPEC_EMS_STRATEGIES.md',
            '8.simulation/ems_transformer/docs/EMS_CODE_MAPPING.md',
        ],
        description='M00~M20 코드가 정의·참조되는 6 위치. 변경 시 모두 동기 갱신 의무.',
    )


class LegacyEmsCodeMapping(BaseModel):
    """
    EMS 전략 코드 SSOT = M00~M20 (ems_strategies.json#StrategyCode). 구 E0~E13, S1~S7 코드는 deprecated. 본 schema 는 deprecated 코드의 M-code 매핑 + drift 차단 메타 (정규식 / lint hook / auto-add 스크립트 참조) 를 단일 진실원으로 보유한다.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    ssot: Ssot
    deprecated_e_codes: DeprecatedECodes = Field(
        ...,
        description='구 generate_ems_idfs.py (GCS) E0~E13 코드. 2026-05-03 함수명↔구현 drift 정정. 신규 코드 작성 금지. 잔존 데이터 발견 시 정정 PR.',
    )
    deprecated_s_codes: DeprecatedSCodes = Field(
        ...,
        description='구 src/api/main.py (ems_transformer legacy multi-task transformer) S1~S7 코드. 새 코드 작성 금지. 본 schema 의 매핑은 legacy 호환 reference 만.',
    )
    deprecated_q_legacy: DeprecatedQLegacy = Field(
        ...,
        description='구 src/api/main.py 의 Q1~Q7 query type 코드 (정책 코드와는 다른 layer). 현행 Q1~Q17 (gateway_routing.json#qa_types) 와 namespace 분리. debate 이후 Q18~Qn 확장은 future_debate namespace.',
    )
    drift_guard: DriftGuard = Field(
        ...,
        description='drift 재발 차단 메타. Phase 2 의 lint hook + auto-add 스크립트가 본 메타 참조.',
    )
