# generated by datamodel-codegen:
#   filename:  lint_format.json
#   timestamp: 2026-06-30T02:33:05+00:00

from __future__ import annotations

from pydantic import BaseModel


class LintFormatConfigSsotPhaseK18(BaseModel):
    """
    ruff·black·prettier 통일 규칙. 각 프로젝트 pyproject.toml [tool.ruff] 가 본 값을 참조.
    """
