# generated by datamodel-codegen:
#   filename:  logging_format.json
#   timestamp: 2026-06-30T02:33:10+00:00

from __future__ import annotations

from pydantic import BaseModel


class LoggingFormatSsotPhaseK14(BaseModel):
    """
    structlog + OpenTelemetry trace_id 통일 로깅 포맷.
    """
