# generated by datamodel-codegen:
#   filename:  market_prices.json
#   timestamp: 2026-06-30T02:33:16+00:00

from __future__ import annotations

from datetime import date

from pydantic import BaseModel, Field


class Kau(BaseModel):
    """
    KRX 배출권 (K-ETS)
    """

    fallback_krw_per_tco2: float | None = None
    reference_date: date | None = None
    refresh_cycle: str | None = None


class Smp(BaseModel):
    """
    계통한계가격 (System Marginal Price)
    """

    fallback_mainland_krw: float | None = None
    fallback_jeju_krw: float | None = None
    refresh_cycle: str | None = None


class ElectricityTariff(BaseModel):
    """
    한전 일반용(을) 고압A 선택II 여름철 시간대별 단가 (원/kWh). KEPCO 전기요금표 2026.6.1 시행 (시간대 개편: 최대부하 15~21시).
    """

    off_peak: float | None = None
    mid_peak: float | None = None
    peak: float | None = None
    peak_hours: list[int] | None = None
    mid_peak_hours: list[int] | None = None
    off_peak_hours: list[int] | None = None


class Residential(BaseModel):
    """
    공동주택(주택용) 비용→kWh 환산 단가
    """

    electricity_krw: float | None = None
    gas_krw: float | None = None
    district_heat_krw: float | None = None
    hot_water_krw: float | None = None


class UnitPrices(BaseModel):
    """
    에너지 평균 단가 (원/kWh)
    """

    electricity_krw: float | None = None
    gas_krw: float | None = None
    residential: Residential | None = Field(
        None, description='공동주택(주택용) 비용→kWh 환산 단가'
    )


class Renewable(BaseModel):
    """
    신재생에너지 시장가
    """

    rec_unit_price_krw: float | None = None
    rec_weight_building: float | None = None
    ppa_price_krw_per_kwh: float | None = None
    ppa_self_consumption: float | None = None


class MarketPrices(BaseModel):
    """
    시장/정책 기준값 SSOT (폴백가). ENERGY_SSOT.md §4 기반. API 장애 시 사용되는 기본값.
    """

    kau: Kau | None = Field(None, description='KRX 배출권 (K-ETS)')
    smp: Smp | None = Field(None, description='계통한계가격 (System Marginal Price)')
    electricity_tariff: ElectricityTariff | None = Field(
        None,
        description='한전 일반용(을) 고압A 선택II 여름철 시간대별 단가 (원/kWh). KEPCO 전기요금표 2026.6.1 시행 (시간대 개편: 최대부하 15~21시).',
    )
    unit_prices: UnitPrices | None = Field(
        None, description='에너지 평균 단가 (원/kWh)'
    )
    renewable: Renewable | None = Field(None, description='신재생에너지 시장가')
