# generated by datamodel-codegen:
#   filename:  market_prices.json
#   timestamp: 2026-09-11T10:06:38+00:00

from __future__ import annotations

from datetime import date
from typing import Any

from pydantic import BaseModel, Field


class Kau(BaseModel):
    """
    KRX 배출권 (K-ETS)
    """

    fallback_krw_per_tco2: float | None = None
    reference_date: date | None = None
    refresh_cycle: str | None = None


class Smp(BaseModel):
    """
    계통한계가격 (System Marginal Price)
    """

    fallback_mainland_krw: float | None = None
    fallback_jeju_krw: float | None = None
    refresh_cycle: str | None = None


class ElectricityTariff(BaseModel):
    """
    한전 일반용(을) 고압A 선택II 여름철 시간대별 단가 (원/kWh). KEPCO 전기요금표 2026.6.1 시행 (시간대 개편: 최대부하 15~21시).
    """

    off_peak: float | None = None
    mid_peak: float | None = None
    peak: float | None = None
    peak_hours: list[int] | None = None
    mid_peak_hours: list[int] | None = None
    off_peak_hours: list[int] | None = None


class ElectricityTariffByRegion(BaseModel):
    currency: str | None = None
    off_peak: float | None = None
    mid_peak: float | None = None
    peak: float | None = None
    peak_hours: list[int] | None = None


class Residential(BaseModel):
    """
    공동주택(주택용) 비용→kWh 환산 단가
    """

    electricity_krw: float | None = None
    gas_krw: float | None = None
    district_heat_krw: float | None = None
    hot_water_krw: float | None = None


class UnitPrices(BaseModel):
    """
    에너지 평균 단가 (원/kWh) — 2026-09-10 스코프 확정: electricity_krw=일반용 전력량요금 mid-peak(기본요금 제외), gas_krw=서울 도시가스 일반용(영업1) 소매 사용요금(부가세 별도). residential 은 K-apt 관리비→kWh 역산 전용이며 2026 공표 단가와 어긋남(_audit 참조). 신규 계산은 retail_reference_2026 사용.
    """

    electricity_krw: float | None = None
    gas_krw: float | None = None
    residential: Residential | None = Field(
        None, description='공동주택(주택용) 비용→kWh 환산 단가'
    )
    field_scope: dict[str, Any] | None = Field(
        None, alias='_scope', description='각 키의 스코프 단어(인용 시 병기 의무)'
    )
    field_audit: dict[str, Any] | None = Field(
        None, alias='_audit', description='2026-09-10 감사 결과·후속 조치'
    )


class Renewable(BaseModel):
    """
    신재생에너지 시장가
    """

    rec_unit_price_krw: float | None = None
    rec_weight_building: float | None = None
    ppa_price_krw_per_kwh: float | None = None
    ppa_self_consumption: float | None = None


class MarketPrices(BaseModel):
    """
    시장/정책 기준값 SSOT (폴백가). ENERGY_SSOT.md §4 기반. API 장애 시 사용되는 기본값.
    """

    kau: Kau | None = Field(None, description='KRX 배출권 (K-ETS)')
    smp: Smp | None = Field(None, description='계통한계가격 (System Marginal Price)')
    electricity_tariff: ElectricityTariff | None = Field(
        None,
        description='한전 일반용(을) 고압A 선택II 여름철 시간대별 단가 (원/kWh). KEPCO 전기요금표 2026.6.1 시행 (시간대 개편: 최대부하 15~21시).',
    )
    electricity_tariff_by_region: dict[str, ElectricityTariffByRegion] | None = Field(
        None,
        description='리전(국가)별 시간대 전기요금 — 국제 additive. KR 은 상위 electricity_tariff(원/kWh)가 canonical, TW=台電 3단(元/kWh, TWD).',
    )
    unit_prices: UnitPrices | None = Field(
        None,
        description='에너지 평균 단가 (원/kWh) — 2026-09-10 스코프 확정: electricity_krw=일반용 전력량요금 mid-peak(기본요금 제외), gas_krw=서울 도시가스 일반용(영업1) 소매 사용요금(부가세 별도). residential 은 K-apt 관리비→kWh 역산 전용이며 2026 공표 단가와 어긋남(_audit 참조). 신규 계산은 retail_reference_2026 사용.',
    )
    renewable: Renewable | None = Field(None, description='신재생에너지 시장가')
    carbon_fee_by_region: dict[str, dict[str, Any]] | None = Field(
        None,
        description='리전(국가)별 탄소가격 — 국제 additive. KR 은 kau(K-ETS, 원/tCO2)가 canonical. TW=碳費(氣候變遷因應法, TWD/tCO2e, 2025.1.1 발효).',
    )
    retail_reference_2026: dict[str, Any] | None = Field(
        None,
        description='2026 canonical 소매·도매 단가 참조표 (원/kWh, 부가세 별도, 기준일 2026-09-01). 요금 계산·경제성·Query500 financial_assumptions 정본. 스코프 단어 없이 인용 금지.',
    )
    frozen_sets: dict[str, Any] | None = Field(
        None,
        description='재현성 때문에 값을 고정한 세트의 등록부. 신규 계산에 쓰지 않는다. immutable=true 인 값은 변경 금지.',
    )
