# generated by datamodel-codegen:
#   filename:  measure_cost_catalog.json
#   timestamp: 2026-09-11T10:06:39+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, confloat, conint, constr


class Method(BaseModel):
    """
    경제성 계산 기본 파라미터. NPV/SIR/할인회수기간=ISO 15686-5 / ASTM E964·E1121 / NIST BLCC 표준.
    """

    discount_rate_default: confloat(ge=0.0, le=0.2) | None = Field(
        None,
        description='실질 할인율 기본값(민간 3~8%). NIST Handbook 135 공공 실질 ~3%. 순위 좌우 → 근거 명시 의무.',
    )
    non_additive: bool | None = Field(
        None,
        description='비가산성 가드(스펙 §2). true=순차 적용 시 앞 조치가 고갈시킨 잔여 에너지에만 뒤 조치 적용(중복 제거). 독립 합산은 저감 과대평가.',
    )


class Market(BaseModel):
    """
    시장가 — market_prices.json#kau.fallback_krw_per_tco2 (canonical) 인용. 재정의 금지. 변동 큼 → KRX(ets.krx.co.kr) 실시간 재확인.
    """

    ref: Literal['market_prices.json#/default/kau/fallback_krw_per_tco2'] = (
        'market_prices.json#/default/kau/fallback_krw_per_tco2'
    )


class CarbonPriceScenarios(BaseModel):
    """
    탄소가격 3-시나리오(스펙 §5). 편익=ΔkWh×단가 + ΔtCO₂×탄소가격. 시나리오별 조치 순위 뒤집힘 → 민감도 제시.
    """

    market: Market | None = Field(
        None,
        description='시장가 — market_prices.json#kau.fallback_krw_per_tco2 (canonical) 인용. 재정의 금지. 변동 큼 → KRX(ets.krx.co.kr) 실시간 재확인.',
    )
    policy_upside_krw_per_tco2: float | None = Field(
        None,
        description='정책 상승 전망(K-ETS 4기 유상경매 30→50%, 5년 뒤 5만 전망). 신규 reference(estimated).',
    )
    social_cost_krw_per_tco2: float | None = Field(
        None,
        description='사회적 탄소비용(SCC) — 미 EPA 중앙값 $190 ≈ 25만원(할인율 2%). 신규 reference(estimated, 출처 EPA/RFF).',
    )


class MeasureClass(Enum):
    """
    조치 3분류. operational=운영(EMS 제어·커미셔닝, 저CAPEX·즉효) / passive=외피(단열·창호·기밀·차양, 고CAPEX·장수명) / equipment_replacement=설비교체(고효율 열원·조명·전동기).
    """

    operational = 'operational'
    passive = 'passive'
    equipment_replacement = 'equipment_replacement'


class EndUse(Enum):
    """
    절감이 적용되는 용도별 에너지 버킷. 연료(gas/elec) 접미사로 요금·배출계수 매핑.
    """

    heating_gas = 'heating_gas'
    cooling_elec = 'cooling_elec'
    lighting_elec = 'lighting_elec'
    fanpump_elec = 'fanpump_elec'
    plug_elec = 'plug_elec'
    vent_elec = 'vent_elec'


class Confidence(Enum):
    """
    A=권위기관 정량(DOE/ASHRAE/LBNL) / B=업계 다수 수렴 또는 국내 공공기관 공식 단가 / C=단일·마케팅 경향.
    """

    A = 'A'
    B = 'B'
    C = 'C'


class Transferability(Enum):
    """
    policy_evaluation_contract.json#assumptions[].transferability 와 동일 어휘(UI 3색 배지). validated=한국 공공기관 실증·공식 단가 / estimated=간접 역산·보조금 기준 추정 / no_korean_data=한국 실측/공개단가 부재로 국제값 현지화.
    """

    validated = 'validated'
    estimated = 'estimated'
    no_korean_data = 'no_korean_data'


class FuelSwitch(BaseModel):
    """
    연료전환 조치(히트펌프 등) — 가스 제거 + 전기 추가. 없으면 순수 절감.
    """

    elec_add_from: EndUse = Field(
        ..., description='전기로 대체되는 용도(예: heating_gas).'
    )
    cop: confloat(ge=1.0) = Field(..., description='대체 설비 성능계수(히트펌프 COP).')
    source_efficiency: confloat(ge=0.0, le=1.0) = Field(
        ..., description='기존 설비 효율(보일러 열효율).'
    )


class Measures(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='조치 한글 식별명.')
    measure_class: MeasureClass
    measure_ref: str | None = Field(
        None,
        description="원 네임스페이스 참조 — 'policy_measures:ENV01' / 'ems:M06' / 'equipment:led'.",
    )
    savings_by_enduse: dict[EndUse, confloat(ge=0.0, le=1.0)] = Field(
        ...,
        description='용도별 절감 분율(deemed, 0~1). 예: {"cooling_elec": 0.35}. 다용도 조치는 복수 키.',
    )
    fuel_switch: FuelSwitch | None = Field(
        None,
        description='연료전환 조치(히트펌프 등) — 가스 제거 + 전기 추가. 없으면 순수 절감.',
    )
    capex_krw_per_m2: confloat(ge=0.0) = Field(
        ...,
        description='연면적당 초기 투자비(원/m²). ⚠ 대부분 국제값 현지화 추정(capex_confidence 참조).',
    )
    lifetime_yr: conint(ge=1) = Field(
        ..., description='조치 수명(년) — NPV/할인회수 분석기간.'
    )
    simple_payback_yr_ref: str | None = Field(
        None, description='조사 관측 회수기간 범위(참조용, 계산값 아님).'
    )
    savings_confidence: Confidence
    capex_confidence: Confidence
    transferability: Transferability
    source: str = Field(
        ..., description='근거 출처(DOE/LBNL/ASHRAE/KEA/그린리모델링 등).'
    )
    note: str | None = Field(None, description='가정·함정 메모.')


class MeasureCostCatalogMacc(BaseModel):
    """
    조치별 깜냥절감(deemed savings) + 단위 CAPEX + 수명 SSOT. 운영(EMS)·패시브(외피)·설비교체를 '돈'으로 비교(한계저감비용곡선 MACC)하기 위한 근거 데이터. Spec source = 공모전/2026-04-24_AI챔피언_전국민AI경진대회/docs/MEASURE_ECONOMICS_SPEC.md (2026-07-12). sibling policy_measures.json#$defs.MeasureCode(자본·설계 조치 8종, 공학 기여분) + ems_strategies.json#StrategyCode(운영 M00~M20)에 '비용 축'을 additive 로 얹는다 — measure_ref 로 두 네임스페이스를 참조. 탄소가격·요금·배출계수는 재정의하지 않고 market_prices.json(kau/unit_prices) + emission_factors.json(0.4173) 을 인용한다(ssot-canonical-compliance). ⚠ deemed 절감률=조사 근거(신뢰도 A~C), CAPEX 단위단가=국제값 현지화 추정(한국 공개 단가표 부재=no_korean_data). 실측/E+ 정밀화 시 상위호환 교체.
    """

    method: Method | None = Field(
        None,
        description='경제성 계산 기본 파라미터. NPV/SIR/할인회수기간=ISO 15686-5 / ASTM E964·E1121 / NIST BLCC 표준.',
    )
    carbon_price_scenarios: CarbonPriceScenarios | None = Field(
        None,
        description='탄소가격 3-시나리오(스펙 §5). 편익=ΔkWh×단가 + ΔtCO₂×탄소가격. 시나리오별 조치 순위 뒤집힘 → 민감도 제시.',
    )
    measures: dict[constr(pattern=r'^[A-Z][A-Z0-9_]{1,15}$'), Measures] = Field(
        ...,
        description='조치 경제성 카탈로그. 키=조치 코드(경제-축, 대문자). measure_ref 로 policy_measures/ems_strategies/equipment 네임스페이스 참조.',
    )
