# generated by datamodel-codegen:
#   filename:  model_binding.json
#   timestamp: 2026-09-25T06:47:29+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, confloat, constr


class ModelFamily(Enum):
    """
    physics_site=그 건물 자신의 E+ 모델 · physics_archetype=원형(참조 건물) E+ · grid_table=원형 격자 조회표 · surrogate_ml=E+ 를 흉내 낸 ML 대리 모델
    """

    physics_site = 'physics_site'
    physics_archetype = 'physics_archetype'
    grid_table = 'grid_table'
    surrogate_ml = 'surrogate_ml'


class Status(Enum):
    issued = 'issued'
    provisional = 'provisional'
    rejected = 'rejected'
    expired = 'expired'
    revoked = 'revoked'
    superseded = 'superseded'


class FeatureSchemaStatus(Enum):
    """
    ML 입력 특징 스키마가 있나. 물리·격자 모델은 not_applicable(그 개념이 없다)
    """

    hashed = 'hashed'
    not_applicable = 'not_applicable'


class CalibrationStatus(Enum):
    site_calibrated = 'site_calibrated'
    domain_calibrated = 'domain_calibrated'
    uncalibrated = 'uncalibrated'
    not_applicable = 'not_applicable'


class OodStatus(Enum):
    in_domain = 'in_domain'
    warning = 'warning'
    out_of_domain = 'out_of_domain'
    not_evaluated = 'not_evaluated'


class DomainCheck(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    building_type_match: bool | None = Field(
        ..., description='null = 확인하지 못했다(거짓이 아니다)'
    )
    hvac_type_match: bool | None = Field(
        ..., description='null = 확인하지 못했다(거짓이 아니다)'
    )
    feature_schema_match: bool | None = Field(
        ..., description='null = 확인하지 못했다(거짓이 아니다)'
    )
    ood_status: OodStatus
    ood_score: confloat(ge=0.0) | None = None
    ood_threshold: confloat(ge=0.0) | None = None
    building_type_source: str | None = None
    hvac_note: str | None = None
    registry_note: str | None = None
    registry_usage_type: str | None = None
    weather_city: str | None = None


class AllowedUs(Enum):
    screening = 'screening'
    advisory = 'advisory'
    shadow_mpc = 'shadow_mpc'
    approved_bounded_control = 'approved_bounded_control'
    relative_comparison = 'relative_comparison'
    savings_rate_relative = 'savings_rate_relative'
    fuel_accounting_shape = 'fuel_accounting_shape'


class ProhibitedUs(Enum):
    physics_verdict = 'physics_verdict'
    field_safety = 'field_safety'
    national_extrapolation = 'national_extrapolation'
    mv_claim = 'mv_claim'
    unapproved_control = 'unapproved_control'
    savings_amount = 'savings_amount'
    eui_claim = 'eui_claim'
    fuel_split_claim = 'fuel_split_claim'


class ModelBinding(BaseModel):
    """
    특정 모델 체크포인트를 특정 자원과 용도에 적용할 수 있는지 고정하는 계약. 데이터가 많다는 이유만으로 자동 발급하지 않는다. v1.1(2026-09-25): 물리 모델(E+)·격자 조회표 결속을 담는다 — model_family 로 계열을 가르고(한 자원에 계열마다 issued 하나), ML 대리 모델만 feature_schema_hash·checkpoint_hash 를 필수로 둔다. 그 밖의 계열은 feature_schema_status='not_applicable'.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    binding_id: constr(min_length=1)
    model_id: constr(min_length=1)
    model_version: constr(min_length=1)
    model_family: ModelFamily = Field(
        ...,
        description='physics_site=그 건물 자신의 E+ 모델 · physics_archetype=원형(참조 건물) E+ · grid_table=원형 격자 조회표 · surrogate_ml=E+ 를 흉내 낸 ML 대리 모델',
    )
    resource_id: constr(min_length=1)
    default_for_resource: bool | None = Field(
        None,
        description='한 자원에 계열이 다른 issued 결속이 둘 이상일 때, 계열을 밝히지 않은 호출이 받는 것. 자원마다 많아야 하나',
    )
    issued_at: AwareDatetime
    expires_at: AwareDatetime | None = None
    status: Status
    feature_schema_hash: constr(pattern=r'^(sha256:)?[a-fA-F0-9]{64}$') | None = None
    feature_schema_status: FeatureSchemaStatus | None = Field(
        None,
        description='ML 입력 특징 스키마가 있나. 물리·격자 모델은 not_applicable(그 개념이 없다)',
    )
    checkpoint_hash: constr(pattern=r'^(sha256:)?[a-fA-F0-9]{64}$') | None = None
    calibration_status: CalibrationStatus
    calibration_id: str | None = None
    domain_check: DomainCheck
    allowed_uses: list[AllowedUs]
    prohibited_uses: list[ProhibitedUs]
    reasons: list[str]
    evidence_refs: list[str] | None = None
