# generated by datamodel-codegen:
#   filename:  mqtt_topics.json
#   timestamp: 2026-06-30T02:33:28+00:00

from __future__ import annotations

from enum import IntEnum
from typing import Any

from pydantic import BaseModel, Field


class Qos(IntEnum):
    integer_0 = 0
    integer_1 = 1
    integer_2 = 2


class TopicEntry(BaseModel):
    pattern: str = Field(..., description='토픽 패턴 (변수는 {var_name} 형식)')
    namespace: str
    qos: Qos
    retained: bool | None = False
    publisher: str | None = Field(None, description='발행자 프로젝트')
    subscriber: str | None = Field(None, description='구독자 프로젝트 (콤마 구분)')
    payload_schema: str | None = Field(None, description='JSON Schema $id 참조 (선택)')
    description: str | None = None


class MqttTopicsSsotPhaseI4(BaseModel):
    """
    워크스페이스 MQTT 토픽 통합. 기존 protocols/mqtt-topics.md (DR 3계층) + AgentLeague + EduArena 통합. 토픽 패턴 + QoS + retain + publisher/subscriber 명세.
    """

    namespaces: dict[str, Any] | None = None
    topics: list[TopicEntry] | None = None
