# generated by datamodel-codegen:
#   filename:  nl_intents.json
#   timestamp: 2026-06-30T02:33:32+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, constr


class Patterns(BaseModel):
    """
    정규식 추출 패턴 (한국어 기준)
    """

    ven_id: str | None = None
    strategy_code: str | None = None
    hvac_setpoint: str | None = None
    lighting_pct: str | None = None
    ess_keywords: list[str] | None = None


class Constraints(BaseModel):
    """
    추출값 범위 제약
    """

    hvac_setpoint_min_c: float | None = None
    hvac_setpoint_max_c: float | None = None
    lighting_pct_max: float | None = None


class NaturalLanguageIntentsSsot(BaseModel):
    """
    자연어 → 제어/조회/시뮬 의도 매핑. control_intent.py·voice_assistant·LLM 라우터·에이전트가 공유.
    """

    strategies_by_keyword: (
        dict[constr(pattern=r'^M(0[0-9]|1[0-9]|20)$'), list[str]] | None
    ) = Field(
        None,
        description='전략 코드 ↔ 한국어 키워드 매핑. control_intent.py CONTROL_STRATEGIES SSOT.',
    )
    control_keywords: list[str] | None = Field(
        None,
        description='제어 의도 게이트 키워드 (이 중 하나라도 있어야 detect_control_intent 통과)',
    )
    gate_tokens: list[str] | None = Field(
        None, description='추가 게이트 토큰 (CONTROL_KEYWORDS + 단위·M00~M20)'
    )
    patterns: Patterns | None = Field(
        None, description='정규식 추출 패턴 (한국어 기준)'
    )
    constraints: Constraints | None = Field(None, description='추출값 범위 제약')


class IntentType(Enum):
    """
    최상위 의도 유형. edgeControl=설비 제어, query=조회, simulate=시뮬레이션, analyze=에이전트 호출, report=리포트 생성
    """

    edgeControl = 'edgeControl'
    query = 'query'
    simulate = 'simulate'
    analyze = 'analyze'
    report = 'report'


class Language(Enum):
    """
    지원 언어. ko=한국어, en=영어, id=인도네시아어 (BEMS 테넌트)
    """

    ko = 'ko'
    en = 'en'
    id = 'id'
