# generated by datamodel-codegen:
#   filename:  openapi_responses.json
#   timestamp: 2026-09-11T10:06:42+00:00

from __future__ import annotations

from pydantic import BaseModel


class OpenapiStandardResponsesSsotPhaseK17(BaseModel):
    """
    FastAPI 라우터 공통 응답 스키마 (200/400/401/403/404/409/422/429/500). error_response.json 의 ProblemResponse 와 정합.
    """
