# generated by datamodel-codegen:
#   filename:  operation_manifest.json
#   timestamp: 2026-09-28T08:49:38+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class DefaultPeriod(Enum):
    """
    질문·요청 칩이 기간을 말하지 않을 때: needs 가 모두 제공되는 기간의 교집합, 아니면 되묻기
    """

    coverage_of_needs = 'coverage_of_needs'
    ask = 'ask'


class AbsenceWhenMissing(Enum):
    missing = 'missing'
    not_applicable = 'not_applicable'


class Operation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    needs: list[str] = Field(
        ...,
        description='필요한 사실 종류(예 hourly_load·anomaly_label.strong·outdoor_temp·indoor_temp)',
        min_length=1,
    )
    criteria: list[str] | None = Field(
        None, description='judgement_thresholds.json 의 경로(예 comfort.indoor_max_c)'
    )
    day_window: str | None = Field(
        None, description='calendar_conventions.json#default.day_windows 이름'
    )
    default_period: DefaultPeriod = Field(
        ...,
        description='질문·요청 칩이 기간을 말하지 않을 때: needs 가 모두 제공되는 기간의 교집합, 아니면 되묻기',
    )
    assumptions: list[str] | None = None
    absence_when_missing: AbsenceWhenMissing | None = None


class OperationManifest(BaseModel):
    """
    연산 매니페스트 스키마(2026-09-28 일반화 G1). 연산마다 '필요한 사실'(needs)을 선언하면 기본 기간·입력 목록·가정이 파생된다 — 연산 이름에 건 손 표 7개(REPLAY_DEFAULT_PERIOD·OPERATION_CRITERIA·OPERATION_INPUTS …)를 대신한다. 내용(operations)은 게이트웨이 세션(3b)이 G4 에서 채운다 — 지금은 빈 표이고, 빈 표를 '선언 완료'로 세지 않는다.
    """

    operations: dict[str, Operation] | None = None
