# generated by datamodel-codegen:
#   filename:  operation_manifest.json
#   timestamp: 2026-10-01T10:28:00+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, conint


class DefaultPeriod(Enum):
    """
    질문·요청 칩이 기간을 말하지 않을 때: coverage_of_needs = needs 채널이 모두 제공되는 기간 · ask = 되묻기 · tool_rule = 도구 구현의 기본 기간 규칙(매니페스트가 아직 정하지 않음 — 0.2 추가) · not_applicable = 시간 축이 없는 연산(0.2 추가)
    """

    coverage_of_needs = 'coverage_of_needs'
    ask = 'ask'
    tool_rule = 'tool_rule'
    not_applicable = 'not_applicable'


class AbsenceWhenMissing(Enum):
    missing = 'missing'
    not_applicable = 'not_applicable'


class SubjectKind(Enum):
    assigned_asset = 'assigned_asset'
    portfolio = 'portfolio'
    building_no = 'building_no'
    region = 'region'
    national = 'national'
    archetype = 'archetype'


class InputSource(Enum):
    """
    입력 출처 — bound = 서버가 대상 자료에서 채움 · caller_series = 호출자가 줌(0.2)
    """

    bound = 'bound'
    caller_series = 'caller_series'
    NoneType_None = None


class Implementation(Enum):
    """
    구현 위치(0.2)
    """

    internal = 'internal'
    external = 'external'
    remote = 'remote'
    NoneType_None = None


class RegisteredWhen(Enum):
    """
    등록부에 서는 조건 — 정형 질문 스위치(QUESTION_FORMS)에 따라 서는 도구가 있다(0.2)
    """

    always = 'always'
    question_forms_on = 'question_forms_on'
    question_forms_off = 'question_forms_off'


class Operation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    needs: list[str] = Field(
        ...,
        description="필요한 자료 종류 — default.needs_vocabulary 의 낱말 또는 'channel:<채널>'(점포 연산이 읽는 실측 채널 — general_ops.periods.CHANNEL_SERVED_SPAN 의 키). 0.1 의 예(hourly_load 등)는 채워진 적이 없다",
        min_length=1,
    )
    criteria: list[str] | None = Field(
        None, description='judgement_thresholds.json 의 경로(예 comfort.indoor_max_c)'
    )
    day_window: str | None = Field(
        None, description='calendar_conventions.json#default.day_windows 이름'
    )
    default_period: DefaultPeriod = Field(
        ...,
        description='질문·요청 칩이 기간을 말하지 않을 때: coverage_of_needs = needs 채널이 모두 제공되는 기간 · ask = 되묻기 · tool_rule = 도구 구현의 기본 기간 규칙(매니페스트가 아직 정하지 않음 — 0.2 추가) · not_applicable = 시간 축이 없는 연산(0.2 추가)',
    )
    assumptions: list[str] | None = None
    absence_when_missing: AbsenceWhenMissing | None = None
    tool: str | None = Field(None, description='게이트웨이 도구 이름(0.2)')
    operation: str | None = Field(
        None, description='연산 이름 — 연산이 하나뿐인 도구는 null(0.2)'
    )
    selector: str | None = Field(None, description='연산을 고르는 인자 이름(0.2)')
    subject_kinds: list[SubjectKind] | None = Field(
        None, description='받는 대상 종류 — 능력표 subject_kinds(0.2)'
    )
    required_arguments: list[str] | None = Field(
        None, description='질문이 말해야 하는 인자 — 능력표 needs(0.2)'
    )
    produces: list[str] | None = Field(
        None, description='내는 부분 id — 능력표 produces(0.2)'
    )
    axes: list[str] | None = Field(None, description='값을 내는 축 — 능력표 axes(0.2)')
    input_source: InputSource | None = Field(
        None,
        description='입력 출처 — bound = 서버가 대상 자료에서 채움 · caller_series = 호출자가 줌(0.2)',
    )
    implementation: Implementation | None = Field(None, description='구현 위치(0.2)')
    comparison_unit: str | None = Field(
        None,
        description='점포 연산의 비교 단위(재생 주·재생월·재생일·served — store_operations_brief.REPLAY_DEFAULT_PERIOD, 0.2)',
    )
    registered_when: RegisteredWhen | None = Field(
        None,
        description='등록부에 서는 조건 — 정형 질문 스위치(QUESTION_FORMS)에 따라 서는 도구가 있다(0.2)',
    )


class OperationManifest(BaseModel):
    """
    연산 매니페스트 스키마(2026-09-28 일반화 G1 · 2026-10-01 G4 채움). 등록된 연산마다 '필요한 자료'(needs)·대상 종류·질문 인자·내는 부분·기본 기간 규칙을 선언한다. 키 = 도구 이름(연산이 하나인 도구) 또는 '도구/연산'(연산 이름은 도구마다 겹친다). 내용(default.operations)은 손으로 적지 않는다 — 게이트웨이 생성기 8.simulation/ems_transformer/tools/gen_operation_manifest.py 가 능력표(capability_table)·도구 스키마·점포 연산 채널 표에서 파생해 쓰고, 게이트웨이 능력표 적재 검사가 등록된 연산마다 항목이 있는지 센다(검사 0건 = 실패).
    """

    operations: dict[str, Operation] | None = None
    generator: str | None = Field(None, description='내용을 쓴 생성기(0.2)')
    derivation_ko: str | None = Field(None, description='파생 규칙 한 줄(0.2)')
    operation_count: conint(ge=0) | None = Field(
        None, description='operations 항목 수(0.2)'
    )
    needs_vocabulary: dict[str, str] | None = Field(
        None, description='needs 낱말 → 뜻(channel:* 는 앞붙이 — 0.2)'
    )
