# generated by datamodel-codegen:
#   filename:  policy_measures.json
#   timestamp: 2026-06-30T02:33:46+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, confloat


class MeasureCode(Enum):
    """
    자본·설계 조치 코드(8종). prefix 의미: ENV=외피·창호 retrofit / PV=신재생 생성(자립률 분자) / SRC=열원·연료 전환 / MAT=저탄소 자재(내재탄소). prefix 3+ 문자 의무(legacy_ems_code_mapping.json#drift_guard 충돌 회피). ems_strategies.json#StrategyCode(M00~M20)와 직교 네임스페이스.
    """

    ENV01 = 'ENV01'
    ENV02 = 'ENV02'
    ENV03 = 'ENV03'
    PV01 = 'PV01'
    PV02 = 'PV02'
    SRC01 = 'SRC01'
    SRC02 = 'SRC02'
    MAT01 = 'MAT01'


class MeasureMetric(Enum):
    """
    measure 가 무엇을 줄이거나 기여하는가. operational_kwh=운영 에너지 절감(기후·연식 보정 대상) / self_sufficiency=신재생 자립률 분자(생성) / primary_energy=1차에너지 환산계수 기반 / embodied_carbon=내재탄소(LCA 회계, 운영 E+ 무관).
    """

    operational_kwh = 'operational_kwh'
    self_sufficiency = 'self_sufficiency'
    primary_energy = 'primary_energy'
    embodied_carbon = 'embodied_carbon'


class Measures(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(
        ..., description='조치 영문 식별명(PascalCase, 예: EnvelopeInsulation).'
    )
    metric: MeasureMetric
    base: confloat(ge=0.0, le=1.0) = Field(
        ...,
        description='추정 기여/절감 분율(0~1, 문헌·공학계수). 실측/E+ 정밀화 시 교체.',
    )
    eplus_ref: list[str] = Field(
        ...,
        description='SIM E+ 정밀화(ems_transformer) 시 사용할 EnergyPlus 객체 목록. LCA-only(MAT) measure 는 빈 배열.',
    )
    note: str | None = Field(None, description='조치 근거·가정 메모(추정 출처).')


class PolicyMeasures(BaseModel):
    """
    MeasureCode SSOT — 운영 EMS 전략(ems_strategies.json#StrategyCode, M00~M20)이 표현하지 못하는 자본·설계 조치(외피 retrofit / 신재생 생성 / 열원 전환 / 저탄소 자재). StrategyCode 와 별개 네임스페이스다. AgentLeague debate(F14 producer)가 inline 으로 들고 있던 비공식 원본(backend/modules/debate/policy_levers.py#POLICY_MEASURES)을 SSOT 로 정식 등재. 코드 prefix 는 3+ 문자(ENV/PV/SRC/MAT) 의무 — 단일문자 E?/S? 로 간소화 금지(legacy_ems_code_mapping.json#drift_guard 가 deprecated 로 차단). 각 measure 의 base(추정 기여 분율) + eplus_ref(E+ 정밀화 입력 객체) 보존. base 값은 문헌·공학계수 기반 **추정**이며 실측/EnergyPlus 정밀화 시 교체 가능(상위 호환).
    """

    measures: dict[MeasureCode, Measures]
