# generated by datamodel-codegen:
#   filename:  port_allocation.json
#   timestamp: 2026-06-30T02:33:59+00:00

from __future__ import annotations

from typing import Any

from pydantic import Field, RootModel


class PortAllocationSSOT(RootModel[Any]):
    root: Any = Field(
        ...,
        description='myjob 워크스페이스 전체 포트 할당 SSOT. Tier 1 (myjob/CLAUDE.md Port Allocation) 의 머신리더블 버전. 변경 시 양쪽 동시 갱신 필수.',
        title='PortAllocationSSOT',
    )
