# generated by datamodel-codegen:
#   filename:  ppa_contract.json
#   timestamp: 2026-09-11T10:06:45+00:00

from __future__ import annotations

from datetime import date
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, confloat


class Period(Enum):
    monthly = 'monthly'
    quarterly = 'quarterly'
    annual = 'annual'


class TakeOrPay(BaseModel):
    """
    최소인수 약정 — 비용최적 목적함수의 하한 제약.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    min_offtake_kwh: confloat(ge=0.0) | None = Field(
        None, description='기간 내 최소 인수량(kWh). 미달분도 지불 의무.'
    )
    period: Period | None = None


class Term(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    start: date | None = None
    end: date | None = None


class PpaContract(BaseModel):
    """
    전력구매계약(PPA) (R18 Item 4). 재생에너지 직접구매 — 단가·탄소배출계수·take-or-pay 최소인수. APE 비용최적(edge-agent)의 목적함수 하한 제약 + a23_tariff(be-3d) 소비. canonical 값(단가·계수)은 생성본 import — 손편집 금지. 콘솔은 contract_id 참조만.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    contract_id: str = Field(
        ...,
        description='계약 식별자 — 콘솔 ppaContractId 가 이 값으로 조회(참조 무결성). UNIQUE.',
    )
    counterparty: str | None = Field(None, description='발전 사업자/공급자명(선택).')
    price_krw_per_kwh: confloat(ge=0.0) = Field(
        ..., description='PPA 단가(원/kWh). canonical — 생성본 import.'
    )
    carbon_factor_kgco2_per_kwh: confloat(ge=0.0) | None = Field(
        None,
        description='PPA 전원 탄소배출계수(kgCO2/kWh). 재생 PPA=0 근사. canonical = emission_factors.json 파생(손편집 금지).',
    )
    take_or_pay: TakeOrPay | None = Field(
        None, description='최소인수 약정 — 비용최적 목적함수의 하한 제약.'
    )
    term: Term | None = None
