# generated by datamodel-codegen:
#   filename:  provision.json
#   timestamp: 2026-06-30T02:34:02+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field, confloat, conint, constr


class Source(Enum):
    """
    발행 경로. xlsx_upload=엑셀 업로드, ui_edit=관리자 UI, api=VW API, bulk_replay=R6-3 관측 데이터 배포.
    """

    xlsx_upload = 'xlsx_upload'
    ui_edit = 'ui_edit'
    api = 'api'
    bulk_replay = 'bulk_replay'


class BuildingType(Enum):
    """
    common.json §BuildingType SSOT.
    """

    office_large = 'office_large'
    office_medium = 'office_medium'
    office_small = 'office_small'
    hospital = 'hospital'
    school = 'school'
    retail = 'retail'
    convenience_store = 'convenience_store'
    apartment = 'apartment'
    other = 'other'


class Kind(Enum):
    telemetry = 'telemetry'
    dispatch = 'dispatch'


class Backend(Enum):
    replay = 'replay'
    energyplus = 'energyplus'
    real_bas = 'real_bas'
    virtual = 'virtual'


class Protocol(Enum):
    """
    설비 통신 방법 (backend 와 다름 — RFC R6-6 용어 통일).
    """

    replay = 'replay'
    energyplus = 'energyplus'
    modbus = 'modbus'
    bacnet = 'bacnet'
    matter = 'matter'
    virtual = 'virtual'


class Replay(BaseModel):
    """
    backend=replay 시 필수. R6-3 옵션 a 로 GB 가 CSV 경로·URL 전달 가능.
    """

    csv: str | None = Field(None, description='로컬 CSV 경로 또는 GB 서빙 URL')
    csv_url: AnyUrl | None = Field(
        None, description='GB 가 HTTP 로 서빙하는 CSV. Edge 가 다운로드 후 로컬 캐시.'
    )
    col_ts: str | None = None
    col_power_w: str | None = None
    year_shift_to: int | None = None
    speed: float | None = None


class Energyplus(BaseModel):
    idf: str | None = None
    epw: str | None = None
    step_seconds: conint(ge=60) | None = None
    rt_factor: float | None = None


class Modbus(BaseModel):
    host: str | None = None
    port: int | None = None
    slave_id: int | None = None


class Bacnet(BaseModel):
    ip: str | None = None
    device_id: int | None = None
    object_list: list[Any] | None = None


class Connection(BaseModel):
    """
    연결 설정. protocol·data_points·interval + backend별 상세 (replay/energyplus/modbus/bacnet).
    """

    protocol: Protocol = Field(
        ..., description='설비 통신 방법 (backend 와 다름 — RFC R6-6 용어 통일).'
    )
    data_points: list[str] | None = None
    interval_sec: conint(ge=1) | None = None
    replay: Replay | None = Field(
        None,
        description='backend=replay 시 필수. R6-3 옵션 a 로 GB 가 CSV 경로·URL 전달 가능.',
    )
    energyplus: Energyplus | None = None
    modbus: Modbus | None = None
    bacnet: Bacnet | None = None


class Interlocks(BaseModel):
    """
    안전 인터록 오버라이드. 지정 안 하면 Edge 기본값 사용.
    """

    max_indoor_temp_c: float | None = None
    min_indoor_temp_c: float | None = None
    min_ess_soc_pct: float | None = None
    min_lighting_pct: float | None = None


class Config(BaseModel):
    """
    Edge 설정 본문. edge-agent/templates/ 의 YAML 구조와 동일.
    """

    schema_version: str | None = Field(
        None, description="energy-contracts 버전. 예: '1.2'."
    )
    ven_id: str
    building_name: str | None = None
    pnu: str | None = None
    building_type: BuildingType | None = Field(
        None, description='common.json §BuildingType SSOT.'
    )
    group_id: str | None = None
    kind: Kind
    backend: Backend
    baseline_kw: confloat(ge=0.0) | None = None
    max_reduction_kw: confloat(ge=0.0) | None = None
    envelope: dict[str, Any] | None = Field(
        None, description='building_envelope.json v1.0 구조. 전체 스키마 참조.'
    )
    connection: Connection | None = Field(
        None,
        description='연결 설정. protocol·data_points·interval + backend별 상세 (replay/energyplus/modbus/bacnet).',
    )
    interlocks: Interlocks | None = Field(
        None, description='안전 인터록 오버라이드. 지정 안 하면 Edge 기본값 사용.'
    )


class ApplyMode(Enum):
    """
    적용 방식. hot_reload=무중단 반영(드라이버 재생성 불필요 필드만), restart_required=재기동 필요(backend·kind 변경 등), dry_run=검증만 하고 ack 만 보냄.
    """

    hot_reload = 'hot_reload'
    restart_required = 'restart_required'
    dry_run = 'dry_run'


class Provision(BaseModel):
    """
    GB → Edge 프로비저닝 페이로드. VW 엑셀 업로드 또는 관리자 UI 편집의 결과로 GB 가 `fleet/provision/{ven_id}` 토픽에 발행. Edge 는 수신 후 로컬 YAML 적용 → 재기동 또는 핫리로드. R6-3 옵션 a (관측형 replay 데이터 배포) 도 같은 토픽으로 CSV 참조 전달.
    """

    provisioning_id: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    ) = Field(
        ...,
        description='프로비저닝 이벤트 고유 ID (UUIDv4 권장). 중복 수신 시 Edge 는 idempotent 처리 — 동일 ID 는 한 번만 적용.',
    )
    ven_id: constr(
        pattern=r'^VEN-(STORE|EP|REAL|TEST|E2E|SHOP)-[A-Z0-9][A-Z0-9\-]*$'
    ) = Field(
        ...,
        description='대상 VEN. 토픽의 {ven_id} 와 일치해야 함. common.json §VenId SSOT.',
    )
    revision: conint(ge=1) = Field(
        ...,
        description='설정 개정 번호. VW 중앙 저장소에서 단조증가. Edge 는 현재 revision < 수신 revision 일 때만 적용.',
    )
    issued_at: AwareDatetime = Field(
        ..., description='VW/관리자가 발행한 시각 (ISO 8601).'
    )
    issued_by: str | None = Field(
        None, description="발행자 식별. 관리자 이메일·계정 ID·'system' 등. 감사로그용."
    )
    source: Source | None = Field(
        None,
        description='발행 경로. xlsx_upload=엑셀 업로드, ui_edit=관리자 UI, api=VW API, bulk_replay=R6-3 관측 데이터 배포.',
    )
    expected_config_hash: constr(pattern=r'^[a-f0-9]{16}$') | None = Field(
        None,
        description='Edge 가 이 provision 적용 후 생성할 예상 config_hash (edge_status.json v1.1 §config_hash). Edge 가 적용 후 계산한 해시와 일치하지 않으면 ack 에 mismatch 플래그.',
    )
    config: Config = Field(
        ..., description='Edge 설정 본문. edge-agent/templates/ 의 YAML 구조와 동일.'
    )
    apply_mode: ApplyMode | None = Field(
        'hot_reload',
        description='적용 방식. hot_reload=무중단 반영(드라이버 재생성 불필요 필드만), restart_required=재기동 필요(backend·kind 변경 등), dry_run=검증만 하고 ack 만 보냄.',
    )
    secrets_ref: str | None = Field(
        None,
        description='민감정보(BACnet 비밀키·API 토큰) 별도 전달 레퍼런스. 옵션 — 미래 mTLS R6-8 과 연계.',
    )
