# generated by datamodel-codegen:
#   filename:  provision_ack.json
#   timestamp: 2026-06-30T02:34:04+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, Field, conint, constr


class Status(Enum):
    """
    applied=적용 완료, pending_restart=수신 OK 이나 재기동 필요, rejected=검증 실패(이유는 reason), validated=dry_run 검증 통과, hash_mismatch=적용 후 config_hash 불일치(상세 actual_config_hash 참조).
    """

    applied = 'applied'
    pending_restart = 'pending_restart'
    rejected = 'rejected'
    validated = 'validated'
    hash_mismatch = 'hash_mismatch'


class ProvisionAck(BaseModel):
    """
    Edge → GB 프로비저닝 수신/적용 결과. Edge 가 `fleet/provision_ack/{ven_id}` 토픽에 발행. provisioning_id 로 원본 요청과 매칭.
    """

    provisioning_id: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    )
    ven_id: constr(pattern=r'^VEN-(STORE|EP|REAL|TEST|E2E|SHOP)-[A-Z0-9][A-Z0-9\-]*$')
    revision: conint(ge=1) | None = None
    status: Status = Field(
        ...,
        description='applied=적용 완료, pending_restart=수신 OK 이나 재기동 필요, rejected=검증 실패(이유는 reason), validated=dry_run 검증 통과, hash_mismatch=적용 후 config_hash 불일치(상세 actual_config_hash 참조).',
    )
    acked_at: AwareDatetime
    applied_at: AwareDatetime | None = Field(
        None,
        description='실제 적용 완료 시각. status=pending_restart 시 재기동 후 갱신.',
    )
    actual_config_hash: constr(pattern=r'^[a-f0-9]{16}$') | None = Field(
        None,
        description='Edge 가 적용 후 계산한 해시. expected_config_hash 와 비교. status=hash_mismatch 면 서버 측 검토.',
    )
    reason: str | None = Field(
        None,
        description="status=rejected 시 사유. 예: 'backend 불일치', 'envelope.geometry.floor_area_m2 필수', 'revision 이 현재보다 낮음'.",
    )
    warnings: list[str] | None = Field(
        None,
        description="적용은 됐지만 주의 사항. 예: 'source_of_truth=archetype — 실측 권장'.",
    )
