# generated by datamodel-codegen:
#   filename:  question_spec.json
#   timestamp: 2026-09-11T10:06:47+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, confloat, conint, constr


class Intent(Enum):
    """
    annual_cost=연간 에너지·비용·탄소 절감, setpoint=설정온도 변경 영향, retrofit=외피 대 설비 우선순위, flexibility=단기 kW 조정 여력, evidence=결과의 근거, unclear=판정 불가. unclear 는 추측 대신 되묻기 위한 값이며 기본값 대체를 금지한다.
    """

    annual_cost = 'annual_cost'
    setpoint = 'setpoint'
    retrofit = 'retrofit'
    flexibility = 'flexibility'
    evidence = 'evidence'
    unclear = 'unclear'


class Conditions(BaseModel):
    """
    질문에 명시된 값만 기록한다. 추정·보간·클램프 금지이며, 범위를 벗어난 값은 그럴듯한 값으로 고치지 말고 파싱 실패로 처리한다.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    setpoint_c: confloat(ge=10.0, le=40.0) | None
    gross_area_m2: confloat(le=10000000.0, gt=10.0) | None
    floors: conint(ge=1, le=200) | None


class Source(Enum):
    deterministic = 'deterministic'
    deterministic_fallback = 'deterministic_fallback'
    llm = 'llm'


class Provenance(BaseModel):
    """
    해석 자체의 증거. 계산 단계와 동일하게 감사 가능해야 한다.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    backend: constr(min_length=1)
    source: Source
    evidence_state: Literal['llm_interpreted'] = 'llm_interpreted'
    model_id: constr(min_length=1) | None = None
    model_version: constr(min_length=1) | None = None
    prompt_hash: constr(pattern=r'^sha256:[0-9a-f]{64}$') | None = None
    output_hash: constr(pattern=r'^sha256:[0-9a-f]{64}$') | None = None
    site_names_redacted: bool | None = None
    input_tokens: conint(ge=0) | None = None
    output_tokens: conint(ge=0) | None = None
    reasons: list[str] | None = None


class QuestionSpec(BaseModel):
    """
    자연어 건물 에너지 질문의 구조화 결과. 파서(규칙 기반 또는 LLM)가 채울 수 있는 필드의 전부이며, 데이터 보유 수준·제어 권한 등 주장 등급을 결정하는 필드는 의도적으로 포함하지 않는다. 파서는 질문 의도와 질문에 명시된 개입 조건만 보고하고, 에너지·비용·절감량 같은 수치를 생성하지 않는다. 건물 식별자는 파서 출력이 아니라 소비 측 레지스트리 조회로 확정한다.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    intent: Intent = Field(
        ...,
        description='annual_cost=연간 에너지·비용·탄소 절감, setpoint=설정온도 변경 영향, retrofit=외피 대 설비 우선순위, flexibility=단기 kW 조정 여력, evidence=결과의 근거, unclear=판정 불가. unclear 는 추측 대신 되묻기 위한 값이며 기본값 대체를 금지한다.',
    )
    confidence: confloat(ge=0.0, le=1.0)
    interpreted_as: constr(min_length=1) | None = Field(
        ..., description='사용자 확인용 한 문장 재진술. unclear 인 경우 null 가능.'
    )
    conditions: Conditions = Field(
        ...,
        description='질문에 명시된 값만 기록한다. 추정·보간·클램프 금지이며, 범위를 벗어난 값은 그럴듯한 값으로 고치지 말고 파싱 실패로 처리한다.',
    )
    provenance: Provenance | None = Field(
        None, description='해석 자체의 증거. 계산 단계와 동일하게 감사 가능해야 한다.'
    )


class ForbiddenCapabilityFields(RootModel[list[str]]):
    root: list[str] = [
        'building_metadata',
        'geometry',
        'equipment',
        'history_granularity',
        'has_eui',
        'realtime_telemetry',
        'control_authority',
        'model_binding_id',
    ]
