# generated by datamodel-codegen:
#   filename:  rate_limit_policy.json
#   timestamp: 2026-06-30T02:34:08+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, confloat, conint


class Policy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    requests: conint(ge=1) = Field(..., description='window 안 허용 요청 수')
    period_seconds: confloat(ge=1.0) = Field(..., description='window 길이 (초)')
    description: str | None = None


class RateLimitPolicySsotInboundHttp(BaseModel):
    """
    slowapi 호환 inbound HTTP rate-limit 정책 9 종 선언적 SSOT. 본 SSOT 위치: myjob/docs/SSOT_GOVERNANCE.md §9.5.
    """

    use_cases: dict[str, Policy] = Field(
        ..., description='use-case 라벨 → RateLimitPolicy 매핑'
    )
