# generated by datamodel-codegen:
#   filename:  reduction_schedule.json
#   timestamp: 2026-06-30T02:34:16+00:00

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, confloat, conint, constr


class Recurrence(Enum):
    none = 'none'
    daily = 'daily'
    weekdays = 'weekdays'
    weekly = 'weekly'
    monthly = 'monthly'


class Source(Enum):
    vworld = 'vworld'
    gridbridge = 'gridbridge'
    auto = 'auto'


class ReductionSlot(BaseModel):
    start_time: constr(pattern=r'^\d{2}:\d{2}$')
    end_time: constr(pattern=r'^\d{2}:\d{2}$')
    reduction_kw: confloat(ge=0.0)
    strategy: constr(pattern=r'^M(0[0-9]|1[0-9]|20)$') | None = Field(
        None, description='EMS 전략 ID (M00~M20)'
    )
    constraints: dict[str, Any] | None = Field(
        None, description='{max_temp, min_lighting, ...}'
    )
    condition: dict[str, Any] | None = Field(
        None, description='활성화 조건 {smp_above, temp_above}'
    )
    priority: conint(ge=1, le=10) | None = 1


class DailySchedule(BaseModel):
    date: date_aliased = Field(..., description='YYYY-MM-DD')
    slots: list[ReductionSlot] = Field(..., min_length=1)


class ReductionSchedule(BaseModel):
    """
    감축 스케줄 — N일간 시간대별 절감 계획. VWorld→GridBridge/EdgeAgent 전달.
    """

    schedule_id: str | None = Field(None, description='스케줄 고유 ID')
    name: str | None = Field(None, description='스케줄 이름')
    ven_id: str | None = Field(None, description='대상 VEN (경로2: 개별)')
    group_id: str | None = Field(None, description='대상 ESG 그룹 (경로1: 그룹)')
    days: list[DailySchedule] = Field(..., min_length=1)
    recurrence: Recurrence | None = None
    created_by: str | None = 'system'
    source: Source | None = None
