# generated by datamodel-codegen:
#   filename:  region_codes.json
#   timestamp: 2026-06-30T02:34:34+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class SimulationCities(BaseModel):
    name_en: str | None = None
    name_kr: str | None = None
    climate_zone: str | None = Field(
        None, description='한국 기후구역 (중부1/중부2/남부/제주)'
    )
    solar_kwh_m2_yr: float | None = Field(None, description='연평균 수평면 전일사량')


class HvacTypes(BaseModel):
    sim_id: str | None = Field(None, description='sim_id 내 2자리 코드')
    name_en: str | None = None
    name_kr: str | None = None
    cooling: str | None = None
    heating: str | None = None
    staging_m03: bool | None = None
    economizer_m02: bool | None = None


class RegionCodes(BaseModel):
    """
    도시·기후구역·일사량 SSOT. NAMING_UNIFICATION.md §4 + ENERGY_SSOT.md §6 기반.
    """

    simulation_cities: dict[str, SimulationCities] | None = Field(
        None, description='시뮬레이션 도시 코드 C01~C11'
    )
    hvac_types: dict[str, HvacTypes] | None = Field(
        None, description='HVAC 유형 코드 H_A~H_G. NAMING_UNIFICATION.md §3.'
    )
