# generated by datamodel-codegen:
#   filename:  region_codes.json
#   timestamp: 2026-09-14T21:15:27+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class SimulationCities(BaseModel):
    name_en: str | None = None
    name_kr: str | None = None
    kbep_city_id: int | None = Field(
        None,
        description='KBEP/F14 city_id 인코딩 (0-base, C01=0 … C18=17). ems_transformer kbep_client._CITY_TO_ID 및 KBEP :8020 city_id 바운드(le=17)와 정합',
    )
    climate_zone: str | None = Field(
        None, description='한국 기후구역 (중부1/중부2/남부/제주)'
    )
    solar_kwh_m2_yr: float | None = Field(None, description='연평균 수평면 전일사량')


class HvacTypes(BaseModel):
    sim_id: str | None = Field(None, description='sim_id 내 2자리 코드')
    name_en: str | None = None
    name_kr: str | None = Field(
        None, description='한국어 표시 이름 — 공조 방식 이름의 유일한 정본'
    )
    cooling: str | None = None
    heating: str | None = None
    staging_m03: bool | None = None
    economizer_m02: bool | None = None
    aliases: list[str] | None = Field(
        None,
        description='같은 설비의 다른 표기. 전 항목에 걸쳐 유일해야 한다(validate_ssot.check_hvac_display_names).',
    )


class RegionCodes(BaseModel):
    """
    도시·기후구역·일사량 SSOT. NAMING_UNIFICATION.md §4 + ENERGY_SSOT.md §6 기반. v2.1 (2026-07-11): KEP C12-C18 도시확장 반영 (KEP_C12C18_CAMPAIGN_2026-07-05.md) — 18도시 + kbep_city_id(0~17) 신설. C12~C18 의 climate_zone/solar 는 권위값 미확보로 의도적 미등재 (캠페인 엔진 = 전 도시 중부2 baked envelope + 도시별 EPW). v2.2 (2026-09-15): hvac_types.*.name_kr 를 공조 방식 **한국어 표시 이름의 유일한 정본**으로 지정하고 aliases(A~G·HA~HG) 를 더했다. H_B 를 IDF 실측(패키지형 VAV·DX·전기 재열)으로 정정.
    """

    simulation_cities: dict[str, SimulationCities] | None = Field(
        None,
        description='시뮬레이션 도시 코드 C01~C18 (C12~C18 = 2026-07-11 KEP 도시확장)',
    )
    hvac_types: dict[str, HvacTypes] | None = Field(
        None,
        description='HVAC 유형 코드 H_A~H_G. 물리 정의 = NAMING_UNIFICATION.md §3(2026-08-31 IDF 실측 정정본). name_kr = 화면·문서에 쓰는 **유일한** 한국어 표시 이름(소비처는 생성본 HVAC_NAME_KR 또는 가드된 미러로만 쓴다). aliases = 같은 설비를 가리키는 다른 표기(글자 하나·sim_id) — 서빙 인코더 kbep_client._HVAC_TYPE_TO_ID 와 같은 짝.',
    )
