# generated by datamodel-codegen:
#   filename:  region_codes.json
#   timestamp: 2026-09-11T10:06:49+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class SimulationCities(BaseModel):
    name_en: str | None = None
    name_kr: str | None = None
    kbep_city_id: int | None = Field(
        None,
        description='KBEP/F14 city_id 인코딩 (0-base, C01=0 … C18=17). ems_transformer kbep_client._CITY_TO_ID 및 KBEP :8020 city_id 바운드(le=17)와 정합',
    )
    climate_zone: str | None = Field(
        None, description='한국 기후구역 (중부1/중부2/남부/제주)'
    )
    solar_kwh_m2_yr: float | None = Field(None, description='연평균 수평면 전일사량')


class HvacTypes(BaseModel):
    sim_id: str | None = Field(None, description='sim_id 내 2자리 코드')
    name_en: str | None = None
    name_kr: str | None = None
    cooling: str | None = None
    heating: str | None = None
    staging_m03: bool | None = None
    economizer_m02: bool | None = None


class RegionCodes(BaseModel):
    """
    도시·기후구역·일사량 SSOT. NAMING_UNIFICATION.md §4 + ENERGY_SSOT.md §6 기반. v2.1 (2026-07-11): KEP C12-C18 도시확장 반영 (KEP_C12C18_CAMPAIGN_2026-07-05.md) — 18도시 + kbep_city_id(0~17) 신설. C12~C18 의 climate_zone/solar 는 권위값 미확보로 의도적 미등재 (캠페인 엔진 = 전 도시 중부2 baked envelope + 도시별 EPW).
    """

    simulation_cities: dict[str, SimulationCities] | None = Field(
        None,
        description='시뮬레이션 도시 코드 C01~C18 (C12~C18 = 2026-07-11 KEP 도시확장)',
    )
    hvac_types: dict[str, HvacTypes] | None = Field(
        None, description='HVAC 유형 코드 H_A~H_G. NAMING_UNIFICATION.md §3.'
    )
