# generated by datamodel-codegen:
#   filename:  resource_authorization.json
#   timestamp: 2026-09-27T01:06:45+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class Profile(BaseModel):
    login_id: constr(min_length=1)
    role: constr(min_length=1)


class Asset(BaseModel):
    asset_id: constr(min_length=1)


class Permission(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class Context(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assignment_revision: constr(pattern=r'^[0-9a-f]{64}$')
    policy_version: constr(min_length=1)
    policy_sha256: constr(pattern=r'^[0-9a-f]{64}$')
    execution_authorized: Literal[False]
    schema_: Literal['airo-authorization-context/v1'] = Field(..., alias='schema')
    profile: Profile
    assets: list[Asset]
    permissions: list[Permission]


class AssetId(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class Decision(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assignment_revision: constr(pattern=r'^[0-9a-f]{64}$')
    policy_version: constr(min_length=1)
    policy_sha256: constr(pattern=r'^[0-9a-f]{64}$')
    execution_authorized: Literal[False]
    schema_: Literal['airo-authorization-decision/v1'] = Field(..., alias='schema')
    login_id: constr(min_length=1)
    role: constr(min_length=1)
    action: constr(min_length=1)
    asset_ids: list[AssetId]
    allowed: bool
    reason_code: constr(min_length=1)


class VerifiedUserResourceAuthorization(RootModel[Context | Decision]):
    root: Context | Decision = Field(
        ...,
        description='Server-derived context and action decision. Consumers must validate provenance through the authority service; matching JSON alone never authenticates a caller. Secret credentials are prohibited in receipts. Unknown actions must be representable as denied decisions.',
        title='Verified User Resource Authorization',
    )
