# generated by datamodel-codegen:
#   filename:  retry_policy.json
#   timestamp: 2026-06-30T02:34:43+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, confloat, conint


class Jitter(Enum):
    """
    jitter 전략. AWS Brooker 2015 분류.
    """

    none = 'none'
    full = 'full'
    equal = 'equal'
    decorrelated = 'decorrelated'


class Policy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    base_seconds: confloat(ge=0.0) = Field(
        ..., description='attempt=threshold_attempts+1 일 때 delay (초)'
    )
    factor: confloat(ge=1.0) | None = Field(
        2.0, description='지수 배율 (기본 2.0 — doubling)'
    )
    max_seconds: confloat(ge=0.0) = Field(
        ..., description='delay 상한 (초). 사용자 영구 lockout 방지.'
    )
    threshold_attempts: conint(ge=0) | None = Field(
        0, description='이 횟수 이하 attempt 는 delay=0 (free retry). 정상 사용자 보호.'
    )
    window_seconds: confloat(ge=0.0) | None = Field(
        None, description='카운터 자연 소멸 윈도우 (초). 상태 머신 호출자가 사용.'
    )
    jitter: Jitter | None = Field(
        'none', description='jitter 전략. AWS Brooker 2015 분류.'
    )
    description: str | None = None


class UseCases(BaseModel):
    """
    use-case 라벨 → BackoffPolicy 매핑
    """

    model_config = ConfigDict(
        extra='allow',
    )
    __pydantic_extra__: dict[str, Policy]
    auth: Policy | None = Field(
        None,
        description='IP-based auth 401 backoff (be-3d AuthBackoffMiddleware). 5회 무료 후 1s, 2s, 4s, ... 최대 1h.',
    )
    external_api: Policy | None = Field(
        None,
        description='외부 API circuit breaker cooldown (agents circuit_breaker). 30분 base, 24h 상한, repeat 마다 doubling.',
    )
    mqtt_reconnect: Policy | None = Field(
        None,
        description='MQTT 재연결 (paho 내장 X — 명시 정책이 필요할 때). 1s base, 60s 상한, equal jitter (thundering herd 완화).',
    )
    db: Policy | None = Field(
        None,
        description='DB connection / transient query retry. 100ms base, 5s 상한, full jitter.',
    )


class RetryBackoffPolicySsot(BaseModel):
    """
    지수 backoff 정책 4 use-case 선언적 SSOT. AWS Brooker 2015 jitter 분류 차용. 본 SSOT 위치: myjob/docs/SSOT_GOVERNANCE.md §9.5.
    """

    use_cases: UseCases = Field(..., description='use-case 라벨 → BackoffPolicy 매핑')
