# generated by datamodel-codegen:
#   filename:  rq_ai_intent.json
#   timestamp: 2026-06-30T02:34:47+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class StepLatencyBudgetMs(BaseModel):
    """
    PRD v1.6 §3.2 결선 metric — 5 단계별 p99 latency budget.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    step1_input: int | None = None
    step2_parse: int
    step3_form_render: int | None = None
    step4_simulate: int
    step5_visualize: int | None = None


class OutputType(Enum):
    """
    역산 결과 수신자 유형. advisory=시민 체감형(권고), prescriptive=정책형(처방), both=양쪽 (RQ-AI Framework §역산 결과의 두 유형).
    """

    advisory = 'advisory'
    prescriptive = 'prescriptive'
    both = 'both'


class Persona(Enum):
    """
    발화자 페르소나. persona.ts SSOT 와 1:1 미러.
    """

    household = 'household'
    owner = 'owner'
    municipal = 'municipal'
    govt = 'govt'


class Language(Enum):
    ko = 'ko'
    en = 'en'
    id = 'id'


class ConfidenceLevel(Enum):
    """
    LLM 파싱 신뢰도. low 이면 Step 3 에서 사용자 명시적 확인 필요.
    """

    high = 'high'
    medium = 'medium'
    low = 'low'


class Operator(Enum):
    """
    목표 비교 연산자.
    """

    field__ = '<='
    field___1 = '>='
    field___2 = '=='
    field_ = '<'
    field__1 = '>'


class TargetState(BaseModel):
    """
    수치화된 목표 (RQ-AI 요소 #2). emotion → number 변환 결과.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    metric: str = Field(
        ...,
        description='목표 측정 단위 (예: monthly_bill_krw, edu_kwh_per_m2_year, peak_kw, comfort_pmv).',
    )
    operator: Operator = Field(..., description='목표 비교 연산자.')
    value: float = Field(..., description='수치 목표값.')
    unit: str | None = Field(None, description='단위 라벨 (예: 만원/월, kWh/m²·yr, %).')


class Source(Enum):
    """
    값 출처. llm_inferred 는 Step 3 에서 사용자 확인 우선.
    """

    user_input = 'user_input'
    llm_inferred = 'llm_inferred'
    system_default = 'system_default'


class Variable(BaseModel):
    """
    context / control 변수 한 항목 (RQ-AI 요소 #3, #4).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(
        ..., description='변수 식별자 (예: pnu, hvac_setpoint, retrofit_budget).'
    )
    value: Any | None = Field(None, description='변수 값. null 이면 미상 (LLM 미추출).')
    unit: str | None = None
    source: Source = Field(
        ..., description='값 출처. llm_inferred 는 Step 3 에서 사용자 확인 우선.'
    )


class PersonaPlaceholder(BaseModel):
    """
    페르소나별 자연어 입력창 placeholder (Step 1). 4 페르소나 모두 정의 필수.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    placeholder: str = Field(
        ..., description='input[placeholder] 값. 페르소나 톤·관심사 반영.'
    )
    examples: list[str] = Field(
        ..., description='원클릭 예시 발화 (input prefill 후보).', min_length=1
    )
    default_output_type: OutputType


class RqAiIntent(BaseModel):
    """
    Step 2 LLM 파싱 산출물 = Step 3 filled-in form 직렬화 형태.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    intent_id: str = Field(..., description='UUID v4 — Step 4 시뮬 호출 트레이스 ID.')
    persona: Persona
    language: Language
    pain_question: str = Field(
        ..., description='RQ-AI 요소 #1. 사용자 원문 발화 (수정 없이 보존).'
    )
    output_type: OutputType
    target_state: TargetState | None = None
    context_variables: list[Variable] | None = Field(
        None, description='RQ-AI 요소 #3. 못 바꾸는 조건 (pnu, 건물 연식, 기상).'
    )
    control_variables: list[Variable] | None = Field(
        None, description='RQ-AI 요소 #4. 조정 가능 변수 (온도, 시간, 투자액).'
    )
    forward_model_hint: str | None = Field(
        None,
        description='RQ-AI 요소 #5. 호출 후보 모델 식별자 (gateway tool name). 예: korean_bb_forecast_24h, reverse_diagnose, ems_recommend.',
    )
    confidence: ConfidenceLevel
    missing_fields: list[str] | None = Field(
        None, description='LLM 이 추출 못 한 필드 목록. Step 3 에서 사용자 보완 요청.'
    )


class Ko(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    household: PersonaPlaceholder
    owner: PersonaPlaceholder
    municipal: PersonaPlaceholder
    govt: PersonaPlaceholder


class Placeholders(BaseModel):
    """
    Step 1 자연어 입력창 placeholder (페르소나 4 × 언어 1+). ko 는 필수.
    """

    model_config = ConfigDict(
        extra='allow',
    )
    ko: Ko


class RqAiIntentSchemaRqAi7(BaseModel):
    """
    역질문 UI 5단계의 Step 2~3 산출물. 자연어 → LLM 파싱 → 7요소 filled-in form. RQ-AI Framework SSOT (~/.claude/skills-library/rq-ai-framework/SKILL.md §RQ-AI 7요소).
    """

    placeholders: Placeholders = Field(
        ...,
        description='Step 1 자연어 입력창 placeholder (페르소나 4 × 언어 1+). ko 는 필수.',
    )
    intent_example: RqAiIntent | None = Field(
        None,
        description='Step 3 filled-in form 직렬화 예시 (consumer 가 fixture 로 사용).',
    )
    step_latency_budget_ms: StepLatencyBudgetMs = Field(
        ..., description='PRD v1.6 §3.2 결선 metric — 5 단계별 p99 latency budget.'
    )
