# generated by datamodel-codegen:
#   filename:  run_modes.json
#   timestamp: 2026-05-17T05:17:53+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class RunMode(Enum):
    prod = 'prod'
    demo = 'demo'
    dev = 'dev'
    test = 'test'


class AuthPolicy(Enum):
    enforced = 'enforced'
    bypassable = 'bypassable'
    weak_default = 'weak_default'
    bypassed = 'bypassed'


class DataScope(Enum):
    real = 'real'
    is_demo_only = 'is_demo_only'
    real_plus_fixtures = 'real_plus_fixtures'
    isolated_db = 'isolated_db'


class ExternalApiPolicy(Enum):
    live = 'live'
    live_or_mock = 'live_or_mock'
    mocked = 'mocked'


class ModeBehavior(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    auth: AuthPolicy
    data_scope: DataScope
    external_api: ExternalApiPolicy
    visual: str | None = Field(
        None,
        description='UI 표시 라벨. 예: yellow_banner / gray_badge / red_badge / null',
    )
    extensions: dict[str, Any] | None = Field(
        None, description='프로젝트별 자유 확장 영역. 키는 프로젝트명, 값은 임의.'
    )


class RunModesSsotPhaseE(BaseModel):
    modes: dict[RunMode, ModeBehavior] | None = None
    env_vars: dict[str, Any] | None = Field(
        None, description='각 모드를 활성화하는 권장 환경변수명 패턴'
    )
