# generated by datamodel-codegen:
#   filename:  security_policy.json
#   timestamp: 2026-06-30T02:35:05+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class SecurityPolicySsotPhaseI5(BaseModel):
    """
    공통 보안 헤더 + CORS + rate limit 정책. 6 프로젝트 FastAPI 미들웨어 단일 진실. building-energy-3d/main.py SecurityHeadersMiddleware 패턴 일반화. v1.1 (2026-05-25): be-3d CSP P5 #A~#D 완료에 맞춰 default CSP 에서 'unsafe-eval'(script-src) + 'unsafe-inline'(style-src) 제거. Cesium 의존 페이지(vworld/cesium) 와 legacy simulator iframe 은 nginx location 에서 개별 완화.
    """

    headers: dict[str, Any] | None = None
    cors: dict[str, Any] | None = None
    rate_limit: dict[str, Any] | None = None
