# generated by datamodel-codegen:
#   filename:  simulation_channels.json
#   timestamp: 2026-09-11T10:06:53+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, constr


class Tier(Enum):
    """
    A = 결측 불허(하나라도 없으면 대조 불가) / B = 결측 허용(비해당 건물은 전체 NaN 가능)
    """

    A = 'A'
    B = 'B'


class Channel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(pattern=r'^hourly_[a-z_]+$')
    tier: Tier
    unit: str
    description: str | None = None
    physical_source: str | None = Field(
        None,
        description='실건물에서 이 값을 만드는 물건(발주 사양서에 그대로 쓰는 문구)',
    )
    telemetry_sources: list[str] | None = Field(
        None,
        description='이 채널을 채울 수 있는 telemetry 경로. **비어 있으면 대응물이 없다**',
    )
    gap: bool | None = Field(
        None,
        description="true = telemetry 계약에 대응물이 없다. 소비단은 이 채널을 '아직 안 온 것' 이 아니라 **올 수 없는 것**으로 다뤄야 한다",
    )
    substitutable_externally: bool | None = Field(
        None,
        description="true = 건물에서 안 와도 **외부 소스로 채울 수 있다**(기상청 ASOS 등). ⚠ 이 구분이 없으면 판정이 과하게 비관적이 된다 — 외기온을 '건물이 못 보낸다' 는 이유로 대조 불가로 세면, 실제로는 채울 수 있는 건물까지 전부 불가가 된다.",
    )


class SimulationChannelContractSsot(BaseModel):
    """
    실건물 계측을 **시뮬레이션과 대조**하기 위한 채널 계약. 학습·검증 파이프라인이 실제로 쓰는 19채널(Tier A 15 + Tier B 4, 각 `(8760,)`)이며 정본은 캠페인 `ems_transformer/cloud/data_contract.py` 였다 — 소비단(MGCC)이 커버리지를 판정하려면 손으로 베껴야 했으므로(수동 미러) EC 로 승격한다.
    ⚠ **Tier A 는 결측 불허**다. 하나라도 못 받으면 그 건물은 '일부만 맞춰 봤다' 가 아니라 **대조 불가**로 표시한다.
    ⚠ `telemetry_sources` 가 빈 채널은 **telemetry 계약에 대응물이 없다**(gap=true). 이걸 밝히지 않으면 소비단이 '언젠가 오겠지' 로 기다리게 된다 — 오지 않는다.
    """

    expected_hours: list[int] | None = Field(None, description='평년 8760 / 윤년 8784')
    channels: list[Channel]
