# generated by datamodel-codegen:
#   filename:  simulation_scenarios.json
#   timestamp: 2026-09-17T04:04:17+00:00

from __future__ import annotations

from pydantic import BaseModel


class SimulationScenariosSsotPhaseK15(BaseModel):
    """
    EnergyPlus DesignDay / RunPeriod / EMS 패턴 표준. ~/.claude/SIMULATION_DESIGN_SSOT.md 의 머신리더블 추출. v1.1 (2026-09-17): ko_envelope_uvalue 를 원문(에너지절약설계기준 고시 제2026-360호 [별표 1])과 맞췄다 — 옛 값은 중부2 지붕 0.17·제주 벽 0.36 등 원문과 달랐다. 정본은 korean_building_standards.json.
    """
