# generated by datamodel-codegen:
#   filename:  simulation_scenarios.json
#   timestamp: 2026-06-30T02:35:08+00:00

from __future__ import annotations

from pydantic import BaseModel


class SimulationScenariosSsotPhaseK15(BaseModel):
    """
    EnergyPlus DesignDay / RunPeriod / EMS 패턴 표준. ~/.claude/SIMULATION_DESIGN_SSOT.md 의 머신리더블 추출.
    """
