# generated by datamodel-codegen:
#   filename:  target_vocabulary.json
#   timestamp: 2026-09-28T08:40:14+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class TargetVocabulary(BaseModel):
    """
    대상(누구의 무엇을 묻나) 어휘 정본(2026-09-28 일반화 G1). AIR 자산 종류마다 어느 대상 칸으로 가는지·건물번호를 갖는지·시계열을 갖는지를 한 표로 둔다 — 같은 사실을 게이트웨이 두 목록(BUILDING_ASSET=BLD·FAC·RET ↔ ASSET_WITH_SERIES=BLD·FAC·HOM·RET)이 다르게 말해 확인된 가정 15곳이 공공 건물 도구에서 거절됐다. 식별자 정규식은 common.json $defs(BuildingMgmtNo·ParcelId·AirAssetId …) 한 곳이다.
    """


class TargetKind(Enum):
    asset = 'asset'
    portfolio = 'portfolio'


class SubjectField(Enum):
    building_ids = 'building_ids'
    home_ids = 'home_ids'
    portfolio_ids = 'portfolio_ids'


class BuildingNumber(Enum):
    """
    registry_confirmed = 원장에 확인된 25자리 번호가 있을 때만 쓴다(없으면 이름 있는 거절 — 필지로 대체 금지)
    """

    registry_confirmed = 'registry_confirmed'
    not_applicable = 'not_applicable'


class ArchetypeSource(Enum):
    record = 'record'
    registry_usage = 'registry_usage'
    members = 'members'


class AirAssetKindEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    label_ko: str
    target_kind: TargetKind
    subject_field: SubjectField
    building_number: BuildingNumber = Field(
        ...,
        description='registry_confirmed = 원장에 확인된 25자리 번호가 있을 때만 쓴다(없으면 이름 있는 거절 — 필지로 대체 금지)',
    )
    has_series: bool = Field(
        ..., description='자산 자체의 계측 시계열이 있는가(포트폴리오는 구성원 계열)'
    )
    archetype_source: ArchetypeSource | None = None
