# generated by datamodel-codegen:
#   filename:  telemetry.json
#   timestamp: 2026-07-25T01:20:24+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, Field, RootModel, confloat, constr


class Mode(Enum):
    """
    EdgeAgent 운영 모드 audit 표시 (informational only — trust anchor 아님). Trust anchor는 bootstrap channel: ① mTLS 인증서의 mode extension OR ② GridBridge가 발급한 short-lived signed token에 mode embed. payload의 mode 단독 검증 금지 (위변조 가능). startup_check 는 bootstrap channel과 본 필드 일치 확인 — 5분 후 불일치 시 venue suspend + alert.
    """

    prod = 'prod'
    demo = 'demo'
    dev = 'dev'
    test = 'test'


class CanonicalPointAddress(
    RootModel[
        constr(
            pattern=r'^[a-z]{2}\.[a-z][a-zA-Z0-9]*\.(mg|sld|hvac|wtp|campus)\.[a-z][a-z0-9-]*\.[A-Z][A-Z0-9_]*$'
        )
    ]
):
    root: constr(
        pattern=r'^[a-z]{2}\.[a-z][a-zA-Z0-9]*\.(mg|sld|hvac|wtp|campus)\.[a-z][a-z0-9-]*\.[A-Z][A-Z0-9_]*$'
    ) = Field(
        ...,
        description='정규 관제점 주소 {country}.{site}.{domain}.{equip}.{point} — 다국가 플릿 유일 점 주소. 노드 SSOT=ven_id·필지=pnu 는 별도(익명 site 파생). bems-console lib/point-address 정본.',
        examples=[
            'kr.siteA.hvac.ahu-3f.SAT',
            'kr.siteA.mg.ess-1.SOC',
            'kr.siteA.wtp.pump-p2.PMP',
        ],
    )


class Zone(BaseModel):
    zone_id: str = Field(..., description='존 식별자 — 콘솔/BAS 모델 zone.id 와 매핑')
    point_id: CanonicalPointAddress | None = Field(
        None,
        description='(optional) 관제점 정규 주소(CPA). 하위호환 — 미제공 시 zone_id 로 파생(bems-console lib/point-address 정본).',
    )
    indoor_temp_c: float | None = Field(None, description='존 실내 온도 (°C)')
    hvac_setpoint_c: float | None = Field(None, description='존 설정 온도 (°C)')
    co2_ppm: confloat(ge=0.0) | None = Field(None, description='존 CO2 농도 (ppm)')
    humidity_pct: confloat(ge=0.0, le=100.0) | None = Field(
        None, description='존 상대습도 (%)'
    )
    occupancy: bool | None = Field(None, description='존 재실 여부')
    power_kw: float | None = Field(None, description='존 전력 소비 (kW)')


class Telemetry(BaseModel):
    """
    설비 텔레메트리 — EdgeAgent→GridBridge (MQTT 5분 주기).
    """

    ven_id: str
    zones: list[Zone] | None = Field(
        None,
        description='존별 세부 텔레메트리 (선택 — 존/포인트 단위 계측 가능 장치만 방출. 미지원 장치는 생략, 건물 집계값만). v1.1 추가(하위호환 — 미지원 수신자는 무시). 콘솔 공간 IR(zone.id)와 zone_id 매핑 시 measured 승격.',
    )
    timestamp: AwareDatetime
    power_kw: float = Field(..., description='현재 전력 소비 (kW)')
    indoor_temp_c: float | None = Field(None, description='실내 온도 (°C)')
    hvac_setpoint_c: float | None = Field(None, description='에어컨 설정 온도 (°C)')
    lighting_pct: confloat(ge=0.0, le=100.0) | None = Field(
        None, description='조명 디밍 (%)'
    )
    ess_soc_pct: confloat(ge=0.0, le=100.0) | None = Field(
        None, description='ESS 충전률 (%)'
    )
    ess_discharge_kw: float | None = Field(None, description='ESS 방전량 (kW)')
    active_strategy: str | None = Field(None, description='현재 실행 중인 EMS 전략 ID')
    schedule_slot_idx: int | None = Field(
        None, description='현재 실행 중인 스케줄 슬롯 인덱스'
    )
    mode: Mode | None = Field(
        None,
        description='EdgeAgent 운영 모드 audit 표시 (informational only — trust anchor 아님). Trust anchor는 bootstrap channel: ① mTLS 인증서의 mode extension OR ② GridBridge가 발급한 short-lived signed token에 mode embed. payload의 mode 단독 검증 금지 (위변조 가능). startup_check 는 bootstrap channel과 본 필드 일치 확인 — 5분 후 불일치 시 venue suspend + alert.',
    )
    mode_locked: bool | None = Field(
        None,
        description='첫 telemetry에서 lock 후 mode 변경 시 alert + suspend (변조 탐지).',
    )
