# generated by datamodel-codegen:
#   filename:  telemetry.json
#   timestamp: 2026-06-30T02:35:12+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, Field, confloat


class Mode(Enum):
    """
    EdgeAgent 운영 모드 audit 표시 (informational only — trust anchor 아님). Trust anchor는 bootstrap channel: ① mTLS 인증서의 mode extension OR ② GridBridge가 발급한 short-lived signed token에 mode embed. payload의 mode 단독 검증 금지 (위변조 가능). startup_check 는 bootstrap channel과 본 필드 일치 확인 — 5분 후 불일치 시 venue suspend + alert.
    """

    prod = 'prod'
    demo = 'demo'
    dev = 'dev'
    test = 'test'


class Telemetry(BaseModel):
    """
    설비 텔레메트리 — EdgeAgent→GridBridge (MQTT 5분 주기).
    """

    ven_id: str
    timestamp: AwareDatetime
    power_kw: float = Field(..., description='현재 전력 소비 (kW)')
    indoor_temp_c: float | None = Field(None, description='실내 온도 (°C)')
    hvac_setpoint_c: float | None = Field(None, description='에어컨 설정 온도 (°C)')
    lighting_pct: confloat(ge=0.0, le=100.0) | None = Field(
        None, description='조명 디밍 (%)'
    )
    ess_soc_pct: confloat(ge=0.0, le=100.0) | None = Field(
        None, description='ESS 충전률 (%)'
    )
    ess_discharge_kw: float | None = Field(None, description='ESS 방전량 (kW)')
    active_strategy: str | None = Field(None, description='현재 실행 중인 EMS 전략 ID')
    schedule_slot_idx: int | None = Field(
        None, description='현재 실행 중인 스케줄 슬롯 인덱스'
    )
    mode: Mode | None = Field(
        None,
        description='EdgeAgent 운영 모드 audit 표시 (informational only — trust anchor 아님). Trust anchor는 bootstrap channel: ① mTLS 인증서의 mode extension OR ② GridBridge가 발급한 short-lived signed token에 mode embed. payload의 mode 단독 검증 금지 (위변조 가능). startup_check 는 bootstrap channel과 본 필드 일치 확인 — 5분 후 불일치 시 venue suspend + alert.',
    )
    mode_locked: bool | None = Field(
        None,
        description='첫 telemetry에서 lock 후 mode 변경 시 alert + suspend (변조 탐지).',
    )
