# generated by datamodel-codegen:
#   filename:  tenant_regions.json
#   timestamp: 2026-06-30T02:35:17+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, constr


class TenantRegionsSsotPhaseJ9(BaseModel):
    """
    한국 권역(Metro/Gangwon/...) + ASEAN 6 테넌트 + 인도네시아 12 도시 통합. 기존 region_codes.json(시뮬 C01~C11)을 보완. building-energy-id 6 테넌트 + GridBridge 권역 통합 SSOT.
    """


class RegionEntry(BaseModel):
    code: constr(pattern=r'^[A-Z]{2}-[A-Z]{2,8}$')
    name_kr: str
    name_en: str
    country: str = Field(..., description='ISO 3166-1 alpha-2')
    timezone: str | None = None
    climate_zone: str | None = Field(None, description='ASHRAE 169')
    is_tropical: bool | None = False
    parent_region: str | None = None
