# generated by datamodel-codegen:
#   filename:  test_classification.json
#   timestamp: 2026-06-30T02:35:24+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class TestClassificationSsotPhaseG(BaseModel):
    """
    테스트 분류 3축 (Tier × Group × Stage). pytest marker로 활용. 프로젝트는 opt-in 채택.
    """

    tiers: dict[str, dict[str, Any]] | None = None
    groups: dict[str, dict[str, Any]] | None = None
    stages: dict[str, dict[str, Any]] | None = None
    project_default_groups: dict[str, Any] | None = Field(
        None, description='프로젝트별 기본 그룹 (marker 미부여 시 자동 추정용)'
    )


class TestTier(Enum):
    """
    T0=workspace fixture, T1=contract(schema), T2=unit, T3=integration(DB/MQTT), T4=e2e cross-project, T5=UI(Playwright)
    """

    T0 = 'T0'
    T1 = 'T1'
    T2 = 'T2'
    T3 = 'T3'
    T4 = 'T4'
    T5 = 'T5'


class TestGroup(Enum):
    """
    G1=3D-Vis, G2=Backend, G3=Sim, G4=DR-Control, G5=Agents, G6=Auth-RBAC, G7=Cross-Project
    """

    G1 = 'G1'
    G2 = 'G2'
    G3 = 'G3'
    G4 = 'G4'
    G5 = 'G5'
    G6 = 'G6'
    G7 = 'G7'


class TestStage(Enum):
    """
    S1=pre-commit, S2=PR fast, S3=PR full, S4=merge, S5=nightly, S6=pre-release
    """

    S1 = 'S1'
    S2 = 'S2'
    S3 = 'S3'
    S4 = 'S4'
    S5 = 'S5'
    S6 = 'S6'
