# generated by datamodel-codegen:
#   filename:  tests_shared.json
#   timestamp: 2026-06-30T02:35:36+00:00

from __future__ import annotations

from pydantic import BaseModel


class SharedTestFixturesSsotPhaseK13(BaseModel):
    """
    워크스페이스 공통 테스트 fixture. M00~M20 케이스, sample VEN/PNU/Building. 6 프로젝트 중복 제거.
    """
