# generated by datamodel-codegen:
#   filename:  ui_capabilities.json
#   timestamp: 2026-07-09T21:51:00+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class Params(BaseModel):
    type: str | None = None
    required: bool | None = None
    enum_ref: str | None = Field(
        None, description='enum producer 위치(예: policy_levers.py LEVER_CATALOG)'
    )
    range: list[float] | None = Field(None, max_length=2, min_length=2)
    unit: str | None = None
    note: str | None = None


class Sequences(BaseModel):
    label_ko: str
    steps: list[str] = Field(..., description='UICapabilityId 순서 배열')
    note: str | None = None


class UICapabilityId(Enum):
    """
    유계 UI 원자 기능 12종. 시퀀스(seq.*)는 sequences 에 별도 정의.
    """

    ui_apply_policy_lever = 'ui.apply_policy_lever'
    ui_identify_ems = 'ui.identify_ems'
    ui_recommend_retrofit = 'ui.recommend_retrofit'
    ui_forecast_24h = 'ui.forecast_24h'
    ui_counterfactual = 'ui.counterfactual'
    ui_report_qa = 'ui.report_qa'
    ui_run_debate = 'ui.run_debate'
    ui_choropleth_map = 'ui.choropleth_map'
    ui_timeline = 'ui.timeline'
    ui_zoom_ladder = 'ui.zoom_ladder'
    ui_select_buildings = 'ui.select_buildings'
    ui_policy_cascade = 'ui.policy_cascade'


class CapabilityCategory(Enum):
    """
    능력 범주. 흐름(flow)은 sequences 로 표현.
    """

    policy_control = 'policy_control'
    diagnosis = 'diagnosis'
    visualization = 'visualization'


class BindingLayer(Enum):
    """
    실행 계층. f_route=Gateway F-route 라우팅 / m_code_lever=F14+22레버(M-code) / scene_op=op_registry replay / lora_qa=기학습 QA LoRA① / lora_debate=기학습 policy LoRA②. 전부 신규 학습 불요.
    """

    f_route = 'f_route'
    m_code_lever = 'm_code_lever'
    scene_op = 'scene_op'
    lora_qa = 'lora_qa'
    lora_debate = 'lora_debate'


class RoutingTier(Enum):
    """
    NL 라우터 4-tier 사다리. tier0=유계 시퀀스 정확매치 / tier1=단일기능+param추출 / tier2=퍼지→확인UI / tier3=compose 폴백(LoRA③).
    """

    tier0_template = 'tier0_template'
    tier1_function = 'tier1_function'
    tier2_confirm = 'tier2_confirm'
    tier3_compose = 'tier3_compose'


class Capabilities(BaseModel):
    label_ko: str = Field(
        ..., description='쉬운 한국어 라벨(약어 지양·전문용어 괄호 풀이)'
    )
    category: CapabilityCategory
    binding_layer: BindingLayer
    backend: str | None = Field(
        None,
        description='바인딩 대상(F-route 코드 / op 이름 / 서비스). gateway_routing.json·op_registry.json 참조.',
    )
    params: dict[str, Params] | None = Field(
        None,
        description='param 이름 → {type, range|enum_ref, required}. 값 범위·enum 은 producer SSOT 참조(EC 재정의 금지).',
    )
    composition_ok: bool | None = Field(
        None, description='순차 조합(시퀀스 스텝) 가능 여부'
    )
    primary_tier: RoutingTier
    requires_training: bool | None = Field(
        None, description='신규 학습 필요 여부(전부 false — F14형 원칙)'
    )
    note: str | None = None


class UiCapabilitiesFrontendCapabilityContract(BaseModel):
    """
    F14형 유계 UI 능력 계약 SSOT. 자연어를 '생성'이 아니라 '분류·라우팅'으로 매핑할 대상(bounded target)을 정의한다. 재학습 불요 — 각 능력은 기존 F-route 라우팅 / 기학습 LoRA / scene op replay 로 실행. gateway_routing.json(백엔드 능력 F1~F14)의 프론트엔드 대칭 레지스트리.
    """

    capabilities: dict[UICapabilityId, Capabilities] | None = Field(
        None, description='UICapabilityId → 능력 정의.'
    )
    sequences: dict[str, Sequences] | None = Field(
        None,
        description='유계 시퀀스 템플릿(Tier 0). 데모 필수 연출은 고정 op/기능 배열 replay 로 compose 우회(항상 동작).',
    )
