# generated by datamodel-codegen:
#   filename:  venue.json
#   timestamp: 2026-06-30T02:35:39+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, confloat


class Kind(Enum):
    """
    운영 모드 — common.json §Kind SSOT 와 동기화. telemetry=관측형(read-only), dispatch=제어형(양방향).
    """

    telemetry = 'telemetry'
    dispatch = 'dispatch'


class Backend(Enum):
    """
    구현 기술 — common.json §Backend SSOT 와 동기화.
    """

    replay = 'replay'
    energyplus = 'energyplus'
    real_bas = 'real_bas'
    virtual = 'virtual'


class BuildingType(Enum):
    """
    common.json §BuildingType SSOT 와 동기화.
    """

    office_large = 'office_large'
    office_medium = 'office_medium'
    office_small = 'office_small'
    hospital = 'hospital'
    school = 'school'
    retail = 'retail'
    convenience_store = 'convenience_store'
    apartment = 'apartment'
    other = 'other'


class Venue(BaseModel):
    """
    수용가(VEN) 레지스트리 항목 — Layer 2 GridBridge SSOT.
    """

    ven_id: str = Field(
        ..., description='VEN 고유 식별자 (예: VEN-STORE-001, VEN-EPLUS-OFFICE-01)'
    )
    kind: Kind = Field(
        ...,
        description='운영 모드 — common.json §Kind SSOT 와 동기화. telemetry=관측형(read-only), dispatch=제어형(양방향).',
    )
    backend: Backend | None = Field(
        None, description='구현 기술 — common.json §Backend SSOT 와 동기화.'
    )
    group_id: str | None = Field(None, description='ESG·권역 그룹 식별자 (선택)')
    pnu: str | None = Field(None, description='PNU (건축물 공간코드, 선택)')
    building_name: str | None = None
    building_type: BuildingType | None = Field(
        None, description='common.json §BuildingType SSOT 와 동기화.'
    )
    baseline_kw: confloat(ge=0.0) | None = None
    max_reduction_kw: confloat(ge=0.0) | None = Field(
        None, description='제어형만 의미 있음'
    )
    is_active: bool | None = True
    idf_path: str | None = Field(
        None, description='backend=energyplus일 때 IDF 파일 경로'
    )
    epw_path: str | None = Field(
        None, description='backend=energyplus일 때 EPW 파일 경로'
    )
    data_source: str | None = Field(
        None, description='backend=replay일 때 원본 CSV/NPY 경로'
    )
