"""JSON Schema → Python/TypeScript 상수 자동 생성기.

Tier 2 (energy-contracts/schemas/*.json) → Tier 3 (각 프로젝트/_generated_constants.{py,ts}).

생성 산출물:
  - STRATEGIES        — M00~M15 전략 메타 (name_en, name_kr, type, components)
  - STRATEGY_CODES    — list[str]
  - STRATEGY_PATTERN  — regex
  - SIGNAL_MAPPING    — DR signal → strategy
  - LEGACY_MAPPING    — 구 코드 → 통일 코드 (읽기 전용)
  - PORTS             — 포트 번호 상수 (port_allocation.json)

사용법:
  python gen_constants.py --target python --out ../edge-agent/src/_generated_constants.py
  python gen_constants.py --target ts --out ../building-energy-3d/frontend/src/shared/_generated_constants.ts
  python gen_constants.py --target python --out edge-agent  # 프로젝트명만 — 표준 경로
  python gen_constants.py --check                          # 모든 등록 프로젝트 일관성 검사 (CI용)
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

CONTRACTS_ROOT = Path(__file__).resolve().parents[1]
SCHEMAS_DIR = CONTRACTS_ROOT / "schemas"
WORKSPACE_ROOT = CONTRACTS_ROOT.parents[1]

# 표준 프로젝트별 출력 경로 (Tier 3)
PROJECT_TARGETS: dict[str, dict[str, str]] = {
    "edge-agent":         {"python": "projects/edge-agent/src/_generated_constants.py"},
    "gridbridge":         {"python": "projects/gridbridge/src/_generated_constants.py"},
    "building-energy-3d": {
        "python": "projects/building-energy-3d/src/shared/_generated_constants.py",
        "ts":     "projects/building-energy-3d/frontend/src/shared/_generated_constants.ts",
    },
    "agentleague":        {"python": "projects/agentleague/backend/_generated_constants.py"},
    "eduarena":           {"python": "projects/eduarena/backend/_generated_constants.py"},
}


def load_schemas() -> dict:
    """필요한 SSOT 스키마들을 로드해 단일 dict로 반환."""
    ems = json.loads((SCHEMAS_DIR / "ems_strategies.json").read_text(encoding="utf-8"))
    ports = json.loads((SCHEMAS_DIR / "port_allocation.json").read_text(encoding="utf-8"))
    common = json.loads((SCHEMAS_DIR / "common.json").read_text(encoding="utf-8"))
    return {"ems": ems, "ports": ports, "common": common}


def schemas_hash(data: dict) -> str:
    """소스 스키마들의 SHA-256 해시 — 변경 감지용."""
    blob = json.dumps(data, sort_keys=True, ensure_ascii=False)
    return hashlib.sha256(blob.encode("utf-8")).hexdigest()[:16]


# ── Python 생성 ──────────────────────────────────────────────────────────────

PY_HEADER = '''"""AUTO-GENERATED constants from energy-contracts/schemas/.

DO NOT EDIT. Run `python energy-contracts/scripts/gen_constants.py` to regenerate.

Source SSOT: energy-contracts/schemas/ems_strategies.json, port_allocation.json, common.json
Generated by: gen_constants.py (myjob/docs/SSOT_GOVERNANCE.md Phase B)
Source hash: {hash}
"""
from __future__ import annotations

SOURCE_HASH = "{hash}"
'''


def gen_python(schemas: dict) -> str:
    h = schemas_hash(schemas)
    ems = schemas["ems"]["default"]
    ports = schemas["ports"]

    lines = [PY_HEADER.format(hash=h)]

    # Strategy codes
    codes = list(ems["strategies"].keys())
    lines.append("")
    lines.append("# ─ Strategy codes ────────────────────────────────────────────")
    lines.append(f"STRATEGY_CODES: list[str] = {codes!r}")
    lines.append(f'STRATEGY_PATTERN: str = r"^M(0[0-9]|1[0-5])$"')
    lines.append("")

    # Strategies dict
    lines.append("STRATEGIES: dict[str, dict] = {")
    for code, meta in ems["strategies"].items():
        lines.append(f"    {code!r}: {meta!r},")
    lines.append("}")
    lines.append("")

    # Signal mapping
    lines.append("# ─ DR signal → strategy ─────────────────────────────────────")
    lines.append(f"SIGNAL_MAPPING: dict[str, str] = {ems['signal_mapping']!r}")
    lines.append("")

    # Legacy mapping (lookup only)
    lines.append("# ─ Legacy code mapping (lookup only — DO NOT use for new code) ─")
    lines.append(f"LEGACY_MAPPING: dict[str, dict[str, str]] = {ems['legacy_mapping']!r}")
    lines.append("")

    # Ports
    lines.append("# ─ Port allocation (Tier 1 SSOT) ────────────────────────────")
    lines.append("PORTS: dict[str, int] = {")
    for svc in ports.get("services", []):
        if "port" not in svc:
            continue
        # 키 변환: "GridBridge (Computer A canonical)" → "GRIDBRIDGE_A"
        key = re.sub(r"[^A-Za-z0-9]+", "_", svc["name"]).strip("_").upper()
        lines.append(f"    {key!r}: {svc['port']},")
    lines.append("}")
    lines.append("")

    # Computer A 특수 포트 (자주 쓰임)
    lines.append("# ─ Computer A override (Docker가 8001/8002 점유) ────────────")
    machine_a = ports.get("machines", {}).get("A", {})
    lines.append(f"GRIDBRIDGE_HOST_PORT_A: int = {machine_a.get('gridbridge_host_port', 8001)}")
    lines.append('GRIDBRIDGE_URL_DEFAULT: str = "http://localhost:8001"')
    lines.append('GRIDBRIDGE_URL_COMPUTER_A: str = "http://localhost:8003"')
    lines.append("")

    return "\n".join(lines) + "\n"


# ── TypeScript 생성 ─────────────────────────────────────────────────────────

TS_HEADER = '''/**
 * AUTO-GENERATED constants from energy-contracts/schemas/.
 *
 * DO NOT EDIT. Run `python energy-contracts/scripts/gen_constants.py` to regenerate.
 *
 * Source SSOT: ems_strategies.json, port_allocation.json, common.json
 * Generated by: gen_constants.py (myjob/docs/SSOT_GOVERNANCE.md Phase B)
 * Source hash: {hash}
 */

export const SOURCE_HASH = "{hash}";
'''


def gen_typescript(schemas: dict) -> str:
    h = schemas_hash(schemas)
    ems = schemas["ems"]["default"]
    ports = schemas["ports"]

    lines = [TS_HEADER.format(hash=h), ""]

    codes = list(ems["strategies"].keys())
    lines.append("// ─ Strategy codes ────────────────────────────────────────────")
    lines.append(f"export const STRATEGY_CODES = {json.dumps(codes)} as const;")
    lines.append("export type StrategyCode = (typeof STRATEGY_CODES)[number];")
    lines.append(f"export const STRATEGY_PATTERN = /^M(0[0-9]|1[0-5])$/;")
    lines.append("")

    lines.append("export interface StrategyMeta {")
    lines.append("  name_en: string;")
    lines.append("  name_kr: string;")
    lines.append('  type: "single" | "combined";')
    lines.append("  components: StrategyCode[];")
    lines.append("}")
    lines.append("")
    lines.append("export const STRATEGIES: Record<StrategyCode, StrategyMeta> = {")
    for code, meta in ems["strategies"].items():
        lines.append(f"  {code}: {json.dumps(meta, ensure_ascii=False)},")
    lines.append("} as const;")
    lines.append("")

    lines.append("// ─ DR signal → strategy ─────────────────────────────────────")
    lines.append(f"export const SIGNAL_MAPPING: Record<string, StrategyCode> = "
                 f"{json.dumps(ems['signal_mapping'])};")
    lines.append("")

    lines.append("// ─ Legacy code mapping (lookup only) ────────────────────────")
    lines.append("export const LEGACY_MAPPING = "
                 + json.dumps(ems["legacy_mapping"], ensure_ascii=False) + " as const;")
    lines.append("")

    lines.append("// ─ Port allocation ──────────────────────────────────────────")
    lines.append("export const PORTS: Record<string, number> = {")
    for svc in ports.get("services", []):
        if "port" not in svc:
            continue
        key = re.sub(r"[^A-Za-z0-9]+", "_", svc["name"]).strip("_").upper()
        lines.append(f"  {key}: {svc['port']},")
    lines.append("} as const;")
    lines.append("")

    machine_a = ports.get("machines", {}).get("A", {})
    lines.append("// ─ Computer A override ──────────────────────────────────────")
    lines.append(f"export const GRIDBRIDGE_HOST_PORT_A = "
                 f"{machine_a.get('gridbridge_host_port', 8001)};")
    lines.append('export const GRIDBRIDGE_URL_DEFAULT = "http://localhost:8001";')
    lines.append('export const GRIDBRIDGE_URL_COMPUTER_A = "http://localhost:8003";')
    lines.append("")

    return "\n".join(lines)


# ── 작업 실행 ───────────────────────────────────────────────────────────────

def write_target(content: str, out_path: Path) -> bool:
    """파일이 이미 동일하면 False (변경 없음), 다르면 True."""
    if out_path.exists():
        old = out_path.read_text(encoding="utf-8")
        if old == content:
            return False
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    return True


def regenerate_all(check_only: bool = False) -> int:
    schemas = load_schemas()
    drift = 0
    for proj, targets in PROJECT_TARGETS.items():
        for lang, rel_path in targets.items():
            out = WORKSPACE_ROOT / rel_path
            content = gen_python(schemas) if lang == "python" else gen_typescript(schemas)
            if check_only:
                if not out.exists():
                    print(f"[gen_constants] MISSING: {rel_path}")
                    drift += 1
                elif out.read_text(encoding="utf-8") != content:
                    print(f"[gen_constants] DRIFT: {rel_path}")
                    drift += 1
                else:
                    print(f"[gen_constants] OK:    {rel_path}")
            else:
                changed = write_target(content, out)
                tag = "WROTE" if changed else "SAME "
                print(f"[gen_constants] {tag} {rel_path}")
    if check_only:
        print(f"\n[gen_constants] drift {drift} files")
        return 1 if drift else 0
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--target", choices=["python", "ts"],
                    help="단일 생성 시 언어 지정")
    ap.add_argument("--out", help="단일 생성 시 출력 경로")
    ap.add_argument("--check", action="store_true",
                    help="등록된 모든 타겟의 drift 검사 (CI용)")
    ap.add_argument("--all", action="store_true",
                    help="등록된 모든 타겟 재생성")
    args = ap.parse_args()

    if args.check:
        return regenerate_all(check_only=True)
    if args.all:
        return regenerate_all(check_only=False)

    if not args.target or not args.out:
        ap.print_help()
        print("\n[gen_constants] --all 또는 --check 권장. 단일 모드는 --target + --out 필수.")
        return 2

    schemas = load_schemas()
    content = gen_python(schemas) if args.target == "python" else gen_typescript(schemas)
    out_path = Path(args.out)
    if not out_path.is_absolute():
        out_path = WORKSPACE_ROOT / out_path
    changed = write_target(content, out_path)
    print(f"[gen_constants] {'WROTE' if changed else 'SAME '} {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
