#!/usr/bin/env python3
"""viz_hint 정규식 코드젠 — 정본 = energy_contracts/patterns/viz_hints.json.

studio(TS)·게이트웨이(Python) 두 소비자가 같은 4개 패턴 문자열을 손편집 리터럴로
중복 보유하던 것을 **단일 소스 코드젠**으로 승격한다(2026-07-30 완전 SSOT).
  - studio  : projects/energy-decision-studio/lib/actions/_generated_viz_hints.ts (VIZ_HINT_PATTERNS)
  - gateway : 8.simulation/_shared/_generated_viz_hints.py                       (VIZ_HINT_PATTERNS)

⚠ 왜 gen_constants.py(schemas/) 가 아니라 전용 에미터인가:
  viz_hint 정규식은 canonical 에너지 값(배출계수/PE/ZEB)이 아니라 NL→viz 라우팅 규칙이다.
  schemas/ 에 실으면 schemas_hash 가 전 8 consumer(edge/gridbridge/be-3d/agentleague/…)로
  cascade → 두 파일을 위해 무관 repo 전수 regen(false coupling). 그래서 patterns/(schemas 밖)
  단일 소스 + 이 전용 에미터만 두 타깃을 생성한다. gen_constants 의 SOURCE_HASH cascade 와 무관.

사용:
  python scripts/gen_viz_hints.py            # 두 타깃 생성(존재하는 것만)
  python scripts/gen_viz_hints.py --check     # 드리프트 검사(CI/prebuild 게이트)

부재 타깃(격리 체크아웃/CI 에 sibling repo 없음) = SKIP(생성/검사 모두 초록).
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

CONTRACTS_ROOT = Path(__file__).resolve().parents[1]
WORKSPACE_ROOT = CONTRACTS_ROOT.parents[1]
SOURCE = CONTRACTS_ROOT / "energy_contracts" / "patterns" / "viz_hints.json"

# 패턴 순서 = studio detect.ts 사용 순서(dose_setpoint/dose_climate/climate_axis/macc).
PATTERN_KEYS = ("dose_setpoint", "dose_climate", "climate_axis", "macc")

TS_TARGET = WORKSPACE_ROOT / "projects/energy-decision-studio/lib/actions/_generated_viz_hints.ts"
PY_TARGET = WORKSPACE_ROOT / "8.simulation/_shared/_generated_viz_hints.py"


def load_patterns() -> dict[str, str]:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    pats = data["patterns"]
    missing = [k for k in PATTERN_KEYS if k not in pats]
    if missing:
        raise SystemExit(f"[gen_viz_hints] viz_hints.json 에 패턴 누락: {missing}")
    return {k: pats[k] for k in PATTERN_KEYS}


def source_hash(pats: dict[str, str]) -> str:
    payload = json.dumps(pats, ensure_ascii=False, sort_keys=True).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()[:16]


def emit_ts(pats: dict[str, str], h: str) -> str:
    lines = [
        "// AUTO-GENERATED by energy-contracts/scripts/gen_viz_hints.py — DO NOT EDIT.",
        "//   source(정본) = energy-contracts/energy_contracts/patterns/viz_hints.json.",
        "//   regen = (energy-contracts) python scripts/gen_viz_hints.py. 드리프트 게이트 = studio prebuild `gen:viz-hints:check`.",
        "//   detect.ts 와 게이트웨이 app.py 가 이 동일 패턴 문자열에서 RegExp/re.compile 로 파생(정규식 lockstep = 코드젠으로 구조적 보장).",
        f'//   SOURCE_HASH = "{h}"',
        "",
        "/** viz_hint 정규식 본문(플래그 없음 — 소비자가 대소문자 무시 i 로 컴파일). */",
        "export const VIZ_HINT_PATTERNS = {",
    ]
    for k in PATTERN_KEYS:
        lines.append(f"  {k}: {json.dumps(pats[k], ensure_ascii=False)},")
    lines.append("} as const;")
    lines.append("")
    lines.append(f'export const VIZ_HINT_SOURCE_HASH = "{h}";')
    lines.append("")
    return "\n".join(lines)


def emit_py(pats: dict[str, str], h: str) -> str:
    lines = [
        '"""AUTO-GENERATED by energy-contracts/scripts/gen_viz_hints.py — DO NOT EDIT.',
        "",
        "source(정본) = energy-contracts/energy_contracts/patterns/viz_hints.json.",
        "regen = (energy-contracts) python scripts/gen_viz_hints.py.",
        "serving/app.py 가 이 패턴 문자열을 re.compile(..., re.I) 로 컴파일한다(정규식 lockstep = 코드젠 보장).",
        '"""',
        "",
        f'VIZ_HINT_SOURCE_HASH = "{h}"',
        "",
        "# viz_hint 정규식 본문(플래그 없음 — 소비자가 re.I 로 컴파일).",
        "VIZ_HINT_PATTERNS = {",
    ]
    for k in PATTERN_KEYS:
        lines.append(f"    {json.dumps(k)}: {json.dumps(pats[k], ensure_ascii=False)},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _norm_eol(s: str) -> str:
    # core.autocrlf=true 환경은 커밋본을 CRLF 로 체크아웃하나 생성기는 LF 방출 → 내용만 비교.
    return s.replace("\r\n", "\n")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="드리프트 검사만(생성 안 함). 불일치 시 exit 1.")
    args = ap.parse_args()

    pats = load_patterns()
    h = source_hash(pats)
    targets = [(TS_TARGET, emit_ts(pats, h)), (PY_TARGET, emit_py(pats, h))]

    fails = 0
    for path, content in targets:
        if not path.parent.exists():
            print(f"gen_viz_hints: SKIP {path.name} (sibling repo 부재 — 격리 체크아웃/CI).")
            continue
        if args.check:
            existing = _norm_eol(path.read_text(encoding="utf-8")) if path.exists() else ""
            if existing != _norm_eol(content):
                print(f"  ✗ gen_viz_hints --check: {path} 가 viz_hints.json 과 드리프트 → `python scripts/gen_viz_hints.py` 재생성·커밋 필요.")
                fails += 1
            else:
                print(f"gen_viz_hints: OK (--check, {path.name} = viz_hints.json 일치)")
        else:
            path.write_text(content, encoding="utf-8")
            print(f"gen_viz_hints: wrote {path}")

    if fails:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
